### ISSUE TITLE
Multiselect ID 

### ISSUE THREAD

**Issue by didoudine** [stwe/DatatablesBundle#100]
Hi !
I use your wonderful SgDatatablesBundle and i want to know something. 
How can I get the value of a column when I use the multiselect instead of the default one (username)? To use the delete option according to my ID column (it's a datatable of users, displaying their ID in a column "User ID")?

I know how to get my User ID but only with a disgusting way (hard coded right here in the multiselect template) :

{# vendor/sg/datatablesbundle/Sg/DatatablesBundle/Ressources/views/Column/multiselect.html.twig #}
{% block data %}
        {# get id #}
        var first;  
        for (var i in row) {
            if (row.hasOwnProperty(i) && typeof(i) !== 'function') {
                first = row[i];
                break;
            }
        }
{%end block%}

Here it's my code to built the datatable :

 $this->getColumnBuilder()
            ->add(null, "multiselect", array(
                    "start_html" => '<div class="wrapper" id="testwrapper">',
                    "end_html" => '</div>',
                    "width" => "100px",
                    "attributes" => array(
                        "class" => "user",
                        "name" => "id"
                    ),
                    "actions" => array(
                        array(
                            "route" => "BloggerBlogBundle_post_bulk_delete",
                            "label" => "Delete",
                            "role" => "ROLE_ADMIN"
                        ),
                        array(
                            "route" => "BloggerBlogBundle_post_bulk_disable",
                            "label" => "Disable"
                        )
                    )
                ));
           $this->getColumnBuilder()
            ->add("id", "column", array(
                    "title" => "User id",
                    "searchable" => true,
                    "orderable" => true,
                    "visible" => true,
                    "width" => "100px",
                    "class" => "user_id"
                ));
           $this->getColumnBuilder()
            ->add("username", "column", array(
                    "title" => "Login"
                ));

Can you help me? 
thank you in advance!

**Comment by didoudine** [comment]
Nobody ? :(

**Comment by celvin** [comment]
I'm not sure if I understand the expected result, here is a little javascript to get specific columns data using a click by row: ( where td:eq(0)  0= column id 0) 


                $('#tblusers_datatable tbody').on( 'click', 'tr', function () {
                
                disableHtml(".WizardActions");
                
                if ( $(this).hasClass('selected') ) {
                    $(this).removeClass('selected');
                }else {
                    loading(50);
                    $('#tblusers_datatable tbody tr.selected').removeClass('selected');
                    $(this).addClass('selected');                    
                    var id = $('td:eq(0)', $(this)).html();
                    
                    alert(id);
                    console.log(id);

                }
            } );
