### ISSUE TITLE
Virtual column

### ISSUE THREAD

**Issue by jesusherencia** [stwe/DatatablesBundle#102]
Hi,

I would like to create an extra column that shows a value that depends on other properties of the entity.
Example: 
I want to show the columns: quantity, freeShipping (quantity belongs to the entity while freeShipping does not)
If quantity > 2 then freeShipping = 'Yes' else freeShipping = 'No'

So I think I can use the virtual column, does anybody knows how to use a virtual column for this case or could give another solution.

Thanks

**Comment by jesusherencia** [comment]
I'm using v0.6.1, when I use a virtual column it shows the following error:

Warning: in_array() expects parameter 2 to be array, object given

So I modify the following line at DatatablesBundle/Datatable/Data/DatatableData.php (line 177)

From:
 } elseif (in_array($column, $this->getResponse())) {
To:
} elseif (in_array($column, $this->response)) {

And for the moment it's working fine. So may be this could be a bug. I would appreciate if this can be reviewed if it's correct or not.

Thanks

**Comment by ThatCheck** [comment]
In the master branch, Virtual class is noted as Deprecated. Could you post some code, may be I can help you ;) !

**Comment by stwe** [comment]
you should use the last stable version. i have no time to continue working
on that project now. sorry.
Am 16.03.2015 10:40 schrieb "ThatCheck" <notifications@github.com>:

**Comment by didoudine** [comment]
Hi  jesusherencia !
I want to do the same as you, which is to create an extra column that shows a value that depends on other properties of the entity.
did you solve your problem now? Because I can not help it, my Datatable absolutely must be able to show in a column a value set in my Entity.
if someone else has found the solution, it'll be very useful for many people because it is something quite common.

TANKS !

**Comment by ThatCheck** [comment]
There is a easy way to acheive what you want. 

First add all your column you need in your datatable (If you need a column but you don't want to display it, juste set "visible" => false in option of column). 

Then, create a column with virtual attribute. 

And then, use the line formatter (you have some example in the doc) to stuff your virtual column with data.

If your are questions, tag me :) !

**Comment by didoudine** [comment]
I found a nice solution !

In my controller i made : 

public function indexAction()
    {
      $postDatatable = $this->get("blogger_user_datatables.post"); // Call service
      $postDatatable->buildDatatableView();
      return array('datatable' => $postDatatable);
    }

public function resultsAction()
    {
       $datatable = $this->get("sg_datatables.datatable")->getDatatable($this->get("blogger_user_datatables.post"));
       $function = function($qb)
        {
            $qb->andWhere("fos_user.deletionDate IS NULL");
        };
       $datatable->addWhereBuilderCallback($function);
       return $datatable->getResponse();
    }



In my PostDatatable.php : 

class PostDatatable extends AbstractDatatableView
{
     private $em;
     public function __construct(\Doctrine\ORM\EntityManager $em, $templating, $translator, $router, $defaultLayoutOptions)
    {
        parent::__construct($templating, $translator, $router, $defaultLayoutOptions);
        $this->em = $em;
        return $this;
    }

    public function getLineFormatter()
    {
        $formatter = function($line){      
            $em = $this->em->getRepository('Blogger\XXXBundle\Entity\FosUser');
            $line['chef'] = $em->find($line['id'])->getChef();
            return $line;
        };
        return $formatter;        
    } 

     public function buildDatatableView()
    {
        $this->getFeatures()
                     /*->set...........
                     ->all............
                     ->features..*/
        
        $this->getAjax()->setUrl($this->getRouter()->generate("BloggerUserBundle_results"));
        /*..... other setting methods (setStyle, Filtering,...) and $this->getMultiselect() ....*/
        $this->getColumnBuilder()
             ->add("chef", "virtual", array(
                    "title" => "Role",
                    "width" => "30em"
                ))
             ->add /*other added column*/
                ));


It works well, thx for your help guys :)

**Comment by ThatCheck** [comment]
Just take care with you method. If you're print 100 entity, you generate hundred of sql request ;) !

**Comment by didoudine** [comment]
Ok thank you ThatCheck ! But I have a quick question, could you give me your opinion?
https://github.com/stwe/DatatablesBundle/issues/105

Thanks :) !

**Comment by stwe** [comment]
after these commits it should work:
https://github.com/stwe/DatatablesBundle/commit/ee2c72f8c4c7769d2cf557374ddce3942f18a22b
https://github.com/stwe/DatatablesBundle/commit/653451443037bbee31839cab132eb467b5d5ce6c
