### ISSUE TITLE
Multiselect - AddAction

### ISSUE THREAD

**Issue by didoudine** [stwe/DatatablesBundle#105]
Hi everyone !
I would like to know if it was possible to pass a parameter to a route, in the following case :
I had the "BloggerStudyBundle_post_bulk_status" route. It changes the status of 1 or several studies of my datatable but If I do not want to do several actions in my controller, I have to pass a parameter to this route. I can not find the solution ...

In "PostDatatable.php" 

        $this->getMultiselect()
            ->setEnabled(true)
            ->setPosition("first")
            ->setClassName("multi-test-class")
            ->setWidth("100px")
            ->setAttributes(array(
                    "class" => "Study",
                    "name" => "id"
                ))
            ->addAction("Delete", "BloggerStudyBundle_post_bulk_delete")

/* 1st option */
            ->addAction("Status cancelled", "BloggerStudyBundle_post_bulk_status" => 3)
            ->addAction("Status finished", "BloggerStudyBundle_post_bulk_status" => 4)
            ->addAction("Status archived", "BloggerStudyBundle_post_bulk_status" => 5)

/* 2nd option */
           ->addAction(array("route" => "BloggerStudyBundle_post_bulk_status", "route_parameters" => array("id" => 3),"label" => "Status cancelled"))
            ->addAction(array("route" => "BloggerStudyBundle_post_bulk_status", "route_parameters" => array("id" => 4),"label" => "Status finished"))
            ->addAction(array("route" => "BloggerStudyBundle_post_bulk_status", "route_parameters" => array("id" => 5),"label" => "Status archived"))

The 1st option gives me a "syntax error, unexpected '=>'"
And the 2nd option gives me a "Warning: Missing argument 2 for Sg\DatatablesBundle\Datatable\View\Multiselect::addAction()" because the AddAction method does not allow as many arguments : "public function addAction($title, $route){}"
          
Does anyone can help me? 
Or was confronted with this problem?
Thanks!

**Comment by ThatCheck** [comment]
Sorry for the delay. I think, there is no to do what you want in the v0.6.1. 
1) You can update to master but this not a stable release
2) Or just create three route which redirect of your main controller function with the good options. 

I think, the second options is the better one.

**Comment by didoudine** [comment]
Ok thanks for you answer !
I'll put up the second option, the one I had in mind if there was no other solution.

Have a good day ThatCheck ! :)

**Comment by didoudine** [comment]
One last question because I did not manage to implement this solution.
How do I retrieve route options? And where? 
I can send but not the reverse...

Thanks !

**Comment by stwe** [comment]
A Multiselect column doesn't accept route parameters.
