### ISSUE TITLE
Datatable and entity using translatable

### ISSUE THREAD

**Issue by nbk195** [stwe/DatatablesBundle#106]
Hey everyone, 

First of all thanks for your amazing work on that bundle, one of my favorite. 

On my project, i'm using StofDoctrineExtensions Bundle, and particularly Translatable. 
Everything works fine on my views but not with my datatables. 

For more details : 
I have, for the moment 2 locales (fr and en), on my entity i have translatable fields (description and label), different if you are in fr or in en. 
Datatable always send me the value corresponding to the fallback locale define in my config.yml and corresponding to my %locale% parameter. 

The translatable documentation advice to use hint on the query, this way : 
``` php
<?php
// locale
$query->setHint(
    \Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE,
    'en' // take locale from session or request etc.
);
// fallback
$query->setHint(
    \Gedmo\Translatable\TranslatableListener::HINT_FALLBACK,
    1 // fallback to default values in case if record is not translated
);

$articles = $query->getResult(); // object hydration
```

It's fine, but i search into datatable bundle a way to do that but without any success. 
I tried using callback in my controller action:
``` php
        $function = function($qb)
        {
            $qb->getQuery()->setHint(
                \Gedmo\Translatable\TranslatableListener::HINT_FALLBACK,
                1 
            );
        };
        
        // Add callback
        $datatable->addWhereBuilderCallback($function);
```
Have any idea if it's possible and how ? 
Thanks

**Comment by stwe** [comment]
Thank you. Custom queries are currently not possible. Sorry. See #60

**Comment by konradja100** [comment]
Hi, i have very simmilar issue - anyone have solution for this?
