### ISSUE TITLE
Virtual column error

### ISSUE THREAD

**Issue by MavisS2** [stwe/DatatablesBundle#108]
Hi,

When i add virtual column to my datatable, i have error in DatatableData.php in 177 line.
This error is "warning in_array expects parameter 2 to be array".

In this line there is code "} elseif (in_array($column, $this->getResponse())) {" and $this->getResponse don't return array. when I remove this line is the virtual column works properly.

**Comment by stwe** [comment]
I know. There was an error with the virtual column to version 0.6.1. In the master that should be fixed. But master is very unstable at the moment. sorry.

**Comment by stwe** [comment]
see: https://github.com/stwe/DatatablesBundle/commit/0a6c21a86a866e3a2ec6764054677ea8d6d8facb
