### ISSUE TITLE
Two associations with same entity leaves one association column empty

### ISSUE THREAD

**Issue by Minishlink** [stwe/DatatablesBundle#110]
Hello,

It appears that there is a bug during getResponse when two or more entities of the same class are associated with the entity linked to the datatable.

Considering the following (simplified) entities:
* Transfer
  * id
  * (Account) sender
  * (Account) receiver
* Account
  * id
  * (User) user
* User
  * id
  * username

With a datatable (server-side) on Transfer as such:
```php
        $this->getColumnBuilder()
            ->add('sender.user.username', 'column', array(
                'title' => 'Sender',
            ))
            ->add('receiver.user.username', 'column', array(
                'title' => 'Receiver',
            ))
        ;
```

The column Sender is filled but not the column Receiver which is left empty. Looking at the results of the ajax request, it appears that only the id of Receiver is replied, not the User (id or username either) of Receiver.

The problem appears regardless of if I apply a callback trough addWhereBuilderCallback.

All my other columns are fetched and shown correctly.

**Comment by stwe** [comment]
That works for me as well (master branch):

            ->add('comments.createdby.username', 'array', array(
                'title' => 'Created by',
                'searchable' => true,
                'orderable' => true,
                'data' => 'comments[, ].createdby.username',
            ))
            ->add('comments.updatedby.username', 'array', array(
                'title' => 'Updated by',
                'searchable' => true,
                'orderable' => true,
                'data' => 'comments[, ].updatedby.username',
            ))

**Comment by Minishlink** [comment]
I confirm it now works on 0.7. (I was on 0.6.1)

**Comment by stwe** [comment]
Thank you for your feedback.
