### ISSUE TITLE
Object entity in DatatableView

### ISSUE THREAD

**Issue by DarekTw** [stwe/DatatablesBundle#112]
In AliDattableBundle there is possibility to access an entity and define custom renderers.
It is very nice feature and can make lineformatter easier - columns visual false no needed any more.
What do you think about this?

------

https://github.com/AliHichem/AliDatatableBundle#-custom-renderer

**Comment by stwe** [comment]
see: https://github.com/stwe/DatatablesBundle/issues/102
"If you're print 100 entity, you generate hundred of sql request ;) !".

**Comment by stwe** [comment]
My way is the virtual column with line-formatter. You can get the entity repository in your datatables class.
