### ISSUE TITLE
filter datatable in indexAction

### ISSUE THREAD

**Issue by Falar81** [stwe/DatatablesBundle#118]
Hi,
how do I filter the table here?

<code>

    public function indexAction()
    {
        $postDatatable = $this->get("sg_datatables.post");
        $postDatatable->buildDatatableView();

        return array(
            "datatable" => $postDatatable,
        );
    }
</code>

i have a form in this action and need to filter data here.
thanks!

**Comment by stwe** [comment]
What exactly do you want to do? Please watch the examples.

**Comment by Falar81** [comment]
ok,
this is my controller action:



     /**
     * 
     * @Security("is_granted('ROLE_USER')")
     * @Route("/list", name="prodotti_list")
     * @Template()
     */  
    public function listAction(Request $request)
    {
        //$em = $this->getDoctrine()->getManager();
        $entity = new ProdottiSearch();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            //This is a form containing data to be filtered in the table
            $em = $this->getDoctrine()->getManager();
            
           $prodottiDatatable = $this->get("sg_datatables.prodotti");
           //.....
            ////// I need to make a custom where here
           $prodottiDatatable->buildDatatableView();

            return array(
                "datatable" => $prodottiDatatable,
            );
        }
        $prodottiDatatable = $this->get("sg_datatables.prodotti");
        $prodottiDatatable->buildDatatableView();

        return array(
            "datatable" => $prodottiDatatable,
        );
    }

the prodottiResultsAction:

    /**
     * Get all Post entities.
     *
     * @Route("/prodottiResults", name="prodotti_results")
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function prodottiResultsAction()
    {
        /**
         * @var \Sg\DatatablesBundle\Datatable\Data\DatatableData $datatable
         */
        $datatable = $this->get("sg_datatables.datatable")->getDatatable($this->get("sg_datatables.prodotti"));

        // Callback example
        //        $function = function($qb)
        //        {
        //            $qb->andWhere("Post.visible = true");
        //        };

        // Add callback
        //        $datatable->addWhereBuilderCallback($function);
        //
        return $datatable->getResponse();
    }

I have to use the server-side approach because my table products contains over 10000 units.
how can I solve using this bundle?

thank you so much!

**Comment by jinxboy13** [comment]
I don't have the form but I have the same problem I need to add query in the first indexaction at the server-side mode.
Thanks

**Comment by stwe** [comment]
from the examples.....

use `addWhereResult`,  `addWhereAll` or get the actual query.

``` php
public function indexResultsAction()
{
    $datatable = $this->get('app.datatable.post');
    $datatable->buildDatatable();

    $query = $this->get('sg_datatables.query')->getQueryFrom($datatable);

    // Callback example
    $function = function($qb)
    {
        $qb->andWhere("post.visible = true");
    };

    // Add the callback function as WhereResult
    //$query->addWhereResult($function);

    // Or add the callback function as WhereAll
    //$query->addWhereAll($function);

    // Or to the actual query
    //$query->buildQuery();
    //$qb = $query->getQuery();
    //$qb->andWhere("post.visible = true");
    //$query->setQuery($qb);
    //return $query->getResponse(false);

    return $query->getResponse();
}
```

**Comment by Falar81** [comment]
How do I use the controller the parameter get request? currently I use the session, it is not the best way but it works. 
thanks a lot
