### ISSUE TITLE
getLineFormatter with serverSide false

### ISSUE THREAD

**Issue by Falar81** [stwe/DatatablesBundle#119]
hi,

getLineFormatter method not work when serverSide is set to false?
i need to apply this: 
$line["id"] = sprintf('%05d', $line["id"]);

thanks

**Comment by stwe** [comment]
No. The virtual field can be set in the controller. Example:

    /**
     * Client side Post datatable.
     *
     * @Route("/cs", name="cs_post")
     * @Method("GET")
     * @Template(":post:index.html.twig")
     *
     * @return array
     */
    public function clientSideIndexAction()
    {
        $repository = $this->getDoctrine()->getRepository("AppBundle:Post");

        $query = $repository->createQueryBuilder("p")
            ->select("p, c")
            ->join("p.comments", "c")
            ->getQuery();

        $results = $query->getArrayResult();

        foreach ($results as $key => $value) {
            $results[$key]["your virtual field"] = "test";
        }

        $encoders = array(new JsonEncoder());
        $normalizers = array(new GetSetMethodNormalizer());
        $serializer = new Serializer($normalizers, $encoders);

        $datatable = $this->get("app.datatable.client_side.post");
        $datatable->setData($serializer->serialize($results, "json"));

        return array(
            "datatable" => $datatable,
        );
    }
