### ISSUE TITLE
Call to undefined method Backend\..\ActivityDatatable::getFeatures()

### ISSUE THREAD

**Issue by ymRed** [stwe/DatatablesBundle#120]
Hi, i'm having problems with the installation of the Bundle. I get this error when i try to access the indexAction of the Datatables controller class.
Can anybody help me?

FatalErrorException: Error: Call to undefined method Backend\adminBundle\Datatables\ActivityDatatable::getFeatures() in C:\wamp2\www\crmba_prod\src\Backend\adminBundle\Datatables\ActivityDatatable.php line 19

The Controller:

<?php
namespace Backend\adminBundle\Datatables;
use Sg\DatatablesBundle\Datatable\View\AbstractDatatableView;
/**
 * Class ActivityDatatable
 *
 * @package Backend\adminBundle\Datatables
 */
class ActivityDatatable extends AbstractDatatableView
{
    /**
     * {@inheritdoc}
     */
    public function buildDatatableView()
    {
        $this->getFeatures()
                        ->setServerSide(true)
                        ->setProcessing(true);
                $this->getAjax()->setUrl($this->getRouter()->generate('activity_results'));
        $this->setStyle(self::BOOTSTRAP_3_STYLE);

        $this->getColumnBuilder()
.............
.............

Thank you in advance.

**Comment by stwe** [comment]
The function getFeatures() was removed in master. Look at the examples:

https://github.com/stwe/dtbundle-demo
https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/example.md

        $this->features->setFeatures(array(
            "auto_width" => true,
            "defer_render" => false,
            "info" => true,
            "jquery_ui" => false,
            "length_change" => true,
            "ordering" => true,
            "paging" => true,
            "processing" => true,
            "scroll_x" => false,
            "scroll_y" => "",
            "searching" => true,
            "server_side" => true,
            "state_save" => false,
            "delay" => 0
        ));
