### ISSUE TITLE
DatatableQuery::getCountAllResults doesn't create joins

### ISSUE THREAD

**Issue by dchabanenko** [stwe/DatatablesBundle#122]
I have a bug, using own whereBuilderCallback with joins and have an error:

'entity.fieldname.id' is not defined.

I have noticed, that the error occurs while calling DatatableQuery::getCountAllResults https://github.com/stwe/DatatablesBundle/blob/master/Datatable/Data/DatatableQuery.php#L216 and that query differs from mine. Addition of my whereBuilderCallback with a join, causes the error. 
I suppose the query with and without joins may have different number of output rows. 
What about adding joins to the query in DatatableQuery::getCountAllResults?
Or maybe remove $this->setWhereCallbacks($qb); if this query is for calculating unfiltered results?

**Comment by stwe** [comment]
the data and query class are good candidates for refactoring

**Comment by Koovvall** [comment]
You shouldn't comment this line:
$this->setWhereCallbacks($qb);

I think you should add this line before:
$this->setLeftJoins($qb);

After that everything will be ok :)
