### ISSUE TITLE
PostgreSQL

### ISSUE THREAD

**Issue by aluzardo** [stwe/DatatablesBundle#124]
I can´t use DatatablesBundle with PostgreSQL.

The main reason is PostgreSQL doesn`t permit "like" with integer columns.

It is the error.

HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
*********\* Error **********

ERROR: operator does not exist: integer ~~ unknown
SQL state: 42883
Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
Character: 49

**Comment by stwe** [comment]
Hi, same as #30

**Comment by celvin** [comment]
I fixed it, 
I just added a doctrine function in config.yml under orm (CastAsString)

- the config.yml file

	    orm:
		auto_generate_proxy_classes: "%kernel.debug%"
		auto_mapping: true

		dql:
		    string_functions:
		        cast: Base\DQL\CastAsString



- the CastAsString.php function source :
	
		<?php
		namespace Base\DQL;

		use Doctrine\ORM\Query\AST\Functions\FunctionNode;
		use Doctrine\ORM\Query\Lexer;
		use Doctrine\ORM\Query\Parser;
		use Doctrine\ORM\Query\SqlWalker;

		class CastAsString extends FunctionNode
		{
		    public $stringPrimary;

		    public function getSql(SqlWalker $sqlWalker)
		    {
			return 'cast(' . $this->stringPrimary->dispatch($sqlWalker) . ' AS text )';
		    }

		    public function parse(Parser $parser)
		    {
			$parser->match(Lexer::T_IDENTIFIER);
			$parser->match(Lexer::T_OPEN_PARENTHESIS);

			$this->stringPrimary = $parser->StringPrimary();

			$parser->match(Lexer::T_CLOSE_PARENTHESIS);
		    }
		}



- and then you are able to use cast in the sg/datatables " DatatableQuery.php "

This line in "setWhere" method could look like this:

		$orExpr->add($qb->expr()->like('cast('.$searchField.')', '?' . $key));

**Comment by stwe** [comment]
see #297

**Comment by stwe** [comment]
Hey folks. Bad news: I'm not working with PostgreSQL. I have no idea about it and therefore can not write any good software supporting PostgreSQL. I also don' t like it. Therefore, I will close all the issues. Feel free to forke the bundle. Thanks for your understanding and greetings.
