### ISSUE TITLE
how to add custom filters (form with select, checkboxes etc) in server-side mode ?

### ISSUE THREAD

**Issue by FredoVelcro** [stwe/DatatablesBundle#126]
Hello,

I want my datable to be filtered with custom form fields on top of it.
I use the server-side mode because too many records (+10 000).

What i'm trying to do is adding the Request object in the controller action to get additionnals fields/parameters (the serialized filters form values)

```php
/**
     * Get all Region entities.
     *
     * @Route("/results", name="region_results")
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexResultsAction(Request $request)
    {
        /**
         * @var \Sg\DatatablesBundle\Datatable\Data\DatatableData $datatable
         */
        $datatable = $this->get("sg_datatables.datatable")->getDatatable($this->get("datatable.region"));

        // Callback example
        $function = function(QueryBuilder $qb)
        {
            $qb->andWhere("country = :country")->setParameter(':country', $request->get('country'));
        };

        // Add callback
        $datatable->addWhereBuilderCallback($function);

        return $datatable->getResponse();
    }
```

Is this the good way to do it ?
If yes, how can i "inject" my filters parameters values in the ajax call ?

Thank you for any help ;-) 

NB : i think it is a very common use case of datatables

**Comment by stwe** [comment]
Sorry. Currently not possible. You are absolutely right.....a very common use case of datatables. This is a hobby project and it is a lot of work to integrate new features. Custom queries are at the top my priority list.
