### ISSUE TITLE
Twig function - icon

### ISSUE THREAD

**Issue by DarekTw** [stwe/DatatablesBundle#131]
There is conflict with braincrafted/bootstrap-bundle which has also a twig function with name 'icon'.
I need to change bundles order in AppKernel to resolve this problem.

Could you change a function name?
datatable_icon?

**Comment by stwe** [comment]
yes of course....
Am 27.05.2015 14:33 schrieb "DarekTw" <notifications@github.com>:

There is conflict with braincrafted/bootstrap-bundle which has also a twig
function with name 'icon'.
I need to change bundles order in AppKernel to resolve this problem.

Could you change a function name?
datatable_icon?

—
Reply to this email directly or view it on GitHub
<https://github.com/stwe/DatatablesBundle/issues/131>.
