### ISSUE TITLE
Notice: Undefined index: columns 

### ISSUE THREAD

**Issue by ahmadsajid1989** [stwe/DatatablesBundle#135]
Hi I used followed your documentation properly.. using the stable version v0.6.1 getting this error, i generated the datatable class using your generator, so i suppose there shouldnt be a problem with that class. Can you tell where can i fix?

Stack Trace

    in vendor/sg/datatablesbundle/Sg/DatatablesBundle/Datatable/Data/DatatableData.php at line 281  -
                $this->addSelectColumn($this->metadata, $this->rootEntityIdentifier);
                $this->addAllColumn($this->tableName . '.' . $this->rootEntityIdentifier);
                $counter = count($this->requestParams["columns"]);
                for ($i = 0; $i < $counter; $i++) {

**Comment by stwe** [comment]
Please use master.
