### ISSUE TITLE
Function addWhereBuilderCallback and  unnecessary filtered.

### ISSUE THREAD

**Issue by speedy001** [stwe/DatatablesBundle#140]
If I use addWhereBuilderCallback i don't want have something like this:

Showing 1 to 3 of 3 entries (filtered from 7 total entries)

it should be like this:

Showing 1 to 3 of 3 entries.

I think that problem is in function getCountAllResults.

Now this function looks like this::

    public function getCountAllResults($rootEntityIdentifier)
    {
        $qb = $this->em->createQueryBuilder();
        $qb->select("count(" . $this->tableName . "." . $rootEntityIdentifier . ")");
        $qb->from($this->entityName, $this->tableName);

        return (int) $qb->getQuery()->getSingleScalarResult();
    }

Maybe this function should be like this:

    public function getCountAllResults($rootEntityIdentifier)
    {
        $qb = $this->em->createQueryBuilder();
        $qb->select("count(" . $this->tableName . "." . $rootEntityIdentifier . ")");
        $qb->from($this->entityName, $this->tableName);

        $this->setWhereCallbacks($qb);

        return (int) $qb->getQuery()->getSingleScalarResult();
    }

**Comment by stwe** [comment]
see: https://github.com/stwe/DatatablesBundle/commit/08897b019d224dfd64df44b7815687e1410d37f5
