### ISSUE TITLE
Invisible column filter problem

### ISSUE THREAD

**Issue by nopr0n** [stwe/DatatablesBundle#141]
I have a JS problem with invisble columns.
Whenever i add an invisible column, I have the following error message in my navigator console : 
Uncaught TypeError: Cannot read property 'sWidth' of undefined -> jquery.dataTables.min.js:54 

I can provide my datatables options if needed.

Thanks

**Comment by stwe** [comment]
there is a bug with 

    'individual_filtering' => true

**Comment by stwe** [comment]
see: https://github.com/stwe/DatatablesBundle/commit/9b2a7457c22acec3baf26e141f7a4c741bf79b65
