### ISSUE TITLE
Removing columns in ColumnBuilder

### ISSUE THREAD

**Issue by tkuska** [stwe/DatatablesBundle#144]
It could be useful to add possibility of removing columns in ColumnBuilder.
In case we want to use existing DatatableService in few places of our app, but in one case few columns should not be shown, it easier to inherit existing service and remove some columns, or access columnBuilder and remove columns in controller, than creating new service.

**Comment by stwe** [comment]
Example: 

    public function indexAction()
    {
        $datatable = $this->get('app.datatable.server_side.post');

        $datatable->getColumnBuilder()->removeByKey(2);

        return array(
            'datatable' => $datatable,
        );
    }
