### ISSUE TITLE
Support of TableTools plugin

### ISSUE THREAD

**Issue by DrDJo** [stwe/DatatablesBundle#147]
Could be cool to support the TableTools plugin to provide CSV, XLS export and print with the current order / filter.

http://www.datatables.net/release-datatables/extensions/TableTools/examples/simple.html

This plugin is great, nice work.

**Comment by stephanvierkant** [comment]
TableTools is now retired: http://www.datatables.net/extensions/tabletools/

**Comment by stwe** [comment]
Thanks. Good to know

**Comment by mdhheydari** [comment]
+1
I think having these functionalities is awesome. We could use buttons as a replacement for TableTools:
http://www.datatables.net/extensions/buttons/

**Comment by migmolrod** [comment]
Maybe this issue should be closed, then we can keep this conversation in #203 which is more generic and also includes TableTools (even though TableTools are kind of 'deprecated')
Just an opinion.

**Comment by stwe** [comment]
@migmolrod  is right. Go on with comments in #203.
