### ISSUE TITLE
Results count does not take joins

### ISSUE THREAD

**Issue by FredoVelcro** [stwe/DatatablesBundle#151]
Hello,

I have a bug that i didn't notice before (since 0.7 i think).
I use the server side mode.

The count of filtered results is wrong (recordsFiltered in JSON), it always equals the total count of entities (recordsTotal) : 
Showing 1 to 10 of 286 entries
The pagination is broken, for example, if i only have 12 records matching the filters, the pagination is created for all the 286 total rows, so going to page 3 return nothing...

Hope my explanaton is clear enough !

**Comment by DarekTw** [comment]
Hi,

I guess You have used $query->addWhereResult($function);
this function doesn't affect on count but

> addWhereAll

seems be the right function
https://github.com/stwe/DatatablesBundle/blob/aa36f229eb1ddf3020aac94a90525906899059a3/Datatable/Data/DatatableQuery.php#L576

https://github.com/stwe/DatatablesBundle/blob/204a7c82b7ef274f7c74a3c2eae5cb5f6f005209/Resources/doc/example.md#step-4-add-controller-actions

**Comment by FredoVelcro** [comment]
Hi,

Thank you, you're right the solution was to call : 
```php
$query->addWhereAll($function);
```

**Comment by DarekTw** [comment]
I think in documentation could be described difference between addWhere, addWhereResult, and addWhereAll functions

**Comment by FredoVelcro** [comment]
Totally agree ! :+1:
