### ISSUE TITLE
Automatically buildDatatableView is not a so good idea?

### ISSUE THREAD

**Issue by Minishlink** [stwe/DatatablesBundle#153]
Hello,

ee2c72f8c4c7769d2cf557374ddce3942f18a22b makes problems to use parameters or services during buildDatatableView, because buildDatatableView is called right as the service is initialized.

**Comment by stwe** [comment]
Absolutely right... my mistake. I will fix as soon as possible.

**Comment by Invis1ble** [comment]
:+1:

**Comment by stwe** [comment]
ok what can I do. For example, write an empty function (Let's call them, 'setup') in the ctor. of the AbstractDatatableView class:

    public function __construct(
        AuthorizationCheckerInterface $authorizationChecker,
        TokenStorageInterface $securityToken,
        Twig_Environment $twig,
        TranslatorInterface $translator,
        RouterInterface $router,
        EntityManagerInterface $em,
        array $defaultLayoutOptions
    )
    {
        $this->authorizationChecker = $authorizationChecker;
        $this->securityToken = $securityToken;
        $this->twig = $twig;
        $this->translator = $translator;
        $this->router = $router;
        $this->em = $em;

        $this->features = new Features();
        $this->options = new Options();
        $this->callbacks = new Callbacks();
        $this->columnBuilder = new ColumnBuilder();
        $this->ajax = new Ajax();

        $this->data = null;
        $this->templates = $defaultLayoutOptions['templates'];

        $this->qb = null;

        $this->setup(); <---- call before buildDatatableView
        $this->buildDatatableView();
    }

    //-------------------------------------------------
    // DatatableViewInterface
    //-------------------------------------------------

    /**
     * {@inheritdoc}
     */
    public function setup()
    {}

The controller:

    public function indexAction()
    {
        $datatable = $this->get('app.datatable.server_side.post');
        $datatable->setup();

        return array(
            'datatable' => $datatable,
        );
    }

**Comment by Invis1ble** [comment]
@stwe The problem is that in `buildDatatableView()` implementations we need some services that has not been initialized yet at this moment. I think just removing calling `buildDatatableView()` from constructor solves this issue. We can call `buildDatatableView()` in the controllers like in version 6.1, for example.

**Comment by stwe** [comment]
@Invis1ble : Yes, of course. I can do it that way. But the problem is the following: the `buildDatatableView()` must also be called in the result action. I don't like the name `buildDatatableView()`  in this case. Symfony2 does not pass the same DatatablesClass service instance to other actions. Anyway, I believe that. Is that right? 
Perhaps the function `buildDatatableView()` should be renamed (e.g. `setup()`).

**Comment by Invis1ble** [comment]
What is the "result action" ? Do you mean filtering, sorting etc.? If so then it is another instance ofcourse (in case server-side processing), because it is another request. In case of non-server-side processing I don't know, not tried it yet. But `sg.datatable.view` services has `container` scope, so it must be like singletone.
Renaming to `setup()` looks good to me.

**Comment by stwe** [comment]
I mean the following controller actions:

    public function indexAction()
    {
        $datatable = $this->get('app.datatable.post');
        // 1st call
        $datatable->buildDatatableView()

        return array(
            'datatable' => $datatable,
        );
    }

    public function indexResultsAction()
    {
       $datatable = $this->get('app.datatable.post');
       // 2nd call
       $datatable->buildDatatableView()

        $query = $this->get('sg_datatables.query')->getQueryFrom($datatable);
    }

**Comment by stwe** [comment]
New Example:

// Datatables class

    class PostDatatable extends AbstractDatatableView
    {
        // Example service
        private $logger;

        public function __construct(
            LoggerInterface $logger,
            AuthorizationCheckerInterface $authorizationChecker,
            TokenStorageInterface $securityToken,
            Twig_Environment $twig,
            TranslatorInterface $translator,
            RouterInterface $router,
            EntityManagerInterface $em,
            array $defaultLayoutOptions
        )
        {
            parent::__construct(
                $authorizationChecker,
                $securityToken,
                $twig,
                $translator,
                $router,
                $em,
                $defaultLayoutOptions
            );

            $this->logger = $logger;
        }

        // use buildDatatable instead buildDatatableView() // !!!! <====  !!!
        public function buildDatatable() // // !!!! <====  !!!
        {
            $this->logger->info('I just got the logger');
        
            // ...

        }

 // The service

        app.datatable.server_side.post:
            class: AppBundle\Datatables\PostDatatable
            arguments: [@logger]
            tags:
                - { name: sg.datatable.view }

// The controller actions

    public function indexAction()
    {
        $datatable = $this->get('app.datatable.server_side.post');
        $datatable->buildDatatable(); // !!!! <====  !!!

        return array(
            'datatable' => $datatable,
        );
    }

    /**
     * Get all Post entities.
     *
     * @Route("/results", name="post_results")
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexResultsAction()
    {
        $datatable = $this->get('app.datatable.server_side.post');
        $datatable->buildDatatable(); // !!!! <====  !!!

        $query = $this->get('sg_datatables.query')->getQueryFrom($datatable);

        return $query->getResponse();
    }

**Comment by Invis1ble** [comment]
Thanks!

**Comment by Minishlink** [comment]
It works great, thanks ! :)

**Comment by Minishlink** [comment]
For the example, I would suggest to inject the optional service via setting injection. It seems better in this case.

```php
class PostDatatable extends AbstractDatatableView
{
    // Example service
    private $logger;

    public function setLogger(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }

    // use buildDatatable instead buildDatatableView() // !!!! <====  !!!
    public function buildDatatable() // // !!!! <====  !!!
    {
        $this->logger->info('I just got the logger');

        // ...

    }
```

```yaml
app.datatable.server_side.post:
    class: AppBundle\Datatables\PostDatatable
    calls:
        - [setLogger, ["@logger"]]
    tags:
        - { name: sg.datatable.view }
```

**Comment by stwe** [comment]
@Minishlink My Opinion: I dislike setter injections. Why do you prefer it in this case.

**Comment by Minishlink** [comment]
It takes less lines of code. Approximately 20 lines in your code are repeated in each DatatableView class which needs a service. (constructor + use statements of the interfaces) My approach is, I think, lightweight and flexible : if you don't need the service in buildDatatable but only in the lineFormatter (or vice versa), you can call setXService in your main controller action (buildDatatable) or in the "results" action (lineFormatter). If you need it in both, you can use the setting injection (or property injection).
