### ISSUE TITLE
Show or hide columns with role 

### ISSUE THREAD

**Issue by aluzardo** [stwe/DatatablesBundle#155]
Can I show or hide a columns using the user role?

**Comment by stwe** [comment]
Example;
        
        $this->columnBuilder
            ->add('id', 'column', array(
                'class' => '',
                'padding' => '',
                'name' => '',
                'orderable' => true,
                'render' => null,
                'searchable' => true,
                'title' => 'Id',
                'type' => '',
                'visible' => true,
                'width' => '40px',
                'default' => ''
            ));
            if ($this->authorizationChecker->isGranted('ROLE_ADMIN')) {
            $this->columnBuilder->add('visible', 'boolean', array(
                'class' => '',
                'padding' => '',
                'name' => '',
                'orderable' => true,
                'render' => 'render_boolean',
                'searchable' => true,
                'title' => $this->translator->trans('dtbundle.post.titles.visible'),
                'type' => '',
                'visible' => true,
                'width' => '50px',
                'true_icon' => 'glyphicon glyphicon-ok',
                'false_icon' => '',
                'true_label' => 'yes',
                'false_label' => 'no',
                'search_type' => 'eq',
                'filter_type' => 'select',
                'filter_options' => ['' => $this->translator->trans('dtbundle.post.filter.any'), '1' => $this->translator->trans('dtbundle.post.filter.yes'), '0' => $this->translator->trans('dtbundle.post.filter.no')],
            ));
            }
        $this->columnBuilder
            ->add('owner', 'virtual', array(
                'title' => $this->translator->trans('dtbundle.post.titles.owner')
            ));
