### ISSUE TITLE
Filtering/searching in server-side should take into account the lineFormatter

### ISSUE THREAD

**Issue by Minishlink** [stwe/DatatablesBundle#156]
Hello,

Let's say I have a field 'order' which is either 'a' or 'b' (which is stupid but that's an example). The lineFormatter converts 'a' to 'First' and 'b' to 'Second'.
If you search or filter by typing 'first', nothing will come up because the bundle search through the unformatted data ('a' and 'b').

Note that it may by useful to also search through the unformatted data so that it takes into account both formatted and unformatted data.

**Comment by DarekTw** [comment]
I think that this problem has gone since we have a select filter https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/example.md#your-datatables-class

in your example it will be
```
                'filter_type' => 'select', // use select dropdown with options: any/yes/no options are automatically associated with 'boolean' columntype
                'filter_options' => ['' => 'Any', 'a' => 'First', 'b' => 'Second'], // for client-side mode options keys should be equal to the values actually showed on the table
```

**Comment by Minishlink** [comment]
In this simple use case it is actually a workaround, thanks ! :)

But unfortunately, there are other cases where you can't foresee the possible results beforehand...

**Comment by stwe** [comment]
@Minishlink : I think that is not possible. The lineFormatter converts a given result from your database to a value in your view. Suppose you enter the view-value 'First' in the global search form. How can I find the value 'a' in the database with it? In the workaround from @DarekTw , on the other hand there is a relationship between the value of 'a' (database value) and 'First' (view value). In this case, I know that I have to search for 'a' and not for 'First'.

**Comment by stwe** [comment]
I set this issue to the wishlist. I have no idea at the moment.

**Comment by Minishlink** [comment]
I guess the only way to make this working would be to give up on `lineFormatter` and replace it with something using`DataTransformer`. Or any other way which makes formatting reversible.

**Comment by nopr0n** [comment]
Why not let the dev decide how the data should be searched ?
The searchs fields value should be accessible on the query callback.

**Comment by LaurentFl** [comment]
And if you allow multiple properties in the 'filter_property' with 'filter_type' => 'text', maybe it will work?
Something like this?

`public function getLineFormatter()
    {
        $router = $this->router;
        $formatter = function ($line) use ($router) {
            $route = $router->generate('member_get', array(
                'id' => $line['id']
            ));
            $line['first_name'] = '<a href="' . $route . '">' . $line['first_name'] . ' ' . $line['last_name'] . '</a>';
            return $line;
        };
        return $formatter;
    }
public function buildColumns()
    {
        $this->columnBuilder->add('first_name', 'column', array(
            'title' => $this->translator->trans('Name'),
            'filter_type' => 'text',
            'filter_property' => array(
                'first_name',
                'last_name'
            )
        ))
            ->add('last_name', 'column', array(
            'visible' => false
        ));
    }`

**Comment by stwe** [comment]
still no ideas

**Comment by chriskonnertz** [comment]
This is not a  solution for the problem, however:

Column Builder:
 
```
$this->columnBuilder
  ->add('firstName', 'column', [
      'searchable' => true,
      'visible' => false,
    ])
  ->add('lastName', 'column', [
      'searchable' => true,
      'visible' => false,
    ])
  ->add('name', 'virtual', [
      'title' => 'Name',
    ])
```

Line Formatter:

```
public function getLineFormatter()
{
    $formatter = function($line)
    {
        $line['name'] = $line['firstName'].'"The Great"'.$line['lastName'];

        return $line;
    };
    return $formatter;
}
```

This code won't work, one cannot search for invisible columns. Wouldn't it be better if this was possible? So you cannot find for 'John "The Great" Doe' but at least "John", "Doe" and I assume even "John Doe". Just an idea. Ofcourse this does not solve the whole problem.

**Comment by stwe** [comment]
The virtual column is search- and orderable in dev-master. And you can use the select-filter.

**Comment by Minishlink** [comment]
That's a nice Christmas present, thank you! :)
