### ISSUE TITLE
Search and sort "virtual" column?

### ISSUE THREAD

**Issue by lightzor** [stwe/DatatablesBundle#158]
Hello, Actually I use virtual columns to concat some elements, but after that, I can't anymore search or order the column ('searchable' => true, 'orderable' => true), it will responds an ajax error.

Is it a way to make it works or to concat (per exemple : Lastname + Firstname) in the same column and make it still searchable/orderable?

Thank you very much, you did a great work on this bundle !

**Comment by stwe** [comment]
Search and filter on a virtual column not yet implemented and disabled by default. Sorry.

**Comment by Minishlink** [comment]
You can build the datatable with 'lastname' and 'firstname' columns. Make 'lastname' as invisible. Use the lineFormatter to concatenate 'firstname' with 'lastname'. Then wait for fix #156 :)

**Comment by lightzor** [comment]
Well, the fact is I get some data from entities and the other point is I can't use line formater with associations. so customer.adress.town && customer.adress.country is not working if I use line formater I dunno why.

**Comment by Minishlink** [comment]
A line stores associations like this:

```php
$line['parent']['child'] = 'something'; // instead of $line['parent.child']

**Comment by lightzor** [comment]
Thanks ! Hope the #156 will be fix asap ! 

Thanks alot for your work again !

**Comment by stwe** [comment]
Same problem as in #156 .... I have no idea at the moment.
I set this issue to the wishlist.

**Comment by stwe** [comment]
still no ideas

**Comment by stwe** [comment]
https://github.com/stwe/DatatablesBundle/commit/4cd83a5abdce64ffc1a6bc1090330f371f1a9846

```php
            ->add('test', VirtualColumn::class, array(
                'title' => 'Test virtual',
                'searchable' => false,
                'orderable' => false,
                'order_column' => 'title',
                'search_column' => 'createdBy.username',
            ))
```
