### ISSUE TITLE
Datetime formating?

### ISSUE THREAD

**Issue by lightzor** [stwe/DatatablesBundle#161]
Hello, actually in the doc I just see we can format a date using "LLL" or less L...

But per exemple, if I'm from France and date the dates are in format "dd/MM/yyyy", how to get it working in the datatable ? And still being searchable and sortable? 

At the moment using 'date_format' => 'l' will print the date "7/8/2015" in the table (close to the result wanted), but then I can't search 7/8 it will print 0 results.

Thank you again for your big work and sorry for my english.

**Comment by stwe** [comment]
same as: #98 

Update your moment.js and datatables.js and try again.

**Comment by Minishlink** [comment]
Hello,
Do you have the lastest version of DataTables.js (1.10.7) and moment.js (2.10.3) ?
Cf #98 I had the same issue until I updated everything recently. I just don't know which plugin introduced the problem.

**Comment by lightzor** [comment]
Hello, well I'm using //cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.js and moment 2.9.0. How to print the date in an european format ?

**Comment by Minishlink** [comment]
It seems I get this problem when not using server-side.

@stwe, what about [this plugin](https://datatables.net/blog/2014-12-18) ?
