### ISSUE TITLE
AbstractDatatableView - constructor use deprecated method

### ISSUE THREAD

**Issue by kisztof** [stwe/DatatablesBundle#163]
Cannot set configs while implementing datatable. Constructor in AbstractDatatableView used deprecated method.

Got:
```
An exception has been thrown during the rendering of a template ("render(): The ajax url parameter must be given.") in CRMBundle:customer:index.html.twig at line 18.
```

**Comment by stwe** [comment]
That's right. See: #153 with all the examples. The deprecated function `buildDatatableView()` is called automatically. But that was not a good idea. You may use them as described in the examples to version 0.7. Starting with version 0.7.1, it is better to use the function `buildDatatable()` and call this in the controller.
