### ISSUE TITLE
Actions and selectbox

### ISSUE THREAD

**Issue by didoudine** [stwe/DatatablesBundle#165]
Hi everyone !

Before the release 0.7 we can have all actions of the datatable in a listbox. But now, the actions are automatically one after the other under the datatable.

This option (to get the actions in a listbox) is still available ? If yes, how can i implement it ?

Thanks a lot :)

**Comment by stwe** [comment]
You mean the multiselect actions? You can override the template (multiselect_actions.html.twig), as described here:

http://symfony.com/doc/current/book/templating.html#overriding-bundle-templates

Copy the multiselect_actions.html.twig template from the SgDatatablesBundle to `app/Resources/SgDatatablesBundle/views/Datatable/multiselect_actions.html.twig`

**Comment by didoudine** [comment]
Ok thanks for your help and your bundle ofc !
