### ISSUE TITLE
Entity without field named 'id'

### ISSUE THREAD

**Issue by paulnroll** [stwe/DatatablesBundle#167]
if I have other id field name, I get error.

```
"Error: There is no mapped field named 'id' on class"
```

query exception:

```
QueryException: SELECT partial users.{userId,userName,id} FROM
```

Look at the line:
https://github.com/stwe/DatatablesBundle/blob/master/Datatable/Data/DatatableQuery.php#L225

probably issue is there ;)

**Comment by stwe** [comment]
I know. At the moment, the identifiers are hard-coded. Sorry.  I'm going to change as soon as possible.
