### ISSUE TITLE
firefox datatable_length is empty by default

### ISSUE THREAD

**Issue by lightzor** [stwe/DatatablesBundle#171]
Hello,

In firefox, the datable_length "select" is empty by default (blank printed) instead of 10 per exemple.

This happen with firefox and not chrome. Any tips how to fix it?

Thank you !

**Comment by stwe** [comment]
Firefox (ESR 38.0.1) is my default browser and I can't reproduce the issue.

**Comment by stwe** [comment]
Can't reproduce.....
