### ISSUE TITLE
Datatable as multiselect form field

### ISSUE THREAD

**Issue by robertblock** [stwe/DatatablesBundle#173]
I think I'm missing something very, very simple. If so, please be gentle. I've been staring at this for too long.

I'd like to use a datatable as a multiselect form field as part of a larger form. For instance:

Name: Text Input
Category: Dropdown
Items: Datatable (would be Item 'entity' as multiselect in native Symfony form)
Submit: Submit

I know how to render the table, but I don't know the best way to post the form for validation.

Thanks in advance.

**Comment by stwe** [comment]
My bundle is only for the representation of the data. I can not recommend using the Bundle within a form therefore.
