### ISSUE TITLE
DataTable Info into view

### ISSUE THREAD

**Issue by alexandrePeccard** [stwe/DatatablesBundle#174]
Hello, 

I have a trouble in my project developping.
I can't reach the real number of entries into the DataTable info field into the view part.

I have a filter which decreases the field "number" in the Ajax action. 

By default the method adwareResult is used. Maybe I am wrong that's why i am asking a little bit help.
Is there a way to surchage it to get the good number or to add a direct filter on the field? Or any other method?
Currently we hide the row but ..

See the code above:

```php
    /**
     * Get all Post entities.
     *
     * @Route("/results", name="user_results")
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexResultsAction()
    {
        $datatable = $this->get('app.datatable.user');
        $datatable->buildDatatable();

        $query = $this->get('sg_datatables.query')->getQueryFrom($datatable);

        // Callback example
        $function = function($qb)
        {
            $qb->andWhere("company = :company")->setParameter('company', $this->getCompany());
        };

        // Add the callback function as WhereResult
        $query->addWhereResult($function);

        return $query->getResponse();
    }
```

Thanks a lot.

Alexandre

**Comment by stwe** [comment]
Try

    $query->addWhereAll($function);

instead

    $query->addWhereResult($function);
