### ISSUE TITLE
Update to 0.7.1 problem

### ISSUE THREAD

**Issue by remyma** [stwe/DatatablesBundle#176]
Hello
since composer update my depency to version v0.7.1 , datatable doesn't work anymore; 

I used getFeatures and setStyle methods
```php
$this->getFeatures()
            ->setServerSide(true)
            ->setProcessing(true);

$this->setStyle(self::BOOTSTRAP_3_STYLE);
```
but they doesn't exists in abstractDatatable anymore.  I noticed there is also a buildDatatable method to replace deprecated buildDatatableView, but this one is still called from constructor.

Can you explain how am i supposed to use this version ?
Should I rollback to 0.6 ?

Thanks

**Comment by stwe** [comment]
You should read the examples: https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/example.md

the new config style:

    public function buildDatatableView()
    {
        $this->features->setFeatures(array(
            'processing' => true
        ));

        $this->ajax->setOptions(array(
            'url' => $this->container->get('router')->generate('post_results')
        ));

        $this->options->setOptions(array(
            'paging_type' => Style::FULL_PAGINATION,
            'responsive' => true,
            'class' => Style::BASE_STYLE,
            'individual_filtering' => false
        ));

        // ...
    }

For the difference between `buildDatatable` and `buildDatatableView` you should read: #153, 
#163 and the changelog from v0.7.1 https://github.com/stwe/DatatablesBundle/blob/v0.7.1/CHANGELOG.md

**Comment by remyma** [comment]
Ok, thanks ;-)
