### ISSUE TITLE
Render "action" depending on data

### ISSUE THREAD

**Issue by MisterGrouik** [stwe/DatatablesBundle#180]
Hi.
For example.
I have en entity called "Car".
"Car" has an attribute "active".
If "active" = 0, I'd like to show the action "enable"
If "active" = 1, I'd like to show the action  "disable"

Is it possible in the current state of this bundle ? It appears not but I'm not sure. 

Regards (and thank you for this bundle).
Vincent

**Comment by stwe** [comment]
you can use the `render_if` option of the action column

    'render_if' => array('active')
