### ISSUE TITLE
Multiple entity managers

### ISSUE THREAD

**Issue by Peterknijff** [stwe/DatatablesBundle#181]
When retrieving an entity that is not in the default entity manager it fails. Is there any possibility to provide a specific entity manager in order to retrieve the correct entity?

In case this is not/"yet" possible, what should the approach be to fix this issue?

![schermafbeelding 2015-08-07 om 01 21 56](https://cloud.githubusercontent.com/assets/6030070/9125595/bdadc342-3ca2-11e5-8a56-3d7255d84acf.png)

**Comment by stwe** [comment]
multiple entity manager currently not supported

**Comment by Peterknijff** [comment]
Thanks for your reply! Any chance for support in the future?

Met vriendelijke groet,

Peter Knijff

Uniq Group - Fullservice evenementenbureau
Prins Reinierstraat 18L
<https://www.google.com/maps?cid=3293432129058344965>
4651 RZ - Steenbergen
*Ingang aan achterzijde pand (Bronkhorststraat)

Telefoon: 0167 - 70 05 12
Mobiel: 06 46 40 86 46

peter@uniq-group.nl
http://www.uniq-group.nl



2015-08-21 17:23 GMT+02:00 Steffen <notifications@github.com>:

**Comment by stwe** [comment]
@Peterknijff : I think so. Multiple entity managers are often desired by professional developers. I set the feature to wishlist.

**Comment by stwe** [comment]
oh no I do not know my own program .I'm on vacation, sorry. Try to inject the non default entity manager to your DatatablesClass. 
http://stackoverflow.com/questions/13118288/how-to-inject-non-default-entity-managers

**Comment by Peterknijff** [comment]
Hi Steffen, thanks for you reply! Well that sounds interesting, sounds
logically.

Do you know how I can pass the entity manager tot the class itself. I'm
trying to pass the entity manager as a parameter but i'm getting an error.

Catchable Fatal Error: Argument 1 passed to
Sg\DatatablesBundle\Datatable\View\AbstractDatatableView::__construct()
must implement interface
Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface,
instance of
EntityManager55d84a2f1deee_546a8d27f194334ee012bfe64f629947b07e4919\__CG__\Doctrine\ORM\EntityManager
given.

Do you know how I can pass default values as parameters within this
service?

Have a nice vacation though! Thanks in advance.

**Comment by stwe** [comment]
try:

    app.datatable.server_side.post:
        class: AppBundle\Datatables\PostDatatable
        arguments: [@security.authorization_checker, @security.token_storage, @twig, @translator.default, @router, @uniq_rental_entity_manage, %sg_datatables.datatable.templates%]
        tags:
            - { name: sg.datatable.view, alias: post_datatable }

another example is: #153

**Comment by Peterknijff** [comment]
Thank you Steffen,

Got it working thanks to your advice, a litte note on your reply, parameter
%sg_datatables.datatable.templates% should
be %sg_datatables.default.layout.options%.

Thanks a lot!

**Comment by stwe** [comment]
That was renamed:
version 0.7.1 = %sg_datatables.default.layout.options%
master = %sg_datatables.datatable.templates%
