### ISSUE TITLE
4th level associations not working

### ISSUE THREAD

**Issue by nielsvermaut** [stwe/DatatablesBundle#182]
Hi again, 

I'm trying to create a table with a deep association to load test how performant Datatables can get. However it throws an error whenever I try to go deeper than level 2

Take in account

Message
- (Author)
- ....

Author
- (Image)
- ...

Image
- (Alt)
- url
- ...

Alt
- (Showoff)
- ...

Showoff
- endian

```
           //This works
            ->add('author.image.url', "column", [
                "title" => "Image",
                "searchable" => false,
                "orderable" => false,
            ])
           // This doesn't
            ->add('author.image.alt.showoff.endian', "column", [
                "title" => "Alt Id",
                "searchable" => false,
                "orderable" => false,
            ])
```

```
[Syntax Error] line 0, col 283: Error: Expected end of string, got 'alt'
```

Any ideas on how to make this work?

**Comment by stwe** [comment]
I know. But you really need that?

**Comment by Gielovic** [comment]
I don't see why you would not support this, as it worked in previous versions (0.6.1). I can imagine a case in which you try to mimic a hierarchical structure (i.e. customer who lives in a street, city, state, country, continent). If I want to show the country in a list of customers, this would not be possible right now.

As I mentioned, it did work in previous versions,

**Comment by stephanvierkant** [comment]
+1. This would be really usefull.

**Comment by celvin** [comment]
+1

**Comment by Gielovic** [comment]
Really looking forward to this. I'm having great difficulty to enhance the old version of the datatable. Somehow, using a CSS rule to put filter fields on top does not work anymore.

**Comment by stwe** [comment]
@Gielovic 

this puts filter on the top

```php
        $this->options->set(array(
            'individual_filtering' => true,
            'individual_filtering_position' => 'head'
            // ...
        ));
```

**Comment by colinodell** [comment]
+1 I really need this functionality.

Are there any workarounds beside downgrading to an older version?

**Comment by colinodell** [comment]
@nielsvermaut  and @Gielovic: If you need this functionality and are stuck on 0.7.1, I've got a patch here which seems to work well: #280.  Haven't tested it on 0.7.0 though, and it definitely needs changes to work for newer versions.
