### ISSUE TITLE
Count relationship

### ISSUE THREAD

**Issue by bnd170** [stwe/DatatablesBundle#183]
Its posible to get a relationship nº of rows relationed?

Line a entity.relation|lenght

**Comment by stwe** [comment]
Please describe exactly what you want to do.

**Comment by bnd170** [comment]
Wanna to show related records between two tables.
FOSUserBundle for example, I want to show a counter indicating the total groups in which each user included.

Example:

User           email          Total groups
bNd            myemail           5

**Comment by stwe** [comment]
That is a very good idea. I'm going to implement as soon as possible.

**Comment by bnd170** [comment]
Thanks a lot! Would be nice.

Btw the bundle is awesome! :+1:

**Comment by stwe** [comment]
please try the `array` column type with the new render function `render_count` 

Example:

        $this->columnBuilder
            // ...
            ->add("posts.comments.title", "array", array(
                "title" => "Comments titles",
                'render' => 'render_count',          // <----- set this render function
                "data" => "posts[, ].comments[, ].title"  // <---- must be set correctly
            ))
            ->add("posts.comments.comment", "array", array(
                "title" => "Comments comments",
                'render' => 'render_count',
                "data" => "posts[, ].comments[, ].comment"
            ))
            ->add('posts.comments.comment', 'array', array(
                'title' => 'Posts count',
                'render' => 'render_count',
                "data" => "posts[, ].title"
            ))
        ;

Check your results and set the right data option!

**Comment by bnd170** [comment]
It works, but I added a check by passing data as empty, the cell returned "1"

```

    function render_count(data, type, row, meta) {
        var array = data.split(',');
        return (data == '') ? 0 : array.length;
    }
```

**Comment by stwe** [comment]
I have changed the count config.

Example:

            ->add('posts.comments.title', 'array', array(
                'title' => 'Posts comments',
                'count' => true,
                'data' => 'posts[, ].comments[, ].title',
                'count_action' => array(
                    'route' => 'post_show',
                    'route_parameters' => array(
                        'id' => 'id'
                    ),
                    //'label' => 'Comments',
                    //'icon' => 'fa fa-eye-slash',
                    'attributes' => array(
                        'rel' => 'tooltip',
                        'title' => 'Comments',
                        'class' => 'badge alert-info',
                        //'class' => 'btn btn-primary btn-xs',
                        'role' => 'button'
                    ),
                )
            ))

The result of the above config with Bootstrap3 is a nice href-badge:

![count](https://cloud.githubusercontent.com/assets/2964748/9611971/3c422140-50e3-11e5-9df9-c062a562f16a.jpg)

**Comment by stephanvierkant** [comment]
I would like to reopen this issue. The given solution is a JavaScript, but I think a ``count()`` action should be done server side. That makes filtering possible, so you are can order the user list by number of comments, find posts without comments, etc. 

Some explanation why it can't be a client side script for me: @alrayyes and I are building a bridge between this bundle and PHPExcel. The current file export functions ([TableTools](http://datatables.net/extensions/tabletools/)) work client side (using html5 or flash) and they are a real pain. They depend on the user's browser and I've removed that option from our applications because I get too many complaints from my customers.

If all rendering is done server side, it can exported to csv/xls/xslx/odf easily using our bridge/bundle. I think that would be great and I will publish our bundle when it's ready. I'd love your comments on that.

**Comment by zgoniaiko** [comment]
@stwe can you please check if ordering by count works for you on v0.11

I try with many-to-many relation and try to order by num of entities ("Posts comments" num in example)

as result I see error

```
Cannot select distinct identifiers from query with LIMIT and ORDER BY on a column from a fetch joined to-many association. Use output walkers.

Stack Trace

    in vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryWalker.php at line 149
    at LimitSubqueryWalker ->validate (object(SelectStatement))
    in vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryWalker.php at line 74
    at LimitSubqueryWalker ->walkSelectStatement (object(SelectStatement))
    in vendor/doctrine/orm/lib/Doctrine/ORM/Query/TreeWalkerChain.php at line 113
    at TreeWalkerChain ->walkSelectStatement (object(SelectStatement))
    in vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php at line 380
    at Parser ->parse ()
    in vendor/doctrine/orm/lib/Doctrine/ORM/Query.php at line 281
    at Query ->_parse ()
    in vendor/doctrine/orm/lib/Doctrine/ORM/Query.php at line 293
    at Query ->_doExecute ()
    in vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php at line 969
    at AbstractQuery ->executeIgnoreQueryCache (null, '3')
    in vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php at line 924
    at AbstractQuery ->execute (null, '3')
    in vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php at line 751
    at AbstractQuery ->getScalarResult ()
    in vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/Paginator.php at line 151
    at Paginator ->getIterator ()
    in vendor/sg/datatablesbundle/Sg/DatatablesBundle/Datatable/Data/DatatableQuery.php at line 757
```

**Comment by stephanvierkant** [comment]
@stwe What's the status on this? Do you agree a `count()` should/could be done server side?

**Comment by stwe** [comment]
yes, but with currently low priority .

**Comment by manseuk** [comment]
I'm willing to have a look at doing this - got a one to many table with ~10,000 records - all i need is a count - so its far better to do this server side.

What are your thoughts on implementation ?
