### ISSUE TITLE
Render on client the first page and the rest on the server

### ISSUE THREAD

**Issue by jneto81** [stwe/DatatablesBundle#184]
It is possible to render the data on the client the first time, for the first grid page, and after, get the data from the server ? A mix between server side and client side.

**Comment by stwe** [comment]
No. For large data, the server-side option should be used. see: https://datatables.net/examples/server_side/simple.html Otherwise, the client-side

**Comment by jneto81** [comment]
My idea is to build a dashboard with +- 20 grids. And i don't want to make + 20 request just to load the grids, after the initial request, and making the user wait for the grids to appear.

I try to make the mix, changing your code, and it works but with some problems with the total entries and number of pages.

In AbstractDatatableView, on render, i add

```php
        if (null !== $this->data) {
            $options['view_data'] = $this->data;
        }
```

and on ajax.html.twig i add  "data": {{ view_data|raw }} on the server side code
```
{% if view_features.serverSide %}
    "serverSide": true,
    "data": {{ view_data|raw }},
    "ajax": {
        "url": "{{ view_ajax.url }}",
        "type": "{{ view_ajax.type }}"
    },
{% else %}
    "serverSide": false,
    "data": {{ view_data|raw }},
{% endif %}


```
On the controller, i use setData and the initial data is set on the javascript. It works, except for the total and pages. ( because of the defer_loading )
I know is not a perfect solution, but it is what i need. 
What do you think about this approach ?
