### ISSUE TITLE
Bootstrap 3 styling of DataTable

### ISSUE THREAD

**Issue by fleskalebas** [stwe/DatatablesBundle#185]
First, thanks for this bundle! I use it to upgrade my existing datatables to a serverside generated one, for faster loading times.

I used to use bootstrap 3 styling for datatables (with the extra datatables.bootstrap.js) but it seems that one isn't working with this bundle.

My datatable class has the bootstrap option set:
`'class' => Style::BOOTSTRAP_3_STYLE,` and my javascript includes all necessary files:

`{% block javascripts %}
		{{ parent() }}
		{% javascripts 'js/jquery.dataTables.min.js' 'js/dataTables.bootstrap.js' 'js/moment.js'%}
			<script src="{{ asset_url }}"></script>			
		{% endjavascripts %}
		{{ datatable_render_js(datatable) }}
	{% endblock %}`

The table itself is styled, but:
- The search input is on the next line instead of the same line as the amount of result select box
- Pagination is flat text instead of Bootstrap layout pagination.

I looked into it and the difference between my old datatable and the new one, generated by your bundle, is that my old datatable wraps the pagination in `<ul><li></li></ul>` but yours doesn't. The datatables.bootstrap.js file is responsible for wrapping in list items but it doesn't work.

What can I do about this? :)

**Comment by stwe** [comment]
@fleskalebas : This bundle works very well with Bootstrap3. Please look at my example: https://github.com/stwe/dtbundle-demo

You must set `use_integration_options` to true.

    $this->options->setOptions(array(
        'paging_type' => Style::FULL_NUMBERS_PAGINATION,
        'class' => Style::BOOTSTRAP_3_STYLE . ' table-condensed', // default: Style::BASE_STYLE
        'use_integration_options' => true // default is false
     ));

please give me feedback

**Comment by fleskalebas** [comment]
I will try it monday. Haven't see the 'use_integration_option' in the documentation. Was a little bit hard to find ;)

**Comment by fleskalebas** [comment]
It worked! Thank you!

**Comment by grekpg** [comment]
what about 1.x version ? 
i add : 'classes' => Style::BOOTSTRAP_3_STYLE. ' table-condensed',
and combine : 
$this->features->set(array(
            'scroll_x'=>true,
            'auto_width'=>true,
        ));

but horizontal scrolling is not showing
