### ISSUE TITLE
Client-Side mode - Multiselect doesnt refresh data

### ISSUE THREAD

**Issue by bnd170** [stwe/DatatablesBundle#186]
After accepting confirm that activates the column type "multiselect" launches the call is fine, but does not refresh the table.

Have I forgotten anything configuration?

**Comment by stwe** [comment]
In my test environment that works properly.
Look at my example: https://github.com/stwe/dtbundle-demo

**Comment by jongreig** [comment]
I'm having the same problem, but with client-side rendering set. On looking at the JS for the 'success' AJAX response, the only action that is triggered is `oTable.draw();`, which looks like that assumes it will be server-side-rendered data.

**Comment by stwe** [comment]
Ok I'll try that.

**Comment by stwe** [comment]
The Client-Side mode currently does not work with all features. There are some problems with the Buttons-Extension and MultiSelectColumn. At the moment I can not say whether the Client-Side mode is supported by me in the future. Priority has the Server-Side mode.

**Comment by stwe** [comment]
The ClientSide mode is no longer supported by me.
