### ISSUE TITLE
How to get sum in oneToMany

### ISSUE THREAD

**Issue by fleskalebas** [stwe/DatatablesBundle#193]
Imagine I have two entities: User and Vehicles. A user can have multiple Vehicles. Vehicles has four columns: id, user_id, vehicle_type, amount.

I have made a Datatable of the User entity, this works fine. I added an array_column with
```
->add('vehicles.id', 'array', array(
	'render' => 'render_count', // set this render function for a counter
	'data' => 'vehicles[, ].id'
))
```
With this I have the count of vehicles, but not the total amount (that is SUM(amount)). How can I get the sum of all vehicles of an user in a column?

**Comment by stwe** [comment]
You can try the line formatter with a virtual column.

Example:

1) Your Repo-Function

    public function getPlantSum($seasonId)
    {
        return $this->createQueryBuilder('p')
            ->select('SUM(p.quantity)')
            ->join('p.season', 's')
            ->where('s = :seasonId')
            ->setParameter('seasonId', $seasonId)
            ->getQuery()
            ->getSingleScalarResult();
    }


2) Formatter

    /**
     * {@inheritdoc}
     */
    public function getLineFormatter()
    {
        $formatter = function($line) {
            $repository = $this->em->getRepository('AppBundle:Plant');
            $sum = $repository->getPlantSum($line['id']);
            $line['plants'] = $sum;

            return $line;
        };

        return $formatter;
    }

2) your column:

            ->add('plants', 'virtual', array(
                'title' => 'Plants'
            ))


However, at the moment a virtual column is not sortable and not searchable.

**Comment by mssimi** [comment]
This is very bad solution since it call query in loop.
