### ISSUE TITLE
Is it possible to make our own column types?

### ISSUE THREAD

**Issue by migmolrod** [stwe/DatatablesBundle#194]
Just that: is it possible to make our own column types?
I think it could be a pretty nice feature. A bit like the custom form field types in original Symonfy 2 Form component.

**Comment by stwe** [comment]
yes. see #56 

You can use your custom column type, simply by creating a new instance of the type:

    $this->columnBuilder
        ->add("title", new CustomColumn(), array( /* ... */ ));

**Comment by migmolrod** [comment]
Thank you very much, mate. Sorry for the duplicate.

And what a great piece of art we have here in this bundle :) Thanks for all this work.
