### ISSUE TITLE
Filter class

### ISSUE THREAD

**Issue by migmolrod** [stwe/DatatablesBundle#195]
Would it be possible to add a new property to AbstractColumn, called filterClass (filter_class) so we can apply css classes to filter inputs (text or select) separately?
I see that https://github.com/migmolrod/DatatablesBundle/blob/master/Resources/views/Filters/filter_text.html.twig
has just an '.individual_filtering' class applied and no way to add our own classes to it.

Then https://github.com/migmolrod/DatatablesBundle/blob/master/Resources/views/Filters/filter_select.html.twig
is not better. It has the '.individual_filtering' class as well, but it also looks at {{ column.class }} which I think is a bit wrong. Because if you want to apply '.select2' class to the select field, you're also applying it to the th and every td below it.

If a separated property was used, we could easily have select filters using Select2 or make text filters match the rest of our text inputs without messing up the rest of the datatable.

I can try to make a PR with those changes. Hope I don't break anything :joy:

**Comment by stwe** [comment]
The filter has already five properties in AbstractColumn and is a candidate for refactoring.
