### ISSUE TITLE
Short array notation

### ISSUE THREAD

**Issue by migmolrod** [stwe/DatatablesBundle#197]
I think this is critical.

The composer.json states that the bundle only needs php >= 5.3.2
The reality is that it need php >= 5.4 because it uses short arrays notation here and there.
I mean, with
```php
$myvar = [ ];
```
instead of
```php
$myvar = array();
```

I think we should either correct the php requirement in composer.json or change the short arrays for normal pre 5.4 arrays. If you ask me, I find better the second option.

**Comment by migmolrod** [comment]
New PR to sort this out
https://github.com/stwe/DatatablesBundle/pull/198

**Comment by stwe** [comment]
merged pr #198
