### ISSUE TITLE
Apply filter twig to column of datatable

### ISSUE THREAD

**Issue by yblancof2** [stwe/DatatablesBundle#201]
Good morning need twig apply a filter to a column of datatable. For example I have a 'name' column and want to apply the filter truncate twig to reduce the amount of carateres. I hope you can help me. Best regards

**Comment by stwe** [comment]
try to use the line-formatter

example:

https://github.com/stwe/dtbundle-demo/blob/master/src/AppBundle/Datatables/PostDatatable.php
