### ISSUE TITLE
Uncaught SyntaxError: Unexpected number

### ISSUE THREAD

**Issue by stephanvierkant** [stwe/DatatablesBundle#202]
I tried the dtbundle-demo, but I'm getting a JS error. 

A ``Uncaught SyntaxError: Unexpected number`` is caused by this line:

https://github.com/stwe/DatatablesBundle/blob/master/Resources/views/Column/action.html.twig#L50

**Comment by alrayyes** [comment]
I have the same issue in Firefox & Chrome. It appears they don't accept comparison operators as parameters to the Boolean object. Why is Boolean used here?

**Comment by stwe** [comment]
This is is an dtbundle-demo issue!

render_if should be used as follows:

                        'render_if' => array(
                            'visible' => true
                        )
