### ISSUE TITLE
Override twig template

### ISSUE THREAD

**Issue by MisterGrouik** [stwe/DatatablesBundle#205]
Hi.

Is it possible to override the default template ? I saw the configurator, but it only lets you define one template at once.
How can I define multiple template and use differents one for my datatables ?

**Comment by stwe** [comment]
You can override the template (e.g. multiselect_actions.html.twig), as described here:

http://symfony.com/doc/current/book/templating.html#overriding-bundle-templates

e.g.: Copy the multiselect_actions.html.twig template from the SgDatatablesBundle to app/Resources/SgDatatablesBundle/views/Datatable/multiselect_actions.html.twig
