### ISSUE TITLE
Set dom when use_integration_options = true

### ISSUE THREAD

**Issue by stephanvierkant** [stwe/DatatablesBundle#206]
When ``use_integration_options`` is set to ``true``, ``dom`` is ignored. I think you should be able to change it anyway.

It's also useful for https://github.com/stwe/DatatablesBundle/issues/203.

**Comment by stwe** [comment]
Example: The DataTables integration for Bootstrap 3 use their own `dom`, so that the use_integration_option does the right job.

```js
/* Set the defaults for DataTables initialisation */
$.extend( true, DataTable.defaults, {
	dom:
		"<'row'<'col-sm-6'l><'col-sm-6'f>>" +
		"<'row'<'col-sm-12'tr>>" +
		"<'row'<'col-sm-5'i><'col-sm-7'p>>",
	renderer: 'bootstrap'
} );
```
