### ISSUE TITLE
Multiple primary keys

### ISSUE THREAD

**Issue by stephanvierkant** [stwe/DatatablesBundle#210]
I've got an entity with a composite key (multiple primary keys). I see the generator doesn't support it, but does this bundle?

I'm having this error: 
> Error: The partial field selection of class AcmeBundle\Entity must contain the identifier.

**Comment by stwe** [comment]
This bundle does not support multiple Ids

**Comment by stephanvierkant** [comment]
Are there any plans yet to support it?

**Comment by stephanvierkant** [comment]
I changed my code: it now uses a unique index instead of a composite primary key (which it was a good idea for many other reasons), so I don't need this feature anymore. So if nobody else cares, you can lower the priority of this feature request.

**Comment by LaurentFl** [comment]
I also have an identity with multiple primary keys and I've found a workaround:
 - You need to add an invisible column with the second key of the association. It will generate a correct Partial in the Doctrine query.

Example with User / UserGroup / Group:
 - User and Group : contains the OneToMany (Note: I had to rename $user_groups to $userGroups to avoid an error: Class AppBundle\Entity\User has no association named groups ???):
```
    // User class
    /**
     * @ORM\OneToMany(targetEntity="UserGroup", mappedBy="user", cascade={"persist"}, orphanRemoval=true)
     */
    protected $userGroups;
```
 ```
    // Group class
    /**
     * @ORM\OneToMany(targetEntity="UserGroup", mappedBy="groupp", cascade={"persist"}, orphanRemoval=true)
     * @ORM\OrderBy({"display" = "ASC"})
     */
    protected $user_groups;
```
 - UserGroup: contains the ManyToOne:
    ```
    /**
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="User", inversedBy="userGroups")
     */
    protected $user;

    /**
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="Group", inversedBy="user_groups")
     */
    protected $groupp;
```

And in the DataTable class:
```
public function buildColumns()
    {
        // First invisible column to generate correct Partial query
        $this->columnBuilder->add('userGroups.groupp', 'column', array(
            'visible' => false
        ))
            ->add('userGroups.groupp.name', 'array', array(
            'title' => $this->translator->trans('Groups'),
            'data' => 'userGroups[, ].groupp.name'
        ))
    }
```

Hope this can help!

**Comment by LaurentFl** [comment]
After more tests, this "workaround" leads to unexpected results...
I've finally added an unique id to my table.
