### ISSUE TITLE
some portions of datatable not rendering

### ISSUE THREAD

**Issue by alanscott** [stwe/DatatablesBundle#213]
![screen shot 2015-10-11 at 7 25 30 pm](https://cloud.githubusercontent.com/assets/6107646/10421799/8aa65d38-7064-11e5-9de5-3b6101fd4062.png)

Something, somewhere, in my implementation of this wonderful bundle is broken. Instead of getting a properly rendered lengthMenu, or pagination, or search... I'm stuck with the default placeholders. I have verified the properties I set in my Datatable class are being passed and making it to the `defaults` object in the JavaScript. But something is keeping them from being interpreted by the DataTable.

I know it must be something in my configuration, but I've run out of places to look. Any thoughts as to what process/setting/ghost-in-the-machine might interrupt the interpretation of the values passed to the `$(element).DataTable()` call?

**Comment by alanscott** [comment]
And here is the `DataTable` object taken as it exists right before:
```
            console.log(defaults);
            if ( $.fn.dataTable.isDataTable( selector ) ) {
                            } else {
                var oTable = $(selector).DataTable(defaults);
            }
```

```
aLengthMenu: Array[4]0: 101: 252: 503: 100
length: 4__proto__: Array[0]
aaSorting: Array[1]
ajax: ObjectaoColumns: Array[10]
aoSearchCols: Array[10]
asStripeClasses: Array[1]
autoWidth: true
bAutoWidth: true
bDeferRender: false
bFilter: true
bInfo: true
bJQueryUI: false
bLengthChange: true
bPaginate: true
bProcessing: true
bScrollCollapse: false
bServerSide: true
bSort: true
bSortClasses: true
bSortMulti: true
bStateSave: false
columns: Array[10]
deferRender: false
delay: 0
displayStart: 0
dom: "lfrtip"
iDisplayLength: 10
iDisplayStart: 0
iStateDuration: 7200
info: true
jQueryUI: false
language: Object
lengthChange: true
lengthMenu: Array[4]
oLanguage: Object
order: Array[1]
orderClasses: true
orderMulti: true
ordering: true
pageLength: 10
paging: true
pagingType: "full_numbers"
processing: true
renderer: ""
sDom: "lfrtip"
sPaginationType: "full_numbers"
sScrollX: ""
sScrollY: false
scrollCollapse: false
scrollX: false
scrollY: false
searchCols: Array[10]
searchDelay: 0
searching: true
serverSide: true
stateDuration: 7200
stateSave: false
stripeClasses: Array[1]
```

**Comment by migmolrod** [comment]
Have you enabled translation in Symfony itself?
http://symfony.com/doc/current/book/translation.html#configuration

Those placeholders you say are typical untranslated keys when you either don't have the translation component working or the messages files are missing.

**Comment by alanscott** [comment]
@migmolrod 
You were right. I had overlooked enabling translation. Thanks!
