### ISSUE TITLE
Indexes for setParameter already used

### ISSUE THREAD

**Issue by aruku** [stwe/DatatablesBundle#219]
I ran into this problem this morning and I haven't seen any notice about it the documentation, so I'll post it just in case it can be solved in someway (or maybe is not a bug but a feature in Doctrine):

If you do the following to apply a filter:
```
                $qb->andWhere('vulco_product.family = ?1');
                $qb->setParameter(1, $family);
```

DatatablesBundle will use the param you are providing here for other comparisons in its query, not just  in the one you are adding, so the results will be messed up or probably you will not get any results at all (which is what happened to me because the bundle was using the id of the ```$family``` entity to filter by the name on the related entity).

An obvious fix is to use strings as identifiers for the parameter:
```
                $qb->andWhere('vulco_product.family = :family');
                $qb->setParameter('family', $family);
```

**Comment by stwe** [comment]
i have no issue with:

```php
        $functionVisible = function($qb)
        {
            $qb->andWhere("post.visible = ?1");
            $qb->setParameter(1, true);
        };

       $query->addWhereAll($functionVisible);
```

What exactly is the problem?

**Comment by aruku** [comment]
It was using the value passed in the "initial" part of the query, the one that it generates without you adding anything else.
This is the resulting query:
```
SELECT DISTINCT id_3 FROM (SELECT v0_.id AS id_0, v0_.name AS name_1, v0_.rate_price AS rate_price_2, v0_.id AS id_3, v0_.name AS name_4, v0_.rate_price AS rate_price_5 FROM vulco_product v0_ WHERE ((v0_.id LIKE '%ut%' OR v0_.name LIKE 3 OR v0_.rate_price LIKE '%ut%') AND v0_.family_id = 3) AND (v0_.site = 'es') AND (v0_.removed_at IS NULL)) dctrn_result ORDER BY id_0 ASC LIMIT 25 OFFSET 0
```

It included the filter I needed (```AND v0_.family_id = 3```), but also another wrong one (```OR v0_.name LIKE 3```) where it usually queries for the string you use to filter the results.

**Comment by aruku** [comment]
You can test it adding the callback for your own filter and using the search feature on the tables.
