### ISSUE TITLE
How to integrate translations ? 

### ISSUE THREAD

**Issue by whitewhidow** [stwe/DatatablesBundle#221]
i have a column,   wich is a property, wich has been moved to a translation entity, as per A2LIX documentation,   how can i get this column to show up ?

**Comment by stwe** [comment]
A2LIX translations? This one?: https://github.com/a2lix/I18nDoctrineBundle. This Bundle is not supported. Sorry.

**Comment by whitewhidow** [comment]
yep,   then switched to gedmotranslatables,   not working either .

**Comment by whitewhidow** [comment]
your code is building its own query, completely ignoring any translations-related doctrine stuff ..?

**Comment by stwe** [comment]
Yes. And for information: this bundle is only in version 0.7.x. available. I'm trying to develop it in my free time after work and on weekends!! Everything I can not immediately implement. For my private projects, it is good. sorry.

**Comment by migmolrod** [comment]
I have it perfectly working. And with perfectly, I mean that the column actually shows the correct translated value.

1st step: use A2lixI18nDoctrineBundle or KnpDoctrineBehaviors or any other with an indexBy strategy for translation storage. Read and follow the instructions in their documentation.

2nd step: now treat your translatable column like any other relationship, because that's all translations actually are: relationships between translatable entities and their counterpart translation entities.

Sample from my project:

```php
public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver);

	    $resolver->setDefaults(array(
		    'name' => 'name',
		    'title' => $this->translator->trans('name'),
		    'title_icon' => 'fa fa-pencil fa-fw fa-lg',
		    'data' => 'translations[, ].name',
		    'default' => $this->translator->trans('fallback.nontranslated', array(), 'messages'),
	    ));

        $resolver->setRequired(array('data'));
        $resolver->addAllowedTypes('data', 'string');

        return $this;
    }
```
Pay extra attention to the 'data' => 'translations[, ].name' part, that does all the magic.

**Comment by whitewhidow** [comment]
I managed to get that far last iime, before posting

is `'data' => 'translations[, ].name` not normally used to get comma seperated list, of the name properties of entities in a relation?

anyways, i started work on my own datagrid from scratch, in wich it simply works with `->addColumn('name')`, and boem, its translated..

added dynamic filtering, wich also takes into account the translations, added paging, added bulk actions, added custom templating, added custom rowactions, added sorting and much more. i'll be uploading it all to github in a few days, it still needs some massive cleanup,   when its up, feel free to take a look at how i took care of the tanslations, im sure you can use it to improve upon your code aswell

**Comment by stwe** [comment]
You ask the question of whether something is supported. This question I have answered. Write your own bundle and upload it. No problem. We're glad. But your last comment ("im sure you can use it to improve upon your code aswell") was simply stupid. Something nobody needs here.

**Comment by stwe** [comment]
Example with `Gedmo`: 

// Post entity:

```php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Translatable\Translatable;

/**
 * Class Post
 *
 * @ORM\Table()
 * @ORM\Entity
 * @Gedmo\TranslationEntity(class="PostTranslation")
 *
 * @package AppBundle\Entity
 */
class Post implements Translatable
{
    /**
     * @var integer
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @Gedmo\Translatable
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @Gedmo\Locale
     * Used locale to override Translation listener`s locale
     * this is not a mapped field of entity metadata, just a simple property
     */
    private $locale;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="PostTranslation", mappedBy="object", cascade={"persist", "remove"})
     */
    private $translations;

    public function __construct()
    {
        // ...

        $this->translations = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->title;
    }

    /**
     * Set title.
     *
     * @param string $title
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title.
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    public function getTranslations()
    {
        return $this->translations;
    }

    public function addTranslation(PostTranslation $translation)
    {
        if (!$this->translations->contains($translation)) {
            $this->translations[] = $translation;
            $translation->setObject($this);
        }
    }

    public function setTranslatableLocale($locale)
    {
        $this->locale = $locale;
    }
}
```

// Post datatable

```php
            ->add('title', 'column', array(
                'title' => 'Title',
            ))
```

// DatatableQuery
```php
    /**
     * Constructs a Query instance.
     *
     * @return Query
     */
    private function execute()
    {
        $query = $this->qb->getQuery();

        $query->setHint(
            \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );
        
        $query->setHint(
            \Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE,
            'it'       //  <=======   Example; @todo: implement getLocale()
        );

        $query->setHydrationMode(Query::HYDRATE_ARRAY);

        return $query;
    }
```

**Comment by stwe** [comment]
@migmolrod : can you try out my solution?

**Comment by whitewhidow** [comment]
Why did you even remove your comment ? 

> You ask the question of whether something is supported. This question I have answered. Write your own bundle and upload it. No problem. We're glad. But your last comment ("im sure you can use it to improve upon your code aswell") was simply stupid. Something nobody needs here.

Well,  im not a native English speaker, so im sorry if my comment came across the wrong way, wich it clearly did.   but you are right, calling people's comments stupid, is the way to go. i'll go ahead and leave your repo now, since i know im not welcome here. bye

**Comment by stwe** [comment]
@whitewhidow : everything is ok. you are welcome.

**Comment by drbarzaga** [comment]
Tengo un datatable que esta asociado a una entidad y esta a su vez tiene una entidad de tradiciones usando KnpDoctrineBehaviors, pero cuando decido mostrar un campo de la entidad que esta en la entidad de traducion usando todo lo mencionado arriba obtengo el siguiente error:

Cannot select distinct identifiers from query with LIMIT and ORDER BY on a column from a fetch joined to-many association. Use output walkers.

Alguien sabe cual puede ser la causa?
