### ISSUE TITLE
call method with argument

### ISSUE THREAD

**Issue by didoudine** [stwe/DatatablesBundle#224]
Hi everyone !

I'd like to know how to call a method with arguments in "data" options for "array" column.

**Comment by stwe** [comment]
As `data` option is only a string allowed. What do you want to do?

**Comment by didoudine** [comment]
- I have 3 entities : "Sample", "Property" and "SampleProperty".

- "Property" constains samples attributes definition and can be modify by users.

- "SampleProperty" contains values and indexes of "Sample" and "Property".

- I have a getProperty(Property.id) method which returns "SampleProperty" object.

- I want to display all property values for each sample in datatable.


Thanks for help me.
