### ISSUE TITLE
Problem after composer update

### ISSUE THREAD

**Issue by bnd170** [stwe/DatatablesBundle#228]
I'm installing new bundles into my project.

Before `composer update` all works fine, but when the commands ends... my symfony2 shows me this error.

> Datatables\DrawDatatable::buildDatatable() must be compatible with Sg\DatatablesBundle\Datatable\View\DatatableViewInterface::buildDatatable($locale = NULL)

**Comment by stwe** [comment]
Replace buildDatatable () with buildDatatable ($locale=null) in your Datatable and Controller classes.
