### ISSUE TITLE
isDatatable

### ISSUE THREAD

**Issue by proflore17** [stwe/DatatablesBundle#229]
Hello 
uncaught typeError cannot read property 'isDatatable' of undefined

I follow the installation but the Datatable seems empty.

**Comment by stwe** [comment]
I think you have not successfully integrated the DataTables plug - in in your project .

**Comment by proflore17** [comment]
Great.
I did not insert the datatable js file. 
Now I only have the header of the table.
Here is the error that I face to : Uncaught Error: The route "fraistransactions_show" does not exist.
when I do  a debug the route is listed. 
Thanks

**Comment by stwe** [comment]
https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/Resources/doc/index.md

add this to your route annotations:

```php
options={"expose"=true}
```

Example:

```php
    /**
     * Finds and displays a Post entity.
     *
     * @Route("/{id}", name="post_show", options={"expose"=true})
     * @Method("GET")
     * @Template(":post:show.html.twig")
     */
    public function showAction($id)
```

**Comment by proflore17** [comment]
Sure. Thanks a lot
