### ISSUE TITLE
Edit colum value

### ISSUE THREAD

**Issue by proflore17** [stwe/DatatablesBundle#232]
Hello

just a question: is it possible to edit a column value inside the datatable

Thank you

**Comment by stwe** [comment]
No
Am 19.11.2015 18:51 schrieb "proflore17" <notifications@github.com>:

**Comment by proflore17** [comment]
hello stwe

can I use jquery modal for the edit action in the datatable. 
I don't want  redirection to another page for editing

thank you

**Comment by migmolrod** [comment]
You'll need to take a look at datatables documentation itself, specially the "Editor" extension: https://editor.datatables.net/

Although I guess you're on your own and you'll need to implement it internally in your project.
