### ISSUE TITLE
Options for daterangepicker

### ISSUE THREAD

**Issue by BigZ** [stwe/DatatablesBundle#237]
Hi there,

I'd like to customize a few options for daterangepicker (locale, in my case). 
I have to make a choice for my PR : 
- make a "daterangepickerLocale" option which would be fool-proof but limited in feature
- make a "daterangepickerOptions" array that would be future-proof but not that explicit. One would get a json encoded array in twig.

Should this option have global or local scope ? (whole datatable vs. one column)
Or both ?

Have a nice day every one,

**Comment by stwe** [comment]
Hi Romain, I am totally not satisfied with the current integration of dateRangepicker. 
All good features depend on Bootstrap. That was never the goal of this bundle. But all use it.

```html
        {% block foot_javascripts %}
            <script type="text/javascript">
                $( document ).ready(function() {
                    moment.locale("{{ app.request.locale }}");
                    $('input[name="daterange"]').daterangepicker();
                });
            </script>
        {% endblock %}
```

The filter and all filter options i will refactor for v0.9. Currently I set in the datetime column the name on dateRange and I have a DateRangePicker. This is very confusing. In my opinion local options should be set globally. The filter option should come into the Column.

**Comment by stwe** [comment]
Hi @BigZ can I still expect a pr ?

**Comment by BigZ** [comment]
for sure. i was unsure you expected it !

**Comment by stwe** [comment]
It would make us happy :+1:
