### ISSUE TITLE
tag request

### ISSUE THREAD

**Issue by inmarelibero** [stwe/DatatablesBundle#239]
hi, could you please tag the master branch? I was trying to use the `$this->features->set(array())` method, but v0.7.1 does not have it

**Comment by BigZ** [comment]
while waiting for it, you can use dev-master

**Comment by stwe** [comment]
The next release is already planned for late of November 2015...

**Comment by inmarelibero** [comment]
@stwe ok thanks

**Comment by stwe** [comment]
@inmarelibero : Has been done. Version 0.8 is available .

**Comment by inmarelibero** [comment]
cool, thanks!
Il 01/dic/2015 23:50, "Steffen" <notifications@github.com> ha scritto:
