### ISSUE TITLE
Query Callbacks : error when no results

### ISSUE THREAD

**Issue by MisterGrouik** [stwe/DatatablesBundle#243]
I have an error when I use a query callback to filter the results rendered in the datatable if there's no results :
"No result was found for query although at least one row was expected"

In DatatableQuery.php, in getCountAllResults() and getCountFilteredResults(), by changing 
return (int) $qb->getQuery()->getSingleScalarResult();

with

return (int) $qb->getQuery()->getOneOrNullResult();

It works again. I think you should change it.

Regards

**Comment by MisterGrouik** [comment]
It bugs when I use $query->addWhereAll($function). addWhereResult works correctly but sadly it's addWhereAll I want to use.

**Comment by stwe** [comment]
Sorry but i can't reproduce this issue. Show me your actions and your datatables class. thanks.

**Comment by MisterGrouik** [comment]
Datatable class:
    <?php

   namespace Topo\FormBundle\Datatables;

   use Sg\DatatablesBundle\Datatable\View\AbstractDatatableView;
   use Sg\DatatablesBundle\Datatable\View\Style;

   /**
    * Class UserAlerteComptaDatatable
    *
    * @package Topo\UserBundle\Datatables
    */
   class ReponseUserDatatable extends AbstractDatatableView {
      protected $type;

      /**
       * {@inheritdoc}
       */
      public function getLineFormatter() {
        $formatter = function ($line) {
          $line['type'] = $this->type;

          return $line;
        };

        return $formatter;
      }

      public function setType($type) {
         $this->type = $type;
      }

      public function buildDatatable($locale=null) {
         /*
         $this->callbacks->setCallbacks(array(
             'draw_callback' => "function( settings ) {
                                     alert( 'DataTables has redrawn the table' );
                                 }"
         ));
         */

         $this->features->set(array(
           'auto_width' => false,
           'defer_render' => false,
           'info' => true,
           'jquery_ui' => false,
           'length_change' => true,
           'ordering' => true,
           'paging' => true,
           'processing' => true,
           'scroll_x' => false,
           'scroll_y' => '',
           'searching' => true,
           'server_side' => true,
           'state_save' => false,
           'delay' => 0
         ));

         $this->ajax->set(array(
           'url' => $this->router->generate('topo_form_reponse_get_user_datatable', array('type' => $this->type)),
           'type' => 'GET'
         ));

         $this->options->set(array(
           'display_start' => 0,
           'dom' => '<"datatables_header"lf>rt<"datatables_footer"ip>', // default, but not used because 'use_integration_options' = true
           'length_menu' => array(10, 25, 50, 100),
           'order_classes' => true,
           'order' => [[0, 'asc']],
           'order_multi' => true,
           'page_length' => 10,
           'paging_type' => Style::FULL_NUMBERS_PAGINATION,
           'renderer' => '', // default, but not used because 'use_integration_options' = true
           'scroll_collapse' => false,
           'search_delay' => 800,
           'state_duration' => 7200,
           'stripe_classes' => array(),

           'class' => Style::JQUERY_UI_STYLE,
           'individual_filtering' => true,
           'individual_filtering_position' => 'foot',
           'use_integration_options' => false
         ));

         $user = $this->em->getRepository('TopoUserBundle:User')->findAll();

         $this->columnBuilder
           ->add('id', 'column', array(
             'class' => '',
             'padding' => '',
             'name' => '',
             'orderable' => true,
             'render' => null,
             'searchable' => false,
             'title' => 'Id',
             'type' => '',
             'visible' => true,
             'width' => '40px',
             'default' => ''
           ))
           ->add('email', 'column', array(
             'title' => $this->translator->trans('user.datatable.email'),
             /*'width' => '120px',*/
             'searchable' => true,
           ))
            //Action : désinscription
                  ->add(null, 'action', array(
                    'title' => $this->translator->trans('user.datatable.header.reponses'),
                    'start_html' => '<div class="wrapper">',
                    'end_html' => '</div>',
                    'actions' => array(
                      array(
                        'route' => 'topo_form_reponses',
                        'route_parameters' => array(
                            'id_user' => 'id',
                            'type' => 'type'
                        ),
            //            'label' => $this->translator->trans('user.datatable.action.lire_reponses'),
                        'icon' => 'glyphicon glyphicon-search',
                        'attributes' => array(
                          'rel' => 'tooltip',
                          'title' => $this->translator->trans('user.datatable.action.lire_reponses'),
                          'class' => '',
                          'role' => 'button'
                        ),
                      ),
                    )
                  ))
         ;
      }

      /**
       * {@inheritdoc}
       */
      public
      function getEntity() {
         return 'Topo\UserBundle\Entity\User';
      }

      /**
       * {@inheritdoc}
       */
      public
      function getName() {
         return 'reponse_user_datatable';
      }
   }

Controller action : 
    public function user_listAction($type) {
         $datatable = $this->get('datatable.reponse.user');
         $datatable->setType($type);
         $datatable->buildDatatable();

         return $this->render('TopoFormBundle:Reponse:user_list.html.twig', array(
           'datatable' => $datatable,
           'type' => $type
         ));

      }

Then

    public function user_list_datatableAction($type) {
         $datatable = $this->get('datatable.reponse.user');
         $datatable->setType($type);
         $datatable->buildDatatable();
         $query = $this->get('sg_datatables.query')->getQueryFrom($datatable);


         // Pour customiser la requête de récup des users
         $function = function ($qb) use ($type) {
            $qb->join('users.reponses', 'r', 'WITH', 'r.type = :type');
            $qb->where('r.etat_validation = :etat_validation');
            $qb->groupBy('users.id');
            $qb->setParameter('type', $type);
            $qb->setParameter('etat_validation', 0);
         };

         $query->addWhereAll($function);

         $results = $query->getResponse()->getContent();
         return new Response($results);
      }

As you can see in user_list_datatableAction, there's the query callback I was talking about.
Its function is to filter my "User" list to keep the users I want.
It can happens that this filter gives back no results at all, and that's where I have the error message I described in my first post.

**Comment by MisterGrouik** [comment]
Looks like I was able to workaround this bug using the third method (Get Query) described here, instead of the first :
https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/query.md

Still, I'm not sure if this is normal that the first method doesnt work.

**Comment by stwe** [comment]
I am now trying to cause these NoResultException since one or two hours. I do not succeed.
