### ISSUE TITLE
PostgreSQL and filtering (only case sensitive)

### ISSUE THREAD

**Issue by ownede** [stwe/DatatablesBundle#244]
Hi there,

My project is using PostgreSQL as a database and Doctrine2 as ORM. 
Since PostgreSQL "LIKE" is case sensitive, the column filtering feature in datatables works only case sensitive.

Is there any way to force using ILIKE (this might require [DoctrineExtensions ILIKE](https://github.com/domudall/DoctrineExtensions/blob/master/lib/Dmno/DoctrineExtensions/Comparison/Postgresql/Ilike.php) I guess) to make filtering more user friendly?

**Comment by stwe** [comment]
PostgreSQL is not supported. Sorry.

same as #30 and #124

**Comment by celvin** [comment]
I'm using the bundle with postgreSQL 9.4 perfectly

Celvin Rivas
http://www.vitelika.com
7126-9172 (24/7)
2231-1165 (8am-3pm / L-V)

**Comment by ownede** [comment]
@stwe PostgreSQL works great, just case-sensitive filtering is a problem.

**Comment by stwe** [comment]
see: #297

**Comment by max4kaps** [comment]
Hi stwe! The fix in commit 05787a8 is workable. Are there more concerns to reopen? Cannot it go to pull request?

**Comment by stwe** [comment]
@max4kaps : sorry I don't not understand what is your exact question. It is planned a fully postgresql support. However, I can only work on weekends at the bundle....

**Comment by acanthis** [comment]
For russian string search:
in file Datatable\Data\DatatableQuery.php change

**Comment by Oliver-Gibson** [comment]
Solution provided by @acanthis is the easiest to put in place, it will however increase significantly the queries costs. Here is a cheaper solution:

Create new class in bundle's DQL directory:

`<?php

namespace Sg\DatatablesBundle\DQL;

use Doctrine\ORM\Query\AST\Functions\FunctionNode;
use Doctrine\ORM\Query\Lexer;
use Doctrine\ORM\Query\SqlWalker;
use Doctrine\ORM\Query\Parser;

class IMatchFunction extends FunctionNode
{
    
    public $strExpression = null;
    public $patternExpression = null;

    public function parse(\Doctrine\ORM\Query\Parser $parser)
    {
        $parser->match(Lexer::T_IDENTIFIER);
        $parser->match(Lexer::T_OPEN_PARENTHESIS);
        $this->strExpression = $parser->StringPrimary();
        $parser->match(Lexer::T_COMMA);
        $this->patternExpression = $parser->StringPrimary();
        $parser->match(Lexer::T_CLOSE_PARENTHESIS);
    }

    public function getSql(\Doctrine\ORM\Query\SqlWalker $sqlWalker)
    {
        return '(' . $this->strExpression->dispatch($sqlWalker) . ' ilike ' .
            $this->patternExpression->dispatch($sqlWalker) .
        ')';
    }

}`

Inside setupPostgreSQL function in Datatable\Data\DatatableQuery.php just after :

`$this->em->getConfiguration()->addCustomStringFunction('CAST', '\Sg\DatatablesBundle\DQL\CastFunction');`

Add:

`$this->em->getConfiguration()->addCustomStringFunction('IMATCH', '\Sg\DatatablesBundle\DQL\IMatchFunction');`

Still in DatatableQuery.php replace:

`$orExpr->add($qb->expr()->like($searchField, '?' . $key));`

With

`$orExpr->add('(IMATCH(' . $searchField . ',' . '?' . $key . ') = true)');`

And in Datatable\Filter\AbstractFilter.php inside getAndExpression function replace

`$andExpr->add($pivot->expr()->like($searchField,  '?' . $i ));`

With

`$andExpr->add('(IMATCH(' . $searchField . ',' . '?' . $i . ') = true)');`

**Comment by ownede** [comment]
If someone needs to use case insensitive filtering, I've made a custom filter:
```php

<?php
/**
 * PostgreSQL Case Insensitive Filter
 * @author Kacper Smółkowski <kacpero@gmail.com>
 */
class CaseInsensitiveFilter extends TextFilter
{
    /**
     * {@inheritdoc}
     */
    public function addAndExpression(Andx $andExpr, QueryBuilder $pivot, $searchField, $searchValue, &$i)
    {
        $searchValue = strtolower($searchValue); // instead ILIKE
        $searchField = $pivot->expr()->lower($searchField);

        $andExpr = $this->getAndExpression($andExpr, $pivot, $searchField, $searchValue, $i);
        $i++;

        return $andExpr;
    }

    /**
     * {@inheritdoc}
     */
    public function getAlias()
    {
        return 'caseInsensitive';
    }

}
```

Usage:
```php
<?php

$this->columnBuilder->add("some.field", 'column', [
     'title' => 'Some title',
     'filter' => [new CaseInsensitiveFilter(), ['search_type' => 'like']],
]);
```

**Comment by ljmoleiro** [comment]
i had the same problem , but the @ownede  solution works good !!!!!! thank you

**Comment by stwe** [comment]
Hey folks. Bad news: I'm not working with PostgreSQL. I have no idea about it and therefore can not write any good software supporting PostgreSQL. I also don' t like it. Therefore, I will close all the issues. Feel free to forke the bundle. Thanks for your understanding and greetings.

**Comment by abhijitgujar86** [comment]
> ```
> like
> ```

Hi can you explain how to implement this in short please ?

**Comment by abhijitgujar86** [comment]
@ownede  can you please explain how and where to implement your code ?

**Comment by ownede** [comment]
> @ownede can you please explain how and where to implement your code ?

Just create new filter class (which I pasted up) somewhere in project (namespace YourProject\Datatable\Filter or something like that) and use it like I proposed
