### ISSUE TITLE
TypeError: oTable.buttons is not a function

### ISSUE THREAD

**Issue by olix21** [stwe/DatatablesBundle#254]
I use your bundle with Bootstrap3.
So I've set 
'class' => Style::BOOTSTRAP_3_STYLE,
'use_integration_options' => true,

But I've a javascript error in the rendering:
	
oTable.buttons().container().appendTo('#' + oTable.table().container().id + ' .c...

table (ligne 573, col. 37)

**Comment by stwe** [comment]
You need to install the buttons extension. 
https://datatables.net/extensions/buttons/
