### ISSUE TITLE
Set a ID to a TR or TD depending on a value

### ISSUE THREAD

**Issue by witzkito** [stwe/DatatablesBundle#255]
Hello there,

¿There any way to do something like this?
![captura-datatables](https://cloud.githubusercontent.com/assets/3853111/12116719/a45cea84-b39a-11e5-88d4-2c2b7fdff5cb.png)

Add a class or id to change format with css depending a value of a column.

Thanks!

**Comment by stwe** [comment]
Use a callback function.
Am 05.01.2016 15:09 schrieb "Fernando" <notifications@github.com>:

**Comment by witzkito** [comment]
Thanks for the hint.
I make it  using a draw_callback!

```
public function buildDatatable($locale = null)
    {
     $this->callbacks->set(array(
            'draw_callback' => "function( settings ) {
                                   var cells = document.getElementsByClassName('estado');
                                   for (var i=0, len=cells.length; i<len; i++){
                                        if (cells[i].textContent == 'Baja'){
                                            cells[i].parentElement.style.color = 'red';
                                        }
                                    }
                                }"
        ));
```

**Comment by stwe** [comment]
Thank you. 
This is a good example of the use of callback functions.

**Comment by gcrome** [comment]
This doesn't work with virtual columns.. :(
