### ISSUE TITLE
In-place editing with x-editable

### ISSUE THREAD

**Issue by gcrome** [stwe/DatatablesBundle#263]
Hi!
Is it posible to integrate an inline editing feature? (https://editor.datatables.net/examples/inline-editing/simple). If so, do you have an example? If not, it would be one really nice-tohave...
;)

**Comment by stwe** [comment]
That is possible and planned for the future.

**Comment by gcrome** [comment]
Nice! I'm really looking forward to this!

**Comment by stwe** [comment]
see: https://github.com/stwe/DatatablesBundle/commit/6815edc01972df683397694624fd9a80d7d9685d

This is my first attempt to integrate x-editable.

![editable](https://cloud.githubusercontent.com/assets/2964748/12704024/cdef779c-c851-11e5-8183-6ca1fc1f8736.jpg)

Setup your project:

1. Install x-editable
2. setup column

```
            ->add('title', 'column', array(
                'title' => 'Titel',
                'editable' => true
            ))
```

**Comment by stwe** [comment]
This is currently in progress:

![datetime](https://cloud.githubusercontent.com/assets/2964748/12732283/20c6121c-c935-11e5-911a-acbd386eab4e.jpg)
