### ISSUE TITLE
filter_search_column

### ISSUE THREAD

**Issue by eugenekkh** [stwe/DatatablesBundle#264]
Behaviour of the option "filter_search_column" in column has bug. The bug related with the feature of php. See http://stackoverflow.com/questions/4100488/a-numeric-string-as-array-key-in-php
So, this code is not valid (View/Filters/filter_select.html.twig)
```twig
<option value="{{ key }}" {% if key is sameas(column.filterSearchColumn) %}selected{% endif %}>{{ name }}</option>
```
Variable key usually integer, but filterSearchColumn string. === compare return false all times.

https://github.com/stwe/DatatablesBundle/commit/eafe92362ab6492184d4b4d38aedee75da315ed6

```twig
{% for key,name in column.filterOptions %}
    {{ dump(key) }}{{ dump(column.filterSearchColumn) }}
{% endfor %}
```
![2016-01-30 1 47 52](https://cloud.githubusercontent.com/assets/8081158/12683334/3db7e374-c6eb-11e5-93f7-0d81a31d6cbd.png)

**Comment by stwe** [comment]
Ok. Thank you. I'll try that.

**Comment by stwe** [comment]
You're right. This code

```
{% if key is sameas(column.filterSearchColumn) %}selected{% endif %}
```

is not valid.

The `selected` attribute specifies only that an option should be pre-selected when the page loads. It is not required for this bundle. I use the `value` attribute for the selection .
