### ISSUE TITLE
Remove column, but allow filtering on that column

### ISSUE THREAD

**Issue by stephanvierkant** [stwe/DatatablesBundle#265]
First of all: you're doing a great job! Last year I switched from another datatablebundle and I was already impressed at that time. And it's even getting better!

One of the featured I missed was removing a column in the controller. I see that feature is added: https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/columnBuilder.md. But I still would like to filter on that column.

Let's say I've got a UserDataTable with columns Id, Username, Email, Organisation. When I go to /users/1 I'd like to see all users within Organisation id=1. The Organisation column is useless, but when I open /users/ I'd like to see all my users.

Is it possible to remove columns, but still filter on them?

**Comment by stwe** [comment]
Thanks Stephan. :+1: 

Do not(!) use these functions:

```
    // remove by data 
    $datatable->getColumnBuilder()->removeByData('createdby.id');
    // or remove by key
    $datatable->getColumnBuilder()->removeByKey(2);
```

The filters no longer works correctly. 

I 'll write you a solution to your problem as soon as I have time.

**Comment by stwe** [comment]
@stephanvierkant : is it still relevant?

**Comment by stephanvierkant** [comment]
Yes, I think it is. Or is it already possible to filter on a column (in the controller) and then remove the column?

**Comment by stephanvierkant** [comment]
Well, it is now possible. This is what I've done (simplified):

In my controller (`/users/{organisation}/`):
```
$options = [
    'organisation' => $organisation
]
$datatable = $this->get('sg.datatable.user');
$datatable->buildDatatable($options);
$query = $this->get('sg_datatables.query')->getQueryFrom($datatable);

$query->addWhereAll(function (QueryBuilder $qb) use ($organisation) {
    $qb->andWhere("organisation = " . $organisation->getId());
});
```

In my UserDatatable:
```
public function buildDatatable(array $options = [])
    {
        $orgOptions = [
            'visible' => isset($options['organisation']) ? false : true;
        ];
        $this->columnBuilder->add('organisation.name', 'column', $orgOptions)
    }
```

This will remove the 'organisation' column when the organisation is set, but will still show it when you don't set the organisation.
