### ISSUE TITLE
Use RequireJS

### ISSUE THREAD

**Issue by stephanvierkant** [stwe/DatatablesBundle#267]
This bundle relies on many JS scripts (jquery, datatable, daterangepicker, bootstrap, moment, jsrouting, etc.). I would like to use RequireJS to load all scripts modulair. I'm not using jsrouting, moment or daterangepicker on every page, so I don't want them to load at all.

Are there any plans to support RequireJS? If not, I will try to make a PR.

**Comment by stwe** [comment]
That would be very cool. :+1: That is a very good idea.

Please use the `requirejs` branch.

**Comment by stwe** [comment]
@stephanvierkant : Can you update the messages.nl.yml ???

**Comment by stephanvierkant** [comment]
What do you mean? I haven't done anything yet related to this issue.

**Comment by stwe** [comment]
the messages.nl.yml is not up to date. This has nothing to do with this issue.

**Comment by stwe** [comment]
I think that was a good idea. However managing css files with require.js is a problem. So I close this issue for the moment.
