### ISSUE TITLE
Add background color or class to whole raw

### ISSUE THREAD

**Issue by bnd170** [stwe/DatatablesBundle#272]
Hi stwe,

I have a suggestion to add a background color or class to the entire record if certain cases.

For example, a list of bugs, which are corrected to know, which are to be corrected, which are critical ...

to choose a state of bootstrap http://getbootstrap.com/css/#tables-contextual-classes

**Comment by stwe** [comment]
You can use a datatables callback function ....
Am 10.02.2016 14:09 schrieb "bnd170" <notifications@github.com>:

**Comment by bnd170** [comment]
Can you explain that please?

**Comment by witzkito** [comment]
Hey Bnd, look this issie, https://github.com/stwe/DatatablesBundle/issues/255.
I use callback function to set text-color to a row whit determinate class.

**Comment by bnd170** [comment]
Yes! Thx a lot witzkito, thats exactly i need.
