### ISSUE TITLE
Define an initial search for individual columns

### ISSUE THREAD

**Issue by oidnus** [stwe/DatatablesBundle#274]
How set default value (true) in individual_filtering. I can display on start only isActive field set on true, but can't see option in column options

**Comment by stwe** [comment]
This is currently not implemented. Sorry.

**Comment by stwe** [comment]
Use the `search_column` filter option.

Example:

```
            ->add('name', 'column', array(
                'title' => 'Name',
                'filter' => array('text', array(
                    'search_column' => 'Steffen'
                ))
```
