### ISSUE TITLE
tag 0.9: requesting "friendsofsymfony/jsrouting-bundle": "dev-master"

### ISSUE THREAD

**Issue by inmarelibero** [stwe/DatatablesBundle#276]
in https://github.com/stwe/DatatablesBundle/blob/v0.9/composer.json#L23 you are requesting
`dev-master`
for friendsofsymfony/jsrouting-bundle.

I think this is causing some troubles when (and it should always be so) you don't have
`"friendsofsymfony/jsrouting-bundle": "dev-master"`
in composer.json

**Comment by stwe** [comment]
Requesting `dev-master` is never a good idea. Only for v0.9 and the Symfony3 compatibility it was necessary.

see my tag request at: https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/issues/229

For the next version (0.10) I have updated my composer.json

```
    "require": {
        "php": ">=5.3.2",
        "symfony/framework-bundle": "~2.6|~3.0",
        "friendsofsymfony/jsrouting-bundle": "~1.6"
    },
```
