### ISSUE TITLE
Call entity function for column

### ISSUE THREAD

**Issue by ripnet** [stwe/DatatablesBundle#277]
How can I have the contents of a column be the result of a function on the entity being displayed? For instance, I have a getCalculatedValue() in my Entity class, and I need that to be displayed in a column.

**Comment by stwe** [comment]
Example from my [PepperSeason-Project](https://github.com/stwe/PepperSeason)

1. My [Plant Repository](https://github.com/stwe/PepperSeason/blob/master/src/AppBundle/Entity/PlantRepository.php) has a getPlantSum function:

```
    public function getPlantSum($seasonId)
    {
        return $this->createQueryBuilder('p')
            ->select('SUM(p.quantity)')
            ->join('p.season', 's')
            ->where('s = :seasonId')
            ->setParameter('seasonId', $seasonId)
            ->getQuery()
            ->getSingleScalarResult();
    }
```

2. And this is the [Plant datatables class] (https://github.com/stwe/PepperSeason/blob/master/src/AppBundle/Datatables/PlantDatatable.php). I use the Line Formatter....

```
    public function getLineFormatter()
    {
        $repository = $this->em->getRepository('AppBundle:Plant');
        $router = $this->router;

        $formatter = function($line) use ($repository, $router) {
            $sum = $repository->getPlantSum($line['id']);
            null === $sum ? $line['allPlants'] = 0 : $line['allPlants'] = $sum;

            $route = $router->generate('season_show', array('id' => $line['id']));
            $line['title'] = '<a href="' . $route . '">' . $line['title'] . '</a>';

            return $line;
        };

        return $formatter;
    }
```

**Comment by ripnet** [comment]
Works perfect! Thank you!

**Comment by dnagirl** [comment]
May I suggest you add this example to the [LineFormatter ](https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/lineFormatter.md)docs? It is a very common use case and not at all intuitive.

**Comment by stwe** [comment]
you are right. 
Did I just finished.
