### ISSUE TITLE
Export to pdf and excel 

### ISSUE THREAD

**Issue by oidnus** [stwe/DatatablesBundle#279]
Export to pdf and excel display when visible is false

**Comment by stwe** [comment]
I need detailed informations

**Comment by oidnus** [comment]
In your demo application, I edit postDatatable.php and set attribute  'visible' => false on title. In browser column is invisible but in pdf is still visible 

`  ->add('title', 'column', array(
                'title' => 'Title',
                'editable' => true,
                'visible' => false,
            ))`

**Comment by stwe** [comment]
This is not ab bug. See: https://datatables.net/extensions/buttons/examples/html5/columns.html

Use `extend` and `exportOptions` to show or not show columns.

Example:

```
        $this->features->set(array(
            'scroll_x' => false,
            'extensions' => array(
                'buttons' =>
                    array(
                        'excel',
                        'pdf' => array('extend' => 'pdf', 'exportOptions' => array('columns' => array('1', '3'))),
                    ),
                'responsive' => true
            )
        ));
```
