### ISSUE TITLE
Postgresql global search for timestamp field

### ISSUE THREAD

**Issue by sn0opr** [stwe/DatatablesBundle#283]
Hello,
I'm using Postgresql database,
When searching with the global search input, I get an SQL error because the PostgreSQL doesn't handle the LIKE operator for timestamps

```
SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: timestamp without time zone ~~ unknown
LINE 1: ..._.id WHERE f1_.username LIKE $1 OR a0_.created_at LIKE $2 OR...
^
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

**Comment by stwe** [comment]
@sn0opr : see https://github.com/stwe/DatatablesBundle#6-limitations-and-known-issues

Postgresql is not supported. Sorry.

**Comment by sn0opr** [comment]
@stwe that would be awesome if we handle the database drivers, for those who encoutred the same problem, I changed the code source of the Sg\DatatablesBundle\Datatable\Data\DatatableQuery class after line 476

```
......
if ($this->em->getConnection()->getDriver()->getName() == 'pdo_pgsql' && $column->getAlias() == 'datetime') {
                        $searchField = 'CAST(' . $searchField . ' AS string)';
                    }
.......
```

**Comment by stwe** [comment]
see: #297
