### ISSUE TITLE
datetime column is not working

### ISSUE THREAD

**Issue by animacoder** [stwe/DatatablesBundle#285]
`$this->columnBuilder
            ->add('bitisTarihi', 'datetime', array(
                'title' => 'Created',
                'date_format' => 'LLL' // default = "lll"
            ))
        ;`

when I add a datetime column, datatable doesn't work.

**Comment by stwe** [comment]
And what is the error message in firebug?
Am 24.02.2016 13:54 schrieb "Taner Deliloglu" <notifications@github.com>:

**Comment by animacoder** [comment]
date object is coming with timestamp. 
![ekran resmi 2016-02-24 15 00 58](https://cloud.githubusercontent.com/assets/5382990/13286094/90287f30-db07-11e5-9761-98fff114b0e9.png)

**Comment by animacoder** [comment]
![ekran resmi 2016-02-24 15 03 25](https://cloud.githubusercontent.com/assets/5382990/13286165/0377bcc6-db08-11e5-88ef-d7948dd8b868.png)

**Comment by animacoder** [comment]
I solved with this way but datetime column has been string field: 
` $formatter = function ($line) 
  {
        $line['bitisTarihi'] =  $line['bitisTarihi']->format('d-m-Y');
        return $line;
  };`

` ->add('bitisTarihi', 'column', array(
                'title' => 'Created'
 ))`

**Comment by stwe** [comment]
The timestamp ist the expected result. Did you moment.js installed ?
