### ISSUE TITLE
Request: Multiple select filter

### ISSUE THREAD

**Issue by sn0opr** [stwe/DatatablesBundle#287]
Adding a multiselect filter would be awesome, this is possible with a jquery plugin like SumoSelect [SumoSelect](http://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html)

Thank you

**Comment by stwe** [comment]
or this one: http://davidstutz.github.io/bootstrap-multiselect/

**Comment by sn0opr** [comment]
http://silviomoreto.github.io/bootstrap-select/ is a good choice, clean and simple.

**Comment by oidnus** [comment]
Why not use select2 ?

**Comment by stwe** [comment]
@oidnus I use select2 now in another project and it is also my favorite.
