### ISSUE TITLE
Fails when Sensio-GeneratorBundle is not available

### ISSUE THREAD

**Issue by lsv** [stwe/DatatablesBundle#289]
Sensio Generator bundle is by default only available when require-dev is installed.

With this command ```composer --no-dev install``` the bundle is not installed.

Because of the command ```[GenerateDatatableCommand](https://github.com/stwe/DatatablesBundle/blob/master/Command/GenerateDatatableCommand.php)``` extends a command from SensioGeneratorBundle then the install fails with

```
PHP Fatal error:  Class 'Sensio\Bundle\GeneratorBundle\Command\GenerateDoctrineCommand' not found in <path> vendor/sg/datatablesbundle/Sg/D atatablesBundle/Command/GenerateDatatableCommand.php on line 32
```

My suggestion is to not extend the GenerateDoctrineCommand but integrate the method "parseShortcutNotation" with your own (which is the only method used as far as I can see) and then add the method isEnabled with something like this

```
public function isEnabled()
{
        return class_exists('Sensio\Bundle\GeneratorBundle\Command\GenerateDoctrineCommand');
}
```

**Comment by stwe** [comment]
see: https://github.com/stwe/DatatablesBundle/commit/8b99777aa51fc757dae1f6c805e9f5a70c82a337

**Comment by stwe** [comment]
Now I have an issue:

```bash
C:\xampp\htdocs\DevDatatables>php app/console sg:datatable:generate AppBundle:Post

Fatal error: Call to undefined method Sg\DatatablesBundle\Command\GenerateDatatableCommand::getGenerator() in C:\xampp\htdocs\DevDatatables\src\Sg\DatatablesBundle\Command\GenerateDatatableCommand.ph
p on line 85
[2016-02-29 18:37:37] php.CRITICAL: Fatal Error: Call to undefined method Sg\DatatablesBundle\Command\GenerateDatatableCommand::getGenerator() {"type":1,"file":"C:\\xampp\\htdocs\\DevDatatables\\src\
\Sg\\DatatablesBundle\\Command\\GenerateDatatableCommand.php","line":85,"level":-1,"stack":[]}


  [Symfony\Component\Debug\Exception\UndefinedMethodException]
  Attempted to call an undefined method named "getGenerator" of class "Sg\DatatablesBundle\Command\GenerateDatatableCommand".

```

**Comment by lsv** [comment]
upodated PR #290

**Comment by alister** [comment]
I've recently updated my own code to use 1.0 of the bundle and it is still extending `GenerateDoctrineCommand`, and so a production deployment fails. 

The original code is still there as of v1.0 - https://github.com/stwe/DatatablesBundle/blob/v1.0/Command/CreateDatatableCommand.php

**Comment by alister** [comment]
When `Sg\DatatablesBundle\Command\CreateDatatableCommand` was created (replacing GenerateDatatableCommand ), this fix (PR #290) was not ported to the new command, and so the v1.0 release extends the `Sensio\Bundle\GeneratorBundle` which does not exist in a 'prod' environment.

**Comment by alister** [comment]
To solve this, I've put the GeneratorBundle into the main composer.json `require` section, as opposed to `require-dev`. It's still only enabled in the AppKernel as part of the dev-environment however.

**Comment by fyrye** [comment]
@alister I created a new issue since this issue was closed and the @stwe wouldn't be notified of any comments in it.
When I have time I may submit a pull request to resolve the issue.

**Comment by grekpg** [comment]
WARNING: This bundle does not support Symfony 4. It also does not support the new bundle-less directory structure as created by Symfony Flex. Use the Maker bundle instead.
