### ISSUE TITLE
Allow to override a column Where using a callback

### ISSUE THREAD

**Issue by sn0opr** [stwe/DatatablesBundle#295]
In my case I'm using PostgreSQL, datetimes can't be filted with a `WHERE date LIKE %:search%` so I have to add the CAST PostgreSQL function to cast the date to a string etc...

Another case: I had to filter with the IN clause example: `WHERE status IN (1, 2, 3)`

So allowing to override the where clause by a callback will allow us to handle many cases.

**Comment by stwe** [comment]
see #297
