### ISSUE TITLE
Return concatenated values in column type 'array'

### ISSUE THREAD

**Issue by RedLynux** [stwe/DatatablesBundle#296]
I am using the bundle to display a datatable of distribution lists. The primary entity has an affiliation table that joins the list entity and my user entity.

I am using the following code to display the first name of every user associated with a distribution list.
```
->add(
    'members.name_first',
    'array',
    [
        'data' => 'members[, ].name_first',
    ]
)
```

Is there a way to concatenate additional columns from the user table? I've tried creating three array columns (one for each piece of data I want to concatenate 'name_first', 'name_last', 'email') and then trying to use the LineFormatter to assemble the pieces into single strings but that solution seems at best clunky.

Ultimately I want the column to display data as such:
```
Luke Skywalker (lskywalker@jedi.com)
Leia Organa (lorgana@rebel.com)
Darth Vader (dvader@empire.com)
```

**Comment by sn0opr** [comment]
use the line formatter function: https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/lineFormatter.md

**Comment by RedLynux** [comment]
@sn0opr 
I think I was unclear in stating my issue.

I am trying to concatenate multiple properties from a single affiliation table. As I described above, I can define three array tables (one for each property from the user entity). But that returns such as:
`name_first: Luke, Leia, Darth`
`name_last: Skywalker, Organa, Vader`


ColumnBuilder segment:
```
$this->columnBuilder
    ->add(
        'members',
        'virtual',
        [
            'title'      => 'Member(s)',
            'searchable' => false,
            'orderable'  => false,
        ]
    )
    ->add(
        'members.name_first',
        'array',
        [
            'data'       => 'members[, ].name_first',
            'visible'    => false,
        ]
    )
    ->add(
        'members.name_last',
        'array',
        [
            'data'       => 'members[, ].name_last',
            'visible'    => false,
        ]
    )
    ->add(
        'members.email_canonical',
        'array',
        [
            'data'       => 'members[, ].email_canonical',
            'visible'    => false,
        ]
    )
    ->add(
        'members.email_canonical',
        'array',
        [
            'title'      => 'Count',
            'count'      => true,
            'data'       => 'members[, ].email_canonical',
            'searchable' => false,
            'orderable'  => false,
        ]
    );
```

Here is the LineFormatter that I'm trying:
```
$formatter = function ($line) {
    $name_first = explode(',', $line['members.name_first']);
    $name_last  = explode(',', $line['members.name_last']);
    $email      = explode(',', $line['members.email_canonical']);
    $members    = [];

    foreach ($name_first as $key => $value) {
        $members[] = "{$value} {$name_last[$key]} ({$email[$key]})";
    }

    $line['members'] = implode(', ', $members);
};
```

Obviously the line formatter logic is clunky. And it actually doesn't work, apparently the indexes don't exist that I expect (`members.name_first`, etc). So I was just hoping there was an alternative to the current `data` structure used in the `columnBuilder` when defining the property to return. Currently I am using notation such as `members[, ].name_first`.

**Comment by stwe** [comment]
work with your repositories in LineFormatter 
```
$user = $this->em->getRepository('AppBundle:User')->findById($line[createdBy])[id];
```

**Comment by RedLynux** [comment]
Ahh yes. That makes sense. Thanks.
