### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by stwe** [stwe/DatatablesBundle#297]
but it may take some time...

**Comment by celvin** [comment]
I'm using this bundle with PostgreSQL for production from one year ago, and I'm very happy with it.

**Comment by stwe** [comment]
@celvin : however, there are problems when searching.

**Comment by celvin** [comment]
Yeah, but with some fixes it works perfectly with PostgreSQL 9.x.

**Comment by stwe** [comment]
I have some issues (#283 and #244) fixed yesterday.

**Comment by stwe** [comment]
Hey folks. Bad news: I'm not working with PostgreSQL. I have no idea about it and therefore can not write any good software supporting PostgreSQL. I also don' t like it. Therefore, I will close all the issues. Feel free to forke the bundle. Thanks for your understanding and greetings.

**Comment by celvin** [comment]
Copy that, thanks I will do fork for PostgreSQL and MongoDB, thanks.
