### ISSUE TITLE
'throttle' of undefined

### ISSUE THREAD

**Issue by bnd170** [stwe/DatatablesBundle#298]
I get this on browser console when the tables prints.

I cant search by column also i cant filter any column :(

Uncaught TypeError: Cannot read property 'throttle' of undefined

> var throttledSearch = $.fn.DataTable.util.throttle(

**Comment by stwe** [comment]
see: https://datatables.net/reference/api/$.fn.dataTable.util.throttle%28%29

`throttle` is available since Datatables Version 1.10.3. you have installed the correct version ?

**Comment by bnd170** [comment]
Yes, that was the problem. Downloading the new version it fixes :+1: thanks a lot @stwe
