### ISSUE TITLE
Filtering non string attribute error (PostgreSQL)

### ISSUE THREAD

**Issue by DraCzris** [stwe/DatatablesBundle#30]
Searching on column, that entity attribute is not string, LIKE operator is not working a throwing error:

SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: integer ~~ unknown

HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.

(->setServerSide(true))

**Comment by stwe** [comment]
see #297

**Comment by stwe** [comment]
should be fixed
