### ISSUE TITLE
Translation with knplabs/doctrine-behaviors

### ISSUE THREAD

**Issue by cedricdenis** [stwe/DatatablesBundle#303]
Hi,
Are you planning to support translation with knplabs/doctrine-behaviors ?

When I order column with translations response is
> Cannot select distinct identifiers from query with LIMIT and ORDER BY on a column from a fetch joined to-many association. Use output walkers.

To solve this problem is to set parameter to true in getResponse function
`$fresults->setUseOutputWalkers(true); `

**Comment by stwe** [comment]
https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/translatable.md

**Comment by cedricdenis** [comment]
I am using knplabs/doctrine-behaviors and not stof/StofDoctrineExtensionsBundle
When translation_query_hints is set to true your plugin only detect stof/StofDoctrineExtensionsBundle installed

**Comment by giovkanata** [comment]
Any news on this? @cedricdenis how do you resolved this? I've just discovered this bundle and before to take a deeper look at the code (to resolve this myself) maybe you already have an example snippet to show or point me in the right direction.

**Comment by cedricdenis** [comment]
Thanks a lot for you answer,
I resolved this problem by setting to true the second parameter ($outputWalkers) of getResponse method of DatatableQuery class. For exemple:
```
/**
* @Route("/results", name="post_results")`
*/
public function indexResultsAction()
{
    $datatable = $this->get('app.datatable.post');
    $datatable->buildDatatable();

    $query = $this->get('sg_datatables.query')->getQueryFrom($datatable);

    return $query->getResponse(true, true);
}
```

And ordering work perfectely

**Comment by giovkanata** [comment]
Thanks to you @cedricdenis for the time saving.
