### ISSUE TITLE
In-place editing not work when Responsive Extension is true (child-rows)

### ISSUE THREAD

**Issue by SilvioMessi** [stwe/DatatablesBundle#305]
I have a Datatable with all fields editable. The responsive extension set at true makes the last columns of each row hidden and if i push the "plus" button these columns are shown in a child row but they are not editable.
After inspecting the page source i saw that the original columns are always hidden (display : none) and in the child row there are only a 'copies'. The problem is that the X-editable javascript is not called on this copies, because it's called only once (draw.dt callback).

**Comment by stwe** [comment]
@SilvioMessi Thanks for your PR. :+1: One problem: after editing column in responsive mode the table is not actual, but it is the right value in the database. I think it is necessary to redraw the table every time.
