### ISSUE TITLE
Make icons more flexible

### ISSUE THREAD

**Issue by cmfcmf** [stwe/DatatablesBundle#310]
I have an issue with [the `datatable_icon` Twig function](https://github.com/stwe/DatatablesBundle/blob/master/Twig/DatatableTwigExtension.php#L192), because I want to use [Google Material Icons](https://design.google.com/icons/) which work like this:
```html
<i class="material-icons">add</i>
```
However, it's currently not possible to add content between the `<i>` tags.
I see multiple solutions:
1. Use a template instead of a Twig function for the icons.
2. Add a global configuration option to specify the content of the `sprintf` statement in the `datatableIcon` Twig function.
3. ?

_By the way: I started using this bundle today and I'm quite impressed by it's functionalities! :100:_

**Comment by stwe** [comment]
Was fixed.

http://symfony.com/doc/current/book/templating.html#overriding-bundle-templates

Create a new template with name `icon.html.twig` in `app/Resources/SgDatatableBundle/views/Action/`

Danke für den Hinweis und Grüße nach Potsdam.

**Comment by cmfcmf** [comment]
Dankeschön! :smiley:

**Comment by marcopall** [comment]
please could you give us more details, I'm having same issue with font awsome and I'm almost newbie to symfony.
