### ISSUE TITLE
Action column - how to use voters is_granted('SHOW', entity)

### ISSUE THREAD

**Issue by Tomsgu** [stwe/DatatablesBundle#313]
Hi everyone,

I would like to ask you for help. I have some actions in a list.
```php
->add(null, 'action', array(
      'title' => $this->translator->trans('datatables.actions.title'),
      'start_html' => '<div class="list-action-tabs small line-inline">',
      'end_html' => '</div>',
      'actions' => array(
          array(
              'route' => 'person_show',
              'route_parameters' => array(
                    'id' => 'id'
               ),
               'label' => $this->translator->trans('datatables.actions.show'),
               'icon' => 'glyphicon glyphicon-home',
               'attributes' => array(
               'title' => $this->translator->trans('datatables.actions.show'),
           ),
          //....
      ),
)
```
Some users have an access only to some person entities. I want to check their permissions with voters. is_granted('SHOW', personEntity). Is there some possibility to display only actions depending on this condition?

Thanks in advance!

**Comment by stwe** [comment]
Not yet. Supporting Voters is a good idea .

**Comment by stwe** [comment]
I think voters are a good idea , however, are difficult to implement and a problem with the speed. I would have to check individually for each record .
