### ISSUE TITLE
Uncaught TypeError: $.fn.dataTable.moment is not a function.

### ISSUE THREAD

**Issue by kronikles** [stwe/DatatablesBundle#318]
Uncaught TypeError: $.fn.dataTable.moment is not a function. 
Can't load my dataTable with date. I got version 1.10.11 of jquery.dataTables.js, I also have moment.js & datetime-moment.js.

yet I still got that error.
$.fn.dataTable.moment('DD-MM-YYYY'); this is the error pointing.

Please help me with this.

**Comment by stwe** [comment]
Is moment.js installed?
Am 07.04.2016 12:18 schrieb "Brian Rey" <notifications@github.com>:

**Comment by stwe** [comment]
load moment.js before datatables.js and daterange.js
