### ISSUE TITLE
Ability to attach custom events to the Datatables instance

### ISSUE THREAD

**Issue by cmfcmf** [stwe/DatatablesBundle#321]
I would like to attach custom events to the Datatables instance. Currently, I'd need to overwrite the whole `datatable_js.html.twig` file to be able to do so. It would be great to have an additional hook after the datatable is initialized (line 70).

(I want to implement a custom progress indicator like shown [here](https://datatables.net/reference/event/processing#Example).)

**Comment by stwe** [comment]
try:

```php
// Datatable class

$this->events->set(array(
    'processing' => ':events:processing.js.twig',
));
```

```js
// processing.js.twig

function processing( e, settings, processing) {
    console.info('Processing');
}
```

**Comment by cmfcmf** [comment]
Thank you! Works great :-)
