### ISSUE TITLE
action column render_if Closure cannot work

### ISSUE THREAD

**Issue by winds1983** [stwe/DatatablesBundle#325]
1) action column render_if Closure cannot work
```php
'render_if' => function($rowEntity) {
                            return ($rowEntity['status'] === 'public');
                        },
```

2) How to use Closure in visible?

**Comment by stwe** [comment]
please update to dev-master

**Comment by winds1983** [comment]
@stwe thanks, it works now. but for multiselect, can we use render_if?
Some time, we use soft delete, so when the item is deleted, but we hope to keep on list, and hide the delete button, do we implement it in current version(dev-master)?
or we can support Closure for visible options.
