### ISSUE TITLE
Add custom data to ajax response

### ISSUE THREAD

**Issue by TobiasXy** [stwe/DatatablesBundle#332]
An option to add custom variables to the ajax response would be great.
Currently the `DatatableQuery::getResponse` does not provide any way to change the response data (i.e. adding another value).

To give you an example, I would like to be able to have an ajax response like this:

```
{
	"data": [
		...
	],
	"draw": 1,
	"recordsTotal": 1337,
	"recordsFiltered": 42,
	"myCustomValue": "Hello World"
}
```

A good solution could be to add a method addOutputCallback to the DatatableQuery class. That way one could add a callback able to change the response.

I could also create a PR for this, if you want.

**Comment by stwe** [comment]
Please make auf PR
Am 15.04.2016 15:02 schrieb "TobiasXy" <notifications@github.com>:
