### ISSUE TITLE
Get Data From Repository Function

### ISSUE THREAD

**Issue by spirewebsitedesign** [stwe/DatatablesBundle#335]
Is it possible to load data from a Repository function for the entity? I see someone asked a similar question here: https://github.com/stwe/DatatablesBundle/issues/12 

I don't think it was ever implemented though. I just want to confirm because I need to run a query to get a list of Ids, then load the entities for those ids for display in the datatable. 

Thank you.

**Comment by stwe** [comment]
no. Get all needed Id's and build your own query like this:

https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/query.md#1-whereall-callback
