### ISSUE TITLE
Query Callback wrong filtered amount

### ISSUE THREAD

**Issue by novacp** [stwe/DatatablesBundle#337]
Using your [Query callback](https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/query.md#2-whereresult-callback) does not change the amount of "recordsTotal" and "recordsFiltered":

```
$datatable = $this->get('app.datatable.his');
$datatable->buildDatatable();
$query = $this->get('sg_datatables.query')->getQueryFrom($datatable);

$function = function($qb) use ($adress)
 {
    $qb->andWhere("history.adress = :adr");
    $qb->setParameter('adr', $adress);
  };

 $query->addWhereResult($function);
 return $query->getResponse();
```
I know this is working with "addWhereAll", but what is the function of the "addWhereResult"?
Paging is so generated incorrect - but when I click on a higher page where no results should be, I get an empty result - so the filtering with the anonym function is done - but the "recordsTotal" and "recordsFiltered" are not being updated. Did I cause the problem, miss something or is this a bug?

Regards

**Comment by stwe** [comment]
The function `addWhereResult` is simple redundant. I will remove them eventually .
