### ISSUE TITLE
Initialize DT on event (other than $(document).ready())

### ISSUE THREAD

**Issue by stephanvierkant** [stwe/DatatablesBundle#338]
By default, the Datatable initializes at document.ready. It should be possible to load the table on another event (i.e. button.onClick).

**Comment by stwe** [comment]
Do you use it with a button? Does it work well?

**Comment by stephanvierkant** [comment]
Yes, it does. I'll test some more to make sure everything is fine.

**Comment by stwe** [comment]
Hi @stephanvierkant 
Thank you for working on this bundle and your exceptional ideas.
I've never had a use case for this feature. Please give me an example.

**Comment by stephanvierkant** [comment]
My use case is pretty simple: I've got a table behind a tab and I want to initialize it when I load the tab.
