### ISSUE TITLE
Config for options and features on app level

### ISSUE THREAD

**Issue by zgoniaiko** [stwe/DatatablesBundle#345]
Is it possible to specify default values for datatables in the `app/config.yml` and allow to override them in datatable classes.

As I can see we can set `templates` and `query` there.

For `features` and `options` we have to specify same array of values for each datatable class (like `extensions` or `dom`)

```
$this->features->set(...);
$this->options->set(...);
```

We can solve it by extend some custom class instead of `Sg\DatatablesBundle\Datatable\View\AbstractDatatableView` like

```
class CustomDatatableView extends AbstractDatatableView
{
    public function buildDatatable(array $options = array())
    {
        $this->features->set(...);
        $this->options->set(...);
    }
}

class EntityDatatable extends CustomDatatableView
{
    public function buildDatatable(array $options = array())
    {
        parent::buildDatatable($options);

        $this->ajax->set(...);
        $this->columnBuilder->add(...);
    }
}
```

**Comment by stwe** [comment]
Config variables are not currently planned.
