### ISSUE TITLE
Bug with 3 relations many-to-one

### ISSUE THREAD

**Issue by greg-avanim** [stwe/DatatablesBundle#352]
Hi,

On v0.10, there's a bug when we access an attribute by 3 relations many-to-one (or one-to-one).
For example, in datatable class, a column named entity1.entity2.entity3.attribute.

I've corrected this bug in function setupColumnArrays of DatatableQuery class by replacing at line 263

$join = str_replace('_', '.', $select);

by

$lastSeparatorIndex = strrpos($select, '_');
$join = substr($select, 0, $lastSeparatorIndex) . '.' . substr($select, $lastSeparatorIndex + 1);

Can I suggest that you apply this code please ?
I really need this asap.
Thank you,

Greg

**Comment by stwe** [comment]
And with dev master?
Am 03.05.2016 15:01 schrieb "greg-avanim" <notifications@github.com>:

**Comment by greg-avanim** [comment]
With dev master, I have another bug with only 1 relation many-to-one, it's not stable yet...

**Comment by stwe** [comment]
I need your entities and your table class
Am 03.05.2016 15:07 schrieb "greg-avanim" <notifications@github.com>:

**Comment by greg-avanim** [comment]
I'm asking for a pull request to correct this error.
Can you accept it asap please ?
Thank you

**Comment by greg-avanim** [comment]
Do you still need my files ?

**Comment by stwe** [comment]
@greg-avanim : What exactly is the problem? Have you any example or code (entities && table class)? In my dev environment with dev-master all works as expected. Version 0.10 I will not change. Before I accept the PR, I would like to reproduce the issue.
I program this bundle in my free time and can not immediately change everything always. Give me an understandable error description.

**Comment by stwe** [comment]
Generally: This bundle has some several stable versions. But overall, it is in an early development stage. A version 0.x is supported and changed until the next version. When a version 1.x appears I can not say right now. I have to consider everything alone and try again. It costs all a lot of time and a lot of free time.

**Comment by greg-avanim** [comment]
You just need 3 entities with relationship many-to one or one-to one like this :
A->B->C

And in your datatable class, when you define 2 columns A.B.x and A.B.C.y, you have this error :

Association name expected, 'C' is not an association

I'm sending to you my classes.

I know that this bundle needs a lot of time.
I use it for 3 clients and it's really great.
Thank you for that.

[Archive.zip](https://github.com/stwe/DatatablesBundle/files/251793/Archive.zip)

**Comment by stwe** [comment]
Absolutely strange. With your entities I get actually an error message. I have an own example: Chili -> Heat ->User->Post run as expected. At the moment I do not know what happens there.

**Comment by stwe** [comment]
this run as expected:

```
            ->add('entityB.entityC.name', 'column', [
                'title' => 'C name',
                'orderable' => true,
                'searchable' => true
            ])
            ->add('entityB.name', 'column', [
                'title' => 'B Name',
                'orderable' => true,
                'searchable' => true
            ])
```

this **fails** with `Association name expected, 'entityC' is not an association`. 

```
            ->add('entityB.name', 'column', [
                'title' => 'B Name',
                'orderable' => true,
                'searchable' => true
            ])
            ->add('entityB.entityC.name', 'column', [
                'title' => 'C name',
                'orderable' => true,
                'searchable' => true
            ])
```

**Comment by stwe** [comment]
@greg-avanim : I test your solution in the associations branch.

**Comment by greg-avanim** [comment]
Thanks to you 👍
