### ISSUE TITLE
DataTable not showing filter

### ISSUE THREAD

**Issue by lecongminh** [stwe/DatatablesBundle#354]
Error: The option "filter" does not exist. Defined options are: "class", "default", "editable", "filter_options", "filter_property", "filter_search_column", "filter_type", "name", "orderable", "padding", "render", "search_type", "searchable", "title", "type", "visible", "width".

->add('id', 'column', array(
                'title' => 'Id',
                'filter' => array('text', array(
                    'search_type' => 'eq'
                ))
))

**Comment by lecongminh** [comment]
`->add('id', 'column', array(
                'title' => 'Id',
                'filter' => array('text', array(
                    'search_type' => 'eq'
                ))
            ))`

**Comment by stwe** [comment]
filtering for 0.10
https://github.com/stwe/DatatablesBundle/blob/v0.10/Resources/doc/filter.md

filtering for dev-master
https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/filter.md
