### ISSUE TITLE
Count with custom query ignore build query option

### ISSUE THREAD

**Issue by zgoniaiko** [stwe/DatatablesBundle#358]
Count functions ignore query provided with `->setQuery()` as result we have inconsistent result. With 
[WhereAll callback](https://github.com/stwe/DatatablesBundle/blob/v0.10/Resources/doc/query.md#1-whereall-callback) it will calculate num of entries correctly and with [Get query](https://github.com/stwe/DatatablesBundle/blob/v0.10/Resources/doc/query.md#3-get-query) it will always show num of entries in table.

[WhereAll callback](https://github.com/stwe/DatatablesBundle/blob/v0.10/Resources/doc/query.md#1-whereall-callback) 
```
    $datatable = $this->get('app.datatable.comment');
    $datatable->buildDatatable();

    $query = $this->get('sg_datatables.query')->getQueryFrom($datatable);

    $function = function($qb)
    {
        $qb->andWhere("post.visible = true");
    };

    $query->addWhereAll($function);

    return $query->getResponse(); //OK correct num of entries here
```

[Get query](https://github.com/stwe/DatatablesBundle/blob/v0.10/Resources/doc/query.md#3-get-query)
```
    $datatable = $this->get('app.datatable.comment');
    $datatable->buildDatatable();

    $query = $this->get('sg_datatables.query')->getQueryFrom($datatable);
    $query->buildQuery();

    $qb = $query->getQuery();
    $qb->andWhere("post.visible = true");

    $query->setQuery($qb);

    return $query->getResponse(false); //FAIL incorrect num of entries here
```

I see few ways to fix it:

1. `getCountAllResults()` and `getCountFilteredResults()` should honour option `$buildQuery` given to `getResponse()`
2. `getCountAllResults()` and `getCountFilteredResults()` should use given query and replace select part with count one 
3. set option boolean property `built` on `->setQuery()` and call `->buildQuery()` based on this property (allow to change signature of method from `getResponse($buildQuery = true)` to `getResponse()`)

**Comment by stwe** [comment]
which version? dev -master or v0.10?

**Comment by zgoniaiko** [comment]
@stwe it appear on v0.10.

on master it calculate num of entries in different ways too.
I've added 118 rows to table and 10 of them invisible

output from master

WhereAll callback show

```
Showing 101 to 108 of 108 entries
```

Get query show
```
Showing 101 to 108 of 108 entries (filtered from 118 total entries)
```

output from v0.10

WhereAll callback show

```
Showing 101 to 108 of 108 entries
```

Get query show
```
Showing 101 to 118 of 118 entries
```

**Comment by stwe** [comment]
With dev-master you have the right count of entries. Only the getQuery method shows additional the total count (in your example filtered from 118 total entries).
