### ISSUE TITLE
Pre-filter a datatable

### ISSUE THREAD

**Issue by bettinz** [stwe/DatatablesBundle#361]
Hello, Maybe it's a stupid question, but I can't find an answer in documentation.
I've 2 entities: Event and Result. I want to show a list of events and then a list of results limited by selected event (like /event/2 and /event/2/results). I've read the query settings, but I can't pass that value from controller to datatable right? So, how can I "pre-filter" values?

Thank you
Edit: I've found this https://github.com/stwe/DatatablesBundle/issues/209#issuecomment-152648102
I'll try and update here

**Comment by stwe** [comment]
buildDatatable has an options array to pass values.

```
public function buildDatatable(array $options = array())
```
You can also use an action button.
