### ISSUE TITLE
In-place editing with roles

### ISSUE THREAD

**Issue by bettinz** [stwe/DatatablesBundle#372]
Hello, before opening this issue I've tried downloading the demo. This is my problem:
Referring to demo, we have "user" and "root". User can change title of posts written by root.
Is it possible to add a "role" function to "editable" attribute? 
Like: ROLE_ADMIN can change posts, so if you're logged with "ROLE_USER" you can't. In future will be better a filter like "if this post is mine, I can edit".
What do you think?
Thank you

**Comment by stwe** [comment]
That make absolutely sense. Thanks for the hint.

**Comment by stwe** [comment]
As a first step: I'll add an option "editable role".
