### ISSUE TITLE
How to use render_if in multiselect?

### ISSUE THREAD

**Issue by winds1983** [stwe/DatatablesBundle#373]
For multiselect, can we use render_if?
Some time, we use soft delete or set permission(not role, need complex logic), so when the item is deleted, but we hope to keep on list, and hide the delete button, do we implement it in current version(dev-master)?
or we can support Closure for visible options.

**Comment by stwe** [comment]
I must take a look if i have time

**Comment by winds1983** [comment]
@stwe ok, thanks, could you let me know if it is added?

**Comment by stwe** [comment]
@winds1983 : Question: You want to hide the checkbox if a condition is true/false?

**Comment by winds1983** [comment]
@stwe yes
