### ISSUE TITLE
how to send parameters to callback template?

### ISSUE THREAD

**Issue by celvin** [stwe/DatatablesBundle#376]
With this, I can't send parameters:

https://github.com/stwe/DatatablesBundle/blob/e27449ddde744e3d1f9f9816b452f1d05cbda2ac/Resources/doc/setup.md#3-callbacks

Before I was using:

        public function buildDatatable(array $options = array()) {

        $callbackContent='
            /*nRow, aData, index*/
            /*console.log(aData);*/
            
            var userID="'.$options['id'].'";
                if (id == "2") {
                   $nRow.css({"color":"red"});
                };
            return nRow;
            ';

        $this->callbacks->set(array(
            'row_callback' => "function( nRow, aData, index ) {
                                    $callbackContent
                                }"
        ));

.......

**Comment by stwe** [comment]
Oops!
I did not think about that. Will be changed

**Comment by celvin** [comment]
Those are the patches that I'm using in my project if you like them you can
apply.

https://github.com/stwe/DatatablesBundle/compare/master...celvin:patch-2
https://github.com/stwe/DatatablesBundle/compare/master...celvin:patch-1

Celvin Rivas
http://www.vitelika.com
7126-9172 (24/7)
2231-1165 (8am-3pm / L-V)

**Comment by stwe** [comment]
@celvin : Thanks. Have you an short copy & paste example for the docs?

**Comment by celvin** [comment]
Example of use:

        $this->callbacks->set(array(
            'row_callback' =>array('ProcesosGeneralesBundle:callbacks:row.js.twig',array('userID'=>$options['userID']))
        ));


        ------ row.js.twig ----
        function rowCallback(nRow, aData, index) {
           /*nRow, aData, index*/
           /*console.log(aData);*/

           var userID = "{{userID}}";
           var $nRow = $(nRow);
    
           if (userID=="2") {
               $nRow.css({color: "red"});
           }

           return nRow;
       }

**Comment by stwe** [comment]
@celvin At first: Thanks. The new array setup style is the following:

```
        $this->callbacks->set(array(
            'row_callback' => array(
                'template' => ':post:row_callback.js.twig',
                'vars' => array('id' => '2')
            ),
            'init_complete' => array(
                'template' => ':post:init.js.twig'
            )
        ));
```

sample js file:

```
function rowCallback(nRow, aData, index) {
    var id = "{{ id }}";
    var $nRow = $(nRow);

    if (aData.id == id) {
        $nRow.css({"background-color": "red"});
    }

    return nRow;
}
```
