### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by cafernandez** [stwe/DatatablesBundle#386]
The command sg:datatable:generate has no support for mongoDB

**Comment by stwe** [comment]
Only Doctrine ORM is supported. I don't use ODM in any project. I'm not adding code or features that I don't understand.

**Comment by peteryanni** [comment]
Hi Stwe,

do you mind If I add it ?

**Comment by giovannialbero1992** [comment]
Hi Stwe,
  but don't you accept a PR that introduce compatibility with ODM?
