### ISSUE TITLE
EditableController with route to call

### ISSUE THREAD

**Issue by bettinz** [stwe/DatatablesBundle#387]
Hello, I'm using editable functions with roles, and it works fine. Now I'm trying to sum a value from a column when it's edited with in-place editing.
Like columns a, b and c and column result (with a + b +c). And if A is > of 100 update entity with a boolean on true.
I'm not sure how to add this feature, I think you can extend "editable" with a route (connected to an Action) like ajax to call after (or before) the persist of your EditableController.
What do you think?
Thank you

**Comment by stwe** [comment]
that has nothing to do with editable feature. You can get the column result in your model.

**Comment by bettinz** [comment]
Hello, the problem is to "fire" the exact moment of editing. When the user press the tick button to save the value I need to update total. I can update total every time the datatable is rendered or every time ajax with results is called, but I can't fire the event of editable; to be more clear, when you call
```php
if (true === $supportedFieldType) {
                $em->persist($entity);
                $em->flush();
            }
```
and you get `return new Response('Success', 200);` how can I call an action like /results/updateTotal and do the sum? What I'm thinking is an ajax called just after the Success Response.

**Comment by stwe** [comment]
you can try to override the EditableController. At the moment I have no other idea.
