### ISSUE TITLE
Composer does not recognize version 0.11

### ISSUE THREAD

**Issue by TobiasXy** [stwe/DatatablesBundle#394]
I tried to install version 0.11 of this bundle using composer. I use this version constraint: `"sg/datatablesbundle": "^0.11"`

But composer tells me:

> The requested package sg/datatablesbundle ^0.11 exists as sg/datatablesbundle[dev-master, v0.1, v0.10, v0.2, v0.3, v0.4, v0.4.1, v0.4.2, v0.5, v0.5.1, v0.5.2, v0.5.3, v0.6, v0.6.1,
 v0.7, v0.7.1, v0.8, v0.9] but these are rejected by your constraint.

So apparently the version 0.11 is unknown to composer, even though it is available on packagist.org.

I also tried deleting the composer.lock file and clearing the composer cache. It didn't help.
Do you know anything about that?

**Comment by stwe** [comment]
on packagist available is v0.11

so you can try `"sg/datatablesbundle": "^v0.11"`

**Comment by TobiasXy** [comment]
Unfortunately does not change it, I still get the same error message.

**Comment by MisterGrouik** [comment]
Same problem.

**Comment by ownede** [comment]
Same here.

```
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package sg/datatablesbundle ^v0.11 exists as sg/datatablesbundle[dev-master, v0.1, v0.10, v0.2, v0.3, v0.4, v0.4.1, v0.4.2, v0.5, v0.5.1, v0.5.2, v0.5.3, v0.6, v0.6.1, v0.7, v0.7.1, v0.8, v0.9] but these are rejected by your constraint.
```

**Comment by stwe** [comment]
i will check this at weekend

**Comment by stwe** [comment]
Absolutely strange. but it works after I deleted the Github release.  This release was linked to the tag v0.11.

![unbenannt](https://cloud.githubusercontent.com/assets/2964748/16143483/51f1a8f8-346d-11e6-9f98-4d43b710a319.JPG)
