### ISSUE TITLE
Render_if and Parameter different from Id

### ISSUE THREAD

**Issue by bettinz** [stwe/DatatablesBundle#395]
Hello, I've two questions, maybe unrelated; this is the code:
```php
'actions'=>array(
                    array(
                        'route'=>'edit_work_result',
                        'route_parameters'=>array(
                            'video'=>'videoA'
                        ),
                        'label'=>'A',
                        'icon' => 'glyphicon glyphicon-eye-open',
                        'attributes' => array(
                        'rel' => 'tooltip',
                        'title' => 'A',
                        'class' => 'btn btn-primary btn-xs fancybox fancybox.ajax',
                        'role' => 'button',
                        ),
                    ),
```
I want to show the button only if "videoA" is not null. videoA is not a column in table, but it's an attribut for the entity. So I want to use, as a condition, a value not show in the current datatable. Is that possibile?

Another question: I'm using `'video'=>'videoA'` as a parameter; this parameter is always `undefined` because it's not a column. The strange thing is that the parameter `id` here:
```php
 array(
                        'route' => 'delete_work_result',
                        'route_parameters' => array(
                            'id' => 'id'
                        ),
                        'label' => $this->translator->trans('datatables.actions.delete'),
                        'icon' => 'glyphicon glyphicon-eye-open',
                        'attributes' => array(
                            'rel' => 'tooltip',
                            'title' => $this->translator->trans('datatables.actions.delete'),
                            'class' => 'btn btn-primary btn',
                            'role' => 'button'
                        ),
```
always work. I don't have a column called id, but it fetch the correct id value. Other values different from id, doesn't work. But if I uncomment:
```php
            ->add('videoA', 'column', array(
                'title' => 'VideoA',
            ))
```
it works.

**Comment by stwe** [comment]
your second question: The Id is always in the result. For this behavior you don't need define a column.

**Comment by stwe** [comment]
but it's an attribut for the entity.......where do you get the `videoA` variable?

**Comment by bettinz** [comment]
I'm not sure to understand your question. This is my use case:
I've an event with "n" results. Every result maybe have 3 videos, videoA, videoB and and videoC.
So this is my implementation: an action column with 3 actions, one for each video. 
But I want to show the button only if videoA (or B or C) is not null (first question), and I need to create a route with the string of videoA in the url (second question); but videoA isn't visible (because it's just a sting with numbers), so I don't know how to get this value in `route_parameters` with your bundle.
Thank you

**Comment by bettinz** [comment]
Hello, you've closed my issue but I don't know with available options about how to do this.
Thanks
