### ISSUE TITLE
Export option for checkboxes

### ISSUE THREAD

**Issue by novacp** [stwe/DatatablesBundle#396]
I was trying to export a table into a pdf, excel etc. but the boolean columns are not being exported, they just stay blank. How to "format" them during export?

Within Datatable, the following code for extension (excel):

`
        'extensions' => array(

	'buttons' =>

		array(

			'excel' => array(

				'extend' => 'excel',

				'exportOptions' => array(

					// show only the following columns:

					'columns' => array(

						'1', 

						'2', 

						'3', // this one is checkbox and stays blank on export 

						'4'  // this one is checkbox and stays blank on export

					)

				)

			)

		)

        )
`

On jquery datatable page, I've read that there is a format option within exportOptions, but I don't know how to add it within the Datatable php class. The column type of the field (3+4) is "boolean".

**Comment by stwe** [comment]
At the moment no idea.

https://datatables.net/extensions/buttons/examples/html5/outputFormat-function.html
