### ISSUE TITLE
Error if I add action column

### ISSUE THREAD

**Issue by MisterGrouik** [stwe/DatatablesBundle#397]
When I add a column "action" and reload the page, I get an error "Connection has been reset" in my browser. If I comment this part, everything works.

This is part of the code for action columns:
```
->add(null, 'action', array(
             'title' => 'pouet',
             'actions' => array(
               array(
                 'route' => 'topo_app_information_delete',
                 'route_parameters' => array(
                   'id_information' => 'id'
                 ),
                 'icon' => 'glyphicon glyphicon-remove',
                 'attributes' => array(
                   'rel' => 'tooltip',
                   'class' => 'btn btn-primary btn-xs information_supprimer',
                   'role' => 'button'
                 ),
                 'confirm' => true,
                 'confirm_message' => $this->translator->trans('table.delete.confirmation', array(), 'datatable_information'),
               ),
               array(
                 'route' => 'topo_app_information_edit',
                 'route_parameters' => array(
                   'id_information' => 'id'
                 ),
                 'icon' => 'glyphicon glyphicon-edit',
                 'attributes' => array(
                   'rel' => 'tooltip',
                   'class' => 'btn btn-primary btn-xs',
                   'role' => 'button'
                 ),
               ),
             )
           ))
```

My route are defined correctly as you can see
`topo_app_information_delete:
    path:   /admin/information/{id_information}/delete
    defaults: {_controller: TopoAppBundle:Information:delete}
    requirements:
        id_information: \d+
    options:
        expose: true

topo_app_information_edit:
    path:   /admin/information/{id_information}/edit
    defaults: {_controller: TopoAppBundle:Information:edit}
    requirements:
        id_information: \d+
    options:
        expose: true`

When I type those url directly in my browser, it works so there's no problem with the route themselves...

**Comment by MisterGrouik** [comment]
Found the problem.

In the class Action.php

`public function isVisible(array $data = array())
    {
        if (null !== $this->renderIf && !empty($this->renderIf) && !empty($data)) {
            if (is_array($this->renderIf)) {
                $result = false;

                foreach ($this->renderIf as $key => $item) {
                    if (strpos($key, '.') !== false) {
                        $array = array();
                        $this->assignArrayByPath($array, $key, $item);
                        if (empty($this->array_intersect_assoc_recursive($array, $data))) {
                            $result = false;
                            break;
                        } else {
                            $result = true;
                        }
                    } else {
                        $result = ($item == $data[$key]);
                    }
                }

                return $result;
            } elseif ($this->renderIf instanceof Closure) {
                    return call_user_func($this->renderIf, $data);
            }
        }

        return true;
    }`


the line  "if (empty($this->array_intersect_assoc_recursive($array, $data)))" is not correct under PHP 5.5. You have to do

$var = $this->array_intersect_assoc_recursive($array, $data)
if (empty(var ))

**Comment by stwe** [comment]
Thanks for this hint.
