### ISSUE TITLE
Multiple action columns not possible anymore

### ISSUE THREAD

**Issue by MisterGrouik** [stwe/DatatablesBundle#398]
If I add more than one action column in my DT, the last one will appear correctly, but all the actions column before the last one are empty.

It was working correctly on 0.10. Now with 0.11 it doesn't work anymore...

**Comment by MisterGrouik** [comment]
I'm sorry. It was on dev-master and not 0.11

**Comment by stwe** [comment]
Devmaster is currently 0.11
Am 15.06.2016 08:34 schrieb "MisterGrouik" <notifications@github.com>:

**Comment by stwe** [comment]
Multiple Action-Columns were never planned. You should use a single Action-Column with multiple actions.

**Comment by MisterGrouik** [comment]
That's unfortunate. Why wouldn't you let the user use multiple action-columns as it worked in 0.10 ?
Sometimes, for more clarity, you want to have a column for each action. 
Even more, maybe I want an action column, then a data column, then another action column.

The way it's done in 0.11 forces us to use the lineBuilder on virtual column to have multiple action columns.

But ok, if it was your design, I respect it and will use the lineBuilder.

**Comment by stwe** [comment]
I did not think about that. The bundle is now very often downloaded and everyone uses it differently.

What is the error message with multiple action columns?

**Comment by oidnus** [comment]
+1 to man action column. It is good idea separation admin action from user action.

**Comment by MisterGrouik** [comment]
Actually there's no error message.
With 0.10, you could add many action column and everything is ok.
With 0.11, if you add multiple action column, each column is displayed, but only the last action column contains the button that trigger the action, the other action column are empty.

**Comment by stwe** [comment]
@MisterGrouik I have no issue with two ActionColumns. 

![actions](https://cloud.githubusercontent.com/assets/2964748/16363308/d5d24d3e-3bc6-11e6-9b0b-eeed99e3c27d.JPG)

Show me your Datatables Class.
