### ISSUE TITLE
Example of `render` option for array column?

### ISSUE THREAD

**Issue by dnagirl** [stwe/DatatablesBundle#411]
Could you provide an example of how to use the `render` option when adding an array column, please?  

If I wanted to wrap each of the array elements in a `<div>`, for example, what would be the value of `render`?

```
		$this->columnBuilder
			->add('name', 'column', array())
			->add('synonyms.synonym', 'array', array(
				'data' => 'synonyms[, ].synonym',
				'render' => 'WHAT GOES HERE?'

			))
```

**Comment by dnagirl** [comment]
So I mostly figured it out:

If I write a dataTables render function, e.g.

```
jQuery.fn.dataTable.render.list = function( d, type, row ) {
    if( d == "") return d;
    if (!(/string|number|boolean/).test(typeof d)) return d;
    var arr = d.split('|');
    var ul = '<ul class="list-unstyled"><li class="ui-menu-item" role="menuitem">' + arr.join('</li><li>') + '</li></ul>';
    return ul;
};
```
and make sure it's loaded as an asset along with all the other necessary javascript, I can refer to it in the `render` property.
e.g.
```
		$this->columnBuilder
			->add('name', 'column', array())
			->add('synonyms.synonym', 'array', array(
				'data' => 'synonyms[|].synonym',
				'render' => '$.fn.dataTable.render.list'

			))
```
My function relies on the elements of the data array being joined on `|` which I chose because it's unlikely to show up in one of my element values. But I wish that I could pass the data in its original array form instead of as a string. That would be much more robust.

Is there a way to insist that data be an array instead of a string?

**Comment by stwe** [comment]
the problem was solved? Did you delete the solution?
