### ISSUE TITLE
DateTime column alternative value if null

### ISSUE THREAD

**Issue by kabdessamad1** [stwe/DatatablesBundle#418]
Alternative value if date time is null like in twig :
```twig
{% if is null post.updatedAt %}
    {{ 'No update' }}
{%else%} 
    {{ post.updated|date('d-m-Y H:i:s') }}
{% endif %}
```
i tried line formatter plus virtual columns but is not searchable

**Comment by stwe** [comment]
the "default content" option comes back.

**Comment by stwe** [comment]
For Column && ArrayColumn && BooleanColumn && DateTimeColumn && TimeagoColumn

use: 

```
'default_content' => 'No value'
```

**Comment by kabdessamad1** [comment]
Any due date for v0.12

**Comment by stwe** [comment]
in the next days
