### ISSUE TITLE
Image column problem

### ISSUE THREAD

**Issue by mssimi** [stwe/DatatablesBundle#422]
Hey, when using image column on one to one relation there is problem with accessing array keys in render content function. When $this->getDql() contains something like 'entityA.entityB', then $row[$this->getDql()] is replaced as $row['entityA.entityB'], which is not correct and will fail as it should be $row['entityA']['entityB']. 

[https://github.com/stwe/DatatablesBundle/blob/master/Datatable/Column/ImageColumn.php#L115](url)

I made pr to fix this [https://github.com/stwe/DatatablesBundle/pull/424](url)

**Comment by mssimi** [comment]
Hey, any news on this? I rly like your project, but I can't use it, unless I use my fork:(

**Comment by stwe** [comment]
I always try as soon as possible work through everything . I will test this and fixed definitely ... asap

**Comment by stwe** [comment]
Is the Image-Column an association (example: one to one ), the image is not rendered. Your PR has another issue, if the association === null.

**Comment by mssimi** [comment]
thx:)
