### ISSUE TITLE
Pass strings to route parameters

### ISSUE THREAD

**Issue by netsuo** [stwe/DatatablesBundle#423]
Hi,

For several action columns routes, I need to set some parameters that are not data. A simple example is some of the actions are REST services that can render response in html or json, so I have to specify the "_format" parameter to the route.

But in your code you only try to construct a route_parameters array in javascript by searching it in the row's data.

A simple way to let user set parameters from simple strings (or functions returning strings) would be to test if the variable is undefined or not here: https://github.com/stwe/DatatablesBundle/blob/ab36449cdf1ba0a361a54067c92ae4955e335049/Resources/views/Action/actions_string.html.twig#L14

If not, just set routeParameters["{{ key }}"] = {{ value }};

Something like this: routeParameters["{{ key }}"] = row.{{ value }} !== undefined ? row.{{ value }} : '{{value}';

I know I probably could just replace the template but what are your thoughts about this, would'nt it be better to choose if we want to pass some hardcoded parameters ?

**Comment by stwe** [comment]
https://github.com/stwe/DatatablesBundle/commit/dceb428cb4131bca84954446b299a5ddddae8293
https://github.com/stwe/DatatablesBundle/commit/813d005867f60bddb580385105a36a9430a1ce44
