### ISSUE TITLE
Not possible to make multiple table SQL query

### ISSUE THREAD

**Issue by ducho** [stwe/DatatablesBundle#425]
Is not possible to make multiple table SQL.

```
$query = $this->get('sg_datatables.query')->getQueryFrom($datatable);
 $qb2 = $this->getDoctrine()->getManager()->getRepository('HlaseniaBundle:Spravodajca')->createQueryBuilder('s');

        $qb = $query->buildQuery()->getQuery();
        $qb->andWhere(
            $qb->expr()->in(
                'beUserCreated.username',
                $qb2->select('s.email')
                    ->getDQL()
             )
        );

        $query->setQuery($qb);

        return $query->getResponse();
```

**[Semantical Error] line 0, col 326 near 'beUserCreated,': Error: 'beUserCreated' is already defined.** 

SELECT partial be_user_log.{id,id,code,id,dateCreated,id,ip}, partial beUserCreated.{id,id,name}, partial be_user_log.{id,id,code,id,dateCreated,id,ip}, partial beUserCreated.{id,id,name} FROM Romboid\AppBundle\Entity\BeUserLog be_user_log LEFT JOIN be_user_log.beUserCreated beUserCreated LEFT JOIN be_user_log.beUserCreated beUserCreated, Romboid\AppBundle\Entity\BeUserLog be_user_log LEFT JOIN be_user_log.beUserCreated beUserCreated LEFT JOIN be_user_log.beUserCreated beUserCreated WHERE beUserCreated.username IN(SELECT s.email FROM Romboid\HlaseniaBundle\Entity\Spravodajca s) ORDER BY beUserCreated.name asc, beUserCreated.name asc

**Comment by stwe** [comment]
Please you see the possibilities to change the query .
https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/query.md

These options cover the most common cases . More is not possible or too specific. This bundle can not do everything. :weary:

**Comment by ducho** [comment]
Never mind! Thanks.
