### ISSUE TITLE
should I close the repository ?

### ISSUE THREAD

**Issue by ducho** [stwe/DatatablesBundle#427]
I need to set up data-id attribute with row.id but closure function not working with return as string.

```
array(
                        'route' => 'item_delete',
                        'route_parameters' => array(
                            'id' => 'id'
                        ),
                        'label' => '',
                        'icon' => 'fa fa-times',
                        'attributes' => array(
                            'data-id' => 'id',
                            'data-action' => 'delete',
                            'rel' => 'tooltip',
                            'title' => $this->translator->trans('datatables.actions.cancel'),
                            'class' => 'btn btn-danger btn-xs btn-action',
                            'role' => 'button'
                        )
 )
```

**Comment by stwe** [comment]
```
                        'attributes' => array(
                            'data-id' => 'id', // <=== You need here the actual row.id ??
```

**Comment by ducho** [comment]
Yes, actual entity row id.

**Comment by stwe** [comment]
With dev-master it is possible to set row IDs. Maybe this helps.

**Comment by ducho** [comment]
@stwe good joke but not working :-1:  
returned string "id" instead the value "1"
`<a href="/admin/report/1" data-id="id" data-action="delete" rel="tooltip" title="Cancel" class="btn btn-danger btn-xs btn-delete-row" role="button"><i class="fa fa-times"></i></a>`

**Comment by stwe** [comment]
It is precisely these stupid sayings , for which I now seriously considering to close the repository . 
I do this in my spare time and it's free.

@ducho 
Write your own bundle and save you stupid sayings .
