### ISSUE TITLE
Using custom query for column

### ISSUE THREAD

**Issue by stevro** [stwe/DatatablesBundle#429]
Is there any possibility to customize the query for a column?

I have a entity named Shipment, that has a One-to-Many with an entity Itinerary. And I want to display in separate columns the loading point vs the unloading point. The type is an attribute on Itinerary.

I managed to do this using a custom render function in javascript for each column.
Ex:
```
PHP
->add('itinerary.address', 'array', array(
                    'title' => 'Descarcare',
                    'data' => 'itinerary[, ].address',
                    'render'=> 'renderUnloadingItinerary'
                ))

JS
function renderUnloadingItinerary(data, type, row, meta) {
    var string = '';

    row.itinerary.forEach(function (itin) {
        if (itin.type === 'unloading') {
            string = string  + itin.address + '<br>';
        }
    });

    return string;
}
```

But if I search for one of the columns it will automatically eliminate the results from the other column as they do no match the search.

**Comment by stwe** [comment]
Unfortunately not, sorry.
