### ISSUE TITLE
Actions column not rendering actions in wrapper block

### ISSUE THREAD

**Issue by ghost** [stwe/DatatablesBundle#43]
After trying master which merges the 0.5.2 multiaction column with single action by following documentation examples and columns documentation, looks like it does not render HTML content inside the wrapper, just showing the empty Actions column with the start and end wrapper code only. I've verified route and parameters exist, tried to add/remove `role` and `renderif` but still renders nothing.

**Comment by vooxo** [comment]
IMPORTANT:
When using route names defined via annotation in a controller, ```"expose"=true``` must be set!
Example:
```php
/**
* @Route("/edit/{id}", name="grid_eschool_partner_edit", options={"expose"=true})
*/
```
Otherwise Router will throw an error that the route doesn't exist.
