### ISSUE TITLE
Search generates query error in arabic or chinese or ...

### ISSUE THREAD

**Issue by Kharestani** [stwe/DatatablesBundle#433]
When the bundle creates a query it starts to search through every column but MySQL has a problem with queries in which there is a 'LIKE' when the column is not english related languages so people make the unicode of database something like utf8-general-ci but even with this; MySQL reports errors on none text columns like id or date time and when the  bundle searches with 'LIKE' the database report errors.

for example if you have three columns: id, name, date
when you search in arabic 'سی' this will cause error in database like this:
![image](https://cloud.githubusercontent.com/assets/5319248/17533694/389f2f9e-5e9b-11e6-99e1-664311bddcb4.png)
![image](https://cloud.githubusercontent.com/assets/5319248/17533753/6f580650-5e9b-11e6-9b94-561c202da883.png)

Thanks

**Comment by stwe** [comment]
And if you remove the datetime field?

**Comment by Kharestani** [comment]
I got mixed results from it! I ended up using only column filters
