### ISSUE TITLE
add data-id for each row 

### ISSUE THREAD

**Issue by abdallahmaali** [stwe/DatatablesBundle#437]
how i can add data-id on each row in the table ?

**Comment by stwe** [comment]
you need this https://datatables.net/examples/server_side/ids.html ?

**Comment by abdallahmaali** [comment]
i should handle it from server side or from scripts ?

**Comment by stwe** [comment]
I'll add an option to set the Id . Asap

**Comment by abdallahmaali** [comment]
thank you so much 👍

**Comment by stwe** [comment]
try:

```
        $this->options->set(array(
            'row_id' => 'id' // or 'xx.yy',
        ));
```

**Comment by abdallahmaali** [comment]
The option "row_id" does not exist

**Comment by stwe** [comment]
update the Bundle
clear your cache

**Comment by abdallahmaali** [comment]
i did the follwing 
1- update bundle
 sudo composer require sg/datatablesbundle

2-clear cache

and i add row_id in the option but i still face same problem 
The option "row_id" does not exist

**Comment by stwe** [comment]
look at this file: https://github.com/stwe/DatatablesBundle/blob/master/Datatable/View/Options.php
and you can see the option row_id exist.

with the command
`sudo composer require sg/datatablesbundle` you will get the last stable version of the bundle (v0.11). 

But you need currently dev-master!

1) change your composer.json

```
"sg/datatablesbundle": "dev-master",
```

2) clear your composer.lock file
3) clear your vendor dir
4) clear your cache
5) sudo composer update

Don't forget:

In the next few days I set a tag for version 0.12. Then you can change your composer.json again:
```
"sg/datatablesbundle": "v0.12",
```

**Comment by abdallahmaali** [comment]
thank you so much  every thing its okay now ,i really appreciate your efforts
