### ISSUE TITLE
Custom column with closure

### ISSUE THREAD

**Issue by novacp** [stwe/DatatablesBundle#438]
Hi, I was trying to implement a custom column that gets a dynamic data entry by calling an anonym function, which then queries for a few things in the database by using the id field of the current row:

```
->add('someField', new ExtendedArrayColumn(), array(
      'title' => 'someTitle',
      'width' => '5%',
      'data' => function($row) {
         return $this->mapLicenseToDevice($row);
      }
))
```

I've seen on other Column types, that it is possible to pass anonym functions / Closures to the fields, now is my question on how to do this? Can I pass a closure to 'data' and how does the corresponding column type (ExtendedArrayColumn) needs to look like in order to execute the closure correctly with the passed row?

Regards.

**Comment by stwe** [comment]
No, it does not work with the anonymous functions and data . Do you want to format the display of the field ? For this you can use the LineFormatter .

**Comment by novacp** [comment]
Hi stwe, no it is not a formatting problem. The data I need in the field is mapped through 1-n-n to another entity - not nice but I cannot change it within this project. I could set the field value by using a virtual column and then query for the value within the line formatter, but this would erase filter/sorting ability of the column.

How would you then query for a related value? I thought that I would need some sort of callback..?

**Comment by stwe** [comment]
Search sort and in a virtual column ....
may still take a while.
