### ISSUE TITLE
Make "filtered results" disableable

### ISSUE THREAD

**Issue by Bruce17** [stwe/DatatablesBundle#443]
I have a table containing 17 k++ entries. My queries run fine, except for the one that shows the overall filtered sum in datatables. This query runs ober 2 seconds and I don't need that information. It'd be nice to enable/disable that information.

![image](https://cloud.githubusercontent.com/assets/5036995/17883583/a7b440cc-6913-11e6-81ec-037c0c8a5381.png)

I located the call to: https://github.com/stwe/DatatablesBundle/blob/v0.11/Datatable/Data/DatatableQuery.php#L774

Edit: I have no access to the particular database table, so setting an index on that column is no option at the moment.

**Comment by stwe** [comment]
only of interest: 17 k++ entries ... have you tried the `pipeline` option?

**Comment by Bruce17** [comment]
No I didn't. How can I do that?

**Comment by stwe** [comment]
```
        $this->options->set(array(
            // ...
            'count_all_results' => false
        ));
```

![unbenannt](https://cloud.githubusercontent.com/assets/2964748/18029120/5b5fc0c8-6c8f-11e6-84d0-cf2b59fc866a.JPG)
