### ISSUE TITLE
Filter "select" does not filter properly.

### ISSUE THREAD

**Issue by Bruce17** [stwe/DatatablesBundle#444]
I have a column containing string values and numbers as strings. The filter is of type "select" and has the following values:
```php
array(
  ''     => 'Alle',
  '1'    => '1', 
  '2'    => '2',
  '3'    => '3', 
  '10'   => '10', 
  'Ohne' => 'Ohne',
)
```

The prepared result is wrong, because the selected value is always a key of a resorted array (see screenshots).

![image](https://cloud.githubusercontent.com/assets/5036995/17884981/636b32f6-691b-11e6-9a7d-e37897791070.png) ![image](https://cloud.githubusercontent.com/assets/5036995/17884987/66d4edc4-691b-11e6-9ee5-86866347c3ad.png)

**Comment by stwe** [comment]
I can not reproduce. For me it looks like this:

```
                'filter' => array('select', array(
                    'select_options' => array(
                        '' => 'Alle',
                        '1' => '1',
                        '2' => '2',
                        '3' => '3',
                        '10' => '10',
                        'ohne' => 'ohne'
                    ),
                    'search_type' => 'eq'
                )),
```

![unbenannt](https://cloud.githubusercontent.com/assets/2964748/18080684/cd47d87a-6e96-11e6-9fb0-9cc219be4b90.JPG)

Do you use dev-master?

**Comment by Bruce17** [comment]
No I'm using v0.11. If it's already fixed in dev-master, than I'll wait for the next release v0.12.
