### ISSUE TITLE
Make joins optional in"filtered results"

### ISSUE THREAD

**Issue by Bruce17** [stwe/DatatablesBundle#446]
Currently I have a very long running query, because of a added left-join in the count statement. If I leave off the left-join, the count query executes in less than 100 ms.

My suggestion: add a `$options` parameter with the attribute e.g. `withoutJoinsInCount` to the method `getResponse`.

Example:

``` php
public function getResponse($buildQuery = true, array $options = array())
{
    // ...

    $outputHeader = array(
        'draw'            => (int) $this->requestParams['draw'],
        'recordsTotal'    => (int) $this->getCountAllResults($this->rootEntityIdentifier, $options),
        'recordsFiltered' => (int) $this->getCountFilteredResults($this->rootEntityIdentifier, $buildQuery, $options)
    );

    // ...
}

private function getCountFilteredResults($rootEntityIdentifier, $buildQuery = true, array $options = array())
{
    $withoutJoinsInCount = false;
    if (array_key_exists('withoutJoinsInCount', $options)) {
        $withoutJoinsInCount = $options['withoutJoinsInCount'];
    }

    if (true === $buildQuery) {
        $qb = $this->em->createQueryBuilder();
        $qb->select('count(distinct ' . $this->tableName . '.' . $rootEntityIdentifier . ')');
        $qb->from($this->entity, $this->tableName);

        if ($withoutJoinsInCount === false) {
            $this->setLeftJoins($qb);
        }
        $this->setWhere($qb);
        $this->setWhereAllCallback($qb);

        return (int) $qb->getQuery()->getSingleScalarResult();
    } else {
        if ($withoutJoinsInCount === true) {
            // Very radical approach, maybe implement a proper solution to reset only some specific joins.
            $this->qb->resetDQLPart('join');
        }

        // ...
    }
}
```

**Comment by stwe** [comment]
I will take a look at weekend

Am 24.08.2016 10:05 schrieb "Michael" <notifications@github.com>:

**Comment by Oliver-Gibson** [comment]
Hi, sorry for digging up an old issue.

Implementing this in versions prior to dev-master in a way that fits all use cases is not feasible

- If global search or filters are applied the joins are required.
- In addition the joins could be referenced in the callbacks. 

It is also not feasible in current developpement version

- If global search or filters are applied the joins are required.
- The left joins could be referenced by the other types of joins.

This is a special requirement that you will have to implement in your own project. There are also other paths you can explore to get to reasonable performance (doctrine cache for example, see #582 ).

**Comment by stephanvierkant** [comment]
Nothing wrong with digging up old issues, if they're still relevant. :smile: 

See #661.

I think this issue can be closed, as this feature request is resolved. ping @stwe
