### ISSUE TITLE
Datatable language

### ISSUE THREAD

**Issue by stevro** [stwe/DatatablesBundle#450]
Hi, I'd like to provide the language for the datatable from an url.
I see that by default you set some strings for the language option.

The problem is that, if I add a language option and set the url, my filters won't stay up, instead they will be displayed in the footer.

Can you point me to the right solution?

Thanks.

**Comment by stwe** [comment]
I can not easily reproduce the issue. I know neither your controller , your DataTables class or how you produce the URLs . Sorry .
