### ISSUE TITLE
dynamic table id

### ISSUE THREAD

**Issue by dnagirl** [stwe/DatatablesBundle#453]
If I want to have multiple copies of the same table with different data subsets displayed on one page, I will need to have different a different id for each table. How do I do that?

For example, say I want to display several Posts on a page. Attached to each Post is a DataTable with the last several Comments for that post.  If I were displaying only one DataTable of Comments, the id might be "comment_datatable". But since I'm displaying several, I'd like the ids to be "comment_datatable_X" where `x= post.id`.

**Comment by stwe** [comment]
You have, for example, at the top of all postings and at the bottom of a table with all corresponding comments. For this you need two tables. The upper with the postings. Now you need a click event on the line with the post. In this event you update the table below with the comments. That would be my idea. I find that a very good example. I try at the weekend to write an example.

**Comment by dnagirl** [comment]
An example for linked tables would be excellent!

**Comment by stwe** [comment]
see the example in my demo-bundle:
https://github.com/stwe/DtBundleDemo/commit/5dfa6129b2efb0f73d38e8c572897dd7d2613786
