### ISSUE TITLE
Misleading documentation?

### ISSUE THREAD

**Issue by chriskonnertz** [stwe/DatatablesBundle#454]
Hello,

here https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/columns.md#options-2 it says regarding the options of a virtual column: `see: Column`
Columns support the `searchable` option but virtual columns do not, right? (Because the algorithm cannot create a DQL query statement for a virtual column.)

So the documentation seems to be misleading. Maybe adding a note about this anomaly would be a good idea?

Regards,
Chris

**Comment by stwe** [comment]
Yes, you're right.

Note:
The user can create a virtual column or he use the LineFormatter to format an existing column. In both cases, the search and sort is a problem and not currently implemented.

One solution could be that the user provides one or more sql statements for the column to search and sort (where Callback functions for column). But that's just an idea.

**Comment by chriskonnertz** [comment]
Thanks for the update of the documentation!

Für die `orderable` Option ist es aber das selbe, oder? Sortierung funktioniert nicht weil ORDER BY natürlich nur auf eine existierende Spalte einer Tabelle angewendet werden kann.

**Comment by stwe** [comment]
@chriskonnertz : Es ist hier unüblich, aber ich antworte mal auf Deutsch. Ich erhalte viele Anfragen zum Thema Sortieren und Suchen in virtuellen Feldern. Ich mache das hier als Hobby und verdiene meine Geld mit was ganz anderem, habe also ein Zeitproblem, was die Pflege dieses Bundles angeht. Das Problem mit der Virtual-Column ist ganz einfach erklärt. Nehmen wir an, du hast die Felder "Vorname" und "Nachname" in der Datenbank. Jetzt baust du dir daraus ein virtuelles Feld "Name". Natürlich stellt sich jetzt sofort die Frage, was bitte soll ich hier sortieren und suchen? Ein Feld "Name" gibt es in der Datenbank nicht. Letztlich funktioniert die Sache aber Serverseitig und ich muss eine Query bauen. Meine Idee ist jetzt, dass ich für die Sortierung eine Option einfüge, welche den Namen des Feldes enthält, nach welchem sortiert werden soll. In unserem Beispiel könnte dann "post.lastname" angegeben werden. Selbiges werde ich für die Suche implementieren. Dann kann angegeben werden, in welchen Feldern (Plural) gesucht werden soll. Eine andere Idee habe ich nicht. Gleiches gilt für den LineFormatter. 
Jetzt kommen Leute auf die Idee, irgendwelche abenteuerlichen Formatierungen durchzuführen. Da stehen in der View letztliche Dinge, nach denen eben nicht gesucht werden kann. Schlicht, weil die Strings/Werte nicht in der Datenbank stehen. Die ganze Problematik habe ich immer nach hinten geschoben, in der Hoffnung, mal eine Idee zu haben. Daher auch die mangelhafte Doku. Alles hat eben seine Grenzen und das Bundle hat inzwischen einen Umfang, den ich nie wollte.
Grüße.

**Comment by chriskonnertz** [comment]
> Ich mache das hier als Hobby und verdiene meine Geld mit was ganz anderem, habe also ein Zeitproblem, was die Pflege dieses Bundles angeht

Nachvollziehbar bzw. kenne ich in ähnlicher Weise.

> Meine Idee ist jetzt, dass ich für die Sortierung eine Option einfüge, welche den Namen des Feldes enthält, nach welchem sortiert werden soll. 

Klingt für mich super. Ich habe etwas ähnliches wie Dein Datatables-Bundle entwickelt und das dort fast genau so gelöst. Zumindest für meine eigenen use cases erscheint mir das jedenfalls ausreichend.

> Selbiges werde ich für die Suche implementieren.

Das wäre wunderbar. Hast Du einen Zeitplan, kann man Dir dabei vielleicht helfen?

**Comment by Bruce17** [comment]
@stwe 
Wenn du Hilfe brauchst, geb Bescheid. Da ich dein Bundle inzwischen intensiv in einem Projekt verwende, kann ich dich bei den Erweiterungen unterstützen.

**Comment by stwe** [comment]
@Bruce17: Danke :+1: 

Hast du da an was spezielles gedacht, wo du gerne was ändern oder erweitern möchtest?

1) Du nutzt nicht zufällig PostgreSql? Da bräuchte ich definitiv Unterstützung. Da fehlt mir ehrlich gesagt die Lust zu.
2) Der Generator muss komplett aufgeräumt werden. 
3) Nutzt du das Bootstrap Layout? Wäre schön zu wissen, wie das Bundle mit Foundation oder jqueryUi läuft.

Ansonsten bin ich natürlich immer froh, wenn Code oder Ideen geteilt werden. Wenn du also dieses Bundle um ein nützliches Feature erweitert haben solltest, dann her damit.

**Comment by Bruce17** [comment]
1) Leider nein.
2) Kann ich mir bei Gelegenheit mal anschauen.
3) Im Moment verwende ich nur das Bootstrap Layout. Kann bei das ebenfalls bei Gelegenheit mal für jQuer UI anschauen.

Was ich gerne erweitern möchte ist die Dokumentation. Mir fällt es teilweise immer noch schwer einige Spaltenoptionen zu verstehen. Da möchte ich gerne eine zusätzliche "description" Spalte einfügen und ggf. mit Beispielen.

**Comment by Bruce17** [comment]
3) jQuery UI und Foundation sieht bei mir lokal gut aus. Habe es mit ein paar normalen Spalten (column, datetime, action, virtual) getestet.
