### ISSUE TITLE
child-rows

### ISSUE THREAD

**Issue by hieros** [stwe/DatatablesBundle#459]
Hello and thank you for the job.
What is the best way to get the same output as the image "https://github.com/stwe/DatatablesBundle/raw/master/Resources/images/sc1.jpg".
I am trying to implement the child-rows.
Is an action column?
If you have an example, I'm interested.

may be like [this,](https://github.com/stwe/DatatablesBundle/issues/305) but i don't know how to reproduce this one

thank you in advance

**Comment by dnagirl** [comment]
I implemented a new column type so I could get my child row content via an ajax call. I've posted a gist [here ](https://gist.github.com/dnagirl/a9816e33d9d24f12208125bcbf1271ae) if you're interested.

**Comment by hieros** [comment]
Hello and thank you,
I am very interested, how do I do to integrate it?
Create the class but it's ok or should we put the twig part?
Have you an example of the code for the "columnBuilder"

thank you in advance

**Comment by dnagirl** [comment]
Your datatable class might look something like this:

```
<?php

namespace AppBundle\Datatables;

use Sg\DatatablesBundle\Datatable\View\AbstractDatatableView;
use Sg\DatatablesBundle\Datatable\View\Style;
use My\UtilityBundle\Datatable\Column\ChildRowColumn;

/**
 * Class ChemicalDatatable
 *
 * @package RefactorBundle\Datatables
 */
class ChemicalDatatable extends AbstractDatatableView
{
// ...
public function buildDatatable(array $options = array()) {
// ...
		$this->columnBuilder
			->add('id', new ChildRowColumn(), array('ajax' =>array('route' =>'ci_supply_by_chem', 'args' => array('id' => 'id')) ))

```
You'll need the Twig template to output the childRowColumn correctly.

**Comment by hieros** [comment]
Thank you, I progress
I get a blank column, probably because my ajax Action returns nothing.
What should be the form of the return?

I included the js part in the view of the table and the click is detected, even if the column is empty, it's ok.

Without wanting to abuse, you can be an example for the ajax action and for the display twig.

thank you in advance

**Comment by dnagirl** [comment]
Your ajax action can return whatever you want. I've got mine returning a json object. I do this by have the Controller return a Json Response object. e.g. `return new JsonResponse(array(  'thing'=>$someArray, 'otherThing'=>$anObject);`

But you could have it return html or text or whatever. It's up to you.

**Comment by hieros** [comment]
thanks a lot for your help,
This works very well, it's really convenient and customizable.
thank you for spending time to answer me and for sharing.

**Comment by stwe** [comment]
@dnagirl : 
Can you create a PR + example for the docs?

**Comment by dnagirl** [comment]
@stwe: I don't have a lot of time at the moment. But I'll see if I can get it done. If you'd like to just include the [Gist ](https://gist.github.com/dnagirl/a9816e33d9d24f12208125bcbf1271ae)that I linked to upthread, feel free.

**Comment by fyrye** [comment]
For clarification the image illustrates the [responsive](https://github.com/stwe/DatatablesBundle/blob/v0.13/Resources/doc/extensions.md) feature extension.
The feature will automatically collapse the columns that protrude beyond the window display.
Which is why the Actions (_Actionen_) column in the image is in the child row list.

```php
$this->features->set([
   'extensions' => [
      'responsive' => true
   ]
]);
```
