### ISSUE TITLE
state_save and individual_filtering true

### ISSUE THREAD

**Issue by hieros** [stwe/DatatablesBundle#461]
Hello,

When I use the "state_save" filter works well when reloading, but the input element does not display the entered value?
Is it the same with you?

thank you in advance

**Comment by Zoopme** [comment]
Hi,
You can find an explanation here : https://datatables.net/forums/discussion/2864/x#Item_3
I am trying to apply the solution they suggest but I have been stalling so far.
Regards,

**Comment by Mairu** [comment]
Override the SgDatatablesBundle/views/Datatable/options.html.twig template and add the following "option".

```
"initComplete": function (settings) {
    //set previously searched values (when used save_state)
    var $thead = $(settings.nTHead);
    $.each(settings.aoPreSearchCols, function(index, value) {
        if ($.trim(value.sSearch) !== '') {
            $thead.find('[data-filter-property-id="' + index + '"]').val(value.sSearch);
        }
    });
},
```

**Comment by oidnus** [comment]
@Mairu you are great :D

**Comment by stephanvierkant** [comment]
If someone creates a PR for this feature, please consider adding support for fnFilterClear as well: https://datatables.net/plug-ins/api/fnFilterClear (see my comment)
