### ISSUE TITLE
'Default' option doesn't editable

### ISSUE THREAD

**Issue by bettinz** [stwe/DatatablesBundle#464]
Hello, maybe I'm missing something but I've tried to set the 'default' option for a column and it doesn't work (it doesn't show the "default" string)
I've tried with:
```php
->add('a', 'column', array(
                'title' => 'A',
                'editable'=>true,
                'editable_if' => function() {
                    return (
                        $this->authorizationChecker->isGranted('ROLE_ADMIN')
                    );
                },
                'default'=>'-'
            ))
```
This is the situation: an empty column with "null" in database. What I want is to show something like "-" and make the column editable because if it's empty I can't edit the column with the "editable" function. Is it possible to show a default value and make the column editable or show something if the column is empty (and then null)?

Thank you 😄

**Comment by stwe** [comment]
The right default option is:

```
'default_content' => '-',
```

But the column is not editable. I will see what I can.

**Comment by bettinz** [comment]
Thank you 😃 (i hope it's more useful than my previous issues)
And I think I speak for many here: thank you for welcome back, your free time for this project is really appreciated. Thank you again.

**Comment by stwe** [comment]
please try:

1) remove your `default_content` option
2) set column `editable => true`

Now you should see something like

![change](https://cloud.githubusercontent.com/assets/2964748/18792744/fdec2c22-81b7-11e6-9fa6-e5beb817c290.JPG)

**Comment by bettinz** [comment]
It works great! Thank you 👍
