### ISSUE TITLE
Convert timeago column to date diff and date format

### ISSUE THREAD

**Issue by bettinz** [stwe/DatatablesBundle#469]
Hello, I've tried to play with your code, but it's too much for me right now 😄 
This is my idea: we've the timeago column and it start from now. What if we maintain the timeago with one more parameter called "start", so it became:
```php
 ->add('colName', 'timeago', array(
                'title' => 'Column',
                'startDate'=> function($row) {
                                   return $row['startDate'];
                             };
                'format'=>'Days'
            ))
```
if 'start' is defined it calculate the difference between dates (colName - startDate), otherwise it calculate the difference from now as now.
The format option is to specify if we want a "text" result like "One Month ago" or 30 Days.
I've found this documentation:
http://momentjs.com/docs/#/displaying/difference/ for both steps (it allow to decide the format of returned string like days, months, etc)
I think http://momentjs.com/docs/#/displaying/fromnow/ allow to decide the string format (days, months, etc).

**Comment by Bruce17** [comment]
> if 'start' is defined it calculate the difference between dates (colName - startDate), otherwise it calculate the difference from now as now.

This is a very specific use case. Have you tried to write your own column? It's quite easy, see [Column - Make your own](https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/columns.md#12-make-your-own).

> I've found this documentation:
http://momentjs.com/docs/#/displaying/difference/ for both steps (it allow to decide the format of returned string like days, months, etc)
> I think http://momentjs.com/docs/#/displaying/fromnow/ allow to decide the string format (days, months, etc).

I believe the main formatting is done in the backend.

**Comment by bettinz** [comment]
Hello @Bruce17 ! I've never tried with a custom column, but I try right now. Thanks 😃

**Comment by stwe** [comment]
@bettinz : 
I suppose the problem is solved.
