### ISSUE TITLE
Binary string sometimes returned as "normal" string sometimes as "binary" string

### ISSUE THREAD

**Issue by MlleDelphine** [stwe/DatatablesBundle#472]
I am stuck with a random behavior..

I have object with a field that potentially contains special character (Ex : "Bajío", "Institución", "Múltiple").

When I launch search to find an item that contains one of this special character sometimes it works, and sometimes no.. It's driving me crazy !

Someone knows why ?

PHP returns object as this : 
ERROR (in JSON) :
**"institutionName" => b"Banco del Bajío, S.A., Institución de Banca Múltiple"**

SUCCESS (in JSON):

**"institutionName" => "Banco del Bajío, S.A., Institución de Banca Múltiple"**

I dump everywhere.. None object is different between success process and fail process..

Q : Is this a PHP issue or Bundle issue ?

I tried to get this particular item with a simple "findOneBy" and dump it. 
I refresh my page several time (~30 times) and in no case "=> **b**"Banco" the "b" disapeared...

**Comment by MlleDelphine** [comment]
I've created a DoctrineEvent function to catch "postLoad" event.
This function checks if a string is binary or not, if it is I encode it again in utf-8 and it seems to "remove" the "b".

But, it works for my API Rest part but this event is not triggered for this bundle.

Is it using Doctrine ?

**Comment by stwe** [comment]
I look at this. But can take a while

**Comment by MlleDelphine** [comment]
Thanks ! Still stuck with this behavior

**Comment by Oliver-Gibson** [comment]
Hi,

I was unable to reproduce the issue using either v0.13 or dev-master. Could you provide a working example ?

**Comment by stwe** [comment]
@Oliver-Gibson No, he can not and @Englenshan (see# 586) can not. It's crazy.
