### ISSUE TITLE
Error: The partial field selection of class AppBundle\Entity\Class must contain the identifier

### ISSUE THREAD

**Issue by sweoggy** [stwe/DatatablesBundle#474]
Hi,

I am having problem getting the array type work with a OneToMany relation where the Many side has three primary keys. I get the error mentioned in the title. How am I supposed to specify this relation in the column builder?

Currently I have:
```
->add('productAndDGs.setting.name', 'array', array(
                    'title' => 'title',
                    'data' => 'productAndDGs.setting[; ].name',
                    'class' => 'array',
))
```
I have attached an image of how my tables relate to each other. I am trying to reach the sun_protection_settings table from the recipes table.

![sgdatatable-three-primary-key-problem](https://cloud.githubusercontent.com/assets/5914253/19015910/affd7064-880d-11e6-8312-3e6699920b80.png)

**Comment by stwe** [comment]
Your recipes_with_products_and_dsg table has no id. Multiple id's are not supported.
