### ISSUE TITLE
Drop PHP v5.3 support - issue with doctrine/orm

### ISSUE THREAD

**Issue by Bruce17** [stwe/DatatablesBundle#479]
I'm adding some more unit tests to this bundle and I stumbled over an issue with the bundle's dependencies under PHP v5.3. The dependency `doctrine/orm` in its minimum version v2.2.3 doesn't provide the `EntityManagerInterface`, but the `AbstractDatatableView` relies on that interface.

IMHO there are two options to solve this:
- drop PHP v5.3 support
- fix code to support v5.3 again

See my [TravisCI build](https://travis-ci.org/Bruce17/DatatablesBundle/jobs/166759542) for PHP v5.3 using the composer option `--prefer-lowest` to install all package's minimum versions.

I can drop the PHP v5.3 support in my current [feature branch](https://github.com/Bruce17/DatatablesBundle/tree/feature/cast-option) if you're ok with it.

**Comment by Bruce17** [comment]
Mhh it seems to work with with v2.4.0 of `doctrine/orm`, but there are still missing dependencies e.g. `Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface` and `Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface`.

**Comment by stwe** [comment]
Since we support embeddables, the dependencies are broken. I do not know if I still want to fix that.
Currently I am working on a rewrite of the bundle (1.0). Is supported only then Symfony 3.0 with PHP 5.5.9.

**Comment by Bruce17** [comment]
Let me know if you need any help on the rewrite.

I'm currently adding better test support to this bundle.

**Comment by mssimi** [comment]
What r your plans for 1.0?

**Comment by stwe** [comment]
@Bruce17 
In a few weeks (but this year) I need help for:
- write tests,
- the documentation

**Comment by Bruce17** [comment]
I already started on more tests including functional tests. I can create a
PR soon.

Am 16.10.2016 2:40 nachm. schrieb "Steffen" <notifications@github.com>:

**Comment by stwe** [comment]
@Bruce17 v2.5 is needed (http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/changelog/migration_2_5.html#embeddable-objects)

https://github.com/stwe/DatatablesBundle/blob/1.0/composer.json
