### ISSUE TITLE
add locale to actions_string.html.twig

### ISSUE THREAD

**Issue by lazaro3487** [stwe/DatatablesBundle#486]
Is posible to add these lines to SgDatatablesBundle\views\Action\actions_string.html.twig??

actual:

routeParameters = new Array(); line 9

new:

routeParameters = new Array();
{% if app.request.locale is defined and app.request.locale is not null %}
    routeParameters["_locale"] = "{{ app.request.locale }}";
{% endif %}

This is becouse the routes generated in the actions buttons has an undefined value in the locale parameter and jsRoutingBundle throws an error.

Regards.

**Comment by stwe** [comment]
https://github.com/stwe/DatatablesBundle/commit/e11dcab0e3cc26763a099e9e4f6e94c81bc76a46
