### ISSUE TITLE
tables not shown

### ISSUE THREAD

**Issue by andangr** [stwe/DatatablesBundle#490]
After installation, i follow the instruction in the document to create first datatable.
but when i access the result, it show an error " Notice: Undefined index: search"
below are my code

ProductController.php

`<?php

namespace AppBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Sg\DatatablesBundle\Tests;

class ProductController extends Controller
{
	/**
     * Lists all Post entities.
     *
     * @Route("/prd", name="poduct_index")
     * @Method("GET")
     *
     * @return Response
     */
	public function indexAction()
	{
	    $datatable = $this->get('app.datatable.product');
	    $datatable->buildDatatable();

	    return $this->render('product/index.html.twig', array(
	        'datatable' => $datatable,
	    ));
	}

	/**
	 * @Route("/prd/results", name="product_results")
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function indexResultsAction()
	{
	    $datatable = $this->get('app.datatable.product');
	    $datatable->buildDatatable();

	    $query = $this->get('sg_datatables.query')->getQueryFrom($datatable);

	    return $query->getResponse();
	}

    
}`

ProductDatatable.php
`<?php

namespace AppBundle\Datatables;

use Sg\DatatablesBundle\Datatable\View\AbstractDatatableView;
use Sg\DatatablesBundle\Datatable\View\Style;

/**
 * Class ProductDatatable
 *
 * @package AppBundle\Datatables
 */
class ProductDatatable extends AbstractDatatableView
{
     /**
     * {@inheritdoc}
     */
    public function buildDatatable(array $options = array())
    {
        $this->topActions->set(array(
            'start_html' => '<div class="row"><div class="col-sm-3">',
            'end_html' => '<hr></div></div>',
            'actions' => array(
                array(
                    'route' => $this->router->generate('product_new'),
                    'label' => $this->translator->trans('datatables.actions.new'),
                    'icon' => 'glyphicon glyphicon-plus',
                    'attributes' => array(
                        'rel' => 'tooltip',
                        'title' => $this->translator->trans('datatables.actions.new'),
                        'class' => 'btn btn-primary',
                        'role' => 'button'
                    ),
                )
            )
        ));

        $this->features->set(array(
            'auto_width' => true,
            'defer_render' => false,
            'info' => true,
            'jquery_ui' => false,
            'length_change' => true,
            'ordering' => true,
            'paging' => true,
            'processing' => true,
            'scroll_x' => false,
            'scroll_y' => '',
            'searching' => true,
            'state_save' => false,
            'delay' => 0,
            'extensions' => array(),
            'highlight' => false,
            'highlight_color' => 'red'
        ));

        $this->ajax->set(array(
            'url' => $this->router->generate('product_results'),
            'type' => 'GET',
            'pipeline' => 0
        ));

        $this->options->set(array(
            'display_start' => 0,
            'defer_loading' => -1,
            'dom' => 'lfrtip',
            'length_menu' => array(10, 25, 50, 100),
            'order_classes' => true,
            'order' => array(array(0, 'asc')),
            'order_multi' => true,
            'page_length' => 10,
            'paging_type' => Style::FULL_NUMBERS_PAGINATION,
            'renderer' => '',
            'scroll_collapse' => false,
            'search_delay' => 0,
            'state_duration' => 7200,
            'stripe_classes' => array(),
            'class' => Style::BOOTSTRAP_3_STYLE,
            'individual_filtering' => false,
            'individual_filtering_position' => 'head',
            'use_integration_options' => true,
            'force_dom' => false,
            'row_id' => 'id'
        ));

        $this->columnBuilder
            ->add('id', 'column', array(
                'title' => 'Id',
            ))
            ->add('product_name', 'column', array(
                'title' => 'Product_name',
            ))
            ->add('package_code', 'column', array(
                'title' => 'Package_code',
            ))
            ->add('price', 'column', array(
                'title' => 'Price',
            ))
            ->add('description', 'column', array(
                'title' => 'Description',
            ))
            ->add('category', 'column', array(
                'title' => 'Category',
            ))
            ->add('sub_category', 'column', array(
                'title' => 'Sub_category',
            ))
            ->add('compatibility', 'column', array(
                'title' => 'Compatibility',
            ))
            ->add('urldownload', 'column', array(
                'title' => 'Urldownload',
            ))
            ->add('status', 'column', array(
                'title' => 'Status',
            ))
            ->add('created', 'column', array(
                'title' => 'Created',
            ))
            ->add(null, 'action', array(
                'title' => $this->translator->trans('datatables.actions.title'),
                'actions' => array(
                    array(
                        'route' => 'product_show',
                        'route_parameters' => array(
                            'id' => 'id'
                        ),
                        'label' => $this->translator->trans('datatables.actions.show'),
                        'icon' => 'glyphicon glyphicon-eye-open',
                        'attributes' => array(
                            'rel' => 'tooltip',
                            'title' => $this->translator->trans('datatables.actions.show'),
                            'class' => 'btn btn-primary btn-xs',
                            'role' => 'button'
                        ),
                    ),
                    array(
                        'route' => 'product_edit',
                        'route_parameters' => array(
                            'id' => 'id'
                        ),
                        'label' => $this->translator->trans('datatables.actions.edit'),
                        'icon' => 'glyphicon glyphicon-edit',
                        'attributes' => array(
                            'rel' => 'tooltip',
                            'title' => $this->translator->trans('datatables.actions.edit'),
                            'class' => 'btn btn-primary btn-xs',
                            'role' => 'button'
                        ),
                    )
                )
            ))
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getEntity()
    {
        return 'AppBundle\Entity\Product';
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'product_datatable';
    }
}`

twig file 
`{% extends '::base.html.twig' %}

{% block body %}
   {{ datatable_render(datatable) }}
{% endblock %}`

I see only the button for add element.

when i debug on html response, i found this 

> `<table cellpadding="0" cellspacing="0" class="table table-striped table-bordered" border="0" id="product_datatable" width="100%">`
            `<thead>`
            `</thead>`
                `<tbody>`
            `</tbody>`
        `</table>`

'
        

'

**Comment by susanasanz9** [comment]
I have de same problem!

**Comment by stwe** [comment]
with dev-master?

**Comment by andangr** [comment]
i use this version ;
"sg/datatablesbundle": "^0.12.0",

**Comment by did-vmonroig** [comment]
I'm also having this problem with dev-master.

indexAction renders the table and shows Processing..., because indexResultsAction throws "Notice: Undefined index: search" error.

**Comment by susanasanz9** [comment]
Hi! I'm new on that... so I'm not sure if it is going to help you. But I have solved my problem.

I downloaded the dataTables-1.10.12.min.js and placed in web/js. Then, the script: `<script src="{{ asset('js/dataTables-1.10.12.min.js') }}"></script>` must be at the end of the base twig file. That way, my table is shown.

If I call directly on the url the route 'results', the notice: Undefined index: search is showing. But the ajax call from EntityDatatable.php works fine.

PostDatatable.php:
`$this->ajax->set(array(
            'url' => $this->router->generate('post_results'),
            'type' => 'GET',
            'pipeline' => 0
        ));`
That works ok.

Hope that helps!

**Comment by stwe** [comment]
ok i will take a look

**Comment by stwe** [comment]
@susanasanz9 : you can sse the table?

@andangr / @did-vmonroig : I can't reproduce the issue. Please take a look to my DemoProject an be sure that install all assets

**Comment by susanasanz9** [comment]
Yes I can see the table. 

Also, the asset
`<script src="https://cdn.datatables.net/u/bs/jszip-2.5.0,pdfmake-0.1.18,dt-1.10.12,b-1.2.1...`
is getting me an error in the console. I just have changed that script for
`(dataTables-1.10.12.min.js)` and I call it from the bottom of the base.html.twig

**Comment by did-vmonroig** [comment]
@stwe : Sorry, you were right. If I call directly to indexResults, I throws a 500 error, "Notice: Undefined index: search", but I've realized that it's not meant to be called that way. My problem was a faulty FOSJsRoutingBundle installation.

**Comment by andangr** [comment]
nice, thank you..
Don't forget to clear cache, sometime your page will never be updated until you clear cache.

**Comment by susanasanz9** [comment]
I'm not sure. I thinck I'm not.
I don see any .dev-master version in composer.json

2016-10-22 21:18 GMT+02:00 Steffen <notifications@github.com>:
