### ISSUE TITLE
Mana to many builder add first

### ISSUE THREAD

**Issue by susanasanz9** [stwe/DatatablesBundle#494]
Hi,
I have a many to many relationship: Cameras anf Formats.
I have a CameraDatatable its array of Formats is showing ok when I use:

` ->add('formats.resolutionW', 'array', array(
            'title' => 'resolutionW',
            'data' => 'formats[, ].resolutionW' // required option
            ))`
Thas shows each parameter resolutionW of the entire array of formats given,
but I would like to manage just the first format entity of the array given. Then show his resolutionW.
Something like `formats[index(0)].resolutionW`
Any ideas?

Thanks!

**Comment by mssimi** [comment]
Have u tried line formatter?

**Comment by stwe** [comment]
Use the LineFormatter.
