### ISSUE TITLE
Exemple How to start ?

### ISSUE THREAD

**Issue by ychoucha** [stwe/DatatablesBundle#496]
Hello, 

 i m looking a how to , please 

I m looking how to create entity to show the datatables ?

can u have a create example to zero to the editable datatables please

**Comment by giovkanata** [comment]
[DEMO APPLICATION](https://github.com/stwe/DtBundleDemo)

**Comment by ychoucha** [comment]
Hello, 
i know that, but whit that i can 't understand all step to make datatables working

**Comment by ychoucha** [comment]
Sorry, can anyone can help me to create my first datatable using the bundle please : 

# 1> Datatables with one entity no relation

## 1.1> So first i create a entity "agency" : 

`php bin/console doctrine:generate:entity --entity="AppBundle:agency" --fields="name:string(255)" --no-interaction
`
## 1.2> I create a fixture to add some agency :
`<?php
namespace AppBundle\DataFixtures\ORM;
use AppBundle\Entity\agency;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
/**
 * Class LoadData
 *
 * @package AppBundle\DataFixtures\ORM
 */
class agencyData implements FixtureInterface
{
    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
    	$arrayAgencys = array( 
    						array("name"=> 'Edinburgh'),
    						array("name"=> 'London'),
			    			array("name"=> 'Paris'),
			    			array("name"=> 'New York'),
			    			array("name"=> 'San Francisco'),
			    			array("name"=> 'Sidney'),
			    			array("name"=> 'Singapore'),
			    			array("name"=> 'Tokyo'),
			    			array("name"=> 'Dubaï'),
			    			array("name"=> 'Washington'),
    						array("name"=> 'Shenzhen')
    					);    	
    	foreach ($arrayAgencys as $agencyTMP){
    		$agency = new agency();
    		$agency->setName($agencyTMP["name"]);
    		$manager->persist($agency);
    	}
	$manager->persist($agency);     
        $manager->flush();
    }   
}
`

## 1.3> create datatables view

Files : /AppBundle/Datatables/agencyDatatable.php

## 1.4> create twig view



2> i create a new entity "advisor" and i add a relation : 

agency <--- N..N---> advisor



ok so now can u help me to complete all step please

**Comment by stwe** [comment]
@ychoucha  in my opinion, this bundle has a good documentation. See:

https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/installation.md

and the demo bundle.

Maybe you are missing some basic knowledges in Symfony?

**Comment by ychoucha** [comment]
ok,
missing some knowlodge with symfony for now.

so i can't use u bundle for now, i have to use datatables with the old ways :/
