### ISSUE TITLE
Passing optional data to server

### ISSUE THREAD

**Issue by cure85** [stwe/DatatablesBundle#498]
Hi,

Is it possible to pass optional data to server?
Something like: https://datatables.net/reference/option/ajax.data

I'd like to make a select dropdown filter outside of DataTable which will pass a parameter to the QUERY to get for example "only records which bellong to specific category" and show ONLY them in the datatables. 

With the select Dropdown I will have an option to select (ALL, Category1, Category2, ...., CategoryN)

Category should not be visible in the Datatble, so I can not use individual filter option.

Is this possible to build with this bundle as it is now?

Best regards

**Comment by stwe** [comment]
Not in version 0.13.

In version 1.0 this will be possible.

**Comment by Spleach** [comment]
Hi,

I would like to know how can you do it ?

Thanks
