### ISSUE TITLE
Support for DDD

### ISSUE THREAD

**Issue by LauLaman** [stwe/DatatablesBundle#499]
i'm developing using DDD:
My entities are in de `App` domain
My 'Symfony Logic' is in my `AppBundle` Domain

When i try to generate the datatable for my entity i will get the following error:
```
$ bin/console sg:datatable:generate App:Donation --bootstrap3

Bundle "App" does not exist or it is not enabled. Maybe you forgot to add it in the registerBundles() method of your AppKernel.php file?
```

it would be lovely to have support for DDD

**Comment by stwe** [comment]
```
$ bin/console sg:datatable:generate AppBundle:Donation --bootstrap3
```

**Comment by LauLaman** [comment]
This will not work since the entities are not in my `AppBundle`
`Donation.php` is located at `App\Entity\Donation`
this because i want to keep the framework and application logic seperate

**Comment by stwe** [comment]
No reason for a down emotion. Create a Class by hand.

**Comment by LauLaman** [comment]
WTF. 

I just thought this would be a nice feature for the whislist since i think it can be of value for more developers. 

You just close the Issue without starting a dialog or saying you won't do this, and give an totally unrelated comment..

**Comment by stwe** [comment]
Ok sorry I haven't read (I mean the German word "überlesen" ) that your Entities in the App domain.

**Comment by fyrye** [comment]
I agree the option to use `--entity=app:MyEntity` and `--bundle=AppBundle` or `--output-dir=/path/to/output-dir` would be awesome.

**Comment by stephanvierkant** [comment]
Related to #579?
