### ISSUE TITLE
Access entity getter not attached to stored data

### ISSUE THREAD

**Issue by travis1012** [stwe/DatatablesBundle#501]
Hi,

I was wondering if it is possible to use this plugin to access a getter, which does not have the same name a stored variable.

e.g.
```

protected $firstName;
protected $lastName;

public function getFullName() {
return $firstName . " " . $lastName;
}

// (column builder)
// ....
->add('fullName', 'column', [
                'title' => 'Full Name'
])
// ....
```

I have tried to see if this is possible, but I feel that it is not, and I have a number of generated variables on the fly. It would be great if someone could please point me in the right direction.

Thanks.

**Comment by stwe** [comment]
For the fullname you can use a virtual field with the LineFormatter.
