### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by agalchenko** [stwe/DatatablesBundle#505]
Hi!

I have a question about the use of alternative data sources for the table.
I need to build a table with a dynamic number of columns.
Can I use json or js array as a **data source**, as the **'data'** of the original version https://datatables.net/manual/data/?
I see the $data variable in class AbstractDatatableView, but I can not use it.

Thanks.

**Comment by stwe** [comment]
This Bundle supports only the server-side-mode. In server-side processing mode, all ordering, searching, etc. of the data is handed off to the server.  What you want is a client side mode. But I do not support this anymore. Sorry.
