### ISSUE TITLE
Add a button in controller?

### ISSUE THREAD

**Issue by ljmoleiro** [stwe/DatatablesBundle#506]
I have my datatable class defined with two buttons(edit,delete), but when i try to define a new button in my controller with a new route, it doesn't work, the button is not rendered in view,
then I define this button in datatable class and works fine.

**Comment by stwe** [comment]
You must define the buttons in both Controller Actions (indexAction && resultAction).

**Comment by ljmoleiro** [comment]
I'am already define the button in two controller actions (indexAction && resultAction), and buttons are not rendered yet, seems that when buttons are not declared in the original Entity DataTable Class (MyEntityDatatable) they don't show up in view.
