### ISSUE TITLE
Support for postgres in symfony 2.8???

### ISSUE THREAD

**Issue by junimen91** [stwe/DatatablesBundle#507]
Estoy tratando de integrar al Bundle al un sistema que usa postgres, pero estoy teniendo inconvenientes, me retorna [Syntax Error] line 0, col 25: Error: Expected Doctrine\ORM\Query\Lexer::T_OPEN_CURLY_BRACE, got 'menu_entity', alguien sabe como corregir esto..

Lo he utilizado con Oracle en diferentes esquemas, pero porque al usarlo en postgres con diferentes esquemas no funciona?, si es verdad la sensibilidad de postgres en las consultas debe jugar un rol aqui, pero alguien ha solucinado esto, existe alguna configuracion, por favor ayudenme!.

**Comment by witzkito** [comment]
Hola Junimen, en la pagina principal del bundle en limitaciones dice,

> PostgreSql is currently not fully supported.


Tal vez sea eso.

**Comment by junimen91** [comment]
Saludos, si, talvez sea es... Pero cuando se trabajo con esquema public de Postgres no sucede ningun error, el detalle es cuando se crea diferentes esquemas, y en la entidad se declara @ORM\Table(name="esquema.table") al momento de que se genera el sql para mostrar en el datatable se genera asi "SELECT partial esquema.table.{id, nombre} from \Core\YourBundle\Entity\Table esquema.table where esquema.table.nombre asc"... entonces eso causa un error, deberia crear asi el DQL "SELECT partial table.{id, nombre} from \Core\YourBundle\Entity\Table table where table.nombre asc"...

Yo logre solucionar esto, no creo que sea lo más optimo pero me funciona... customize la funcion setupColumnArrays() que se encuentra en DatatableQuery.php..

**Comment by stwe** [comment]
Bad news: PostgreSql is currently not fully supported. There are several tickets open. Please wait.
