### ISSUE TITLE
Unknown "imagine_filter" filter in ii_render_image.html.twig

### ISSUE THREAD

**Issue by ptyskju** [stwe/DatatablesBundle#510]
Hi!
I am receiving error 500 in prod env because of this:

> assetic.ERROR: The template "SgDatatablesBundle:Helper:ii_render_image.html.twig" contains an error: Unknown "imagine_filter" filter in "SgDatatablesBundle:Helper:ii_render_image.html.twig" at line 14.

I am not using imagine, my tables even not have any images or galleries.

**Comment by fyrye** [comment]
@stwe I got the same after manually deleting the cache and performing. `php app/console --env=prod cache:warmup` in Symfony 2.8.14 without LiipImagineBundle installed.
```
[2016-12-27 10:04:29] assetic.ERROR: The template "SgDatatablesBundle:Helper:ii_render_image.html.twig" contains an error: Unknown "imagine_filter" filter in "SgDatatablesBundle:Helper:ii_render_image.html.twig" at line 14.
```

After installing [LiipImagineBundle ](http://symfony.com/doc/master/bundles/LiipImagineBundle/installation.html#step-1-download-the-bundle) the error goes away.

**Comment by elpoutro** [comment]
I get the same after running
`php app/console debug:translation fr --all`

Is that a lack in the dependency definition of the bundle?
May be we can add liip/imagine-bundle in composer.json ?
