### ISSUE TITLE
template customization

### ISSUE THREAD

**Issue by SpiGAndromeda** [stwe/DatatablesBundle#511]
Hi,

i noticed that there is no general mechanism to customize the templates used to generate the table and the functions. 

By customzing the templates it would be possible to integrate every css framework. For example I use the kube framework and it seems that there is no possbility to customize the pagination for using the kube pagination markup.

I hope I just didn't miss that option.

**Comment by stwe** [comment]
You can try to use the `dom` option https://datatables.net/reference/option/dom
Or you wait for a DataTables' Kube integration.

**Comment by stwe** [comment]
There are some ways to change the templates with Symfony. That should not be a problem. If so, please open a ticket.
