### ISSUE TITLE
Error in global search of datatables

### ISSUE THREAD

**Issue by Alice-ing** [stwe/DatatablesBundle#512]
Hello
I am using the bundle in my project with postgres I visualize the data well but when doing the global search I get this error:

jquery.min.js:4 GET http://localhost/DtBundleDemo-master/web/post/results?draw=2&columns%5B0%5D…rt=0&length=50&search%5Bvalue%5D=t&search%5Bregex%5D=false&_=1482031462406 500 (Internal Server Error)

What could it be? Do you have any solution that will help me?

**Comment by stwe** [comment]
Postgresql is currently not fully supported. Unfortunately, you have to wait.....
