### ISSUE TITLE
Add row number column to jquery datatables

### ISSUE THREAD

**Issue by abdallahmaali** [stwe/DatatablesBundle#516]
how i can  add the row number  , i tried to do some thing like following example but its not working  
http://stackoverflow.com/questions/6871198/add-row-number-column-to-jquery-datatables

**Comment by abdallahmaali** [comment]
any one could help me on this issue ?

**Comment by Seb33300** [comment]
Are you using `master` or `v0.13` branch?

Callbacks are [not available](https://github.com/stwe/DatatablesBundle/blob/master/FEATURES.md) in the `master` branch, so it is not possible at the moment.

If you are using the `v0.13` branch, did you try to add a callback like in your link example?
https://github.com/stwe/DatatablesBundle/blob/v0.13/Resources/doc/setup.md#3-callbacks

**Comment by stwe** [comment]
I'll take a look at it when I implement the callbacks

**Comment by abdallahmaali** [comment]
i'm using master  branch

**Comment by bettinz** [comment]
Hello, this is my post from: #562 

Hello @Seb33300 , thank you for the reply. I've read about this code everywhere:

```js
ObjDt.on( 'order.dt search.dt', function () {
    ObjDt.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
       cell.innerHTML = i+1;
    });
}).draw();
```

```js
t.on( 'order.dt search.dt', function () {
    t.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
        cell.innerHTML = i+1;
    } );
} ).draw();
```
And in every code they access to the Datatable object (ObjDt and t); what I can't do, so far, is to access to the datatable. I'm using 0.13 so callbacks works, my question is how to use this code with the oTable object (I think it's oTable, right?)

**Comment by bettinz** [comment]
In 0.13 I've solved with:

row.js.twig:

```js
function rowCallback(nRow, aData, index) {
    console.log(test);

    $('td:eq(0)',nRow).html(index);

    return nRow;
}
```
datatable:
```php
        $this->callbacks->set(array(
            'row_callback' => array(
                'template' => ':workEvent:init.js.twig',
            ),
        ));
```

**Comment by gkrauze** [comment]
@bettinz answer is almost working.
To complete this I had to add a "page" event:
```
function page(e, datatable) {
    window.displaystart = datatable._iDisplayStart;
}
```
and then in the rowCallback:

``` 
 function rowCallback(nRow, aData, index) {
    var ds = window.displaystart|0;
    if(nRow){
        $('td:eq(0)',nRow).html(ds+index+1);
    }
    return nRow;
}
```

Of course if I have multiple datatables on one view, I have to change the variable displayStart into some array containing values for each datatable.
