### ISSUE TITLE
Unique ids for multiselect checkboxes

### ISSUE THREAD

**Issue by gkrauze** [stwe/DatatablesBundle#518]
Hi,

I was searching for possibility to add unique id for checkbox on multiselect column rows but I didn't find such feature. You can either add same id for each checkbox in the multiselect column or omit id attribute. First solution which also appears on examples on documentation is incorrect since id attribute is supposed to be unique.

I can point to a specific checkbox with a Javascript but it would be much easier if id was composed of string given in options and for example id of entity object.

Or maybe it is possible right now.

Regards.

**Comment by stwe** [comment]
I don't' understand.

Every Checkbox becomes an an unique value (e.g. the entity ID) with:

```
'value' => 'id',
```

or use the `attributes` option

```
                'attributes' => array(
                    'data-foo' => uniqid()
                ),
```

**Comment by gkrauze** [comment]
I meant the feature to give id attribute for the checkbox but the one you can predict. If there was a possibility to compose one with fields of the entity in the row, it would give some advantage in obtaining checkbox on specific row.

For example an array parameter which defines composition of the id attribute:

     'id_compose' => ['prefix', 'id']

where `prefix` is any string and `id` is the name of column (for example identifier column). This could produce input checkbox with `id="prefix234"`, with which I can point directly to the input from outside of the table. For example getElementById('prefix'+idStoredElsewhere)....`. With `value = 'id'` I have to use filter selector which is simply much slower and also not so obvious solution.

I thought it could be easy since you provide value of input with the chosen column.

Regards.

**Comment by stwe** [comment]
Ok I understand. You want a unique ID prefix. That makes sense.
The name of the datatable can be used again (eg sg_datatables_post_datatable_5).

**Comment by gkrauze** [comment]
Thanks :)

**Comment by stwe** [comment]
``` php
                'value' => 'id',
                'value_prefix' => true,
```

**Comment by gkrauze** [comment]
@stwe I just wanted to say that I meant the id attribute not value attribute. Is it possible that you provide an option to compose the id attribute in the same way? This is what I wrote before in fact.
