### ISSUE TITLE
Google Material Design styling

### ISSUE THREAD

**Issue by gkrauze** [stwe/DatatablesBundle#519]
Hi,

It would be nice to have possibility of styling with Google Material Design. 
For now I'm doing it with jquery manipulations on DOM but it would be a good feature for many other developers just to use configuration option to apply components for example from this library: 
[Google Material Design Lite components](https://getmdl.io/components/)

This feature is also mentioned in [Datatables styling](https://datatables.net/examples/styling/material.html)

**Comment by stwe** [comment]
You can include the css and js files and you have the Google Material Design. More is not planned by me.
