### ISSUE TITLE
Responsive priority

### ISSUE THREAD

**Issue by Zoopme** [stwe/DatatablesBundle#520]
Hi,

I am trying to use the responsivePriority column option (in relation with the responsive extension), described here : [Datatables.net: columns.responsivePriority](https://datatables.net/reference/option/columns.responsivePriority).

It seems that the option is not available via the bundle.

A possible solution would be to achieve the following :

```
$this->columnBuilder
    ->add('title', 'column', array(
        'attr' => array('data-priority' => '1')
    ))
;
```

Any help much appreciated.

**Comment by stwe** [comment]
as column option available in dev-master

**Comment by Zoopme** [comment]
Thanks @stwe.
