### ISSUE TITLE
Embeddable support in master

### ISSUE THREAD

**Issue by SpiGAndromeda** [stwe/DatatablesBundle#521]
Hi,

til yesterday I used the 0.13 version of this bundle. In order to use the oderData option I moved to the master branch. 

In my project I am using some embeddables. In 0.13 they are used by escaping the point with backslahses:

`embeddable\\.property`

This isn't working now. It leads to an rex-expression error in the query builder. But using the point without backslashes suggests the system to handle this as an association. I looked through the code and didn't find any part considering embeddables. 

So I want to know if this isn't implemented yet, is it forgotten or not done yet or did I miss something?

Best regards
spigandromeda

**Comment by stwe** [comment]
Comes as soon as possible
