### ISSUE TITLE
Many-to-one / Array to string conversion

### ISSUE THREAD

**Issue by turegjorup** [stwe/DatatablesBundle#522]
I'm getting an `Array to string conversion` error in `vendor/sg/datatablesbundle/Sg/DatatablesBundle/Response/DatatableQueryBuilder.php at line 321` on the latest dev/master (f763874d8efac9711564864678f3fc7aa084e6ac)

My column is set up as
```
$salgsomraader = $this->em->getRepository('AppBundle:Salgsomraade')->findAll();
```
```
->add('salgsomraade.titel', Column::class, array(
  'title' => 'Område',
  'searchable' => true,
  'orderable' => true,
  'filter' => array(SelectFilter::class, array(
    'select_options' => array('' => 'All') + $this->getOptionsArrayFromEntities($salgsomraader, 'id', 'titel'),
    'search_type' => 'eq'
  ))
))
```

Entities:
```
class Grund {

...

  /**
   * @var \Salgsomraade
   *
   * @ORM\ManyToOne(targetEntity="Salgsomraade")
   * @ORM\JoinColumns({
   *   @ORM\JoinColumn(name="salgsomraadeId", referencedColumnName="id")
   * })
   */
  private $salgsomraade;

```

```
class Salgsomraade {

  /**
   * @var integer
   *
   * @ORM\Column(name="id", type="bigint", nullable=false)
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="IDENTITY")
   */
  private $id;

  /**
   * @var string
   *
   * @ORM\Column(name="titel", type="string", length=255, nullable=false)
   */
  private $titel;


```

The Select element is correctly output and populated (without Bootstrap styling though), but the AJAX call to fetch content fails with a 500/Array to string conversion:
```
at ErrorHandler ->handleError ('8', 'Array to string conversion', '/vagrant/htdocs/vendor/sg/datatablesbundle/Sg/DatatablesBundle/Response/DatatableQueryBuilder.php', '321', array('qb' => object(QueryBuilder), 'value' => array('alias' => 'salgsomraade', 'type' => 'leftJoin'), 'key' => 'grund.salgsomraade', 'this' => object(DatatableQueryBuilder))) 
in vendor/sg/datatablesbundle/Sg/DatatablesBundle/Response/DatatableQueryBuilder.php at line 321
```

Any cues to what I'm missing?

**Comment by stwe** [comment]
```
  /**
   * @var \Salgsomraade
   *
   * @ORM\ManyToOne(targetEntity="Salgsomraade")
   * @ORM\JoinColumn(name="salgsomraadeId", referencedColumnName="id")
   */
  private $salgsomraade;
```

**Comment by turegjorup** [comment]
Thanks for the reply, Doctrine annotations updated as you suggested. Unfortunately I still get the exact same error

**Comment by stwe** [comment]
Ok. Have you updated your database schema and cleared the cache?

**Comment by turegjorup** [comment]
Yes, Doctrine schema and mapping validate OK, and cache cleared with both `cache:clear` and `rm -rf var/cache`. Still the same error.

You can see the complete code here: https://github.com/grundsalg-aarhus/grundsalg-admin/blob/feature/GRUND-159_DatatablesBundle_1.0_dev/src/AppBundle/Datatables/GrundDatatable.php

Potentially it is a PHP issue - we're using PHP 7.0.14. I read "PHP 5.5.9" as "greater than", but see now that you don't write "or higher" for PHP in the installation chapter?

**Comment by stwe** [comment]
ok, dump your Query with:

``` php
        if ($isAjax) {
            $responseService = $this->get('sg_datatables.response');
            $responseService->setDatatable($datatable);

            $datatableQueryBuilder = $responseService->getDatatableQueryBuilder();
            $datatableQueryBuilder->buildQuery();

            dump($datatableQueryBuilder->getQb()->getDQL()); die();

            return $responseService->getResponse();
        }
```

and show your json-response string

**Comment by stwe** [comment]
Please open again if necessary - with Query and response dumps

**Comment by turegjorup** [comment]
Tested again. If I'm on PHP 5.6 it works, but it fails on PHP 7. Given that you don't support PHP 7 the issue can remain closed. 

For future reference here is some info on the error. On PHP 7 I can't give you neither query nor json-response because it fails while building the query, so I receive a "500 Internal Server Error - ContextErrorException" from Symfony. 

It fails when calling `$datatableQueryBuilder->buildQuery();` in the controller. The line that ultimatly fails is 339 in `Sg\DatatablesBundle\Response\DatatableQueryBuilder`

```
336    private function setJoins(QueryBuilder $qb)
337    {
338        foreach ($this->joins as $key => $value) {
339            $qb->$value['type']($key, $value['alias']);
340        }
341
342        return $this;
343    }
```

Just in case you want to support PHP 7 in v1.0 going forward.

**Comment by stwe** [comment]
@turegjorup There is already a PR for this issue. I will fix this as soon as possible.

see: https://github.com/stwe/DatatablesBundle/pull/538
