### ISSUE TITLE
Inject raw DQL in columns

### ISSUE THREAD

**Issue by Seb33300** [stwe/DatatablesBundle#525]
Hello

Is it possible to add a sub query to set the content of a column?

For instance, on the DtBundleDemo, in the PostDatatable, I would like to add a column to show the count comment of each post.

Seb

**Comment by stwe** [comment]
This should also work with a virtual column and the LineFormatter.

**Comment by Seb33300** [comment]
The `$row` var in the `LineFormatter` is only an array, not the entity object.

So it means that I have to count elements by making a query with the entity manager in the LineFormatter function?
And the query will be executed on each row.

And I will not be able to activate search or order on this column since it is a calculated field without relation with an existing field.


Subqueries (or any valid other DQL code) have the advantage that it can be used in select, where and order by clauses.
So they will be searchable and orderable.

This could be a `DqlColumn` like:
```
$this->columnBuilder
    ->add('SELECT COUNT(e) FROM MyBundle:Entity e WHERE e.id = parentAlias.id', DqlColumn::class, array(
        'title' => 'Title',
        'searchable' => true,
        'orderable' => true,
    ))
;

// will result in
$queryBuilder
    ->select('(SELECT COUNT(e) FROM MyBundle:Entity e WHERE e.id = parentAlias.id) as dqlalias')
    ->where('(SELECT COUNT(e2) FROM MyBundle:Entity e2 WHERE e2.id = parentAlias.id) = :search')
    ->orderBy('dqlalias', 'asc')
;
```

other example:
```
$this->columnBuilder
    ->add('SELECT COUNT(e) FROM MyBundle:Entity e WHERE e.id = parentAlias.id', DqlColumn::class, array(
        'title' => 'Title',
        'searchable' => true,
        'orderable' => true,
    ))
;

// will result in
$queryBuilder
    ->select("(CASE WHEN parentAlias.field < 5 THEN 'ok' ELSE 'ko' END) dqlalias")
    ->where("(CASE WHEN parentAlias.field < 5 THEN 'ok' ELSE 'ko' END) = :search")
    ->orderBy('dqlalias', 'asc')
;
```

**Comment by Seb33300** [comment]
I am thinking about this again.

Instead of making a new `DqlColumn` column type, we could just add a boolean `raw_dql` option to all columns types.

If `raw_dql` is `true`, we can skip automatic metadata detection and others (automatic joins, etc...) et add the `raw_dql` string to the select.

Basic example:
```
this->columnBuilder->add('LENGTH(field_name)', Column::class, ['raw_dql' => true, 'type_of_field' => 'integer']);
```


I also have a case where I need to make a custom join on my entity, so it can't be done automatically.
I modified the DatatableQueryBuilder to add the join but I am not able to add the column because it tries to auto join.
It could be done with raw DQL
```
// Custom join
$queryBuilder = $responseService->getDatatableQueryBuilder()->getQb();
$queryBuilder->join('XXX', 'custom_join_alias', 'WITH', 'XXX');

// Datatable column
this->columnBuilder->add('custom_join_alias.field_name', Column::class, ['raw_dql' => true]);
```

And of course, this should also works with subqueries:
```
this->columnBuilder->add('SELECT COUNT(e) FROM MyBundle:Entity e WHERE e.id = parentAlias.id', Column::class, ['raw_dql' => true]);
```

**Comment by Seb33300** [comment]
Just submit a pull request https://github.com/stwe/DatatablesBundle/pull/551 to make it possible:
``` php
$this->columnBuilder
    ->add('full_name', Column::class, array(
        'title' => 'Full name',
        'dql' => 'CONCAT(user.fisrtname, ' ', user.lastname)',
        'searchable' => true,
        'orderable' => true,
    ))
    // If you want to use a subquery, please put subquery between parentheses and subquery aliases between braces.
    // Note that subqueries cannot be search with a "LIKE" clause.
    ->add('post_count', Column::class, array(
        'title' => 'User posts count',
        'dql' => '(SELECT COUNT({p}) FROM MyBundle:Post {p} WHERE {p}.user = user.id)',
        'searchable' => true,
        'orderable' => true,
        'type_of_field' => 'integer',
    ))
;
```

**Comment by Seb33300** [comment]
This issue will be closed after https://github.com/stwe/DatatablesBundle/pull/561 will be merged
