### ISSUE TITLE
Global filtering not working options is not set

### ISSUE THREAD

**Issue by Seb33300** [stwe/DatatablesBundle#527]
Hello,

In order to make the global filter to work (input at the top right corner), we need to set the `options` value even if we don't have any option to set.

If I don't add this line:
```
$this->options->set([]);
```

Global filtering don't work.

This should works even if `options` is not set.

**Comment by stwe** [comment]
```
$this->options->set([]);
```
This sets the default values for all the options. The default value for "global_search_type" is "like".

In most cases, the user sets some option. Therefore, I have decided to implement it so that the function "set" must be called in any case.
