### ISSUE TITLE
Action column on the first column and default sort

### ISSUE THREAD

**Issue by Seb33300** [stwe/DatatablesBundle#531]
Hello,

By default, sorting is applied on the first column, even when the first column is an action column which cannot be sorted.

Default sorting should be applied to the first sortable column.

Seb

**Comment by stwe** [comment]
You must change the order option. For the first Column:

``` php

        $this->options->set(array(
            // ...
            'order' => array(array(1, 'asc')), // Initial order (sort) to apply to the table.
        ));
```
