### ISSUE TITLE
Footer customization

### ISSUE THREAD

**Issue by robertosanval** [stwe/DatatablesBundle#532]
How could I customize the footer text? I can't find any documentation about this...

**Comment by stwe** [comment]
What a footer text.

**Comment by robertosanval** [comment]
The text that says "Showing x records of x (Filtered of x records).

How can I customize it or disable it?

**Comment by Seb33300** [comment]
If you want to disable it, just change the [dom option](https://datatables.net/reference/option/dom):
```
$this->options->setDom('lfrtp');
```

**Comment by stwe** [comment]
``` php
        $this->options->set(array(
            'dom' => 'lfrtp'
        ));
```
