### ISSUE TITLE
Datatable factory

### ISSUE THREAD

**Issue by Seb33300** [stwe/DatatablesBundle#534]
Hello,

I think it could be very interesting to provide a datatable factory service.

In the same way symfony provide a `createForm` method, we could have a `createDatatable` method instead of defining a service for each datatable we have (which is tiring when we have a lot of datatables).

```
public function myAction()
{
    $myDatatable = $this->createDatatable(MyDatatable::class);
    $myDatatable->buildDatatable();
    // ...
}
```

**Comment by mssimi** [comment]
I like this idea, but what about similar approach with response?

Now we got(1.0)
```
$responseService` = $this->get('sg_datatables.response');
$responseService->setDatatable($datatable);

$datatableQueryBuilder = $responseService->getDatatableQueryBuilder();
$datatableQueryBuilder->buildQuery();

return $responseService->getResponse();
```

This would be cool

`$datatable->createResponse();`

**Comment by mssimi** [comment]
So it is not possible to implement helper method for response?

**Comment by stwe** [comment]
For Example?

**Comment by mssimi** [comment]
I made pull request with updated doc.

**Comment by Seb33300** [comment]
Are we able to access the query builder to make custom query filters with your helper?

**Comment by mssimi** [comment]
Well you can still do that old way if needed, or we can add one more helper for this. I also have idea how we could customize query right inside datatable class itself #555.
