### ISSUE TITLE
Same datatables multiple times on the same page

### ISSUE THREAD

**Issue by Seb33300** [stwe/DatatablesBundle#536]
Hi,

I would like to display the same datatables multiple times on the same page (with different options passed).

**Controller**
```php
// Awaiting approbation tasks
$awaitingApprobationTasks = $this->get('app.datatable.task');
$awaitingApprobationTasks->buildDatatable([], Task::STATE_AWAITING_APPROBATION);

// Pending tasks
$pendingTasks = $this->get('app.datatable.task');
$pendingTasks->buildDatatable([], Task::STATE_PENDING);

return [
        'awaitingApprobationTasks' => $awaitingApprobationTasks,
        'pendingTasks'             => $pendingTasks,
];
```

**View**
```twig
<h4>Awaiting Approbation Tasks</h4>
{{ sg_datatables_render(awaitingApprobationTasks) }}

<h4>Pending Tasks</h4>
{{ sg_datatables_render(pendingTasks) }}
```

But this results in an unique datatable where columns are added twice.

Any way to add the same datatable multiple times?

Thanks

**Comment by stwe** [comment]
The first thing I remember when reading this issue: The table name is the same for all tables. However, this is used as a selector. That's a problem.

**Comment by DarekTw** [comment]
Hi Seb33300,
First of all datatables need to have different names, You can do this by pass dt name by options in buildDatatable method

getName function should then look like this code
```php
    public function getName() {
        return $this->dtName;
    }
```
If You use multi-select actions then take a look at pull request
https://github.com/stwe/DatatablesBundle/pull/626

**Comment by Seb33300** [comment]
Fixed by https://github.com/stwe/DatatablesBundle/commit/c6180162a6ff8d350d8909f9f74599fc977ab6b7

**Comment by RefreshMyMind** [comment]
Can you please share an example of a controller action that handles 2 datatables, I get problem loading data for each one.
