### ISSUE TITLE
Composite primary key

### ISSUE THREAD

**Issue by lazaro3487** [stwe/DatatablesBundle#537]
This bundle support composite primary keys when a foreign Key forms part of the primary key??

I have a table with a primary key conformed by 3 columns, 1 of then is a foreign key but at the execution time this errors is thrown:

Single id is not allowed on composite primary key in entity AppBundle\Entity\GeneralStopSale

Regards.

**Comment by stwe** [comment]
This bundle doesn't support composite Doctrine keys. I don't plan to add this feature anytime soon, so I must close this issue as "won't fix". I'm sorry.
