### ISSUE TITLE
virtual 'searchable'=> true, error

### ISSUE THREAD

**Issue by grekpg** [stwe/DatatablesBundle#540]
i use version  "sg/datatablesbundle": "^0.13.0",

when i use 

 ->add('tags.title', 'virtual', array(
                'searchable'=> true,
                'filter' => array('select2', array(
                    'select_options' => $tags,
                )),

i get error: 

`[Syntax Error] line 0, col 441: Error: Expected StateFieldPathExpression | string | InputParameter | FunctionsReturningStrings | AggregateExpression, got 'LIKE'`

why virtual row try search ? I use search true to get value and create manual query manipulate

**Comment by stwe** [comment]
The "VirtualColumn" is not "searchable" in version 0.13

**Comment by davidromani** [comment]
@stwe and there is any workaround? I can't upgrade further than this version (0.13)
