### ISSUE TITLE
Search field

### ISSUE THREAD

**Issue by grekpg** [stwe/DatatablesBundle#541]
i try this : 

> ->add('tags.title', 'array', array(
>                 'title' => 'Tagi',
>                 'searchable'=> true,
>                 'data' => 'tags[, ].title',
>                 'filter' => array('select', array(
>                     'select_options' => $tags,
>                     'search_type' => 'eq',
>                 )),
> 

but get wrong query 

 WHERE m5_.title = '163' 

i need search in id not title, i can't find how to do this.

for row array 
The option "search_column" does not exist

**Comment by stwe** [comment]
Try the "property" option

**Comment by grekpg** [comment]
Thanks for reply I add 
 'property' => 'tags.id', but it still look in wrong field: 


>   ->add('tags.title',  'array', array(
>                 'title' => 'Tagi',
>                 'searchable'=> true,
>                 'data' => 'tags[, ].title',
>                 //'search_column' => 'tags.id',
>                // 'search_column' => 'tags.id',
>                 'filter' => array('select', array(
>                     'select_options' => $tags,
>                     'search_type' => 'eq',
>                     //'search_column' => 'tags.id',
>                     //'multiple' => true,
>                     'property' => 'tags.id',
> 
>                 )),
> 

WHERE m0_.id LIKE '%161%' AND m0_.id IN ('161')

this is wrong table - LEFT JOIN meet_keyword m6_ - why it look in main table ?

**Comment by stwe** [comment]
``` php
        $tags = $this->em->getRepository('AppBundle:Tag')->findAll();
```

``` php
            ->add('tags.id', Column::class, array(
                'title' => 'Tag ids',
                'data' => 'tags[, ].id',
            ))
            ->add('tags.name', Column::class, array(
                'title' => 'tag',
                'searchable' => true,
                'orderable' => true,
                'data' => 'tags[, ].name',
                'filter' => array(SelectFilter::class, array(
                    'select_options' => array('' => 'All') + $this->getOptionsArrayFromEntities($tags, 'id', 'id'),
                    'search_type' => 'eq',
                    'cancel_button' => true,
                    'search_column' => 'tags.id'
                )),
            ))
```
