### ISSUE TITLE
Impossible to add more than one route's parameter

### ISSUE THREAD

**Issue by greg-avanim** [stwe/DatatablesBundle#542]
In action column, if I add more than one route's parameter, it takes "undefined" value.
Thanks in advance,

**Comment by stwe** [comment]
in dev-master?

**Comment by greg-avanim** [comment]
Sorry dev-master requires symfony 3.0 I can't test it on my symfony 2.8...

**Comment by stwe** [comment]
This will be a problem with 0.13. Works with dev-master.
