### ISSUE TITLE
In-place editing uses wrong entitymanager

### ISSUE THREAD

**Issue by DennisBiesters** [stwe/DatatablesBundle#543]
The datatable uses non default entitymanager but the in-place editing uses the default entitymanager.

Causing the following exception:
The class 'LogBundle\Entity\Blacklist' was not found in the chain configured namespaces AppBundle\Entity

Is it possible to use a non-standard field for the pk (other than id) when using in-place editing? If the column id is not present in the datatable it causes the following exception because the posted pk is undefined: 
The entity does not exist.

**Comment by stwe** [comment]
in dev-master?

**Comment by DennisBiesters** [comment]
stable v0.13

**Comment by stwe** [comment]
You mean the EM in the controller? With dave-master you can write your own action and specify this as Editable-Option.

**Comment by DennisBiesters** [comment]
I mean the EM that is used by the in-place editor. My datatable uses the LogBundle EM for displaying, but the in-place editing uses the AppBundle EM. The in-place editor should use the same EM that is used for displaying the datatable?

This is how the datatable service looks like.
`     app.datatables.blacklist:
         class: LogBundle\Datatables\BlacklistDatatable
         arguments: ['@security.authorization_checker', '@security.token_storage', '@translator.default', '@router', '@doctrine.orm.log_entity_manager', '@twig']
         tags:
            - { name: sg.datatable.view }`

Do you have an example? I look through the dev-master readme but couldn't find that editable option.

**Comment by stwe** [comment]
see: https://github.com/stwe/DatatablesBundle/blob/master/Controller/DatatableController.php

This is the default Editable-Action. Write your own action as above and use your EM. 

``` php
            ->add('createdBy.username', Column::class, array(
                'title' => 'Created by',
                'searchable' => true,
                'orderable' => true,
                'filter' => array(SelectFilter::class, array(
                    'select_options' => array('' => 'All') + $this->getOptionsArrayFromEntities($users, 'username', 'username'),
                    'search_type' => 'eq',
                    'cancel_button' => true
                )),
                'editable' => array(TextEditable::class, array(
                    'pk' => 'id',
                    'placeholder' => 'Edit value',
                    'empty_text' => 'Empty Text',
                    'url' => 'your_route' // <<------- your new Action-Route
                )),
            ))
```
