### ISSUE TITLE
Action button route parameters (route parameters as string)

### ISSUE THREAD

**Issue by Seb33300** [stwe/DatatablesBundle#545]
Hi,

I have an issue with action button route parameters.

I have a route which look like `/app/object/{type}`.
```
'route'            => 'route_name',
'route_parameters' => ['type' => 'mytype'],
```
Which should result in `/app/object/mytype`.

But in my datatable, I have a column field named `mytype` so the `'mytype'` string is catched as if it is a field of the datatable and replaced by the value of the field `mytype`.

Any way to force route parameters as string?

**Comment by stwe** [comment]
Ok, but that should actually work with dev-master ????

**Comment by Seb33300** [comment]
I don't think you understand what I mean.

I do NOT want parameter string value to be replaced.
The circonstance is that I have a field which have the exact same name as the parameter string value I want to pass.

So it is catch and converted with the field value.

**Comment by Seb33300** [comment]
If we take the documentation exemple:
https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/columns.md#the-datatable-class

With the route `/my/custom/route/{id}`
I want to insert in the `id` parameter the value `'id'` to generate the url `/my/custom/route/id`
But `id` is considered as a field and route generated id `/my/custom/route/1`

But I really want `'id'` in my URL, not `'1'`.
