### ISSUE TITLE
default value for filtering in select

### ISSUE THREAD

**Issue by versh23** [stwe/DatatablesBundle#553]
https://github.com/stwe/DatatablesBundle/blob/v0.13/Resources/doc/filter.md#select-filter

i have an array of values for select, but how i can a set default value for filtering?

i think its column search_column. But after rendering table, there are not readalbe value

**Comment by versh23** [comment]
https://github.com/stwe/DatatablesBundle/blob/master/Resources/views/filter/select.html.twig#L40

i see in v1.0 its solved..

**Comment by versh23** [comment]
what about something like that in v0.13 ? 
https://gist.github.com/versh23/0da994673a2bd83fd4b3a47de31cbc84#file-filter_select-html-twig-L20

**Comment by stwe** [comment]
If there are no problems in dev-master, I close this issue.
