### ISSUE TITLE
Idea - different approach to query callbacks

### ISSUE THREAD

**Issue by mssimi** [stwe/DatatablesBundle#555]
Hey, I feel like controller is not good place for adding conditions to query and I think it should be somehow defined in datatable class itself in similar way column builder is.

This is just example how it could look. I hope we can do some brainstorming here to make it flexible enought.

```
class PostDatatable extends BaseAbstractDatatableView
{
    public function buildDatatable(array $options = array())
    {
         //....
        $this->whereBuilder
            ->add('post.status', array(
                'where_type' => 'like',
                'parameter' => $options['post.status']
            ))
        ;
    }
}
```

What do u think?

**Comment by stwe** [comment]
So I find the controller is the right place for it. The Datatable-Class is only a frame for different use cases. The Datatable-Class can be used in various actions. The query can be customized in the various controller actions. For example, an admin index action and a user index action can use the same datatable class.
