### ISSUE TITLE
could i  use  form with GET method  for filtration 

### ISSUE THREAD

**Issue by abdallahmaali** [stwe/DatatablesBundle#557]
i want to create form to make search with customize parameter  ,
because i have a lot of columns and i don't want to show all of them in the table .

so the normal  search   it's will not achieve what i need exactly  without   use get method in url   and create customize query  by pass the parameter from url to query

**Comment by stwe** [comment]
In Germany we have something that is called punctuation marks (Satzzeichen).

**Comment by stwe** [comment]
http://stackoverflow.com/help/how-to-ask

**Comment by abdallahmaali** [comment]
@stwe how i can contact with you ?

**Comment by stwe** [comment]
Open an Issue and observe the rules: http://stackoverflow.com/help/how-to-ask
