### ISSUE TITLE
Unable to set features - extensions export option (pdf, csv, excel) with current dev version of SG Datatable Bundle and Symfony 3.2

### ISSUE THREAD

**Issue by nikunjkabariya** [stwe/DatatablesBundle#558]
Hello,
I have integrated SG Datatable current dev version with symfony 3.2.3. But i am not able to set features option in extension (useful features- export to pdf, csv, excel).
Let me know how to fix it OR when shall this bundle be updated with EXPORT features?
Its urgent.
Because v0.13 version not working perfectly with symfony 3.2.
Guide me with steps or instructions.

Thanks

**Comment by Seb33300** [comment]
Not able at the moment:
https://github.com/stwe/DatatablesBundle/blob/master/FEATURES.md

**Comment by stwe** [comment]
Callbacks && Events comes asap.
