### ISSUE TITLE
How to set multiple checkbox option for bulk action such as Delete and Approve?

### ISSUE THREAD

**Issue by nikunjkabariya** [stwe/DatatablesBundle#559]
Hello,
I would like to set multiple checkbox option for the bulk actions such as Delete and Approve actions. For this i need to add checkbox for each row and one dropdown (having actions Delete, Approve) above list, near Per Page Record dropdown.
Kindly help me.
I am using symfony 3.2 with current dev version of SG Datatable bundle.

Thanks

**Comment by Seb33300** [comment]
Hello,

Have you tried the multiselect column?
https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/columns.md#6-multiselect-column
