### ISSUE TITLE
Add a column with index or counter

### ISSUE THREAD

**Issue by bettinz** [stwe/DatatablesBundle#562]
Hello, I'm trying to add a column with the number of the row, like explained here:
https://datatables.net/examples/api/counter_columns.html
https://datatables.net/forums/discussion/32442/index-column-with-ajax

I can't find any solution, can you help me?

Thanks

**Comment by Seb33300** [comment]
See https://github.com/stwe/DatatablesBundle/issues/516

**Comment by bettinz** [comment]
Hello, maybe I'm making something wrong, because I can't do this with v. 0.13

file WorkResultDatatable

```php
        $this->callbacks->set(array(
            'row_callback' => array(
                'template' => ':workEvent:init.js.twig',
                'vars' => array('id' => '2')
            )        ));
```
file init.js.twig

```js
function rowCallback(nRow, aData, index) {
    var id = "{{ id }}";
    var $nRow = $(nRow);

    if (aData.id == id) {
        $nRow.css({"background-color": "red"});
    }

    return nRow;
}
```

nothing appear 😞

**Comment by bettinz** [comment]
Hello @Seb33300 , thank you for the reply. I've read about this code everywhere:

```js
ObjDt.on( 'order.dt search.dt', function () {
    ObjDt.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
       cell.innerHTML = i+1;
    });
}).draw();
```

```js
t.on( 'order.dt search.dt', function () {
    t.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
        cell.innerHTML = i+1;
    } );
} ).draw();
```
And in every code they access to the Datatable object (ObjDt and t); what I can't do, so far, is to access to the datatable. I'm using 0.13 so callbacks works, my question is how to use this code with the oTable object (I this it's oTable, right?)

**Comment by stwe** [comment]
@bettinz : Please discuss in #516 .
