### ISSUE TITLE
Initial ordering not working with orderable=false

### ISSUE THREAD

**Issue by bettinz** [stwe/DatatablesBundle#564]
Hello, I've a table and I want an initial order and disable the ability for user to order the column.

```php
$this->options->set(array(
            'order' => array(
                array(
                    8, 'desc'
                )
```

and in the column:
```php
->add('total', 'column', array(
                'title' => 'Tot',
                'type'=>'num',
                'orderable'=>false
            ))
```
It simple ignore the order. If i put "orderable" on true it became ordered as expected.
I've seen on datatable forum that it's not the original design: they allow a developer to order columns via "order" option and then disable the feature for end user.
Have anyone found this issue?

**Comment by stwe** [comment]
won't fix in 0.13

**Comment by bettinz** [comment]
Do you plan to fix in 1.x? :-)

**Comment by stwe** [comment]
I'm looking at it

**Comment by stwe** [comment]
@bettinz The behavior still exists in v1.0. Is this really an issue? Do you have a link to the post in the forum?

**Comment by bettinz** [comment]
I'm still looking because I've searched for the issue some time ago.
So far I've found this:
https://datatables.net/forums/discussion/21164/disable-sorting-of-one-column

> The columns.orderable parameter is used to signify that the user should not be able to order the column. However, you as the developer case still do so using the order() method - and as a result of this the order option (the default order) is still being applied. If you don't want an initial sort, set order to be an empty array.
https://datatables.net/forums/discussion/comment/61218/#Comment_61218

**Comment by Oliver-Gibson** [comment]
Hi,

Your use case isn't clear. Do you want to totally disable ordering or only disable it on one column ?

If it is the first case then you can do it this by adding an orderBy to the query see https://github.com/stwe/DatatablesBundle/blob/v0.13/Resources/doc/query.md#2-get-query

**Comment by stwe** [comment]
I think he meant that:

``` php
        $this->options->set(array(
            'order' => array(array(0, 'desc')),
        ));
```

``` php
            ->add('id', Column::class, array(
                'title' => 'Id',
                'orderable' => false,
                'filter' => array(TextFilter::class,
                    array(
                        'cancel_button' => true,
                        'search_type' => 'eq',
                    ),
                ),
            ))
```

Then the ID column is incorrectly sorted and I must now play Sherlock Holmes

**Comment by bettinz** [comment]
Hello @Oliver-Gibson it's explained by stwe in the next post: if you have 3 columns, like A, B, C and I want to order column A (desc) and B (asc) as initial order.
But I don't want to provide user the feature to manually order a column; so I put that columns "orderable=>false". But with this setting the initial order doesn't work.

**Comment by Oliver-Gibson** [comment]
this means that the user is stuck with the initial ordering. In wich case my first response is a solution to your problem (not saying it is the best tho, but it's clean).

**Comment by bettinz** [comment]
Yes, this is a fix. My issue was because the behavior is different from standard datatable as "orderable" doesn't change the initial ordering directive  😃
