### ISSUE TITLE
Render action button instead of action link

### ISSUE THREAD

**Issue by na-ji** [stwe/DatatablesBundle#565]
Hi !

I was wondering if it was possible to add this feature: rendering action as button instead of link. 
With action button, the route parameter could be not mandatory. But if there is a route parameter, adding it with the attribute "data-href". 
The point of this feature would be to add an action button with ajax or javascript action. Currently on my project, I already catch the click on some action in javascript, but there are a few cases I can not catch: when doing a middle click or when doing a right click -> open in new tab.
This new feature could be implemented with a simple boolean option to add on the action.

What do you think about this feature ?

**Comment by Seb33300** [comment]
I don't understand why you can't catch them?

Here is an example:
http://jsfiddle.net/nogoodatcoding/QNUU2/2/

**Comment by na-ji** [comment]
Thanks for the fiddle, but even if it does catch the middle click, it does not prevent it. And this without talking about the right click -> open in new tab that is not even caught. I am on chrome, so like 40% of my users, so I do not want a hack that is not cross-browser.
So right now in my opinion, the cleanest solution is to not use a link and instead a button.

**Comment by Seb33300** [comment]
Didn't tested on Google Chrome.

The `route` option is not an optional so you can't leave it empty.
If you want to add a data attribute to your link, you can use the `attributes` option.

But in you case, you could use:
```javascript
$('a').mousedown(function(e) {
    $(this)
        .data('href', $(this).attr('href'))
        .removeAttr('href')
    ;
});
```

**Comment by na-ji** [comment]
Thank you @Seb33300 for your answer, but that is already what I do right now. For now I have a callback when the action menu open that remove the link and replace them with button. 

Why I suggested this feature if I already had a solution ? Because it will help other people to create AJAX action. A lot of people already asked for that (https://github.com/stwe/DatatablesBundle/issues/529, https://github.com/stwe/DatatablesBundle/issues/500 and https://github.com/stwe/DatatablesBundle/issues/451 for instance) but we do not need the datatable to handle the whole AJAX action. Just the possibility to have a button instead of a link or even making the route parameter optional will greatly help for that.

**Comment by stwe** [comment]
@na-ji Ok, I will also allow a button.

**Comment by stwe** [comment]
**I will do that:**
- `route` is optional
- If `route === null`, then `route = javascript: void (0)`
- new `button` bool option
- If `button === true`, then create a button tag without route informations
- new `name` option
- If `route === null`, name must be set (The action class needs an ID for each action)

**Comment by Seb33300** [comment]
I don't understand why buttons will help people to create ajax actions?

Ajax requests do not depend if they are called by a link or a button.
I am using ajax actions for a while with links without any issue.

We should just provide the `route` option as optional and remove the `href` attribute if the `route` option is null. This will have the same result as a button.


What we could be very interesting is to provide a way to use actions as form.
So we could easily call action route as GET or POST and add extra form parameters.

**Comment by stwe** [comment]
@Seb33300 the route is optional and `href="javascript:void(0);"` is used if route is null. The button is (unfortunately) often desired and is only an additional option.
