### ISSUE TITLE
Text helper renderer

### ISSUE THREAD

**Issue by metalmini** [stwe/DatatablesBundle#566]
Hi,

I am trying to get the text helper function to run with this bundle, but i cant get it to work. After digging in the code i am afraid that this isn't possible. But correct me if i'm wrong. This is a very useful feature, which will be explained on the docs below.

Anyway, from the datatables docs:

>Text helper
>
>The text helper will ensure that any potentially dangerous HTML in the source data will not be executed by escaping the HTML entities. This can be useful if the data being loaded may come from a potentially untrusted data source and can help mitigate [XSS](https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)) attacks.
>
>The text helper doesn't take any parameters making its use simply:

```javascript
{
    data: 'product',
    render: $.fn.dataTable.render.text()
}
```

Currently the render tag does:

```
{% if column.render %}
      "render": function(data, type, row, meta) {
            return {{ column.render }}(data, type, row, meta);
     },
{% endif %}
```
So i think the text helper can never work as the example of the datatables docs.

For security purposes this should be a great add on.

**Comment by stwe** [comment]
column has no longer the render option.
