### ISSUE TITLE
add multiple  filtration  for  columns  from outside table 

### ISSUE THREAD

**Issue by abdallahmaali** [stwe/DatatablesBundle#568]
i'm trying to add extra filters from outside the table  , i used  line formatter to merger multiple column  in one column , but i need  to add extra filters for any column i want  even if its invisible 

the filters inputs should be outside the table maybe above it 

any one could help me please ?

**Comment by abdallahmaali** [comment]
like this example 
http://yadcf-showcase.appspot.com/dom_source_externally_triggered.html

**Comment by stwe** [comment]
This is a nice feature. But at the moment this is not planned. Maybe in the future. Sorry.

**Comment by abdallahmaali** [comment]
ok thank you could give any idea or workaround to do some thing like this ?
