### ISSUE TITLE
`Order` entity is not compatible with DatatablesBundle - Error: Expected Literal, got 'order'

### ISSUE THREAD

**Issue by patrickbussmann** [stwe/DatatablesBundle#570]
Hey guys,

I have a entity which is called `Order` (OrderBundle\Entity\Order).
And everytime I want to open the datatable result action I get this error.

    [Syntax Error] line 0, col 22: Error: Expected Literal, got 'order'
    SELECT count(distinct order.id) FROM OrderBundle\Entity\Order order

This is my test script with few tries but nothing works.
Setting the querybuilder manually does not work because then I have 2 selects. My one with `o` and the Datatables one with `order` as alias.

	/** @var \OrderBundle\Datatables\OrderDatatable $datatable */
	$datatable = $this->get('datatable.order');
	$datatable->buildDatatable();

	/** @var \Sg\DatatablesBundle\Datatable\Data\DatatableDataManager $datatableDataManager */
	$datatableDataManager = $this->get('sg_datatables.query');
	$query = $datatableDataManager->getQueryFrom($datatable);
	//	$query->setQuery($this->getDoctrine()->getManager()->createQueryBuilder()
	//		->select('o')
	//		->add('from', 'OrderBundle:Order o')
	//	);
	//	$query->setQuery($this->getDoctrine()->getManager()->getRepository('OrderBundle:Order')->createQueryBuilder('o'));
	//	$query->buildQuery();
	//
	//	echo $query->getQuery()->getDQL();die();

	return $query->getResponse();

Maybe someone has an idea how to get this to work :+1: 

If the table name would be public it would work :-)

`\Sg\DatatablesBundle\Datatable\Data\DatatableQuery::__construct`
![2017-03-07 01_39_3endor_sg_datatablesbundle_sg_da](https://cloud.githubusercontent.com/assets/15617021/23636678/186868fe-02d7-11e7-9d2e-7769c805ad7a.png)

One line... But can't manipulate the file with normal methods :-1:

**Comment by SpiGAndromeda** [comment]
I got the same problem. Is this issue connected to the current master branch or to the 0.13 version?
The order table is named 'order_table' in the database because 'order' is a reserved keyword ... which causes the problem I think.
I access the order class via association mapping. 

I'll try to figure out how the bundle handles association mapping with table names.

**Comment by SpiGAndromeda** [comment]
I created a little workaround but this is quick and dirty (from `Sg/DatatablesBundle/Datatable/Data/DatatableQuery.php`) :

````
/**
 * Setup column arrays.
 *
 * @author stwe <https://github.com/stwe>
 * @author Gaultier Boniface <https://github.com/wysow>
 * @author greg-avanim <https://github.com/greg-avanim>
 *
 * @return $this
 */
private function setupColumnArrays()
{
	/* Example:
		  SELECT
			  partial fos_user.{id},
			  partial posts_comments.{title,id},
			  partial posts.{id,title}
		  FROM
			  AppBundle\Entity\User fos_user
		  LEFT JOIN
			  fos_user.posts posts
		  LEFT JOIN
			  posts.comments posts_comments
		  ORDER BY
			  posts_comments.title asc
	 */

	$this->selectColumns[$this->tableName][] = $this->rootEntityIdentifier;

	foreach ($this->columns as $key => $column) {
		$data = $column->getDql();

		$currentPart = $this->tableName;
		$currentAlias = $currentPart;

		$metadata = $this->metadata;

		if (true === $this->isSelectColumn($data)) {
			$parts = explode('\\\\.', $data);

			if (count($parts) > 1) {
				// If it's an embedded class, we can query without JOIN
				if (array_key_exists($parts[0], $metadata->embeddedClasses)) {
					$column = str_replace('\\', '', $data);
					$this->selectColumns[$currentAlias][] = $column;
					$this->addSearchOrderColumn($key, $currentAlias, $column);
					continue;
				}
			} else {
				$parts = explode('.', $data);

				$reserved = ['order'];

				while (count($parts) > 1) {
					$previousPart = $currentPart;
					$previousAlias = $currentAlias;

					$currentPart = array_shift($parts);
					//$currentAlias = ($previousPart == $this->tableName ? '' : $previousPart.'_') . $currentPart; // This condition keeps stable queries callbacks
					$currentAlias = ($previousPart == $this->tableName ? '' : $previousPart.'_') . ($currentPart == in_array($currentPart,$reserved) ? $currentPart[0] : $currentPart);

					if (!array_key_exists($previousAlias.'.'.$currentPart, $this->joins)) {
						$this->joins[$previousAlias.'.'.$currentPart] = $currentAlias;
					}

					$metadata = $this->setIdentifierFromAssociation($currentAlias, $currentPart, $metadata);
				}

				$this->selectColumns[$currentAlias][] = $this->getIdentifier($metadata);
				$this->selectColumns[$currentAlias][] = $parts[0];
				$this->addSearchOrderColumn($key, $currentAlias, $parts[0]);
			}
		} else {
			$this->orderColumns[] = null;
			$this->searchColumns[] = null;
		}
	}

	return $this;
}
````
Here the problem was the left join. The bundle simply takes the rigth part of the assiciation mapping and uses it as the name for the left join. 
The workaround checks if the name is part of a reserved list and takes only the first letter of the name if so. I know thats bad style.

A good solution and good style would be escaping the name of the join with `'`. I also tried this and I will continue but thats a little more coding because of the while loop, which takes the `'` for the next left side of association.

**Comment by SpiGAndromeda** [comment]
I also managed the other problem ...
The 'Order' keyword didn't matter. Just for information: I used the callback functionality to set some where clauses in the controller. But I just figured out that there is a huge difference between `setParameter` und `setParameters`. The first adds a parameter ... the latter removes all previous and adds the new one.

**Comment by Oliver-Gibson** [comment]
Here we need to guarantee that aliases don't match DQL keywords. The first idea that comes to mind is to "decorate" aliases ( add a prefix or suffix for exemple). However doing this will break nearly (if not all) code that already uses query callbacks. To avoid this only aliases that match DQL keywords should be "decorated".

**Comment by ychakroun** [comment]
The only solution i found is to change the Order class name to "Orders" or others..

**Comment by SpiGAndromeda** [comment]
Like I did, checking if the alias is not an DQL keyword would solve the problem. But php has no built in function to check if a word is an SQL Keyword ... as far as I know.

**Comment by stwe** [comment]
SQL keywords should not be used as a table name. Absolute bad practice. Case closed.

**Comment by stephanvierkant** [comment]
Same problem here. I'm using FOSUserBundle and it has a Group class: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Model/Group.php

**Comment by stephanvierkant** [comment]
Solved this by created a 'proxy' class, which extends the original class:

```
/**
 * @ORM\Entity
 * @ORM\Table(name="fos_group")
 */
class UserGroup extends Group
{

}
```
GroupDatatable.php: 
```
    /**
     * {@inheritdoc}
     */
    public function getEntity()
    {
        return UserGroup::class;
    }
```

**Comment by stephanvierkant** [comment]
Solved this by created a 'proxy' class, which extends the original class:

```
/**
 * @ORM\Entity
 * @ORM\Table(name="fos_group")
 */
class UserGroup extends Group
{

}
```
GroupDatatable.php: 
```
    /**
     * {@inheritdoc}
     */
    public function getEntity()
    {
        return UserGroup::class;
    }
```

**Comment by ripnet** [comment]
What if the table name is not a reserved word, but the class name is?
