### ISSUE TITLE
column with applied to column's th and filter input

### ISSUE THREAD

**Issue by SpiGAndromeda** [stwe/DatatablesBundle#572]
Hi,

I am unsing the 0.13 version of the bundle.

When using the width option on a column with filter the attribute is applied to the `th` (which is correct) AND the filter `input` itself. This is no problem if using absolute values but it is one using relative values like `10%`. Then the filter input width is `1%`. 
I fixed the problem by overriding the filter templates and removing the style attribute. It also doesn't affect absolute widths ... they are still working.
After having a quick look to the code from the master branch the problem should be still persistent (could not check because I am unsing v0.13).

**Comment by cirovargas** [comment]
Same problem here, version 1.0
