### ISSUE TITLE
default values for filter

### ISSUE THREAD

**Issue by SpiGAndromeda** [stwe/DatatablesBundle#573]
Hi,

is there a way in v0.13 to set a default value for a filter? I tried different callbacks. 
In the init_complete callback I could sucessfully set the input value of the daterange filter to the desired value. Then I used the trigger function to fire a keyup(13) but nothing happend. The exact same method was working using it in the console after everything finished rendering.

best regards,
spigandromeda

**Comment by stwe** [comment]
You can try to write your own filte or you can also the try dev-master version of this bundle.
