### ISSUE TITLE
Question: Can you use raw SQL instead of doctrine ORM?

### ISSUE THREAD

**Issue by buphmin** [stwe/DatatablesBundle#575]
I am working on adding Symfony to a legacy application and was interested in this bundle since we use datatables a lot. I can't find any good examples of using this bundle without entities/doctrine and tried searching the issues but wasn't able to find quite what I'm looking for.

We have over 1000 tables, many of which are not very doctrine friendly so being able to write our own queries is necessary.

Thanks!

**Comment by stwe** [comment]
Short answer: no. You can create a Fork to make this possible.
Note: Symfony and Doctrine are the best friends. Doctrine is one of the best ORM. no reason why it should not work with your tables.

**Comment by buphmin** [comment]
Thanks for your answer. I appreciate it.
