### ISSUE TITLE
default filter value

### ISSUE THREAD

**Issue by grekpg** [stwe/DatatablesBundle#578]
I cannot find how i can setup default filter value , 
i found 'state_save' => in main options , it works but filter is apply but input is empty so user don't know with filter is now active

**Comment by stwe** [comment]
Try to use the `initial_search` filter option.

https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/filters.md

**Comment by Knallcharge** [comment]
NOTE: initial_search does not work when using state_save = true
