### ISSUE TITLE
pass parameter to Line Formatter

### ISSUE THREAD

**Issue by teos619** [stwe/DatatablesBundle#584]
Grettings i am using the Line Formmater to edit the results on the table

here is my controller, I'm trying to pass the parameter "ID" to the functions getLineFormatter
![dt1](https://cloud.githubusercontent.com/assets/11147596/24365316/c78a6764-12d2-11e7-8c34-48932ca9b40e.png)

then I'm trying to use that parameter to modify the content on a virtual column created below

![dt2](https://cloud.githubusercontent.com/assets/11147596/24365383/fad8950a-12d2-11e7-9e94-a2b454421160.png)

![dt3](https://cloud.githubusercontent.com/assets/11147596/24365400/0b513a4a-12d3-11e7-9e5f-45634cf714bc.png)
 but what i get is an error... 

what i need is pass some parameter to the function getLineFormatter and using for modify the content of a virtual column.

help me please, thank you and sorry for the last post and my bad english

**Comment by teos619** [comment]
HelpMe Please :(

**Comment by teos619** [comment]
Any Idea???

**Comment by Oliver-Gibson** [comment]
Hi,

Can't you pass the id via the buildDatatable function, make it a attribute and use it in line formatter ?

**Comment by stwe** [comment]
see also the [DemoBundle](https://github.com/stwe/DtBundleDemo)

https://github.com/stwe/DtBundleDemo/blob/master/src/AppBundle/Datatables/CommentDatatable.php
