### ISSUE TITLE
if i search a chinese character via post method , DatatableQuery break a Doctrine error .

### ISSUE THREAD

**Issue by englenshan** [stwe/DatatablesBundle#586]
I know that ,this is caused by the URLDecode, but I do not know how to solve, in the case of not changing the component source code.
eg. search words : '官方'
An exception occurred while executing 'SELECT DISTINCT a0_.id AS id_0 FROM app_user a0_ WHERE a0_.id LIKE ? OR a0_.type_id LIKE ? OR a0_.nickname LIKE ? OR a0_.phone LIKE ? OR a0_.mail LIKE ? OR a0_.passwd LIKE ? OR a0_.empirical LIKE ? OR a0_.money LIKE ? OR a0_.sex LIKE ? OR a0_.age LIKE ? OR a0_.head_path LIKE ? OR a0_.created LIKE ? LIMIT 50 OFFSET 0' with params ["%\u5b98\u65b9%", "%\u5b98\u65b9%", "%\u5b98\u65b9%", "%\u5b98\u65b9%", "%\u5b98\u65b9%", "%\u5b98\u65b9%", "%\u5b98\u65b9%", "%\u5b98\u65b9%", "%\u5b98\u65b9%", "%\u5b98\u65b9%", "%\u5b98\u65b9%", "%\u5b98\u65b9%"]

**Comment by englenshan** [comment]
Today , that's a surprised, The error disappear himself. Strange!

**Comment by stwe** [comment]
see also #472

**Comment by englenshan** [comment]
@stwe thanks !
