### ISSUE TITLE
Passing static route parameters in an action column

### ISSUE THREAD

**Issue by vctls** [stwe/DatatablesBundle#590]
Hello,
I'm trying to implement custom actions in my datatables, but I have a problem with the route parameters.
The `actions_string.html.twig` template assumes all my `route_parameters` are row attributes:
```twig
if (true == row.sg_datatables_actions[{{ column.index }}]["{{ action.route }}"]) {
    {% for key, value in action.routeParameters %}
        routeParameters["{{ key }}"] = row.{{ value }};
    {% endfor %}

    var route  = Routing.generate("{{ action.route }}", routeParameters);
```
What if I want to pass a parameter that is not an attribute of the row?

**Comment by vctls** [comment]
For now I'll just override the template and set the `row.` prefix explicitly in my Datatable class when I need it.

**Comment by Oliver-Gibson** [comment]
Hi,

Use line formatter to add the parameter(s) to the rows

**Comment by stwe** [comment]
try dev-master

**Comment by vctls** [comment]
Thanks, @stwe .
I did a short test with dev-master, but I already have multiple custom datatables and it's going to take me some time to adapt them to the new version.
Also I am a bit concerned about using dev-master in a production environment.
In the meantime, I'll try your way, thanks @Oliver-Gibson .
