### ISSUE TITLE
Creating custom column type (simplification/optimization)

### ISSUE THREAD

**Issue by Seb33300** [stwe/DatatablesBundle#591]
Hi,

I am trying to create my custom column.

When I look at currents columns types, I can see multiples methods like `renderCellContent`, `renderSingleField` or `renderToMany` which are very similar.

So maybe they could be factorized in the `AbstractColumn` class to make new custom columns easier to create?

I want to create a column type very close to the default `Column` type but I am not able to extends it to achieve it easily.
I just want to override the `getCellContentTemplate` to render a different template, but this method is never called since `renderSingleField` doesn't call the `renderTemplate` method every times.

**Comment by stwe** [comment]
I'm considering removing the getCellContentTemplate () function from the ColumnInterface.

The common (custom) rendering process of a column currently looks like this:

``` php
    public function renderCellContent(array &$row)
    {
        $this->isToManyAssociation() ? $this->renderToMany($row) : $this->renderSingleField($row);
    }
```

- the function `renderToMany()` calls `renderTemplate()`
- the function `renderSingleField()` calls `renderTemplate()`
- the function `renderTemplate()` calls finally `getCellContentTemplate()`

Suppose you want to create a new Column and this Column extends AbstractColumn. Furthermore, the `renderCellContent` is not required in this case. Then the also non-required method `getCellContentTemplate` should be implemented. That makes no sense. Or I set the function to `null` in AbstractColumn.

The `renderToMany()` and `renderSingleField()` functions are not the same for all columns. All columns need these two functions, except the ActionColumn(s). 

What could I do (first idea): 

- remove getCellContentTemplate() function from the ColumnInterface
- put the common `renderCellContent` including special `renderToMany()`, `renderSingleField()` and  `renderTemplate()` from the ColumnClass  in AbstractColumn as basic column
- `renderToMany()`, `renderSingleField()` to ColumnInterface (return null for the ActionColumn)

**Comment by Seb33300** [comment]
> the function `renderToMany()` calls `renderTemplate()`
> the function `renderSingleField()` calls `renderTemplate()`
> the function `renderTemplate()` calls finally `getCellContentTemplate()`

In the default `Column` class, `renderTemplate()` is never called if `isEditableContentRequired()` is false.
So I am not able to extend the `Column` class and override `getCellContentTemplate()`, because this method is called by `renderTemplate()` which is not called.

---

> The `renderToMany()` and `renderSingleField()` functions are not the same for all columns. All columns need these two functions, except the ActionColumn(s).

They are not the same but they are very close. So maybe they could be factorized in a generic code compatible with all calumns? And overrided if needed.

In the `ActionColumn`, the code to render cols is set in the `renderCellContent()`, but we could move it in the `renderSingleField()` (because ActionColumn is always a single field) and keep `renderCellContent()` unchanged (if `renderCellContent()` is moved in the `AbstractColumn`).

---

> remove getCellContentTemplate() function from the ColumnInterface

I don't understand why you want to remove `getCellContentTemplate()` from the `ColumnInterface`?
How can cells be rendered if they don't have a template?

> put the common renderCellContent including special renderToMany(), renderSingleField() and renderTemplate() from the ColumnClass in AbstractColumn as basic column

👍 


> renderToMany(), renderSingleField() to ColumnInterface

👍 


> (return null for the ActionColumn)

Just rename `renderCellContent()` to `renderSingleField()` in column class.
`renderToMany()` should never be called, or you could just set it as:
```php
public function renderToMany(...)
{
    $this->renderSingleField(...);
}
```

**Comment by stwe** [comment]
> How can cells be rendered if they don't have a template?

Short explanation: This is just a template to change an already existing value in $row (the response). So it is not realy needed. This is also the reason why the template in Column is only needed for the Editable case. Everything else is then displayed as it is in the database.

The function remains in the interface. I will try to make the overwriting easier.

**Comment by stwe** [comment]
This ticket reveals the problems of the bundle: In most cases, querying the data works very well and can be easily configured. It can also be adopted in a new version. The configuration of the representation (Columns) must be rewritten. Here is using inheritance, which is wrong. There are too many columns that differ only marginally and the "diamond problem". More flexible would be a system of components for the column (Composition over inheritance). In my opinion, there is a column which gets additional properties / components for the presentation. For example: Column + BoolFormatterComponent + EditableComponent + WhatEverYouWantComponent. This eliminates all inheritance. Users can easily extend columns by using their own components. I have written this only in C ++ and I have to see how it can be done in PHP7. Specially the memory consumption and the speed are new to me. In C ++, it's fast as hell. We will see. I can not promise anything.

**Comment by stwe** [comment]
see my last comment
