### ISSUE TITLE
Disable keyboard entry in date range filter column

### ISSUE THREAD

**Issue by ljmoleiro** [stwe/DatatablesBundle#592]
I want to disable keyboard entry in date range filter, in order to force the use of bootstrap date range picker only.

**Comment by stwe** [comment]
with dev-master?

**Comment by ljmoleiro** [comment]
i got stable v0.13,  should i update to dev-master in order to do that?

**Comment by stwe** [comment]
no, but I need this information to see, how I can help you

**Comment by Oliver-Gibson** [comment]
In v0.13 override template Resources/view/Filters/filter_daterange.html.twig add attribute readonly to the input. See http://symfony.com/doc/current/templating/overriding.html

**Comment by ljmoleiro** [comment]
it work's fine,thanks a lot
