### ISSUE TITLE
Buttons extension: DateTime columns are not properly exported

### ISSUE THREAD

**Issue by Seb33300** [stwe/DatatablesBundle#594]
When using the Buttons extension to add export buttons, `DateTime` columns are filled with javascript instead of the date value.

**Comment by stwe** [comment]
Buttons options are in progress.......

Happy Easter!

**Comment by lequer** [comment]
Facing the same problem now, I though of using the format.body option of pdf exportOptions in [datatable](https://datatables.net/extensions/buttons/examples/html5/outputFormat-function.html), but json_decode will not allow rendering of JavaScript function. As a suggestion for the buttons options and adding use of JavaScript function, what about using [Zend_Json_Expr](https://framework.zend.com/manual/2.4/en/modules/zend.json.objects.html#json-expressions) with
```php
Zend_Json::encode(
     $options,
     false,
     array('enableJsonExprFinder' => true));
```

and replacing json_decode in the rendering part in the template 'DatatablesBundle/Resources/views/datatable/button.html.twig' with the Zend decode.

**Comment by Seb33300** [comment]
I think dates should be formatted with PHP.

Why is moment.js used?

**Comment by stwe** [comment]
@Seb33300  historical reason: This was my workaround for a disabled Intl extension. But this is no longer necessary today.

**Comment by andrea-daru** [comment]
is there a workaround to display datetime value in the exported data?

**Comment by lequer** [comment]
As a workaround, override the template in SgDatatablesBundle/views/render/datetime.html in your app/Resources.
For my purpose:
```js
{% if data is not same as(null) %}
    {{ data|date(date_format) }}
{% endif %}
```
instead of the javascript was sufficient (not using time_ago).

**Comment by mshd** [comment]
@stwe Is there any option to include this workaround in the repository? Maybe even as an extra column (ie. DateColumn and DateColumnPHP) 

@lequer if not, can you include the code how you were able to override the template of datetime.html (I'm using Symfony 3.4)

**Comment by Seb33300** [comment]
@mshd https://symfony.com/doc/current/bundles/override.html#templates
