### ISSUE TITLE
How to add custom where?

### ISSUE THREAD

**Issue by celvin** [stwe/DatatablesBundle#60]
I have a field in entity to filter the state of the record
$qb->andWhere("tblsolicitudes.state = '1' ");  //It works very well

but now I need to filter using a related entity.
something like this:

$qb->andWhere("tblsolicitudes.cservId.cservPrice  > 0 "); // It doesn't works, how should I do it?

Thanks for you help.

**Comment by celvin** [comment]
it could be nice.

**Comment by stwe** [comment]
There is direct access to the query or callbacks:
        
       // Callback example
        $function = function($qb)
        {
            $qb->andWhere("post.id < 5");
        };

        // Add the callback function as WhereResult
        //$query->addWhereResult($function);

        // Or add the callback function as WhereAll
        //$query->addWhereAll($function);

        // Or get the actual query
        $query->buildQuery();
        $qb = $query->getQuery();
        $qb->andWhere("comments.id  < 5");
        $query->setQuery($qb);
        return $query->getResponse(false);

        //return $query->getResponse();

But there is a big problem with the paging for related entities (with the functions: getCountAllResults and getCountFilteredResults)....

**Comment by fdelapena** [comment]
Thanks stwe!

**Comment by DrDJo** [comment]
Hi, I'm filtering my results with a andWhere Query, the results are OK but not the pagination, which seems to be based on the global query.

Do you have this problem too ?

**Comment by emrevural20** [comment]
i agree @DrDJo . I have same problem. Full record show on  pagination bar.

**Comment by stwe** [comment]
Add the callback function as WhereAll:

    $function = function($qb)
    {
        $qb->andWhere("post.id < 5");
    };

    $query->addWhereAll($function);

    return $query->getResponse();

**Comment by DrDJo** [comment]
Hi stwe,

Thanks for your answer.
How can I give some parameter to the function ?
For example, a $postId param.

**Comment by emrevural20** [comment]
Thank for your answe stwe.
Can i make a individual column in datatable?
i didnt succes render a twig temp.

**Comment by emrevural20** [comment]
i try to open indexresultaction route but error undefined index:search 
what is this?

**Comment by stwe** [comment]
open a new ticket with your problem. I need your datatables class and your
controller actions.
Am 03.07.2015 18:57 schrieb "emrevural20" <notifications@github.com>:

**Comment by emrevural20** [comment]
DATATABLE
<?php

namespace DivanCrmBundle\Datatables;

use DivanCrmBundle\Entity\Musteri;
use Sg\DatatablesBundle\Datatable\View\AbstractDatatableView;
use Sg\DatatablesBundle\Datatable\View\Style;

/**
 * Class MusteriDatatable
 *
 * @package DivanCrmBundle\Datatables
 */
class MusteriDatatable extends AbstractDatatableView
{
    /**
     * {@inheritdoc}
     */
    public function buildDatatableView()
    {
        $this->features->setFeatures(array(
            "auto_width" => true,
            "defer_render" => false,
            "info" => true,
            "jquery_ui" => false,
            "length_change" => true,
            "ordering" => true,
            "paging" => true,
            "processing" => true,
            "scroll_x" => false,
            "scroll_y" => "",
            "searching" => true,
            "server_side" => true,
            "state_save" => false,
            "delay" => 0
        ));

                $this->ajax->setOptions(array(
            "url" => $this->router->generate("musteri_results"),
            "type" => "GET"
        ));
        
        $this->options->setOptions(array(
            "display_start" => 0,
            "dom" => "lfrtip",
            "length_menu" => array(10, 25, 50, 100),
            "order_classes" => true,
            "order" => [[0, "asc"]],
            "order_multi" => true,
            "page_length" => 10,
            "paging_type" => Style::FULL_NUMBERS_PAGINATION,
            "renderer" => "",
            "scroll_collapse" => false,
            "search_delay" => 0,
            "state_duration" => 7200,
            "stripe_classes" => array(),
            "responsive" => false,
            "class" => Style::BASE_STYLE,
            "individual_filtering" => true,
            "individual_filtering_position" => "foot",
            "use_integration_options" => true
        ));

        $this->columnBuilder
                ->add("id", "column", array("title" => "Id",))
                ->add("ad", "column", array("title" => "Ad",))
                ->add("tel", "column", array("title" => "Tel",))
                ->add("durum", "column", array("title" => "Durum",))
                ->add("tc", "column", array("title" => "Tc",))
                ;
    }

    /**
     * {@inheritdoc}
     */
    public function getEntity()
    {
        return "DivanCrmBundle\Entity\Musteri";
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return "musteri_datatable";
    }
}


CONTROLLER

<?php

namespace DivanCrmBundle\Controller;

use DivanCrmBundle\Entity\Musteri;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer;
use Symfony\Component\Serializer\Serializer;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;


class DatatableController extends Controller
{
    /**
     * Server side Post datatable.
     *
     *
     * @Method("GET")
     * @Template("DivanCrmBundle:Sayfalar:datatable.html.twig")
     *
     * @return array
     */
    public function indexAction()
    {
        $datatable = $this->get("DivanCrm.datatable.MusteriDatatable");

        return array(
            "datatable" => $datatable,
        );
    }

    /**
     * Get all Post entities.
     *
     *
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexResultsAction()
    {
        $query = $this->get("sg_datatables.query")->getQueryFrom($this->get("DivanCrm.datatable.MusteriDatatable"));

        // Callback example
        /*$function = function($qb)
        {
            $qb->andWhere("post.visible = true");
        };*/

        // Add as WhereAll callback
        //$query->addWhereAll($function);

        // Or add as WhereResult
        //$query->addWhereResult($function);

        // Or to the query
        //$query->buildQuery();
        //$qb = $query->getQuery();
        //$qb->andWhere("post.content = true");
        //$query->setQuery($qb);
        //return $query->getResponse(false);

        return $query->getResponse();
    }
}

MY ROUTE IN ROUTING.YML

**Comment by emrevural20** [comment]
datatable works now but resutls route gives undefined index:search error. yesterday i saw database data 
in this route as json format.

**Comment by emrevural20** [comment]
DATATABLE

<?php

namespace DivanCrmBundle\Datatables;

use DivanCrmBundle\Entity\Musteri;
use Sg\DatatablesBundle\Datatable\View\AbstractDatatableView;
use Sg\DatatablesBundle\Datatable\View\Style;

/**
 * Class MusteriDatatable
 *
 * @package DivanCrmBundle\Datatables
 */
class MusteriDatatable extends AbstractDatatableView
{
    /**
     * {@inheritdoc}
     */
    public function buildDatatableView()
    {
        $this->features->setFeatures(array(
            "auto_width" => true,
            "defer_render" => false,
            "info" => true,
            "jquery_ui" => false,
            "length_change" => true,
            "ordering" => true,
            "paging" => true,
            "processing" => true,
            "scroll_x" => false,
            "scroll_y" => "",
            "searching" => true,
            "server_side" => true,
            "state_save" => false,
            "delay" => 0
        ));

                $this->ajax->setOptions(array(
            "url" => $this->router->generate("musteri_results"),
            "type" => "GET"
        ));
        
        $this->options->setOptions(array(
            "display_start" => 0,
            "dom" => "lfrtip",
            "length_menu" => array(10, 25, 50, 100),
            "order_classes" => true,
            "order" => [[0, "asc"]],
            "order_multi" => true,
            "page_length" => 10,
            "paging_type" => Style::FULL_NUMBERS_PAGINATION,
            "renderer" => "",
            "scroll_collapse" => false,
            "search_delay" => 0,
            "state_duration" => 7200,
            "stripe_classes" => array(),
            "responsive" => false,
            "class" => Style::BASE_STYLE,
            "individual_filtering" => true,
            "individual_filtering_position" => "foot",
            "use_integration_options" => true
        ));

        $this->columnBuilder

                ->add("ad", "column", array("title" => "Ad",))
                ->add("tel", "column", array("title" => "Tel",))
                ->add("durum", "column", array("title" => "Durum",))
                ->add("tc", "column", array("title" => "Tc",))
                ;
    }

    /**
     * {@inheritdoc}
     */
    public function getEntity()
    {
        return "DivanCrmBundle\Entity\Musteri";
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return "musteri_datatable";
    }
}


CONTROLLER

<?php

namespace DivanCrmBundle\Controller;

use DivanCrmBundle\Entity\Musteri;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer;
use Symfony\Component\Serializer\Serializer;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;


class DatatableController extends Controller
{
    /**
     * Server side Post datatable.
     *
     *
     * @Method("GET")
     * @Template("DivanCrmBundle:Sayfalar:datatable.html.twig")
     *
     * @return array
     */
    public function indexAction()
    {
        $datatable = $this->get("DivanCrm.datatable.MusteriDatatable");

        return array(
            "datatable" => $datatable,
        );
    }

    /**
     * Get all Post entities.
     *
     *
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexResultsAction()
    {
        $query = $this->get("sg_datatables.query")->getQueryFrom($this->get("DivanCrm.datatable.MusteriDatatable"));

        // Callback example
        /*$function = function($qb)
        {
            $qb->andWhere("post.visible = true");
        };*/

        // Add as WhereAll callback
        //$query->addWhereAll($function);

        // Or add as WhereResult
        //$query->addWhereResult($function);

        // Or to the query
        //$query->buildQuery();
        //$qb = $query->getQuery();
        //$qb->andWhere("post.content = true");
        //$query->setQuery($qb);
        //return $query->getResponse(false);

        return $query->getResponse();
    }
}

**Comment by emrevural20** [comment]
i need another help. How can i show my column as a link?
