### ISSUE TITLE
Datetime problem

### ISSUE THREAD

**Issue by JorgeHRJ** [stwe/DatatablesBundle#600]
Hello!
I am having an issue with a datetime column. The problem is the datetime which I want to be shown is being modified. For example, if I want to print out "18/04/2017 13:16", it is actually printed out "18/04/2017 14:16" It is adding one hour. 

Anybody knows how to fix this or why could be this happening?

**Comment by stwe** [comment]
In Germany we call summer time. :) I also think that this is not a bug/issue. Possibly a problem with moment.js?

**Comment by roberto910907** [comment]
@JorgeHRJ I used to override always the use of moment.js in datetime type just like https://github.com/stwe/DatatablesBundle/issues/594#issuecomment-315662453.

Regards.
