### ISSUE TITLE
Exception rendering action columns with Twig ^2.0 : Impossible to invoke a method ("href") on a string variable ("SgDatatablesBundle:render:action.html.twig").

### ISSUE THREAD

**Issue by vctls** [stwe/DatatablesBundle#601]
I'm getting this exception when rendering Action columns:

> Impossible to invoke a method ("href") on a string variable ("SgDatatablesBundle:render:action.html.twig").
500 Internal Server Error - Twig_Error_Runtime 

It is thrown at in the `render:action.html.twig` template at line 67:
```twig
    {% if render_if_actions[actionKey] is same as(true) %}
        {% if action.button is same as(false) %}
            {{ action.startHtml|raw }}
            <a {{ _self.href(action, route_parameters[actionKey]) }} {{ _self.attributes(action) }} {{ _self.confirm_dialog(action) }}>
                {{ _self.link_title(action) }}
            </a> 
```
The problem seems to be that in Twig 2, `_self` returns the name of the template instead of a Template instance.
See for example this issue :
https://github.com/symfony/symfony-demo/issues/322

**Comment by stwe** [comment]
Thank you, good to know. Currently I am still working with twig 1.32

**Comment by Seb33300** [comment]
Same issue for me.

Twig have been updated to 2.0 after I updated my php environment to PHP 7.1

**Comment by vctls** [comment]
Thank you @stwe !
