### ISSUE TITLE
Loading JS in the footer

### ISSUE THREAD

**Issue by amylashley** [stwe/DatatablesBundle#603]
We are just starting to get datatables setup with our new Symfony 3 framework. We typically load our JS assets at the bottom of our code instead of in the head. But it looks like your datatables code injects JS scripts in the page, which means they load before our JS assets. Is there any other way around this besides moving our assets to the head? Thanks so much!

**Comment by Seb33300** [comment]
If you are using `dev-master` branch, you can use separates twig function to render js separately:
```twig
{{ sg_datatables_render_html(datatable) }}

{{ sg_datatables_render_js(datatable) }}
```
So you can add the js at the end of your page.

**Comment by amylashley** [comment]
That you @Seb33300- I'll look into that!
