### ISSUE TITLE
query callback replacement

### ISSUE THREAD

**Issue by SpiGAndromeda** [stwe/DatatablesBundle#604]
Hi,

I tried to migrate the datatables from my project running on version 0.13 to the master branch. I noticed that somehow the query callbacks are missing and I wasn't able to figure out how to replace them for my needs. 
I implemented some changes on v0.13 to serve my needs: to realize a default date range for a datetime field I used the query callback and some request reading. So a where clause with a daterange is applied if no filter is defined in the request handled to the controller method. If the filter is defined the where clause is not applied.

But in general: v1.0 seems to be good work. Well done and THX!

**Comment by stwe** [comment]
You can change the query in the controller:

example:

```
        if ($isAjax) {
            $responseService = $this->get('sg_datatables.response');
            $responseService->setDatatable($datatable);

            $datatableQueryBuilder = $responseService->getDatatableQueryBuilder();
            $datatableQueryBuilder->buildQuery();

            /** @var QueryBuilder $qb */
            $qb = $datatableQueryBuilder->getQb();
            $qb->andWhere('post.id = :id');
            $qb->setParameter('id', 5);

            return $responseService->getResponse(true, true);
        }
```

**Comment by SpiGAndromeda** [comment]
Ahh. Thank you very much!
I will have another trie when the twig 2 issue with href is fixed.

**Comment by foaly-nr1** [comment]
Took me a while to figure this one out too. Would be good to add an example to the docs.
