### ISSUE TITLE
jQuery is required in <head> HTML tag

### ISSUE THREAD

**Issue by koprivajakub** [stwe/DatatablesBundle#609]
I have a large project, where all the scripts are built by node (gulp). I handle the priority of scripts in the gulpfile so I don't have to bother with it in the HTML itself.

`/DatatablesBundle/Resources/views/Datatable/datatable_js.html.twig` is inserted to the middle of the DOM where are not all scripts loaded because many developers (including me) are inserting all the scripts to end of the page just before the closing `</body>` tag so I do not stall the page load for external resources unrelated to the DOM of the page.

**Comment by Seb33300** [comment]
You should render the JS part at the end of the page.

See https://github.com/stwe/DatatablesBundle/issues/603

**Comment by stwe** [comment]
for 0.13 see https://github.com/stwe/DatatablesBundle/blob/v0.13/Twig/DatatableTwigExtension.php

you should use `datatable_rander_html` and `datatable_render_js` instead `datatable_render`

**Comment by koprivajakub** [comment]
I see, sorry, I haven't found it in the docs.
