### ISSUE TITLE
$context['datatable'] = null

### ISSUE THREAD

**Issue by Calex92** [stwe/DatatablesBundle#612]
Hello everyone,

I've got an exception when I try to render my datatable with
`sg_datatables_render(datatable)`
![image](https://cloud.githubusercontent.com/assets/19281292/25489916/96c2ba6c-2b6b-11e7-9a85-b7f3bac7c02a.png)

When I try to go in the cache, check in the file, the value $context['datatable'] is really equals to null.

I've maybe forgot something to add but I've installed the dev-master and the v0.13 and I have the same problem (several times for each of them).
I tried to remove the cache but nothing changed.

I don't know if it's an issue or a problem with my project's config?

**Comment by stwe** [comment]
Show your controller action

**Comment by Calex92** [comment]
It's always when you open an issue that you find the solution!

I did a revert, tried again and it worked ...
Sorry for the inconvenience (but I didn't find why there was an error, sorry)

Just in case, this is my action :
`public function indexAction(Request $request) {
        $isAjax = $request->isXmlHttpRequest();

        $datatable = $this->get('sg_datatables.factory')->create(UserDatatable::class);
        $datatable->buildDatatable();

        if ($isAjax) {
            $responseService = $this->get('sg_datatables.response')->setDatatable($datatable);

            $responseService->getDatatableQueryBuilder()->buildQuery();

            return $responseService->getResponse();
        }
        return $this->render("MGDAdminBundle:User:index.html.twig", array(
            "datatable" => $datatable
        ));
    }`
