### ISSUE TITLE
Individual filter display becomes inconsistent with actual filter value on page refresh with Firefox

### ISSUE THREAD

**Issue by vctls** [stwe/DatatablesBundle#619]
If an individual filter is defined on a column,
when the value is changed and the page refreshed,
Firefox displays the modified value, but the underlying filter is actually using the initial value.

Chrome and IE do not behave this way. They both reset the displayed value.

**Comment by vctls** [comment]
Just tested this with the demo project:
I filtered by comments containing "4", then refreshed the page. The filter still displays "4", but the results aren't actually filtered.
It can be more annoying when an initial value is set:
if you clear the filter then refresh the page, the filter appears empty but the results are actually filtered.
Typing anything in the filter input triggers a refresh of the results.

**Comment by stwe** [comment]
@vctls And with which version ???? I now set a tag for version 1.0 so I do not have to ask such questions anymore.

**Comment by vctls** [comment]
Yes, sorry. I'm using dev-master. Just pulled and tried again, to be sure.

**Comment by vctls** [comment]
Must be something in the way Firefox handles input fields. I'll update the issue if I find anything.

**Comment by stwe** [comment]
@vctls  Give me an update. Is this a problem with this Bundle or Firefox.
