### ISSUE TITLE
Respose Error

### ISSUE THREAD

**Issue by denissiegato** [stwe/DatatablesBundle#623]
Hi..
i have installed the v1 in my project in symfony3 but the plugin not work.
first problem is the ajax request.. it not start automatically:

$this->ajax->set(array(
		    'url' => $this->router->generate('offertCategoryListAjaxCall'),
		    'type' => 'GET',
		    'pipeline' => 0
	    ));

and if i force the request i get en error (second problem):

Notice: Undefined index: draw (500 Internal Server Error)
i think that the problem is in  line 142 of DatatableResponse.php

$outputHeader = array(
            'draw' => (int) $this->requestParams['draw'],
            'recordsFiltered' => count($paginator),
            'recordsTotal' => true === $countAllResults ? (int) $this->datatableQueryBuilder->getCountAllResults() : 0,
        );

**Comment by denissiegato** [comment]
this my code:

services.yml
app.datatable.offertcategory:
        class: BackEndBundle\Datatables\OffertCategoryDatatable
        parent: sg_datatables.datatable.abstract


BackEndBundle\Datatables\OffertCategoryDatatable
<?php

namespace BackEndBundle\Datatables;

use Sg\DatatablesBundle\Datatable\AbstractDatatable;
use Sg\DatatablesBundle\Datatable\Column\ActionColumn;
use Sg\DatatablesBundle\Datatable\Column\BooleanColumn;
use Sg\DatatablesBundle\Datatable\Column\Column;
use Sg\DatatablesBundle\Datatable\Column\ColumnBuilder;
use Sg\DatatablesBundle\Datatable\Column\DateTimeColumn;
use Sg\DatatablesBundle\Datatable\Column\MultiselectColumn;
use Sg\DatatablesBundle\Datatable\Column\VirtualColumn;
use Sg\DatatablesBundle\Datatable\Editable\SelectEditable;
use Sg\DatatablesBundle\Datatable\Editable\TextEditable;
use Sg\DatatablesBundle\Datatable\Filter\DateRangeFilter;
use Sg\DatatablesBundle\Datatable\Filter\NumberFilter;
use Sg\DatatablesBundle\Datatable\Filter\SelectFilter;
use Sg\DatatablesBundle\Datatable\Filter\TextFilter;
use Sg\DatatablesBundle\Datatable\Style;



/**
 * Class OffertCategoryDatatable
 *
 * @package BackEndBundle\Datatables
 */
class OffertCategoryDatatable extends AbstractDatatable
{
    /**
     * {@inheritdoc}
     */
    public function buildDatatable(array $options = array())
    {
	    $this->ajax->set(array(
		    'url' => $this->router->generate('offertCategoryListAjaxCall'),
		    'type' => 'GET',
		    'pipeline' => 0
	    ));

	    $this->language->set(array(
		   // 'cdn_language_by_locale' => true
		    'language_by_locale' => false,
		    'language' => 'it'
	    ));

        $this->options->set(array(
	        'classes' => Style::BOOTSTRAP_3_STYLE,
            'display_start' => 0,
            'defer_loading' => -1,
            'dom' => 'lfrtip',
            'length_menu' => array(10, 25, 50, 100),
            'order_classes' => true,
            'order' => array(array(0, 'desc')),
            'order_multi' => true,
            'page_length' => 10,
            'paging_type' => Style::FULL_NUMBERS_PAGINATION,
            'scroll_collapse' => false,
            'search_delay' => 0,
            'state_duration' => 7200,
            'individual_filtering' => false,
            'individual_filtering_position' => 'head',
            'row_id' => 'id',
            'stripe_classes' => [ 'strip1', 'strip2', 'strip3' ]
        ));

        $this->columnBuilder
            ->add('id', Column::class, array(
                'title' => 'Id',
            ))
            ->add('title', Column::class, array(
                'title' => 'Titolo',
            ))

	        ->add('isActive', BooleanColumn::class, array(
		        'title' => 'Visible',
		        'searchable' => true,
		        'orderable' => true,
		        'true_label' => 'Yes',
		        'false_label' => 'No',
		        'default_content' => 'Default Value',
		        'true_icon' => 'glyphicon glyphicon-ok',
		        'false_icon' => 'glyphicon glyphicon-remove',
		        'filter' => array(SelectFilter::class, array(
			        'classes' => 'test1 test2',
			        'search_type' => 'eq',
			        'multiple' => true,
			        'select_options' => array(
				        '' => 'Any',
				        '1' => 'Yes',
				        '0' => 'No'
			        ),
			        'cancel_button' => true,
		        )),
		        'editable' => array(SelectEditable::class, array(
			        'source' => array(
				        array('value' => 1, 'text' => 'Yes'),
				        array('value' => 0, 'text' => 'No'),
				        array('value' => null, 'text' => 'Null')
			        ),
			        'mode' => 'inline',
			        //'pk' => 'cid',
			        'empty_text' => '',
		        )),
	        ))
            ->add('createdAt', DateTimeColumn::class, array(
                'title' => 'Creazione',
            ))
            ->add(null, ActionColumn::class, array(
                'title' => "Strumenti",
                'actions' => array(

                    array(
                        'route' => "offertCategoryDetail",
                        'route_parameters' => array(
                            'Id' => 'id'
                        ),
                        'label' => $this->translator->trans('datatables.actions.edit'),
                        'icon' => 'glyphicon glyphicon-edit',
                        'attributes' => array(
                            'rel' => 'tooltip',
                            'title' => $this->translator->trans('datatables.actions.edit'),
                            'class' => 'btn btn-primary btn-xs',
                            'role' => 'button'
                        ),
                    ),
	                array(
		                'label' => $this->translator->trans('datatables.actions.delete'),
		                'icon' => 'glyphicon glyphicon-trash',
		                'attributes' => array(
			                'rel' => 'tooltip',
			                'title' => $this->translator->trans('datatables.actions.delete'),
			                'class' => 'btn btn-primary btn-xs btnDelete',
			                'role' => 'button'
		                ),
		                'confirm'=>true,
		                'confirm_message'=>"Eliminare il record slezionato?",
		                'button' => true,
		                'button_value' => 'id',
		                'button_value_prefix' => true
	                )
                )
            ));
    }

    /**
     * {@inheritdoc}
     */
    public function getEntity()
    {
        return 'BackEndBundle\Entity\OffertCategory';
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'offertCategory_datatable';
    }

}


CONTROLLER
/**
	 * @Route("offertCategory", name="offertCategory")
	 */
	public function indexAction()
	{
		$datatable = $this->get('app.datatable.offertcategory');
		$datatable->buildDatatable();
		return $this->render('@BackEnd/Default/offertCategory.html.twig',array('datatable' => $datatable));
	}

	/**
	 * @Route("offertCategory/ajaxCall" , name="offertCategoryListAjaxCall", options={"expose"=true})
	 * @Method({"GET", "POST"})
	 */
	public function offertCategoryAjaxCallAction(Request $request)
	{
		$datatable = $this->get('app.datatable.offertcategory');
		$datatable->buildDatatable();

		$responseService = $this->get('sg_datatables.response');
		$responseService->setDatatable($datatable);

		$datatableQueryBuilder = $responseService->getDatatableQueryBuilder();
		$datatableQueryBuilder->buildQuery();

		//dump($datatableQueryBuilder->getQb()->getDQL()); die();

		return $responseService->getResponse();

	}

**Comment by stwe** [comment]
see: https://github.com/stwe/DtBundleDemo10

you need one action only. see the docs and the example in my demo bundle:

the table:

https://github.com/stwe/DtBundleDemo10/blob/master/src/AppBundle/Datatables/PostDatatable.php

the action:

https://github.com/stwe/DtBundleDemo10/blob/master/src/AppBundle/Controller/PostController.php

```
    /**
     * Lists all post entities.
     *
     * @param Request $request
     *
     * @Route("/", name="post_index")
     * @Method("GET")
     *
     * @return Response
     */
    public function indexAction(Request $request)
    {
        $isAjax = $request->isXmlHttpRequest();
        /** @var DatatableInterface $datatable */
        $datatable = $this->get('sg_datatables.factory')->create(PostDatatable::class);
        $datatable->buildDatatable();
        if ($isAjax) {
            $responseService = $this->get('sg_datatables.response');
            $responseService->setDatatable($datatable);
            $datatableQueryBuilder = $responseService->getDatatableQueryBuilder();
            $datatableQueryBuilder->buildQuery();
            //dump($datatableQueryBuilder->getQb()->getDQL()); die();
            return $responseService->getResponse();
        }
        return $this->render('post/index.html.twig', array(
            'datatable' => $datatable,
        ));
    }
```

**Comment by alister** [comment]
I've got the same issue with `Undefined index: draw`.  How would I arrange it so that the initial database build and display is in one action, and the Ajax fetch, is via another route/action?
