### ISSUE TITLE
Hard dependency with Symfony 3.3 Translator Service

### ISSUE THREAD

**Issue by ronisaha** [stwe/DatatablesBundle#627]
As of SF 3.3 [The translator service is not loaded if user disable translator in config](https://github.com/symfony/symfony/pull/20928). Then the DatatablesBundle Throws error 

> The service * has a dependency on a non-existent service "translator.default"

Its common use case when user doesn't want multilingual support for their application.

Can we remove the hard dependency  of translator service from this bundle?

**Comment by stwe** [comment]
I hope these are "fake news". A web application that does not support multiple languages is the biggest bullshit ever. This is my personal opinion. Never would I make the Translator optional. I do not know why this is supported. Consider the following case: Today you write an application, which is only in "German". And what is in one or two years? Then you may have a lot of success with the application. Then you want to add "English" or "Dutch". But it does not work. What shoud that? 

But...I will look at it and find a solution.

**Comment by ronisaha** [comment]
> A web application that does not support multiple languages is the biggest bullshit ever.

That's not always true. It't not about removing the multilingual support from the library. It's about to respect the user choice. While the framework itself allowing the multilingual support optional. For this reason, when a user disable the translator from framework, the user can't use this library any more!

Thanks for considering this issue!

**Comment by stwe** [comment]
I have just installed Symfony 3.3.2 and the bundle works as expected.

I have used the command:

`symfony new my_project`

**Comment by ronisaha** [comment]
@stwe : to reproduce you have to update your config with

```yml
framework:
    translator: false
```

**Comment by stwe** [comment]
However, most developers use the Translator. Normally removal would not be a problem. But: With the current download numbers, however, a lot of developers would have to change the service configuration. These would kill me.

**Comment by ronisaha** [comment]
I don't understand why a lot of developer would have to change the service configuration(?).  Who willing to use the multilingual support there should not be any changed for them, right? 

If we change the dependency injection with a `translator.wrapper` instead of `translator.default`. the `translator.wrapper` would be the proxy of translator service and if the translator service is disable then it will return the original text.
Then we need to change the static text to its original English value and add them to the configuration so user can override the text using config. This way by default English language user with translator disabled can use without zero extra configuration change if the defaults text suits them.

If i get some time i'll try to implement it this way.

**Comment by Fordiag** [comment]
Question which I don't have the answer regarding this issue.
Why using @translator.default instead of just @translator in service.yml? 
Is there a difference?

By the way works just fine with @translator, symfony 3.3.15 and translator disabled in config.
Not working before this change.
Our translator is disabled for tests environment only...

**Comment by Seb33300** [comment]
I just push the fix on `dev-master` branch
