### ISSUE TITLE
Hide ajax request popup

### ISSUE THREAD

**Issue by Samgo4all** [stwe/DatatablesBundle#628]
Hello, I am trying to use your bundle which looks great but I have a question.

I would like to hide the ajax request popup. 

<img width="663" alt="screen shot 2017-06-08 at 10 20 22" src="https://user-images.githubusercontent.com/24762565/26918944-334b6e18-4c34-11e7-8451-d3767a1e3326.png">

and this one:

<img width="623" alt="screen shot 2017-06-08 at 10 21 50" src="https://user-images.githubusercontent.com/24762565/26918971-52a2e714-4c34-11e7-9cd1-4230af539c83.png">

the controller is the same that your demo bundle:

`
  public function indexAction(Request $request)
    {
        $isAjax = $request->isXmlHttpRequest();

        /** @var DatatableInterface $datatable */
        $datatable = $this->get('sg_datatables.factory')->create(PostDatatable::class);
        $datatable->buildDatatable();

        if ($isAjax) {
            $responseService = $this->get('sg_datatables.response');
            $responseService->setDatatable($datatable);

            $datatableQueryBuilder = $responseService->getDatatableQueryBuilder();
            $datatableQueryBuilder->buildQuery();

            //dump($datatableQueryBuilder->getQb()->getDQL()); die();

            return $responseService->getResponse();
        }

        return $this->render('post/index.html.twig', array(
            'datatable' => $datatable,
        ));
    }
`

Thanks for your help!
Samuel Marnac

**Comment by DarekTw** [comment]
Hi Samgo4all

Which version do you use? dev-master or 1.0 or you have instaled demo version? :)

**Comment by Samgo4all** [comment]
Hi Darek !

You are totally right.

Thank you
