### ISSUE TITLE
Unable to export all rows

### ISSUE THREAD

**Issue by andrea-daru** [stwe/DatatablesBundle#632]
It seems to be impossible to export (excel/csv) all row of a datatable.
It export only the visible row.
The only way seems to be to set the length_menu to -1 (all) and then launch export.
Anyone can help me? thx

**Comment by stwe** [comment]
Old theme. And what makes this feature when the database holds more then 1 million entries?

**Comment by andrea-daru** [comment]
Thanks for your reply!
