### ISSUE TITLE
Get the EntityManagerInterface in datatables

### ISSUE THREAD

**Issue by Samgo4all** [stwe/DatatablesBundle#633]
Hello, I would like to get the entity manager interface in my class but i dont know how, there is always an issue i tried this i get an error 

`public function buildDatatable(array $options = array(), EntityManagerInterface $em)
    {
        $this->ajax->set(array(
        ));

        $this->features->set(array(
            'info' => false,
            'paging' => true,
            'scroll_y' => '200',
        ));

        $this->options->set(array(
            'classes' => Style::BOOTSTRAP_3_STYLE,
            'stripe_classes' => [ 'strip1', 'strip2', 'strip3' ],
            'individual_filtering' => true,
            'individual_filtering_position' => 'head',
            'order_cells_top' => true,

        ));

        $em->getDoctrine()->getManager();

        $note_id = $em->getRepository('NoteBundle:Note_id')->findAll();
        $countnote_id = count($note_id);
        for ($i=0; $i < $countnote_id ; $i++) { 

        $note = $note_id[$i]->getId();
        $notesbyid = $em->getRepository('NoteBundle:Note')->findByNoteId($note);
 
        $this->columnBuilder
             ->add('note', Column::class, array(
                'title' => 'Note'.$i+1,
                'searchable' => true,
                'data' => $notesbyid,
                'orderable' => false,
                'editable' => array(TextEditable::class, array(
                     //'pk' => 'cid',
                     'placeholder' => 'Edit value',
                     'empty_text' => 'Empty Text',
                     'mode'       => 'inline',
                     'clear'      => false
                ))                
            ))
        ;
        }
    }`

> Compile Error: Declaration of NoteBundle\Datatables\NoteDatatable::buildDatatable() must be compatible with Sg\DatatablesBundle\Datatable\DatatableInterface::buildDatatable(array $options = Array)

Thank you for the help :)

**Comment by stwe** [comment]
it is already injected. so simply use 

```
$this->em->
```
