### ISSUE TITLE
add a condition on a column

### ISSUE THREAD

**Issue by Samgo4all** [stwe/DatatablesBundle#634]
Hello, I have this table and I would like to add the following condition to my NoteDatatable:

       . only add in the column the notes which have a note_id_id equals to 4 for exemple.

<img width="1001" alt="screen shot 2017-06-15 at 20 47 16" src="https://user-images.githubusercontent.com/24762565/27196735-02309c9e-520c-11e7-891c-766caf335555.png">

I tried this with the 'data' option but i got an error, only string is available.

`

    $note_id = $this->em->getRepository('NoteBundle:Note_id')->findAll();
    $countnote_id = count($note_id);
    
    for ($i=0; $i < $countnote_id ; $i++) { 

    $note = $note_id[$i]->getId();
    $notesbyid = $this->em->getRepository('NoteBundle:Note')->findByNoteId($note);

        $this->columnBuilder
             ->add('note', Column::class, array(
                'title' => 'Note '.$i,
                'data' => $notesbyid,
                'searchable' => true,
                'orderable' => false,             
            ))
        ;

        }

`

Thank you so much for your help.

**Comment by Samgo4all** [comment]
up pls

**Comment by stwe** [comment]
see #604
