### ISSUE TITLE
Deal with multiple EntityManager connections now ?

### ISSUE THREAD

**Issue by MlleDelphine** [stwe/DatatablesBundle#635]
Hi !

I ran a composer update and now I am unable to set connection that `EntityManager Object `should use.

Before that, I had this on my `ObjectDatable` Class : 

```
class ObjectDatatable extends AbstractDatatableView
{
public function setEntityManager($em){
        $this->em = $em;
    }
    /**
     * {@inheritdoc}
     */
    public function buildDatatable(array $options = array())
    {
        if(array_key_exists('em', $options)){
            $this->setEntityManager($options['em']);
        }
}
...
}
```

And in my Controller : 

```
$em = $this->getDoctrine()->getManager("custom");
$datatable = $this->get('app.datatable.fsproject');
$datatable->buildDatatable(array('em' => $em));
```

Now, `AbstractDatatableView` class is renamed `AbstractDatatable`.
Now, my workaround does not work anymore !

I am unable to bypass this behaviour (taking default connection) by creating call to `"setEntityManager"` as this setter does not exist in AbstractDatatable class.
Unable to override `__constructor() ` from my `ObjectDatatable` class by passing `"doctrine.orm.custom_entity_manager"` service as argument.

This new release broke my code ..

What did I miss ?..

**Comment by MlleDelphine** [comment]
OK.

As injecting _doctrine.orm.custom_entity_manager_ does work at all. I can't find why...
`default `entity manager object is still injected and it has been driving me crazy...
So, now I inject an extra service `Registry` to switch !

```
<!--config/services.xml-->

 <service id="app.datatable.fsproject" class="APIBundle\Datatables\FSProjectDatatable" parent="sg_datatables.datatable.abstract">
            <argument type="service" id="doctrine"/>
        </service>
```

```
class FSProjectDatatable extends AbstractDatatable
{
    public function __construct(AuthorizationCheckerInterface $authorizationChecker,
                                TokenStorageInterface $securityToken,
                                TranslatorInterface $translator,
                                RouterInterface $router,
                                EntityManager $em,
                                Twig_Environment $twig,
                                Registry $registry
    )
    {
        $emFS = $registry->getManager("custom");

        parent::__construct($authorizationChecker, $securityToken, $translator, $router, $emFS, $twig);
    }
```
Really hard to pass from v0.12 to v1.0 >< !..

**Comment by stwe** [comment]
OK. But the problem is resolved? Otherwise, reopen.
