### ISSUE TITLE
DateRange full search

### ISSUE THREAD

**Issue by grekpg** [stwe/DatatablesBundle#637]
i have object with date from to 1.06 - 7.06 (two columns) 
is possible to found this object for range :
20.05 - 20.10 
5.06 - 20.10
1.01 - 5.06
how i can do this ?

**Comment by stwe** [comment]
https://datatables.net/examples/basic_init/multi_col_sort.html

**Comment by stwe** [comment]
I think the issue is solved. Reopen if necessary
