### ISSUE TITLE
Hi, why version 1.0 has minimum Symfony version 3.0. Does it work on Symfony 2.8?

### ISSUE THREAD

**Issue by AleksSem** [stwe/DatatablesBundle#638]
If there is no any problems with that could you please update compose.json?

"symfony/framework-bundle": "~2.8|~3.0",
"symfony/options-resolver": "~2.8|~3.0",
"symfony/property-access": "~2.8|~3.0",

**Comment by stwe** [comment]
That is a long time ago and I'm not sure if there are problems. I will not change that. Sorry
