### ISSUE TITLE
recordsTotal calculation issue

### ISSUE THREAD

**Issue by danielmir** [stwe/DatatablesBundle#639]
Hi,

I noticed that now `\Sg\DatatablesBundle\Response\DatatableQueryBuilder::getCountAllResults` method do not add `$this->setWhereAllCallback($qb);` as in previous bundle version, which was useful for showing correct filtered count, because now it just counts all results in database table and do not add any custom queries. What was the reason of removing it? Maybe now there is another way to solve this issue?

Thanks. 

Great bundle by the way! :)

**Comment by stwe** [comment]
see: https://github.com/stwe/DatatablesBundle/issues/604

**Comment by danielmir** [comment]
Sorry for late response.

About #604, this is not what I meant.

I'm talking about `getCountAllResults()` method, used on these lines:
On v0.13 - sg/datatablesbundle/Sg/DatatablesBundle/Response/DatatableResponse.php:144
On v1 - sg/datatablesbundle/Sg/DatatablesBundle/Datatable/Data/DatatableQuery.php:743

If we compare both versions `getCountAllResults()` methods:

On v0.13:

```php
private function getCountAllResults($rootEntityIdentifier)
{
    $qb = $this->em->createQueryBuilder();
    $qb->select('count(distinct ' . $this->tableName . '.' . $rootEntityIdentifier . ')');
    $qb->from($this->entity, $this->tableName);

    $this->setLeftJoins($qb);
    $this->setWhereAllCallback($qb);

    return (int) $qb->getQuery()->getSingleScalarResult();
}
```

On v1:

```php
public function getCountAllResults()
{
    $qb = $this->em->createQueryBuilder();
    $qb->select('count(distinct '.$this->entityShortName.'.'.$this->rootEntityIdentifier.')');
    $qb->from($this->entityName, $this->entityShortName);
    $query = $qb->getQuery();
    $query->useQueryCache($this->useCountQueryCache);
    call_user_func_array([$query, 'useResultCache'], $this->useCountResultCacheArgs);

    return !$qb->getDQLPart('groupBy') ?
        (int) $query->getSingleScalarResult()
        : count($query->getResult());
}
```

So as I understand, on v0.13 it returned filtered with my custom queries by using `$this->setWhereAllCallback($qb);` as in above example, but on v1 there is no adding of custom queries for the counting.

I think the new version need to have similar adding of custom queries, because now it's returning all records count from the database table, even if I added custom query.

**Comment by Seb33300** [comment]
Not sure if this is related to the count below every datatable, but I also have an issue with this.
The total counter always count all lines in the table instead of counting data from the query builder.

**Comment by danielmir** [comment]
@Seb33300 Yeah, this is the same issue, about the total counter under datatable.

**Comment by ronisaha** [comment]
@stwe Hi could you please lookinto the pull request #654.  If that is not acceptable could you please give some comments or any ETA of your implementation. I'm facing the problem in a production project. A relese with this fix will be very heplful.
Thanks

**Comment by Seb33300** [comment]
Fixed by https://github.com/stwe/DatatablesBundle/pull/673
