### ISSUE TITLE
Editable column - nullable field error

### ISSUE THREAD

**Issue by Asia321** [stwe/DatatablesBundle#643]
Hi, I am trying to add editable options to field which is nullable, that's code: 

`   ->add(
                'client.name',
                Column::class,
                array(
                    'title' => $this->translator->trans('field.office'),
                    'default_content' => '-',
                    'editable' => array(TextEditable::class, array(
                        'pk' => 'id',
                        'mode' => 'inline',
                    )),
                )
            )`

'default_content' works great when I want to only display row where client is null, but with 'editable' option I get error:

> PropertyAccessor requires a graph of objects or arrays to operate on, but it found type "NULL" while trying to traverse path "[client][name]" at property "name".

**Comment by stephanvierkant** [comment]
Closed in favor of #822
