### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by gdw96** [stwe/DatatablesBundle#645]
# Hi,

I need this Bundle but **it's missing after Composer install.**

I found the problem, the path where it looks for the package is:
> _**".\vendor\sg\datatablesbundle\Sg\DatatablesBundle\Sg\DatatablesBundle"**_

But the installation path (by Composer) is:
> **_".\vendor\sg\datatablesbundle\Sg\DatatablesBundle"_**

For the moment, I have simply modified the path in my project and it's works _(only for "missing" problem, not for used this bundle)_. But it would be resolve this for update or other.

Thank's
Cordially,
gdw96

## PS:
Config:
-  "symfony/symfony": "3.3.*",
- "php": ">=5.5.9",
- "doctrine/orm": "^2.5",
- "friendsofsymfony/jsrouting-bundle": "^1.6",
- "sg/datatablesbundle": "^1.0",
- "vich/uploader-bundle": "^1.4",

**Comment by stwe** [comment]
you're right. I did not know that. Thank you

**Comment by gdw96** [comment]
More informations:

In the AppKernel.php the "new new Sg\DatatablesBundle\SgDatatablesBundle()" don't work with the path:
> ".\vendor\sg\datatablesbundle\Sg\DatatablesBundle\Sg\DatatablesBundle"

But with:
> ".\vendor\sg\datatablesbundle\Sg\DatatablesBundle"

For the moment I have the bundle in:
> ".\vendor\sg\datatablesbundle\Sg\DatatablesBundle"

And a copie in:

> ".\vendor\sg\datatablesbundle\Sg\DatatablesBundle\Sg\DatatablesBundle"

Now, I have no problems for used this bundle for the development.
But I should put the project in production before August ..

Thank you.
Cordially,
gdw96

**Comment by stwe** [comment]
see https://github.com/stwe/DatatablesBundle/commit/71d9eae7c2bc1977859dda85ebdbb16f86cbd1e9
