### ISSUE TITLE
Question about ServerSide

### ISSUE THREAD

**Issue by gdw96** [stwe/DatatablesBundle#647]
Hi,

How to deactivate server side with this bundle?

I din't find..

I would like to deactivate the server side and keep the advantages of this bundle (the collumns configuration for exemple or search configuration, etc.).

Thank's,
Cordially,

**Comment by Seb33300** [comment]
Not possible for the moment: https://github.com/stwe/DatatablesBundle/issues/484

**Comment by gdw96** [comment]
Thank's
