### ISSUE TITLE
TypeError: $.fn.dataTable.isDataTable is not a function

### ISSUE THREAD

**Issue by habibun** [stwe/DatatablesBundle#65]
TypeError: $.fn.dataTable.isDataTable is not a function still this error column not rendered.

**Comment by slytimus** [comment]
I ran into the same error.  This appears to be a bug in the angular-datatables-renderer.js file.  Change the line in the file that reads $.fn.dataTable.isDataTable to $.fn.dataTable.fnIsDataTable.  That should fix your problem.  The author of this code should be made aware of this issue.

**Comment by kronikles** [comment]
Uncaught TypeError: $.fn.dataTable.moment is not a function. Can't load my dataTable with date

**Comment by schempil** [comment]
I´ve got the same problem like @kronikles. 

TypeError: $.fn.dataTable.moment is not a function

**Comment by stwe** [comment]
https://github.com/stwe/DtBundleDemo/blob/master/app/Resources/views/base.html.twig
