### ISSUE TITLE
v1.0 Individual filtering breaks responsiveness.

### ISSUE THREAD

**Issue by vctls** [stwe/DatatablesBundle#652]
When individual filtering is enabled, the table spreads way further than its normal width.
This is very easy to test with the demo project.
With individual filtering:
![firefox_2017-07-26_13-31-09](https://user-images.githubusercontent.com/18054077/28618998-ccee441c-7206-11e7-8333-9c5fd8e63e85.png)

Without it:
![firefox_2017-07-26_13-30-59](https://user-images.githubusercontent.com/18054077/28619016-d96cb7b4-7206-11e7-98f9-b9a1744f996c.png)

I have tried tinkering with the stylesheets, but I still havent found out what the problem is.
All I can say is that if you remove the input fields from the DOM, the table goes back to its normal width.

Version 0.13 did not behave this way.

**Comment by vctls** [comment]
That wasn't so hard :)
The inputs simply lack a `style="width: 100%;"` by default.
Adding it solves the problem.

Maybe that could be added to `input.html.twig` template?

**Comment by stephanvierkant** [comment]
Or:
``{{ column.width|default('100%') }}``
