### ISSUE TITLE
Reg Symfony 2.7 support

### ISSUE THREAD

**Issue by enggram** [stwe/DatatablesBundle#659]
Hi, I am running a symfony 2.7.* version and I need custom dql and other options which is currently not supported in 0.13, is it possible to add support for symfony 2.7 and 2.8 on v1.0. It would be very helpful since most of the old projects are still running on the above mentioned symfony versions..

**Comment by stwe** [comment]
For this I would have to test everything again with these versions, for which I have no time. You can make a Fork.
