### ISSUE TITLE
Doctrine error (QueryException) when only one Column is defined (which is a many-to-one association)

### ISSUE THREAD

**Issue by dsjproductions** [stwe/DatatablesBundle#660]
In the (perhaps rare, but possible) case that you only have a single column in your DataTable, which is a many to one association, like - for example in my case: `appointment.visitor.name` - a QueryException is thrown: 

`[Semantical Error] line 0, col -1 near 'SELECT partial': Error: Cannot select entity through identification variables without choosing at least one root entity alias.`

This error is gone when at least one other but "regular" Column is added.

**Comment by stwe** [comment]
That is right. But I do not know if this is really an issue.

Assuming I have defined the following entity:

```
    public function getEntity()
    {
        return 'AppBundle\Entity\Post';
    }
```
And only I just want all the approved comments:

```
            ->add('comments.allowed', BooleanColumn::class, array(
                'title' => 'comments allowed',
                'data' => 'comments[,].allowed',
            ))
```
The QueryBuilder then determines that no properties are requested from the post table. Then also the ID of Post is not in the select statement.

You can simply add a property of Post (for example the ID) and set it to "not visible".
