### ISSUE TITLE
Filtering does not work on different datatables dom layout

### ISSUE THREAD

**Issue by Bruce17** [stwe/DatatablesBundle#662]
Hi,

I'm using a different dom layout there my toolbar, datatable and pagination is in a separate row/column layout. Datatable wraps everything into a `.dataTables_wrapper` element.

Searching works, but filtering does not work for me.  Seems to me that the event handler in `search.js.html` sits on the wrong element.

**Comment by stephanvierkant** [comment]
I found a similar problem with the multiselect. I'll try to create a PR for it.

**Comment by craigh** [comment]
@stephanvierkant how did you solve it, since the related PR wasn't merged.
