### ISSUE TITLE
DataTables warning: table id=sg-datatables-inventory_datatable - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### ISSUE THREAD

**Issue by z4m4kr0n** [stwe/DatatablesBundle#664]
Hi,
I have a problem. The Datatable's search works during local development but when I put my code on a VPS it doesn't work, even if I publish the DEV branch. The initial search works, so I have a Datatable full of results, but when I search there is this pop-ip (DataTables warning: table id=sg-datatables-inventory_datatable - Ajax error. For more information about this error, please see http://datatables.net/tn/7) and the GET method shows me a 404 status error. I followed your tutorial step-by-step and in fact during local developement it's all OK. I use the php server in local and in my vps for testing.

**Comment by stwe** [comment]
you can try:
Mak an update and delete the cache. There was an error with the composer.json

see: https://github.com/stwe/DatatablesBundle/issues/645

**Comment by z4m4kr0n** [comment]
Thanks for the reply,
I tried but nothing changed, I installed it on a new VPS but the Ajax error is still there.

**Comment by z4m4kr0n** [comment]
The problem was with the builtin php server, with Apache is all working. Thanks for the reply and for your job, I hope that this will help someone!

**Comment by haitong506** [comment]
You can see it
http://123link.pw/diAAQi
