### ISSUE TITLE
Postgresql support

### ISSUE THREAD

**Issue by nicodmf** [stwe/DatatablesBundle#669]
I have a project with postgresql, are you interessing that i share the modifications, that could appears ?

**Comment by stwe** [comment]
My idea would be that I set a link to your project. Who would like to use PostgreSql can use your bundle.

**Comment by nicodmf** [comment]
I don't think create a complete project, but more use stwe and permit to correct little thing. As it i have no modification, and the bundle works, so changes will be very light.

**Comment by fyrye** [comment]
As long as the tests are written, I would accept pull requests with Postgresql support.
This would allow you to validate the assertions against your own and allow the community to add-in support for the feature so you wouldn't need to maintain it yourself.
If something breaks, the blame would be on the developer who pushed the changes and you can reject the merge.

**Comment by stwe** [comment]
sorry guys. I still have no idea of PostgreSQL.
