### ISSUE TITLE
Why the DateTimeColumn doesnt show the real date on DB

### ISSUE THREAD

**Issue by cesartamez92** [stwe/DatatablesBundle#670]
Hi, i have an issue on the DateTimeColumn, in the DB show 08/08/17 and the DataTable show 07/08/17 in all rows is substracting one day... How can i configure correctly?
->add('entFecha', DateTimeColumn::class, array(
                'title' => 'Fecha',
                'date_format' => 'L',
                'filter' => array(DateRangeFilter::class,array(
                    'cancel_button' => true,
                )),

**Comment by fcpauldiaz** [comment]
I had the same problem while ago, I tracked the problem to a javascript library. This request solved the issue #485, but author told that they didn't used that functions anymore.
