### ISSUE TITLE
How to render or not a button?

### ISSUE THREAD

**Issue by celvin** [stwe/DatatablesBundle#68]
using "renderif" is only if a column exists no?

but I want to render or no a button if a role has a special flag activated, or evaluate if a function returns true or false.

**Comment by stwe** [comment]
Renderif should be used as follows.

                'role' => 'ROLE_USER',
                'render_if' => array(
                    'id' => 1,
                    'username' => 'admin',
                    'enabled' => false,
                    // ...
                )

**Comment by fdelapena** [comment]
Thank you stwe!
