### ISSUE TITLE
No route found for "GET 

### ISSUE THREAD

**Issue by ahmadzai** [stwe/DatatablesBundle#681]
Hi all, thanks for this wonderful work,
I am trying since (Kabul Time) morning to integrate your nice work in my project, but I don't know what's wrong with it, it gives me Ajax error every time I click paging or I do searching or anything that triggers Ajax request. When I looked it symfony profile, it says No route found for "GET ...... including request text"
Here's the Ajax error: 
`DataTables warning: table id=sg-datatables-post_datatable - Ajax error. For more information about this error, please see http://datatables.net/tn/7`
I also searched it in google as well in datatables.net but didn't find good answer, tried all those tricks including clearing the cache, etc. but didn't work. 
Then I pull the demo application, the same errors were there, could you please help and guide me how to resolve these issues. 
By the way I am using symfony builtin webserver (if it could be server issue ? ) 
Thanks in advance. 
Here's the PHP error: 
`ERROR - Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=createdBy.username&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=comments%5B%2C%20%5D.title&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=true&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B9%5D%5Bdata%5D=9&columns%5B9%5D%5Bname%5D=&columns%5B9%5D%5Bsearchable%5D=false&columns%5B9%5D%5Borderable%5D=false&columns%5B9%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B9%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=1&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1505129036856" (from "http://127.0.0.1:8000/post/")" at C:\xampp7\htdocs\DtBundleDemo10\var\cache\dev\classes.php line 3514 `

**Comment by ahmadzai** [comment]
Hey guys, I found the issue, it's actually the webserver issue, as soon as I browse it through XAMPP, it perfectly works now, will close this issue

**Comment by secit-pl** [comment]
@ahmadzai I faced the same problem. It's related to this php bug https://bugs.php.net/bug.php?id=76010&thanks=10
