### ISSUE TITLE
Action Icon do not display

### ISSUE THREAD

**Issue by marcopall** [stwe/DatatablesBundle#683]
Hi,

I'm having issues with action icon, I tried with different icon coming from Glyphicon and font awsome but no way to display that icons.
Can you Help me?
[testdatatableDatatable.txt](https://github.com/stwe/DatatablesBundle/files/1299048/testdatatableDatatable.txt)

this is my datatatable class

**Comment by Seb33300** [comment]
`fa fa-plus` is a [FontAwesome](http://fontawesome.io) icon, not a [Glyphicon](http://glyphicons.com).

In order to use icons, you have to integrate them in your application.

**Comment by marcopall** [comment]
I'm using bootstap CDN and seems that glyphicon is no more included into the library.
Is there a way for include glyphicon? can't find a manual that describe the integration with symfony.

**Comment by marcopall** [comment]
I have font awsome CDN included and icon still don't work.

**Comment by marcopall** [comment]
I have substituted the bootstrap version from 4 to 3, the glyphicon are in this version.

But actions still not di
[testdatatableDatatable (2).txt](https://github.com/stwe/DatatablesBundle/files/1299386/testdatatableDatatable.2.txt)
[testdatatable.html.txt](https://github.com/stwe/DatatablesBundle/files/1299389/testdatatable.html.txt)

[base.html.txt](https://github.com/stwe/DatatablesBundle/files/1299388/base.html.txt)


splay dei icons.

**Comment by Seb33300** [comment]
Is the `<i class="glyphicon glyphicon-eye-open"></i>` is properly displayed below the datatables?

**Comment by marcopall** [comment]
yes I've checked.
