### ISSUE TITLE
Question Use Repository for query

### ISSUE THREAD

**Issue by jspourre** [stwe/DatatablesBundle#684]
Hi. 
I just started to use this awesome bundle but I have a question. Can i use a custom query from a EntityRepository for datatable ?

**Comment by Seb33300** [comment]
You can found an example on how to modify the query here: https://github.com/stwe/DatatablesBundle/issues/604

**Comment by jspourre** [comment]
Thanks for you answer.
I did and that work, but i wanted to know how to use 

`$query = $this->getDoctrine()->getManager()->getRepository(Entity:class)->customQuery($parameters);`

inside a method for datatable.

**Comment by fyrye** [comment]
@jspourre can you provide a use-case of what you're looking to accomplish _(your custom query)_? For the most part your Datatable acts as your custom query from the repository.

Datatable does support [additional queries](https://github.com/stwe/DatatablesBundle/blob/v1.0.2/Resources/doc/query.md) via DQL along with the response `DatatableQueryBuilder`, which processes a significant amount of the Entity metadata to coincide with the generated Datatable.

So the answer is yes, but it depends on your what you're looking to accomplish.
For example overriding the generated datatable querybuilder using `setQB` would be ill-advised, and suggest instead to expand the generated query builder.
```php
$responseService = $this->get('sg_datatables.response');
$responseService->setDatatable($datatable);
$builder = $responseService->getDatatableQueryBuilder();
$repository->getCustomQueryBuilder($builder->getQb(), $parameters);

return $response->getResponse();
```

This would allow you to expand upon the generated query builder with the desired response from your repository.
```php
class EntityRepository extends \Doctrine\ORM\EntityRepository
{
     public function getCustomQueryBuilder(QueryBuilder $qb, $parameters)
     {
           $qb->andWhere('createdBy.username = :username');
           $qb->setParameter('username', $parameters['key']);

           return $qb;
     }
}
```

Alternatively to add a value to a column, have your repository method return the DQL value.
```php
class EntityRepository  extends \Doctrine\ORM\EntityRepository
{
     public function getCustomDQL($parameters)
     {
          return $this->_em->createQuery('(SELECT COUNT({p}) FROM AppBundle:Post {p} WHERE {p}.createdBy = createdBy.id)')->getDQL();
     }
}
```

Then apply it to your desired column

```php
$builder->add('my_data', Column::class, [
    'dql' => $repository->getCustomDQL($parameters),
//...
]);
```
Which will result in:
```(SELECT COUNT({p}) FROM AppBundle:Post {p} WHERE {p}.createdBy = createdBy.id) AS my_data```

**Comment by stwe** [comment]
I think the problem has been solved.
