### ISSUE TITLE
[Error] `Too few parameters` when using global search with QueryBuilder filtering

### ISSUE THREAD

**Issue by LauLaman** [stwe/DatatablesBundle#685]
Steps to reproduce:
- Create a new Datatable
- Add a Where statement to the QueryBuilder as described [here](https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/query.md#1-customize-the-doctrine-query)
- Try a Column Search -> works!
- Try a Global Search -> Error: `Too few parameters: the query defines # parameters but you only bound #`

```php
//-- EmployeeDatatable.php
$this->columnBuilder
    ->add('id', Column::class, [
        'title' => 'Id',
        'searchable' => true,
        'orderable' => true,
        'filter' => [NumberFilter::class, [
            'classes' => 'test1 test2',
            'search_type' => 'eq',
            'cancel_button' => true,
            'type' => 'number',
            'show_label' => true,
            'datalist' => array['3', '50', '75']
        ]],
    ])
    ->add('firstName', Column::class, [
        /** @Desc("First Name") */
        'title' => $translator->trans('datatable.title.firstName'),
        'searchable' => true,
        'orderable' => true,
    ])
    ->add('lastName', Column::class, [
        /** @Desc("Last Name") */
        'title' => $translator->trans('datatable.title.lastName'),
        'searchable' => true,
        'orderable' => true,
    ])
    ->add('company.id', Column::class, [
        'visible' => false,
        'searchable' => false,
    ]);
```

```php
//-- EmployeeControler.php
if ($isAjax) {
    $responseService = $this->get('sg_datatables.response');
    $responseService->setDatatable($datatable);
    $datatableQueryBuilder = $responseService->getDatatableQueryBuilder();

    /** @var QueryBuilder $qb */
    $qb = $datatableQueryBuilder->getQb();
    $qb->andWhere('company.id = :company');
    $qb->setParameter('company', $company()->getId());

    return $responseService->getResponse();
}
```
<img width="1085" alt="screen shot 2017-09-14 at 00 26 39" src="https://user-images.githubusercontent.com/8283992/30403760-6fff4694-98e3-11e7-8f1a-fa1d394d844f.png">

**Comment by Seb33300** [comment]
I encountered the same issue and opened an issue on the doctrine repository:
https://github.com/doctrine/doctrine2/issues/6699

For now, you can get around this by adding a non searchable column as the first column of your datatable (ActionColumn or invisible column with searchable option as false).

**Comment by LauLaman** [comment]
@Seb33300 I Posted it here because I think it is strange that the individual column search does work. So it might be a problem with this project.
Also, the workaround you suggested confirms this a bit.

**Comment by Seb33300** [comment]
This is because DatatableBundle use `?0` to set parameter of the first column when making a global search query.
The bug have been confirmed by the doctrine team. A fix is on the road.

**Comment by Seb33300** [comment]
Since the pull request is still pending on the doctrine repository, I made a small fix in the DatatablesBundle to prevent the issue.

**Comment by LauLaman** [comment]
@seb3300 you’re a legend!

**Comment by tallan-lh3** [comment]
Still the same problem for me , i'm new user of symfony, i can't fix this bug 

here is my code : 

class PropertyRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Property::class);
    }
    /**
     * @return Query
     */
    public function findAllVisibleQuery(PropertySearch $search): Query
    {
        $query = $this->findVisibleQuery();


        if ($search->getMaxPrice()) {
            $query = $query
                ->andWhere('p.price <= :maxprice')
                ->setParameter('maxprice', $search->getMaxPrice());
        }
        if ($search->getMinSurface()) {
            $query = $query
                ->andWhere('p.surface >= :minsurface')
                ->setParameter('minsurface', $search->getMinSurface());
        }

        if ($search->getOptions()->count()) {
            $k = 0;
            foreach ($search->getOptions() as $k => $options) {
                $k++;
                $query = $query
                    ->andWhere(":option$k MEMBER OF p.options")
                    ->setParameter("options$k", $options);
            }
        }



        return $query->getQuery();
    }

**Comment by tallan-lh3** [comment]
An here is the erroe 
![Capture](https://user-images.githubusercontent.com/59100328/81765778-028d9700-94d5-11ea-96e9-87edb682bbc4.JPG)
