### ISSUE TITLE
Decrypt Database Fields

### ISSUE THREAD

**Issue by gdidok** [stwe/DatatablesBundle#687]
Is there any way to decrypt database fields before populating a datatable?

**Comment by ProfM2** [comment]
The way I would do it, would be to use a LineFormatter, and place your encrypted data in a non-visible column, and create a virtual column for your decrypted data.

I've done something similar for simple formatting of MAC addresses ...


public function buildDatatable(array $options = array())
    {
        ... options and setup removed ...
        $this->columnBuilder
            ->add('macAddress', Column::class, array(
                'visible' => false,
            ))
            ->add('mac_text', VirtualColumn::class, array(
                'title' => 'MAC Address',
                'width' => '20%',
            ))
      ... more stuff ...
        ;
    }

public function getLineFormatter()
    {
        $formatter = function($line){
            $line['mac_text'] = MacConvert::MacBinToStr($line['macAddress']);
            return $line;
        };
        return $formatter;
    }

**Comment by stwe** [comment]
please reopen with a better explanation if necessary
