### ISSUE TITLE
v1.x Production removes Sensio-GeneratorBundle 

### ISSUE THREAD

**Issue by fyrye** [stwe/DatatablesBundle#690]
See #290 this issue persists in v1.x when using `composer.phar install --no-dev` for use in production environments.

**Comment by kissifrot** [comment]
It looked like the command class was fixed in a previous PR, but this change isn't in the code anymore :(

**Comment by eco3** [comment]
Any progress on this?

**Comment by fyrye** [comment]
@eco3 as a temporary fix, move Sensio-GeneratorBundle in your composer.json from from your require-dev to require

```json
"require": {
    "sensio/generator-bundle": "^3.0",
}
```

This will resolve the issue temporarily, until a patch is made to use doctrine, then the change can be reverted

**Comment by grekpg** [comment]
WARNING: This bundle does not support Symfony 4. It also does not support the new bundle-less directory structure as created by Symfony Flex. Use the Maker bundle instead.
