### ISSUE TITLE
SensioLabsInsight is broken

### ISSUE THREAD

**Issue by stephanvierkant** [stwe/DatatablesBundle#695]
Last analyzed 6 months ago: https://insight.sensiolabs.com/projects/61803d08-17ab-4a69-ad13-6ec448762332

**Comment by stwe** [comment]
Yes, but this does not concern any really relevant topics. There is a refactoring problem, which can be ignored.

**Comment by stephanvierkant** [comment]
I mean the last analysis is 6 months old.

**Comment by stephanvierkant** [comment]
@stwe, can you re-enable analysis?

**Comment by stwe** [comment]
I always remember when I see the silver medal. 🥇
