### ISSUE TITLE
dynamic value in the drop-down filters

### ISSUE THREAD

**Issue by K0rINf** [stwe/DatatablesBundle#697]
hi. 

in the source table there are 2 columns, with the filter in the form of a drop-down list.
city   | street
city1 | street1
city1 | street2
city2 | street3

I want that when you select "city1" in the "city" column, in the drop-down list of column "street", there are only the values "street1" and "street2". 

How to make so that values of the drop-down list changed dynamically at a choice of values from the previous columns?

**Comment by stwe** [comment]
How to make it issue. Close.
