### ISSUE TITLE
state_save filters are not restored

### ISSUE THREAD

**Issue by grekpg** [stwe/DatatablesBundle#699]
Is possible to restore filters or show summary with filters are used ? 
Now i have 
state_save: true 
datatable restore filters but i dont know with is used  (all is in default state even simple text filters)

**Comment by SulivanDotEu** [comment]
Same here

**Comment by G4Zz0L1** [comment]
Yep, it doesn't retrieve the correct filter value, even if it's saved in localStorage

**Comment by grekpg** [comment]
problem is filter value is restored in data list - but not shown so user don`t know why dont see all results. Any ideas to fill filters or remove it from query builder.

**Comment by G4Zz0L1** [comment]
Any news on this?

**Comment by SulivanDotEu** [comment]
I put a datatable and our operation department is going crazy about this problem. I'll make some investigation. I really need to fix this and also to add a clear button

**Comment by kurkowskik** [comment]
Same here. Any ideas how to fix it?

**Comment by kurkowskik** [comment]
@grekpg add callback to buildDatatable

```
            $this->callbacks->set([
                'state_loaded' => [
                    'template' => '_datatable_filter_callback.js.twig',
                    'vars' => [],
                ],
            ]);
```

and add template: templates/_datatable_filter_callback.js.twig
```
function stateLoaded(nRow, aData, index) {
    var $nRow = $(nRow);

    for (let i = 0; i < aData.columns.length; i++) {
        $('#' + $nRow[0].sInstance + '-head-filter-' + i).val(aData.columns[i].search.search);
    }
}
```

**Comment by Knallcharge** [comment]
The above fix by kurkowskik restores the filters, but makes it impossible to use "initial_search" on datatables. It restores any user-typed text in the filter boxes, but will not allow to set an initial search programmatically. It only works when setting state_save to false, but then all other options are lost.
Any fix on this?
