### ISSUE TITLE
Default filter

### ISSUE THREAD

**Issue by grekpg** [stwe/DatatablesBundle#701]
I add query modification but see (showing 1 of xxx records - count all) is possible to add query after count total records ?
(user show only own data - but see showing 1 of 15000 records)

**Comment by Seb33300** [comment]
I think you are looking for this: https://github.com/stwe/DatatablesBundle/issues/604

**Comment by grekpg** [comment]
no, i ask about default filter not how to query modification. 
here is situation - a render table for user - and setup query modification where user = :user 
and results is ok - only user rows i see . 
but datatable information is wrong - i see 
display 1 to 10  form 1,132 results  = 1,132 is total rows number , i need show 20 - this is number of rows for this user.

**Comment by Seb33300** [comment]
Your issue is "rows total count" at the bottom left of the datatable which display an incorrect amount?

This was fixed in the 1.0.2 release.
Which version are you using?

**Comment by grekpg** [comment]
unfortunately v0.13 - this project is in symfony 2,8
