### ISSUE TITLE
In-place editing of a whole column

### ISSUE THREAD

**Issue by fmauri** [stwe/DatatablesBundle#703]
Hi! Is it possible to enable an in-place editing of a whole column/row at once (so that the user can "tab" between fields and confirm all the changes in the column at once)? I need to provide a way to edit a whole column of values in the easiest possible way, so I am wondering if that is possible.

**Comment by stwe** [comment]
The editable component of this bundle is unfortunately a completely problematic topic. X-editable has 500 open (!) issues. So I can say: no. I have to think about removing or replacing x-editable.

https://github.com/vitalets/x-editable/issues
