### ISSUE TITLE
custom query for datatable as datasource instead of entity

### ISSUE THREAD

**Issue by ahmadzai** [stwe/DatatablesBundle#704]
hi all, 

I have been using this wonderful bundle in my project for 2 months, recently I came up with a requirement to show the summary of records in a datatable instead of raw data. 
My scenario is little bit different, I am storing immunization campaign data in a table. The campaign normally are for 4 days, means for a single village/cluster there are 4 rows (day 1, day 2, day 3, day4), and I want to show the summary of these 4 days in a datatable. Where I need to do some calculation in my query (doctrine). 

Please suggest me if there's any way to show such a data in datatable.  
Thanks in advance,

**Comment by stwe** [comment]
I would say that you first create a query and then think about the representation of the data. I can not help you before.

**Comment by ahmadzai** [comment]
@stwe thanks for your response, 
The query is not a problem, it's already created the only issue is that how to tell datatable to use that query as datasource instead of entity. 
What I have done is that I created a View (entity) from my query and then assigned that view-entity as datasource. But this method has some performance implications.
