### ISSUE TITLE
GeneratorCommand entity namespace issue

### ISSUE THREAD

**Issue by SulivanDotEu** [stwe/DatatablesBundle#714]
Hello!

I noticed that the command below doesn't handle correctly the namespace

**php app/console sg:datatable:generate SulivanFinBundle:Bank/RawBankRecord**
will generate a class in the correct folder but the namespace withing the file is not correct.

It generates namespace **Sulivan\FinBundle\Datatables;**
instead of namespace **Sulivan\FinBundle\Datatables\Bank;**

Again I'll try to do a PR. (I never did a PR yet, time to learn :D )

**Comment by stwe** [comment]
make a PR
