### ISSUE TITLE
Unexpected/Random 404 on symfony3

### ISSUE THREAD

**Issue by henry-geronimo** [stwe/DatatablesBundle#715]
Hi it doesn't happen every time, but enough to be noticed. It happens to me on two different projects. Sometimes the route generated when filtering/displaying rows is incorrect:
Symphony profiles show me this.

![screenshot-2017-11-17 symfony profiler](https://user-images.githubusercontent.com/29857583/32952926-f50af966-cbae-11e7-805f-25478e68d2c3.png)

Any idea on what might cause this issue ?

**Comment by gladstongarcia** [comment]
I've been there. Found out it is related to some instability with PHP Cli server and big querystrings when using GET method. Won't happen in production server.

Solved it by changing the method to POST:

`$this->ajax->set([
	'type' => 'POST',
]);`
