### ISSUE TITLE
Access row data in action button

### ISSUE THREAD

**Issue by benjaminb-** [stwe/DatatablesBundle#718]
Hi, 

I can't figure out how to access the row data in action button.

I want to access a row value to put it in the attributes array.

Is it possible ?

Thanks !

``` php
->add(null, ActionColumn::class, array(
    'actions' => array(
        array(
            'button' => true,
            'icon' => 'fa fa-files-o',
            'attributes' => array(
                'class' => 'btn btn-sm copy-to-clipboard',
                'data-clipboard-text' => '***here i want a column from the entity***',
                'data-toggle' => 'tooltip',
                'title' => 'Copied to clipboard!'
            ),
        ),
```

**Comment by Seb33300** [comment]
Unfortunately, `attributes` option doen't allow closure so this is not possible.

You could provide a pull request to provide this feature.
This could be implemented in the same way as the `route_parameters` option which already provide this feature.

**Comment by benjaminb-** [comment]
Just did that, thanks !

**Comment by benjaminb-** [comment]
Do you know how long it takes to merge pull requests ? Because i have to finish my current project next week :-)

**Comment by Seb33300** [comment]
Merged.
You can add `dev-master` in your composer.json to get the update with your commit

**Comment by benjaminb-** [comment]
Thanks, but i think my pull request is not working, i've tried with multiples rows and apparently the attributes are the same for each row (like the first one)

**Comment by benjaminb-** [comment]
i'm working on it

**Comment by Seb33300** [comment]
How do you use it?

**Comment by benjaminb-** [comment]
Ok so, if you try to put attributes (with array not closure)

```
                         'attributes' => array(
                                'class' => 'btn btn-sm copy-to-clipboard',
                                'data-clipboard-text' => rand(0, 100),
                                'data-toggle' => 'tooltip',
                                'title' => 'Copied to clipboard!'
                            )
```

and you make a dump of the attributes for each row in action.html.twig

```
{% for actionKey, action in actions %}
    {% if render_if_actions[actionKey] is same as(true) %}
        {{ dump(action.attributes) }}
```

You will see the random number is always the same.

And it's the same for the closure.

**Comment by Seb33300** [comment]
Yes because the array is created only once.

You have to use a closure function which will be called on each row:
``` php
'attributes' => function($row) {
    return array(
        'class' => 'btn btn-sm copy-to-clipboard',
        'data-clipboard-text' => rand(0, 100),  // or $row['column_name']
        'data-toggle' => 'tooltip',
        'title' => 'Copied to clipboard!'
    );
},
```

**Comment by Seb33300** [comment]
I just push a fix for this

**Comment by benjaminb-** [comment]
Oh thanks !
