### ISSUE TITLE
Issue while installing with Symfony 3

### ISSUE THREAD

**Issue by ekussberg** [stwe/DatatablesBundle#720]
I installed the:
```
"friendsofsymfony/jsrouting-bundle": "^2.0",
```

When i try to install the bundle get following:
```
Problem 1
    - Installation request for sg/datatablesbundle v1.0.2 -> satisfiable by sg/datatablesbundle[v1.0.2].
    - sg/datatablesbundle v1.0.2 requires friendsofsymfony/jsrouting-bundle 1.6.0 -> satisfiable by friendsofsymfony/jsrouting-bundle[1.6.0] but these conflict with your requirements or minimum-stability.
```

**Comment by Seb33300** [comment]
This was fixed on master.
I just tagged a new release including the fix. 

Can you try to composer update your project?

**Comment by ekussberg** [comment]
@Seb33300 yeah 🔥  worked!

**Comment by ekussberg** [comment]
@Seb33300 now when running got this:

```
The service "sg_datatables.factory" has a dependency on a non-existent service "translator.default". 
```

and i have it in config.yml:

```
framework:
    default_locale: "%locale%"
    translator: { fallbacks: ["%locale%"] }
```

**Comment by Seb33300** [comment]
Related to this issue: https://github.com/stwe/DatatablesBundle/issues/627

It seems that you have to enabled translator on your project to make this bundle to work.

**Comment by ekussberg** [comment]
@Seb33300 have you a hint where else to enable it? i added the snippet above in config.yml, where else? 🤔

**Comment by Seb33300** [comment]
is the `locale` var defined in your parameter.yml?

**Comment by ekussberg** [comment]
@Seb33300 sorry that was my mistake as i found out now ... i defined two times 'framework'! Thanks for you help!
