### ISSUE TITLE
Manual Join and column [No mapping found for field ... on class ...]

### ISSUE THREAD

**Issue by Kytrix** [stwe/DatatablesBundle#723]
Hello,
I need to display data from a manual join on my entity.
I will not detailed the entire things, but my starting entity 'dispatch' has a field product_id, as another entity, but this relation is not describe in entity (not needed usualy).
Here is what I write in my controller:
```
 $qb = $datatableQueryBuilder->getQb(); // on my DispachDataTable using Dispatch entity
 $qb->leftJoin('SIFrontendBundle:packagingContent', 'pc1' ,'WITH', 'dispatch.product = pc1.product');
```
here the join above seems working, no errors without adding column in datatable.

now inside my DispatchDataTable:
```
->add('pc1.name', Column::class, array(
                'title' => 'pc1',
                'data' => 'pc1',
                'searchable' => false,
            ))
```
And I get the following error:
> No mapping found for field 'pc1' on class 'SI\FrontendBundle\Entity\Dispatch'.

How to define a column wich represent the pc1 entity ?
I also try to use a virtualColumn, but the $row doesn't contains 'pc1' field.

**Comment by SulivanDotEu** [comment]
same issue here.

**Comment by Kytrix** [comment]
I made a little step (by trying the same query inside a repository)
In my repository, when I add :
`->addSelect('pc1')`
instead of retrieve 50 results of entity Dispacth,:
![image](https://user-images.githubusercontent.com/3098540/33874845-77afd736-df20-11e7-9490-85db73c84484.png)

I get 100 results of entity Dispatch and PackagingContenten mixed ! (one line on two)
![image](https://user-images.githubusercontent.com/3098540/33874834-6bff581c-df20-11e7-98ba-aa4411140b67.png)

So I supposed the bundle received the rows "alternatly", 
I look inside the getLineFormatter, and one row belong to entity Dispatch and the next to PackagingContent.

**Comment by Seb33300** [comment]
The only way to do this is to manually join with the query builder and then, add the column using custom DQL.

You can find an example of how to customize the query builder here: https://github.com/stwe/DatatablesBundle/issues/604

An example with custom DQL can be found in the documentation: https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/columns.md#1-column

**Comment by Kytrix** [comment]
the problem with custom DQL it will generate too many querys, that why I want to avoid this.

**Comment by Seb33300** [comment]
Did you look at the documentation?

Custom DQL is just a way to inject your DQL in the query. It will not execute extra queries.

**Comment by Kytrix** [comment]
Okay but this injection of query is made in the select right ?
So it's a subquery called on every line of the query, not sure it's as quick as join ..
I will try to be sure.

**Comment by Seb33300** [comment]
If your DQL is a subquery, so yes, it will be a subquery.
But you can add something else than a subquery just like in the documentation link I sent to you.
DQL example: `CONCAT(user.firstname, ' ', user.lastname)`

**Comment by Kytrix** [comment]
Yes it's subquerys, and in fact I need several joins, so the subquerys will be heavy.
I will look for an alternate solution, write the datatable manualy for this page :/

**Comment by Seb33300** [comment]
I think you didn't understood my first answer.
You can manually add your joins on the datatable query builder and then add required fields to the select without adding subqueries using DQL.

**Comment by Kytrix** [comment]
Okay !! sorry for the missunderstanding.
I will have a look :)

**Comment by Kytrix** [comment]
Do you have an example ?
because in the doc: https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/columns.md#5-virtual-column
it's show to made subqueries.

**Comment by Seb33300** [comment]
Search for custom DQL, not virtual column

**Comment by Kytrix** [comment]
I see exactly where it is, but I can do :

> ->add('pct1.name', Column::class, array(
>                 'title' => 'pct1.name',
>                 'dql' => '(SELECT {pct1}.name 
>                               FROM SIFrontendBundle:packagingContent {pc1}
>                                 LEFT JOIN SIFrontendBundle:packagingContainer {pct1} WITH {pc1}.packagingContainer = {pct1}.id
>                               WHERE dispatch.product = {pc1}.product
>                                    AND {pc1}.isRemoved = 0)',
>             ))

(for me it's a subquery by the way)
and if I try to add a column with another level :

> ->add('pct2.name', Column::class, array(
>                 'title' => 'pct2.name',
>                 'dql' => '(SELECT {pct2}.name
>                               FROM SIFrontendBundle:packagingContent {pc2}
>                                 LEFT JOIN SIFrontendBundle:packagingContainer {pct2} WITH {pc2}.packagingContainer = {pct2}.id                 
>                               WHERE {pct1}.name = {pc2}.name
>                                    AND {pc2}.isRemoved = 0)',   
>             ))

I can't re-use previous {pc1} and {pct1} ... so I need to rewrite the first level again :/

**Comment by Seb33300** [comment]
The datatable is mapped on which entity ?

**Comment by Kytrix** [comment]
Dispatch

**Comment by Seb33300** [comment]
Do your joins on the query builder in controller.

``` php
$responseService = $this->get('sg_datatables.response');
$responseService->setDatatable($datatable);

$datatableQueryBuilder = $responseService->getDatatableQueryBuilder();
$datatableQueryBuilder->buildQuery();

/** @var QueryBuilder $qb */
$qb = $datatableQueryBuilder->getQb();

$qb->leftJoin('SIFrontendBundle:packagingContent', 'pc1' ,'WITH', 'pc1.product = dispatch.product AND pc1.isRemoved = 0')
$qb->leftJoin('SIFrontendBundle:packagingContainer', 'pct1' ,'WITH', 'pc1.packagingContainer = pct1.id')

$qb->leftJoin('SIFrontendBundle:packagingContent', 'pc2' ,'WITH', 'pc2.name = pct1.name AND pc2.isRemoved = 0')
$qb->leftJoin('SIFrontendBundle:packagingContainer', 'pct2' ,'WITH', 'pc2.packagingContainer = pct2.id')
```

Then, add columns with custom DQL:

``` pgp
->add('pct1.name', Column::class, array(
'title' => 'pct1.name',
'dql' => 'pct1.name',
))
->add('pct2.name', Column::class, array(
'title' => 'pct2.name',
'dql' => 'pct2.name',
))
```

**Comment by Kytrix** [comment]
THANK YOU !!
I tried 'dql' => '(SELECT pct1.name)' 
but not pct1.name .

From the doc I really didn't get that :)
