### ISSUE TITLE
Unable to find template "SgDatatablesBundle:datatable:datatable.html.twig"

### ISSUE THREAD

**Issue by secit-pl** [stwe/DatatablesBundle#724]
Symfony 4 - `{{ sg_datatables_render(datatable) }}` throws the following exception:

`Unable to find template "SgDatatablesBundle:datatable:datatable.html.twig"`

**Comment by jejeman1110** [comment]
Hello, I have same error with Symfony 3.4
I think the error starts with symfony 3.3 (perhap's the new DI container ? http://symfony.com/doc/3.3/service_container/3.3-di-changes.html)

**Comment by Seb33300** [comment]
Did you tried to use dev-master version of this bundle?

**Comment by jejeman1110** [comment]
Thank for your answer.
I tried the dev-master version and same error...

**Comment by Seb33300** [comment]
Strange... I am using this bundle with Symfony 3.4 and I am not able to reproduce this issue.

**Comment by jejeman1110** [comment]
I did more tests.
If you start a new project with SF3.4, you have this error.
If you upgrade a project from SF3.0 => 3.1 => 3.2 => 3.3 => 3.4 no issue
¯\_(ツ)_/¯

**Comment by Seb33300** [comment]
Can you try to change `SgDatatablesBundle:datatable:datatable.html.twig` to `@SgDatatables/datatable/datatable.html.twig` in `DatatableTwigExtension.php`?

**Comment by Seb33300** [comment]
It seems to be an issue with syntax using `:`.
[Symfony 4 documentation](https://symfony.com/doc/current/templating/namespaced_paths.html) doesn't refer to it, and this syntax wasn't recommended in previous versions.

I will try to make the change

**Comment by Seb33300** [comment]
I just push the new twig path syntax on master.
Can you composer update and make another try?

**Comment by jejeman1110** [comment]
I did more tests.
If you start a new project with SF3.4, you have this error.
If you upgrade a project from SF3.0 => 3.1 => 3.2 => 3.3 => 3.4 no issue
¯\_(ツ)_/¯

**Comment by jejeman1110** [comment]
I just test it again, and your update seems to fix this issue with a new SF3.4 project.
I didn't test with SF4
Thank you ! ;-)

**Comment by Seb33300** [comment]
@secit-pl can you test with `dev-master`?

**Comment by secit-pl** [comment]
@Seb33300 sorry for long response time. Current dev-master version works for me.

**Comment by joubertredrat** [comment]
I will make fix to this and send PR.
