### ISSUE TITLE
Column render option removed

### ISSUE THREAD

**Issue by jimihay** [stwe/DatatablesBundle#727]
I'm working on upgrading a project from v0.13 to 1.0.3 and the column property for "render" was removed. How can something similar be achieved in 1.0.3?

**Comment by roxid** [comment]
Here is an idea: If you just want a column rendering a specific twig template, create a custom column class by extending `AbstractColumnClass` and implement the methods `getCellContentTemplate`, `renderSingleField`, `renderToMany` (leave method body blank if not needed) and `renderTemplate`. See class `Column` for examples on how to implement these methods.

If you want to be able to specify the template in your datatable class, add a property (plus setter and getter) for specifying the template name to your custom column class, add an option for that property in `configureOptions` and return the property value in `getCellContentTemplate`.
