### ISSUE TITLE
Mark a specific row

### ISSUE THREAD

**Issue by RafalMalik** [stwe/DatatablesBundle#728]
I don't know, however, is it possible to mark specific row with class name? I would like to make the css class lines with a certain value. It is important,  however, class should be given to the row, not to specific cell. 

Any sugestion, how to do it? I use the lineFormatter, but it allows to add the html code with class to the cell, and doesn't allow to work on the entire row.

Regards.

**Comment by Talv** [comment]
I think the recommended approach to this is to use `row` draw [callback](https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/callbacks.md).

Example:
```php
public function getLineFormatter()
{
    return function ($row) {
        $row['row_classes'] = 'status-' . $row['status'];
        return $row;
    };
}

public function buildDatatable(array $options = array())
{
    $this->callbacks->setRowCallback([
        'template' => 'row-class.js.twig',
    ]);
}
```
```js
// row-class.js.twig
function rowCallback(nRow, aData, index) {
    var $nRow = $(nRow);

    if (typeof aData.row_classes !== 'undefined') {
        var classes = aData.row_classes;
        if (Array.isArray(aData.row_classes)) {
            classes = classes.join(' ');
        }
        $nRow.addClass(classes);
    }

    return nRow;
}
```
