### ISSUE TITLE
bulk delete button works in DtBundleDemo10, but not in version 1.0.3 l because of Remove action method on ActionColumn 

### ISSUE THREAD

**Issue by Sluimers** [stwe/DatatablesBundle#733]
In PropertyAccessor line 623 for MultiselectColumn when adding actions, in the demo 
calls this method:
```php
$object->{$access[self::ACCESS_NAME]}($value);
```
but in version 1.0.3 this method is called:
```php
$this->writeCollection($zval, $property, $value, $access[self::ACCESS_ADDER], $access[self::ACCESS_REMOVER]);
```

This results into the setAttributes method of Action instead of MultiSelectAction being called.

P.S. Unless the remove action was meant fix another bug, added features should be reserved for minor versions.

**Comment by Seb33300** [comment]
I don't understand what you are talking about.

PropertyAccessor is part of the Symfony project, not from this bundle.

**Comment by Sluimers** [comment]
Yes, but ColumnBuilder somewhere calls a function within the PropertyAccessor.

https://github.com/stwe/DatatablesBundle/blob/master/Datatable/Column/ColumnBuilder.php#L125

**Comment by Seb33300** [comment]
Is this issue related to this PR: https://github.com/stwe/DatatablesBundle/pull/744

If yes, can you confirm if the PR solves your issue?

**Comment by Sluimers** [comment]
Confirmed.
