### ISSUE TITLE
Customized doctrine query semantical error

### ISSUE THREAD

**Issue by DennisBiesters** [stwe/DatatablesBundle#738]
I'm trying to use a customized doctrine query, but im getting the following error:
`[Semantical Error] line 0, col 103 near 'homePubl = :id': Error: 'homePubl' is not defined.`

Datatable class i'm using

```
$this->columnBuilder
        ->add('homeOms', Column::class, array(
         ))
         ->add('homeDatum', DateTimeColumn::class , array(
            'visible' => false,
        ))
        ->add('homePubl', Column::class, array(
            'visible' => false,
        ));
```

Customized query in controller

```
if ($request->isXmlHttpRequest()) {
            $responseService = $this->get('sg_datatables.response');
            $responseService->setDatatable($hometexts);

            $datatableQueryBuilder = $responseService->getDatatableQueryBuilder();

            $qb = $datatableQueryBuilder->getQb();
            $qb->andWhere('homePubl = :id');
            $qb->setParameter('id', '1');

            return $responseService->getResponse();
        }
```

Without the customized query it works and uses the following query
`SELECT g0_.home_id AS home_id_0, g0_.home_oms AS home_oms_1, g0_.home_datum AS home_datum_2, g0_.home_publ AS home_publ_3 FROM gps_home g0_ WHERE g0_.home_id IN (?) ORDER BY g0_.home_datum DESC`

I also tried andWhere('home_publ_3 = :id') and ('g0_.home_publ = :id')

What am i doing wrong?

**Comment by Seb33300** [comment]
You have to use the name of the entity in lowercase as prefix in your custom condition.

``` php
$qb->andWhere('entityname.homePubl = :id');
```

**Comment by DennisBiesters** [comment]
Thanks, it is working now!

But that means that the readme is incorrect?
https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/query.md

`$qb->andWhere('createdBy.username = :username');`

must be 
`$qb->andWhere('post.createdBy.username = :username');`

**Comment by Seb33300** [comment]
In the example, createdBy is a `ManyToOne` relation field.
In this case, we have to prefix using the field name.

We cannot use multiple prefix `post.createdBy.` in SQL
