### ISSUE TITLE
Question: Is it possible to use another entity manager then the default one

### ISSUE THREAD

**Issue by DennisBiesters** [stwe/DatatablesBundle#743]
I have 3 entity managers in my project. Is it possible to declare the entity manager that the datatable must use?

`The class 'LogBundle\Entity\AuthLog' was not found in the chain configured namespaces AppBundle\Entity`

**Comment by k3ssen** [comment]
You can define datatabes as services, meaning you can choose which services to use as arguments. 

The abstract class looks as follows:

    sg_datatables.datatable.abstract:
        class: Sg\DatatablesBundle\Datatable\AbstractDatatable
        abstract: true
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@translator.default'
            - '@router'
            - '@doctrine.orm.entity_manager'
            - '@twig'

So if you want to use a different entity manager, you could define your datatable as follows:

    app.datatables.my_datatable_that_uses_a_different_em:
        class: App\Datatable\MyDatatableThatUsesADifferentEm
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@translator.default'
            - '@router'
            - '@doctrine.orm.my_entity_manager'
            - '@twig'

(note: you can define service much more efficiëntly than this. I recommend taking a look at the several symfony documentations for services)
