### ISSUE TITLE
Improvements: clear button (erase all filters)

### ISSUE THREAD

**Issue by SulivanDotEu** [stwe/DatatablesBundle#745]
Hello everyone,

I have a proposal to improve the user experience. My work asked me to add a clear button, in order to reset every filter and start from zero.

I'll try make a pull request my I am not familiar with that yet (I never contributed to code unfortunatly).

    {% block main %}
    {{ sg_datatables_render(datatable) }}
    <a id="clear-dt" href="#" class="btn btn-default">Clear</a>
    {% endblock %}

    {% block javascripts %}
    <script>
        $(function () {

        var selector = "#sg-datatables-{{ datatable.name }}";

        let tableId = "sg-datatables-{{ datatable.name }}";
        let localeStorageId = 'DataTables_' + tableId + '_/admin/invoice/stwe/datatable';

        var datatable = $(selector).DataTable();

        $('#clear-dt').on('click', function () {
            datatable.state.clear();
            window.location.reload();
        });
    });
    </script>
    {% endblock %}

**Comment by stwe** [comment]
Thanks. I thinks its an example for an clear button.
