### ISSUE TITLE
custom dql - IF CURRENT_DATE() < activeTo

### ISSUE THREAD

**Issue by grekpg** [stwe/DatatablesBundle#748]
configuration 

```
 ->add('activeTo', DateTimeColumn::class, array(
                'title' => 'Expiry date',
                'filter' => array(DateRangeFilter::class, array()),
            ))
            ->add('active', Column::class, array(
                'dql' => 'IF CURRENT_DATE() < activeTo',
                'type_of_field' => 'boolean',
                'searchable' => true,
                'orderable' => true,
                'title' => 'Active',
            ))
```

give error : 
[Syntax Error] line 0, col 108: Error: Expected Doctrine\ORM\Query\Lexer::T_FROM, got '('

i try also 

`'dql' => 'IF( CURRENT_DATE() < activeTo, TRUE, FALSE)',`

it does not work either

**Comment by Seb33300** [comment]
`IF` is not a valid DQL instruction, you should use `CASE WHEN`.
``` php
'dql' => 'CASE WHEN CURRENT_DATE() < entity.activeTo THEN true ELSE false',
```

**Comment by grekpg** [comment]
[Semantical Error] line 0, col 120 near 'DocumentExport.activeTo': Error: 'DocumentExport' is not defined.

i try 

'dql' => 'CASE WHEN CURRENT_DATE() < DocumentExport.activeTo THEN true ELSE false END',

'dql' => 'CASE WHEN CURRENT_DATE() < documentExport.activeTo THEN true ELSE false END',

'dql' => 'CASE WHEN CURRENT_DATE() < entity.activeTo THEN true ELSE false END',

'dql' => 'CASE WHEN CURRENT_DATE() < activeTo THEN true ELSE false END',


ok i found - 
'dql' => 'CASE WHEN CURRENT_DATE() < documentexport.activeTo THEN true ELSE false END',

**Comment by Seb33300** [comment]
You could find the generated DQL query on the error page or in the logs. So you can find the alias to use.

**Comment by grekpg** [comment]
this work - dql' => 'CASE WHEN CURRENT_DATE() < documentexport.activeTo THEN true ELSE false END', i propose better is use like easyAdminBundle - same alias = entity so developers know and have always same
