### ISSUE TITLE
PHP Fatal error:  Class 'Sensio\Bundle\GeneratorBundle\Command\GenerateDoctrineCommand' not found in 

### ISSUE THREAD

**Issue by grekpg** [stwe/DatatablesBundle#752]
symfony 3.4 flex 

PHP Fatal error:  Class 'Sensio\Bundle\GeneratorBundle\Command\GenerateDoctrineCommand' not found in /home/grek/PhpstormProjects/envio24/vendor/sg/datatablesbundle/Command/CreateDatatableCommand.php on line 31

In CreateDatatableCommand.php line 31:
                                                                                                             
  Attempted to load class "GenerateDoctrineCommand" from namespace "Sensio\Bundle\GeneratorBundle\Command".  
  Did you forget a "use" statement for another namespace?

**Comment by stephanvierkant** [comment]
See #725. SensioGeneratorBundle is de facto a dependency, while not in `composer.json`.

**Comment by Seb33300** [comment]
Same as https://github.com/stwe/DatatablesBundle/issues/725
