### ISSUE TITLE
Searching in column is not working if scroll_x in features is enabled

### ISSUE THREAD

**Issue by pmolyavko** [stwe/DatatablesBundle#758]
Hello!
I have done this: `        $this->features->set([
            'scroll_x' => true
        ]);` 
Scroll appeared. Then I tried to find something in any column, but nothing happened. Ajax request has not been sent. Is it bug, or I do something wrong?

**Comment by Seb33300** [comment]
Can you update your project to `dev-master`?

I have merged [this pull request](https://github.com/stwe/DatatablesBundle/pull/730) which should solve your issue.

**Comment by Seb33300** [comment]
Fixed by https://github.com/stwe/DatatablesBundle/pull/730
