### ISSUE TITLE
How to add an external filter

### ISSUE THREAD

**Issue by sn0opr** [stwe/DatatablesBundle#763]
First of all I would like to thank you for the great bundle, it helps me a lot !

I need to add some external filters outside of the table (not a Column filter), something like the main Search input but with a specific criteria, it might also be a checkbox or a select . Is that possible ?

Thank you.

**Comment by roxid** [comment]
Would adding (form) data to the ajax request be of any help to that issue? See #780

**Comment by roxid** [comment]
Use the `pre_xhr` event to add the data of your custom filter to the datatable's ajax data.

**Comment by sn0opr** [comment]
Thank you @roxid that's what I did :)

**Comment by ljmoleiro** [comment]
> Thank you @roxid that's what I did :)

Hi,  its been a while but can you be more explicit with your solution please? I need to do an external filter too.
Thanks

**Comment by roxid** [comment]
Sure. Create a filter for the `pre_xhr` event as described in the [events documentation](https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/events.md). The parameters passed to the function of that specific event are listed in the [official datatables docs](https://datatables.net/reference/event/preXhr).

Add your data to filter by to the data object, see [this comment](https://github.com/stwe/DatatablesBundle/issues/797#issuecomment-399357325) as an example. Then in your backend extract that filter data from the request and [customize the doctrine query](https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/query.md#1-customize-the-doctrine-query) according to your requirements.

**Comment by ljmoleiro** [comment]
> hat filter data from the request

Thanks a lot.
