### ISSUE TITLE
Problem with searching on column with custom dql

### ISSUE THREAD

**Issue by jbogunia** [stwe/DatatablesBundle#765]
Hi, 
I have problem with searching on column 'messages' 

``` php
->add('messages', Column::class, array(
    'title' => $this->translator->trans('cms.conversation.field.last_message'),
    'visible' => true,
    'searchable' => true,
    'dql' => "(SELECT {cm}.content FROM AppBundle:ConversationMessage {cm} WHERE {cm}.id = (SELECT MAX({d}.id) from AppBundle:ConversationMessage {d} WHERE {d}.conversation = conversation))",
))
```
This dql choose one last message from ConversationMessage entity, display it properly, but if I search for something I get nothing in respons.

Any suggestions?

**Comment by Seb33300** [comment]
Any error in the ajax request?
Did you look at the generated query to see what is wrong in the query?

**Comment by jbogunia** [comment]
There is no ajax error (or I check it wrong 😁 )

Table looks like this:

![messages](https://user-images.githubusercontent.com/14938101/39309828-326d05b4-4969-11e8-8aa8-c4acb50ad71d.png)

And when I search for "test" content ("Last message column") it shows this:

![messages_searched](https://user-images.githubusercontent.com/14938101/39309959-7533dfda-4969-11e8-986b-8e6e0847bde9.png)

And the ajax result looks like this:

![messages_query](https://user-images.githubusercontent.com/14938101/39309982-84d9af64-4969-11e8-89be-3e3267725c00.PNG)

I found another bug, when I delete content from select (SELECT {cm}) it shows id in this column and it can be searchable but only if You give full number, otherwise You'll get nothing in the response

**Comment by jbogunia** [comment]
Ok, I found that I use old version of DatatablesBundle - i have 1.0.2. Anyway is still problem with searching. I have to enter full search message, otherwise I'll get nothing in response

**Comment by Seb33300** [comment]
Yes, this is because doctrine doesn't support LIKE on subqueries: https://github.com/doctrine/doctrine2/issues/6363

**Comment by Seb33300** [comment]
This is because you used a subquery in your custom DQL: `(SELECT ... FROM ...)`
Doctrine is not able to do a LIKE search on subquery. So you have to search on the exact value.

But it's working fins on non subquery columns.

**Comment by Quantumphilisp** [comment]
Just wanted to add for anyone like me trying to find a solution onlien and stumbling on this issue. you can work around this by making your own filter that inherit from abstractfilter or textfilter, adding the 'like' inside the subqueries itself inside the filter, then call qb->exists instead of like.
