### ISSUE TITLE
Action Column Disable Shrinking

### ISSUE THREAD

**Issue by LaggyBaggy** [stwe/DatatablesBundle#767]
Hello,

I currently have an Action column with 4 buttons.
![screen shot 2018-05-03 at 2 49 35 pm](https://user-images.githubusercontent.com/38960015/39596710-3e4c5876-4ee1-11e8-8411-449439f68645.png)

It seems by default when the table shrinks (either due to window size or on a mobile device)
the buttons get squished like so
![screen shot 2018-05-03 at 2 50 35 pm](https://user-images.githubusercontent.com/38960015/39596752-62b2e626-4ee1-11e8-934f-6725fe9344b0.png)

What I want to know is there any option or config that I can configure to basically force that row to never shrink and always appear like the first picture?

Note none of the other rows seem to shrink, they get clipped which im fine with, it seems unique to action column

Action column like so:

> $this->columnBuilder
>      ->add(null, ActionColumn::class, array(
>                 'title' => 'Actions',
>                 'actions' => array(
>                     array(
>                         "route" => "details",
>                         "route_parameters" => array(
>                             "name" => getName(),
>                             "orderId" => "orderId"
>                         ),
>                         "icon" => "fa fa-info-circle",
>                         "attributes" => array(
>                             "data-toggle" => "tooltip",
>                             "title" => "View Details",
>                             "class" => "btn btn-primary",
>                             "role" => "button"
>                         )
>                     ),
>                     // rest of buttons identical to above

**Comment by LaggyBaggy** [comment]
I think I fixed it, I just added a min-width style attr to the div def on column

> >add(null, ActionColumn::class, array(
                'title' => 'Actions',
                'start_html' => '<div class="start_actions" style="min-width: 180px">',
                'end_html' => '</div>',
                'actions' => array(

**Comment by Seb33300** [comment]
I think you could also specify nowrap using css on this column.

https://www.w3schools.com/cssref/pr_text_white-space.asp
