### ISSUE TITLE
Search on a Many-Many Column

### ISSUE THREAD

**Issue by LaggyBaggy** [stwe/DatatablesBundle#768]
Hello in my project I have a Order and a User Entity.
An order can be "subscribed" or watched by many users, and a user can watch many orders.
The order has the main side of the relationship
I have an orders table with the following column:
```
->add('subscribedEmployees.username', Column::class, array(
                'data' => 'subscribedEmployees[,].username',
                'searchable' => true,
                'visible' => false
            ))
```
Note I have the column Hidden as I do not want the user to actually see this column

where subscribedEmployees is a field in the Order entity which contains a list of all employees subscribed to it.

My question is this:

How can I show only the orders in the table which are watched by the current user?  I tried doing a search over the column but for some reason it always returns everything.

I mentioned above the column is hidden.  What I want ideally is a button that can be toggled where it will show either only users followed orders, or all orders

I added custom js for the search like so:

```
oTable.column(2).search({{app.user.username}});
oTable.draw();
```

How ever it always returns all rows and not the users followed orders

**Comment by stwe** [comment]
This is a "how i make it" issue. 

In general, I can say that a many-to-many solution is not optimal. You should think that over. Mostly, several one-to-many and/or many-to-one relationsare better. This bundle has minimal support for "many-to-many", as I have rarely used these associations.
