### ISSUE TITLE
Numeric column filter as string

### ISSUE THREAD

**Issue by ikerib** [stwe/DatatablesBundle#770]
Hi,

we have some fields that are integer but we need the filter act like string, I mean, having:
1001
1010
1011
11
1101
1111
11345
if in the filter box I write for example 11 I only see this one, but I need this:
11
1101
1111
11345

How to achieve that?

this is my code right now:

``` php
->add('erregistroZbkia', Column::class, array(
    'title' => $this->translator->trans('Erregistro Zbkia'),
    'searchable' => true,
    'orderable' => true,
    'filter' => array(NumberFilter::class, array(
        'search_type' => 'like',
        'cancel_button' => true,
        'type' => 'number',
    )),
))
```

I tried with nu

**Comment by Seb33300** [comment]
Unfortunately Doctrine is not able to use a LIKE clause on numbers.

So this will not be possible until this will be fixed on Doctrine side: https://github.com/doctrine/doctrine2/issues/6363
