### ISSUE TITLE
Many data

### ISSUE THREAD

**Issue by Shushu075** [stwe/DatatablesBundle#773]
Hi!
I need many data in one column.

Example :  the city Lyon have many district.

I don't want a line for each district.

How should i do? Please.

**Comment by youkoal** [comment]
Hello, i have an issue related to this kind of question, hope this can help you : 
```
$this->columnBuilder
    ->add('district.Name', Column::class, array(
        'data' => 'district[,].Name',
        ...
```

the result will be a new column with all related district name in it

**Comment by Shushu075** [comment]
Hello!
Thank you so much for your answer :)
I tried this syntax because I had seen other same issues but it doesn't work...
I think the problem comes from elsewhere (entity relation). I close the issue. 
Thanks again !
