### ISSUE TITLE
Count entities of oneToMany-association

### ISSUE THREAD

**Issue by IT-Talents** [stwe/DatatablesBundle#774]
Is there an easy way to count the associations in v1.0.x? The `array` column type has been removed and there is no `count`option in the `column` type. :(

**Comment by Seb33300** [comment]
You can add a subquery with custom DQL: https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/columns.md#1-column

**Comment by IT-Talents** [comment]
Would you mind giving an example? I'm running into syntax errors. Let's assume a datatable showing users and listing the number of comments they made. `comments` is a oneToMany association of my `User` entity (`User` being the owner of `comments`).

**Comment by Seb33300** [comment]
Did you looked at the example in the documentation?

``` php
$this->columnBuilder
    // If you want to use a subquery, please put subquery between parentheses and subquery aliases between braces.
    // Note that subqueries cannot be search with a "LIKE" clause.
    ->add('post_count', Column::class, array(
        'title' => 'User posts count',
        'dql' => '(SELECT COUNT({p}) FROM MyBundle:Post {p} WHERE {p}.user = user)',
        'type_of_field' => 'integer',
        'searchable' => true,
        'orderable' => true,
    ))
;
```

**Comment by Seb33300** [comment]
I think you can use `$row['post_count']` (for the above example) to get the value of the column.

**Comment by IT-Talents** [comment]
I just tried building the link manually in the `getLineFormatter()` method following your suggestion, it works. But I was hoping to use the `action` column options instead. Unfortunately it's not possible to use a closure  for the `label` option, maybe this would be an improvement for future releases? Or am I missing something else here?

**Comment by Seb33300** [comment]
You are right, it is not possible since action do not accept closure for action label: 
https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/columns.md#action-options

You can send a pull request if you need this feature and I will check it.

**Comment by IT-Talents** [comment]
Ok, I'll look into that, thanks for your help.
