### ISSUE TITLE
Concat data

### ISSUE THREAD

**Issue by Shushu075** [stwe/DatatablesBundle#775]
Hi!
Can i concat many data in one column?
I have a adress table with streetNumber column, streetName column ...
Example: 
`->add('fulladress', Column::class, array(`
                `'title' => 'Adress',`
                 `'data' => 'streetNumber streetName streetCity'`
               ` ))`
Thanks.

**Comment by Seb33300** [comment]
You can use custom DQL like provided in the documentation:
``` php
$this->columnBuilder
    ->add('full_name', Column::class, array(
        'title' => 'Full name',
        'dql' => "CONCAT(user.firstname, ' ', user.lastname)",
        'type_of_field' => 'string',
        'searchable' => true,
        'orderable' => true,
    ))
;
```
