### ISSUE TITLE
Installion on Symfony 4 fails

### ISSUE THREAD

**Issue by proualexandre** [stwe/DatatablesBundle#777]
When installing the bundle in Symfony 4, I obtain this error  : The service "sg_datatables.factory" has a dependency on a non-existent service "security.authorization_checker".

**Comment by CharlyPoppins** [comment]
I just installed the bundle and had not problems.

Try ```composer require symfony/security-bundle```

**Comment by proualexandre** [comment]
Thanks for you answer. But unfortnatly this is not the solution, the symfony/security-bundle was already installed in my project when the issue occured. Does the DatablesBundle require specific configuration to work on symfony 4 ?

**Comment by CharlyPoppins** [comment]
Ok that's strange, check if the bundle is enable in config/bundles.php
```Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],```

Also, can you run execute :```rm -rf vendor
composer update```

And if it still don't work share your **composer.json**, so I can compare with mine.

Service **security.authorization_checker** is supposed to be defined there :
```vendor/symfony/security-bundle/Resources/config/security.xml```

**Comment by proualexandre** [comment]
Thanks ! Executing : `rm -rf vendor composer update` resolves my issue.

**Comment by DylanDelobel** [comment]
Got this issue today, I would also add `symfony/translation` is required

Maybe add them on the README?
