### ISSUE TITLE
Setting the entity alias in the DatatableQueryBuilder

### ISSUE THREAD

**Issue by IT-Talents** [stwe/DatatablesBundle#778]
It would be nice if there was any way overriding the entity alias (currently defined by the method `getEntityShortName`). Sometimes it's necessary to manipulate the QueryBuilder like explained in the [docs](https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/query.md#1-customize-the-doctrine-query), but what if that is done using methods from a service which uses another alias?

Additionally in my special case the entity is named `Member`. The problem here seems to be, that `MEMBER` is a reserved keyword of DQL (not SQL, which is already checked in the method `getEntityShortName`), for an example look [here](https://stackoverflow.com/questions/25190810/doctrine-expected-lexert-member-got). This leads to syntax errors in the DQL query.

I came up with a quick solution by adding a method to the `DatatableQueryBuilder`:

```php
public function setEntityShortName($entityShortName)
{
    $this->entityShortName = $entityShortName;
    
    // reset qb and reinitialize columns
    $this->qb = $this->em->createQueryBuilder()->from($this->entityName, $this->entityShortName);
    $this->initColumnArrays();

    return $this;
}

private function initColumnArrays()
{
    $this->selectColumns = array();
    $this->searchColumns = array();
    $this->orderColumns = array();
    $this->joins = array();

    foreach ($this->columns as $key => $column) {
    ....
}
```

Use this method to override the alias in the controller:

```php
$datatableQb = $responseService->getDatatableQueryBuilder();
$datatableQb->setEntityShortName('m');
````

What do you think?

**Comment by Seb33300** [comment]
Reserved words are normally catched by this pull request: https://github.com/stwe/DatatablesBundle/commit/dc0e41d40bfe21fe193dcc530d32b01b9c510aa2

Are you using the latest version?

**Comment by IT-Talents** [comment]
This catches only database platform specific reserved words, but unfortunately not DQL keywords like `MEMBER`.

**Comment by IT-Talents** [comment]
As far as i know there is currently no way to get DQL's reserved keywords programmatically like done in the PR you mentioned. But anyway I think it would be nice to be able to specify the QueryBuilder alias in the controller.

**Comment by roxid** [comment]
Note: this issue is still active, the account was just transformed into an organization account. I'm managing the account.

**Comment by stwe** [comment]
https://www.periscopedata.com/blog/better-sql-schema
