### ISSUE TITLE
Adding data to datatable ajax data

### ISSUE THREAD

**Issue by IT-Talents** [stwe/DatatablesBundle#780]
How to add custom data to the datatable ajax request on client-side? I know I can set the ajax data in my datatable class, but I have to add form data to the the ajax request. Can I use one of the callbacks to achieve this?

**Comment by roxid** [comment]
Note: this issue is still active, the account was just transformed into an organization account.

**Comment by roxid** [comment]
This can be achieved using the `pre_xhr` event.
