### ISSUE TITLE
Personnalisation / CSS

### ISSUE THREAD

**Issue by Shushu075** [stwe/DatatablesBundle#785]
Bonjour,

Je souhaiterai personnaliser le datatable, je sais qu'il y a bootstrap mais si je souhaite aussi inclure ma propre page style.css comment faire?

Et comment puis-je limiter le nombre de ligne à afficher dans les colonnes?

Merci.

**Comment by Seb33300** [comment]
Salut,

Tu peux ajouter ton propre fichier CSS sur ton site comme n'importe quel autre fichier CSS (http://symfony.com/doc/current/best_practices/web-assets.html). 
Il n'y a rien de spécifique à ce bundle à ce sujet.

Sinon, je ne suis pas certain de comprendre ce que tu entends par 
> limiter le nombre de ligne à afficher dans les colonnes

Pour limiter le nombre de ligne d'un datatable, tu as l'option `page_length`
https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/options.md

**Comment by Shushu075** [comment]
Salut!

Merci de prendre le temps de me répondre!

Parce que j'ai essayé de changer le style du datatable avec mon fichier CSS que j'ai intégré comme d'habitude dans Symfony mais ça n'a rien changé... et il est bien lu parce que le style s'applique bien au reste de la page (tout ce qui n'est pas du datatable).

J'ai vu le page_length mais ce que je veux faire c'est limiter le nombre de ligne d'un texte dans une ligne du datatable.  J'ai un texte qui fait 100 lignes mais je veux que dans la ligne du datatable il n'y en a que 50 qui s'affichent.

J'ai donc essayé de changer le height de la ligne du datatable avec le CSS mais ça n'a pas fonctionné....

**Comment by Seb33300** [comment]
Le Datatable utilise l'élément HTML `<table>`.

Il n'est pas possible de limiter directement la taille d'une ligne d'un <table> avec du css.
Car la hauteur minimum d'une ligne d'un <table> sera toujours la taille nécessaire pour afficher son contenu. Voir : https://stackoverflow.com/questions/13667941/how-to-set-maximum-height-for-table-cell

**Comment by Shushu075** [comment]
Oui, j'ai bien vu que le Datatable utilise l'élément HTML `<table>` et qu'effectivement cela affiche tout le contenu.

Mais je pensais qu'il y avait peut-être une possibilité de le faire en passant par le `public function getLineFormatter()` mais du coup je pense que c'est pas possible, je vais donc ajouter une colonne `text_trunc` dans la BDD. Merci!!!

J'ai encore une autre question, je souhaite faire un `CONCAT` mais sur plusieurs données c'est possible?

J'ai fait ceci :

```
->add('full_participant', Column::class, array(
                'title' => 'Participant',
                'dql' => "CONCAT(e_part.civility,' ',e_part.nom,' ',e_part.prenom)",
                'type_of_field' => 'string',
                'searchable' => true,
                'orderable' => true,
            ))
            ->add('e_part.id', Column::class, array(
                'title' => 'E_part Id',
                'data' => 'e_part[, ].id',
                'visible' => false
                ))
            ->add('e_part.civility', Column::class, array(
                'title' => 'E_part Civility',
                'data' => 'e_part[, ].civility',
                'visible' => false
                ))
            ->add('e_part.nom', Column::class, array(
                'title' => 'E_part Nom',
                'data' => 'e_part[, ].nom',
                'visible' => false
                ))
            ->add('e_part.prenom', Column::class, array(
                'title' => 'E_part Prenom',
                'data' => 'e_part[, ].prenom',
                'visible' => false
                ))
```
Mais ça ne m'affiche qu'un participant alors que j'en ai 3.

J'ai ensuite essayé ça : 

 ```
public function getLineFormatter()
    {
        $formatter = function($row) {
            $row['test'] = 'Participants  ' . $row['e_part']['nom'] . $row['e_part']['prenom'];

            return $row;
        };

        return $formatter;
    }
```
```
->add('test', VirtualColumn::class, array(
                'title' => 'Test virtual',
                'searchable' => true,
                'orderable' => true,
                'order_column' => 'e_part.nom',
                'search_column' => 'e_part.nom',
            ))
```

Et ça ne fonctionne pas non plus mais j'ai surement pas compris comment utiliser le `getLineFormatter()`
