### ISSUE TITLE
MultiselectColumn DatatableResponse::setDatatable(): The Column with the index 1 is on a not allowed position.

### ISSUE THREAD

**Issue by grekpg** [stwe/DatatablesBundle#788]
I have datatable with MultiselectColumn as first row, (when i move to second have same result) 

`DatatableResponse::setDatatable(): The Column with the index 2 is on a not allowed position.
`

**Comment by grekpg** [comment]
Sorry my mistake

**Comment by MarianoSeif** [comment]
Hi!. I have the same problem. How you solved it?
