### ISSUE TITLE
Select2 filter hides entries

### ISSUE THREAD

**Issue by felix-goecking** [stwe/DatatablesBundle#789]
Hi, I'm using version 1.0.4 of your library and having difficulties with the select2 filter. The required libraries are added (Select2 4.0.3) and the filter control gets replaced by the select2 control. I get no javascript errors, but the filter list / dropdown is always empty. I haven't entered anything in the filter text but I only get "No results found". 
![grafik](https://user-images.githubusercontent.com/6575159/40878348-20a0af5e-6690-11e8-8b24-20c0b80d4668.png)

However I inspected the code and the "original" select box contains my list items. 
![grafik](https://user-images.githubusercontent.com/6575159/40878377-7fa6dab4-6690-11e8-82c5-a0bc0a554b84.png)

I had the same issue (and one other) with the dev-master, so I got to version 1.0.4. I'm using Symfony 4.1, but had the same with Symfony 4.0.

Best regards
Felix

**Comment by lemorragia** [comment]
Same problem here...the select2 is initialized with no errors, and the original select does have choices in it, but the select2 element is empty ("No results found"), i'm on symfony 4.3, select2 4.0.8, and sgDatatablesBundle 1.1.4

**Comment by AMuravev** [comment]
I had the same problem. This was due to the fact that in my code there was already initialization of other selects2 like "$('.select2').select2()". I just renamed the class and it worked for me. Seems class '.select2' ' apply to span in table. Hope it makes sense.
