### ISSUE TITLE
Use DateRangeFilter in DQL? Posible?

### ISSUE THREAD

**Issue by CondonesMix** [stwe/DatatablesBundle#790]
Hi,

I try to make a custom column with subquery but I like to view the count of the column only with the data-range, not total.

¿It's posible?

I like somethink like:
        'dql' => '(SELECT COUNT({p}) FROM MyBundle:Post {p} WHERE {p}.user = user AND {p}.date BETWEEN ________ AND ________  )',

Where _______ AND _______  is the range used in daterangefilter

Thanks to all for the help and salutations from Barcelona

**Comment by CondonesMix** [comment]
* in DatatableQueryBuilder.php we see:

   public function getBuiltQb()
   ```
 {
        $qb = clone $this->qb;

        $this->setSelectFrom($qb);
        $this->setJoins($qb);
        $this->setWhere($qb);
        $this->setOrderBy($qb);
        $this->setLimit($qb);

        return $qb;
    }
```

Is posible to add maybe setGroupBy ?

what is your suggestion to use groupby in datatables

**Comment by CondonesMix** [comment]
What happens is that I have a column with the COUNT of each of the articles per line and I would like the COUNT of the total but the filtered date to be shown

So that it is understood better. The table is a list of invoice lines. When grouped by reference, I have a list of products and I want to show in the "count / sum", how many times it has been sold but with the date filter

**Comment by roxid** [comment]
Ok, I got it. I don't have an idea of how to add the date range values into the column's dql in a clean way (in your datatable class). But you could try adding a select containing a subquery to the QueryBuilder instance in your controller and return the resulting count as an additional column from the database query. Something like:

```
...
$qb = $datatableQueryBuilder->getQb();
$subQb = // build the subquery, you should be able to get the date range values from the request data
$qb->addSelect('(' . $subQb->getQuery()->getDQL() . ') AS HIDDEN filtered_count');
...
```

I expect `filtered_count` to be available in the `$line` variable in the `getLineFormatter()` method after adding it as a column to your datatable class. But to be honest I'm not 100% sure, you need to try.

**Comment by CondonesMix** [comment]
Thank you! although it is not the cleanest way. If it works, I'm already very grateful. 

This functionality is key for us, since we use this bundle for our accounting. 

I appreciate the time you have given us and I will try it this weekend. Thanks!
