### ISSUE TITLE
Use Group By in custom DQL possible?

### ISSUE THREAD

**Issue by CondonesMix** [stwe/DatatablesBundle#791]
It's possible custom the call to db in controller to use Group By?

I see , we can use andWhere in our controller (generated by console)

```
            /** @var QueryBuilder $qb */
            $qb = $datatableQueryBuilder->getQb();
            $qb->andWhere('lineafacturacli.referencia = :referencia');
            $qb->setParameter('referencia', 'promocarrito-lube');
```

But we like to use somthing like this

`           $qb->andGroupBy('lineafacturacli.referencia'); 
`
¿It's possible?

.... We search in DatatableQueryBuilder.php but I see this:

```
public function getBuiltQb()
    {
        $qb = clone $this->qb;

        $this->setSelectFrom($qb);
        $this->setJoins($qb);
        $this->setWhere($qb);
        $this->setOrderBy($qb);
        $this->setLimit($qb);

        return $qb;
    }

```
but nothing mention to GroupBy function

It's possible to make it?

**Comment by roxid** [comment]
Did you try just adding `groupBy` to the query builder in your controller? To be honest, I'm not sure this works.

```php
/** @var QueryBuilder $qb */
$qb = $datatableQueryBuilder->getQb();
$qb->andWhere('lineafacturacli.referencia = :referencia');
$qb->setParameter('referencia', 'promocarrito-lube');
$qb->groupBy('lineafacturacli.referencia');
```

**Comment by CondonesMix** [comment]
I tried, but in the DatatableQueryBuilder.php don't have a method to group, only for select, join, where, order and limit.

Group it's not but I think its important add a method to use GroupBy

**Comment by roxid** [comment]
`$datatableQueryBuilder->getQb();` returns the `Doctrine\ORM\QueryBuilder` instance, which has the method [`orderBy`](https://www.doctrine-project.org/api/orm/latest/Doctrine/ORM/QueryBuilder.html#method_orderBy).

**Comment by radhanpuraankit** [comment]
@stephanvierkant @roxid 
I have tried using getQb and groupBy but it's breaking pagination. Please let me know your suggestion.
