### ISSUE TITLE
Conditionnal action

### ISSUE THREAD

**Issue by mathiastm** [stwe/DatatablesBundle#794]
Hi, is that possible to add an action with conditions / row ?

Exemple: 
if my first row is enabled  i want to show a "disable button"
if my second row is disable  i want to show a "enable button"

**Comment by Seb33300** [comment]
You have to use the `render_if` option: https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/columns.md#6-action-column

**Comment by mathiastm** [comment]
thx !!!
