### ISSUE TITLE
[Semantical Error] On dql column search

### ISSUE THREAD

**Issue by mathiastm** [stwe/DatatablesBundle#796]
Hi,
I have a dql column like this : 
`

            $qb
                ->select('my_entity.name')
                ->from('MyBundle:MyEntity', 'my_entity')
                ->setMaxResults(1);

            $this->columnBuilder
                ->add($alias, Column::class, array(
                    'title' => 'test_dql',
                    'dql' => '(' . $qb->getDQL() . ')',
                ));
`
My column is shown but when i search for this column, i have got an ajax error.

[Semantical Error] 'my_entity'' is already defined.

and indeed it is already declared . In the search dql, 'my_entity'' is declared twice. one in SELECT and twice in WHERE clause.

Did someone can help me please ?

**Comment by Seb33300** [comment]
As mentioned in the documentation:

> If you want to use a subquery, please put subquery between parentheses and **subquery aliases between braces**.

I am not sure Doctrine will accept it but you can try:
``` php
$qb->select('my_entity.name')->from('MyBundle:MyEntity', '{my_entity}')->setMaxResults(1);
```

Otherwise:
``` php
'dql' => '(' . str_replace('my_entity', '{my_entity}', $qb->getDQL()) . ')',
```

**Comment by mathiastm** [comment]
thanks a lot !

**Comment by konradja100** [comment]
Hi, i have a very similar problem, but with global filtering - while searching globally, and then filtering by some column I got this error:
![dat3](https://user-images.githubusercontent.com/28842587/42026576-bb72b32e-7ac7-11e8-8f79-a9906670f278.png)


I have custom dql for columns, and this is causing this problem, I've implemented described solution, but it won't work for me :/

```
 $qb
                ->select('SUM(sv.duration)')
                ->from('App:SiteVisit', 'sv')
                ->where('sv.lead = lead.id');


                ->add('lead.duration', Column::class, [
                    'searchable' => true,
                    'title' => $this->translator->trans('company.timeonpage'),
//                    'dql' => '(SELECT SUM({sv}.duration) FROM App:SiteVisit {sv} WHERE {sv}.lead = lead.id)',
                    'dql' => '(' . str_replace('sv', '{sv}', $qb->getDQL()) . ')',
                    'filter' => [TextFilter::class,
                        [
                            'cancel_button' => true,
                        ]
                    ]])
```

Any ideas what is wrong here?

**Comment by mathiastm** [comment]
but I think your problem is not here. I don't see anywhere "sv_search" in your code...

**Comment by konradja100** [comment]
It didn't change anything :/

**Comment by konradja100** [comment]
sv_search is created somewhere "inside" datatable, i didn't create that value

**Comment by konradja100** [comment]
Any ideas how to access oryginal query created by bundle?

**Comment by mathiastm** [comment]
You can scroll down to see output dql on the error page ?
