### ISSUE TITLE
Datatable ajax additionnal parameters

### ISSUE THREAD

**Issue by mathiastm** [stwe/DatatablesBundle#797]
hi, I would like to know if that is possible to add additionals parameters to the ajax request ?
Like datatables does here : [Custom vars](https://datatables.net/examples/server_side/custom_vars.html)

**Comment by Seb33300** [comment]
You can add options you want in `buildDatatable` parameters and than use them to generate your ajax url.

**Comment by mathiastm** [comment]
ok, first thank you for your quick reply.
i already saw that on the documentation but i would like to add those params dynamicaly. 
In my case I have this: 
![telechargement](https://user-images.githubusercontent.com/23093368/41651920-0ecd3432-7482-11e8-88dd-c17623932c17.png)
On click on Nested menu at left position i want to add parameters to datatable ajax request and then i would be able to add a custom where clause to the datatablequerybuilder.

**Comment by mathiastm** [comment]
Maybe it's possible to access to the js Datatable object ? @Seb33300

**Comment by roxid** [comment]
Use the pre_xhr [event](https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/events.md) to add data to the ajax requests.

**Comment by mathiastm** [comment]
Thank you @roxid ! you saved my life ! ;)
