### ISSUE TITLE
Datatable name hash

### ISSUE THREAD

**Issue by konradja100** [stwe/DatatablesBundle#802]
Hi, i have some issue, when I refreash the page, datatable name is changing each time - so I can't "rebuild" filtering from localStorage

![h1](https://user-images.githubusercontent.com/28842587/42268291-6c8d009e-7f7b-11e8-9eed-7ccf536d2dd2.png)
![h2](https://user-images.githubusercontent.com/28842587/42268295-6e042e98-7f7b-11e8-9a3f-4d9500b9f417.png)
![h3](https://user-images.githubusercontent.com/28842587/42268298-6fecd20a-7f7b-11e8-9357-95acce883593.png)

And in the localStorage it has one name (also hashed) - this value is not changing. 

![h4](https://user-images.githubusercontent.com/28842587/42268380-9c1be9ce-7f7b-11e8-96a5-607496715786.png)

I didn't have this issue before, App is in symfony 4.1, and  I'm on dev-master branch (DatatablesBundle).

Any idea why datatable is adding this weird hash to the name?

**Comment by konradja100** [comment]
Update - error did't occurred at 1.0.4 branch, was there any changes at naming tables?

**Comment by Seb33300** [comment]
A unique name have been added in order to be able to add the same datatable multiple times on the same page.

**Comment by kurkowskik** [comment]
@Seb33300 but it breaks state_save feature. Maybe better way to do it is to add optional datatable name parameter in DatatableFactory create method and pass it to datatable constructor?

**Comment by Seb33300** [comment]
I just push a change where Datatables names are now incremental id if multiple datatables with same name on the same page.

This should fix your issue.
