### ISSUE TITLE
Rows are not rendered

### ISSUE THREAD

**Issue by ioanandrei** [stwe/DatatablesBundle#805]
I just installed the bundle, i followed the installation steps and the result it's not the expected.
Insteead of a nice table i have a row with the headers, but no other rows.
Anyone with same problem?
What am i doing wrong?

AppKernel:

`$bundles = [
         ...
          new FOS\JsRoutingBundle\FOSJsRoutingBundle(),
            new Sg\DatatablesBundle\SgDatatablesBundle()
]`

In my controller:

```
public function indexAction(Request $request)
    {
        $isAjax = $request->isXmlHttpRequest();
        $datatable = $this->get('sg_datatables.factory')->create(BillDatatable::class);
        $datatable->buildDatatable();

        if($isAjax)
        {
            $responseService = $this->get('sg_datatables.response');
            $responseService->setDatatable($datatable);
            $responseService->getDatatableQueryBuilder();

            return $responseService->getResponse();
        }


        $em = $this->getDoctrine()->getManager();
        $bills = $em->getRepository('AppBundle:Bill')->getAllBils();
        $title = 'Orders';

        return $this->render('AppBundle:Bill:index.html.twig', array(
            'title' => $title,
            'bills' => $bills,
            'datatable' => $datatable
        ));
    }
```

In twig:

`{{ sg_datatables_render(datatable) }}`

I generated the controller with the name BillDatatable and everything seems to be ok.
Any ideea what's happening?

Edit:
Sample:

![image](https://user-images.githubusercontent.com/34555575/42560653-cccd53da-84ff-11e8-9ef2-22e8710f70b7.png)

**Comment by Eloar** [comment]
@ioanandrei check ajax request. Data is downloaded separately by Ajax request and won't be rendered if data retrieve fails.

**Comment by ioanandrei** [comment]
Where should i check this?
Sorry, but i'm pretty new in symfony :-s
@Eloar

**Comment by ioanandrei** [comment]
In inspector->network everything it's ok
I don't have any 404 status or something similar.

**Comment by Eloar** [comment]
Use symfony profiler (turned in debug when using app_dev.php) and check Doctrine tab for query information. Maybe Your query is not returning any data.

**Comment by ioanandrei** [comment]
Ok
I will try
Can you give me your email address please?
I really need to figure this out and maybe you will not see the messages here
Or can we chat somehow here,on git?

**Comment by ioanandrei** [comment]
I don't have any queries in symfony profiler
0 queries, 0 different statements, 0 invalid entities

**Comment by ioanandrei** [comment]
I see that in query i have this 
```
WHERE 
  t0.id = ? 
```
it should not be a where if it must to select all the rows from database,right?

**Comment by Dr-Ash** [comment]
Please provide BillDatatable.php and a full screenshot of profiler

**Comment by ioanandrei** [comment]
BillDataTable:

`<?php

namespace AppBundle\Datatables;

use Sg\DatatablesBundle\Datatable\AbstractDatatable;
use Sg\DatatablesBundle\Datatable\Style;
use Sg\DatatablesBundle\Datatable\Column\Column;
use Sg\DatatablesBundle\Datatable\Column\BooleanColumn;
use Sg\DatatablesBundle\Datatable\Column\ActionColumn;
use Sg\DatatablesBundle\Datatable\Column\MultiselectColumn;
use Sg\DatatablesBundle\Datatable\Column\VirtualColumn;
use Sg\DatatablesBundle\Datatable\Column\DateTimeColumn;
use Sg\DatatablesBundle\Datatable\Column\ImageColumn;
use Sg\DatatablesBundle\Datatable\Filter\TextFilter;
use Sg\DatatablesBundle\Datatable\Filter\NumberFilter;
use Sg\DatatablesBundle\Datatable\Filter\SelectFilter;
use Sg\DatatablesBundle\Datatable\Filter\DateRangeFilter;
use Sg\DatatablesBundle\Datatable\Editable\CombodateEditable;
use Sg\DatatablesBundle\Datatable\Editable\SelectEditable;
use Sg\DatatablesBundle\Datatable\Editable\TextareaEditable;
use Sg\DatatablesBundle\Datatable\Editable\TextEditable;

/**
 * Class BillDatatable
 *
 * @package AppBundle\Datatables
 */
class BillDatatable extends AbstractDatatable
{
    /**
     * {@inheritdoc}
     */
    public function buildDatatable(array $options = array())
    {
        $this->language->set(array(
            'cdn_language_by_locale' => true
            //'language' => 'de'
        ));

        $this->ajax->set(array(
        ));

        $this->options->set(array(
            'individual_filtering' => true,
            'individual_filtering_position' => 'head',
            'order_cells_top' => true,
        ));

        $this->features->set(array(
        ));

        $this->columnBuilder
            ->add('id', Column::class, array(
                'title' => 'Id',
                ))
            ->add('address', Column::class, array(
                'title' => 'Address',
                ))
            ->add('firstName', Column::class, array(
                'title' => 'FirstName',
                ))
            ->add('secondName', Column::class, array(
                'title' => 'SecondName',
                ))
            ->add('details', Column::class, array(
                'title' => 'Details',
                ))
            ->add('telephone', Column::class, array(
                'title' => 'Telephone',
                ))
            ->add('date', DateTimeColumn::class, array(
                'title' => 'Date',
                ))
            ->add('status', Column::class, array(
                'title' => 'Status',
                ))
            ->add('payMethod', Column::class, array(
                'title' => 'PayMethod',
                ))
            ->add('price', Column::class, array(
                'title' => 'Price',
                ))
            ->add('billItem.id', Column::class, array(
                'title' => 'BillItem Id',
                'data' => 'billItem[, ].id'
                ))
            ->add('billItem.quantity', Column::class, array(
                'title' => 'BillItem Quantity',
                'data' => 'billItem[, ].quantity'
                ))
            ->add('clientId.id', Column::class, array(
                'title' => 'ClientId Id',
                ))
            ->add('clientId.firstName', Column::class, array(
                'title' => 'ClientId FirstName',
                ))
            ->add('clientId.secondName', Column::class, array(
                'title' => 'ClientId SecondName',
                ))
            ->add('clientId.phoneNumber', Column::class, array(
                'title' => 'ClientId PhoneNumber',
                ))
            ->add('clientId.address', Column::class, array(
                'title' => 'ClientId Address',
                ))
            ->add(null, ActionColumn::class, array(
                'title' => $this->translator->trans('sg.datatables.actions.title'),
                'actions' => array(
                    array(
                        'route' => 'bill_show',
                        'route_parameters' => array(
                            'id' => 'id'
                        ),
                        'label' => $this->translator->trans('sg.datatables.actions.show'),
                        'icon' => 'glyphicon glyphicon-eye-open',
                        'attributes' => array(
                            'rel' => 'tooltip',
                            'title' => $this->translator->trans('sg.datatables.actions.show'),
                            'class' => 'btn btn-primary btn-xs',
                            'role' => 'button'
                        ),
                    ),
                    array(
                        'route' => 'bill_edit',
                        'route_parameters' => array(
                            'id' => 'id'
                        ),
                        'label' => $this->translator->trans('sg.datatables.actions.edit'),
                        'icon' => 'glyphicon glyphicon-edit',
                        'attributes' => array(
                            'rel' => 'tooltip',
                            'title' => $this->translator->trans('sg.datatables.actions.edit'),
                            'class' => 'btn btn-primary btn-xs',
                            'role' => 'button'
                        ),
                    )
                )
            ))
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getEntity()
    {
        return 'AppBundle\Entity\Bill';
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'bill_datatable';
    }
}
`

![image](https://user-images.githubusercontent.com/34555575/42568271-3adcad98-8515-11e8-8928-9f2b14e81bc9.png)

**Comment by Dr-Ash** [comment]
are you sure you have all required JS files included ? 
browser console shows nothing ?

**Comment by ioanandrei** [comment]
In console i have 2 errors(this is the moment i saw them,sry):

`blob:http://project/16cddd4b-6644-4043-98ce-2bbac83cf81a:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
orders:533 Uncaught ReferenceError: $ is not defined
    at orders:533`

At orders:533:

`<script type="text/javascript">

    $(document).ready(function () { ---THIS IS LINE 533

        var selector = "#sg-datatables-bill_datatable";
        var oTable;

        var defaults = {
        };

        var language = {
                        "language": {
            "url": "https://cdn.datatables.net/plug-ins/1.10.13/i18n/English.json"
        }
    
            };
+ a lot of code
`


My js cdns(i tooked them from documentation):
`<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment-with-locales.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/2.1.25/daterangepicker.min.js" charset="UTF-8"></script>
    <script src="https://cdn.datatables.net/v/bs/jszip-2.5.0/pdfmake-0.1.18/dt-1.10.12/b-1.2.2/b-colvis-1.2.2/b-flash-1.2.2/b-html5-1.2.2/b-print-1.2.2/fc-3.2.2/fh-3.1.2/r-2.1.0/datatables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.1/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
    <script src="https://cdn.rawgit.com/noelboss/featherlight/1.7.1/release/featherlight.min.js"></script>

    <script src="{{ asset('bundles/sgdatatables/js/pipeline.js') }}"></script>

    <script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
    <script src="{{ path('fos_js_routing_js', {'callback': 'fos.Router.setData'}) }}"></script>`

**Comment by Dr-Ash** [comment]
Remove the jQuery you included; then put this jQuery in head
<head>
....
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
...
</head>

**Comment by ioanandrei** [comment]
Same error

**Comment by ioanandrei** [comment]
After that, i get this error in console:

`ET http://project/app_dev.php/orders?draw=1&columns%5B0%5D%5Bdata%5D=id&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=address&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=firstName&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=secondName&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=details&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=telephone&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=date&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=status&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=payMethod&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=true&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B9%5D%5Bdata%5D=price&columns%5B9%5D%5Bname%5D=&columns%5B9%5D%5Bsearchable%5D=true&columns%5B9%5D%5Borderable%5D=true&columns%5B9%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B9%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B10%5D%5Bdata%5D=billItem%5B%2C%20%5D.id&columns%5B10%5D%5Bname%5D=&columns%5B10%5D%5Bsearchable%5D=true&columns%5B10%5D%5Borderable%5D=true&columns%5B10%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B10%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B11%5D%5Bdata%5D=billItem%5B%2C%20%5D.quantity&columns%5B11%5D%5Bname%5D=&columns%5B11%5D%5Bsearchable%5D=true&columns%5B11%5D%5Borderable%5D=true&columns%5B11%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B11%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B12%5D%5Bdata%5D=clientId.id&columns%5B12%5D%5Bname%5D=&columns%5B12%5D%5Bsearchable%5D=true&columns%5B12%5D%5Borderable%5D=true&columns%5B12%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B12%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B13%5D%5Bdata%5D=clientId.firstName&columns%5B13%5D%5Bname%5D=&columns%5B13%5D%5Bsearchable%5D=true&columns%5B13%5D%5Borderable%5D=true&columns%5B13%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B13%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B14%5D%5Bdata%5D=clientId.secondName&columns%5B14%5D%5Bname%5D=&columns%5B14%5D%5Bsearchable%5D=true&columns%5B14%5D%5Borderable%5D=true&columns%5B14%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B14%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B15%5D%5Bdata%5D=clientId.phoneNumber&columns%5B15%5D%5Bname%5D=&columns%5B15%5D%5Bsearchable%5D=true&columns%5B15%5D%5Borderable%5D=true&columns%5B15%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B15%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B16%5D%5Bdata%5D=clientId.address&columns%5B16%5D%5Bname%5D=&columns%5B16%5D%5Bsearchable%5D=true&columns%5B16%5D%5Borderable%5D=true&columns%5B16%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B16%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B17%5D%5Bdata%5D=17&columns%5B17%5D%5Bname%5D=&columns%5B17%5D%5Bsearchable%5D=false&columns%5B17%5D%5Borderable%5D=false&columns%5B17%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B17%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1531310303234 500 (Internal Server Error)`

But a "show" button and a search field appeard.

**Comment by ioanandrei** [comment]
I also have this:

![image](https://user-images.githubusercontent.com/34555575/42570033-3e7c8fe4-851b-11e8-8b5c-7330858a3ab7.png)

**Comment by Dr-Ash** [comment]
Man your js files are all messed up; look you have included bootstrap twice; review them.

Now it sends the Ajax request, Debug the 500 error

**Comment by ioanandrei** [comment]
I don't know why this is happening beacuse that route was working untill now.

![image](https://user-images.githubusercontent.com/34555575/42570371-5a634314-851c-11e8-942a-ec5097c88996.png)

**Comment by ioanandrei** [comment]
So...i don't really understand what's happening, but it's somekind of working

The bundle requires a bill_show and a bill_edit routes.Beacuse i do not have a bill_edit route(bcs i don't need that), i did a route with name bill_edit,but with the same path and controller as the bill_show.

How can i do this better way?Beacuse this is not...

**Comment by Dr-Ash** [comment]
...in your BillDatatable.php
...in ->add(null, ActionColumn::class, array(
remove the show and edit buttons or the whole ActionColumn

**Comment by ioanandrei** [comment]
I figued it out
I have 2 more questions...I'm really,really sorry

1.Can i use twig filters in this table? If yes, how?
2.In this moment, the table it's not looking very nice, do i need to do something to improve it or this is how it should look?(print screen down)

![image](https://user-images.githubusercontent.com/34555575/42572000-506c5166-8521-11e8-8a14-8cf41f60fd5f.png)

**Comment by Dr-Ash** [comment]
For styling you can choose from the predefined classes or put your own, read the docs please
```
$this->options->set(array(
            'individual_filtering' => true,
            'individual_filtering_position' => 'head',
            'order_cells_top' => true,
            'classes' => Style::BOOTSTRAP_4_STYLE,
        ));
```

You can format table data the way you want with line formatter

**Comment by ioanandrei** [comment]
Ok
Thank you very much and sorry again
