### ISSUE TITLE
Bug with format on Filter DateRangePicker

### ISSUE THREAD

**Issue by Quovandius** [stwe/DatatablesBundle#810]
Hi,

i have notice the same bug of : https://github.com/stwe/DatatablesBundle/issues/722

One solution is add a format date option on filter, like the option filter on DatetimeColumn.

Temporary solution is to update file : 
`Sg\DatatablesBundle\Datatable\Filter\DateRangeFilter`

and update these lines like : 
  ```
    $dateStart = DateTime::createFromFormat('d/m/Y', $_dateStart);
       $dateEnd = DateTime::createFromFormat('d/m/Y', $_dateEnd);
//        $dateStart = new DateTime($_dateStart);
//        $dateEnd = new DateTime($_dateEnd);

```

Is it possible to update bundle for solve this issue ?
Its not a good pratice to update vendor as i said.
Thanks

**Comment by RefreshMyMind** [comment]
Yes with FR locale, this filter is not working correctly.
To resolve the problem  I have override the script for all of the applied date input filters
   `$("#sg-datatables-banque_datatable-head-filter-3,#sg-datatables-ecriture_datatable-head-filter-3,#sg-datatables-banque_datatable-foot-filter-3,` #sg-datatables-ecriture_datatable-foot-filter-3").daterangepicker({
                autoUpdateInput: false,
                locale: {
                    format: "YYYY-MM-DD",
                    applyLabel: "Appliquer",
                    cancelLabel: "Annuler",
                    daysOfWeek: moment.weekdaysMin(),
                    monthNames: moment.monthsShort(),
                    firstDay: moment.localeData().firstDayOfWeek()
                }
            }).on('cancel.daterangepicker', function (ev, picker) {
                $(this).val('');
                $(this).change();
            })
                .on('apply.daterangepicker', function (ev, picker) {
                    $(this).val(picker.startDate.format("YYYY-MM-DD") + ' - ' + picker.endDate.format("YYYY-MM-DD"));
                    $(this).change();
                });
