### ISSUE TITLE
Last associated element in DT

### ISSUE THREAD

**Issue by Eloar** [stwe/DatatablesBundle#813]
Is there a way to show field from last associated element in row? `dql` option allows to show agregate info about associative table, but I would like to show info from single associated element. Something like showing last comment content on posts DataTable

**Comment by Seb33300** [comment]
You can use DQL to do a subquery to get the last comment.

**Comment by Eloar** [comment]
The problem is such subquery returns more than one element in most cases. As far as I know there is only way to limit result to 1 on QueryBuilder, not Query itself

**Comment by Seb33300** [comment]
A subquery will return lines you are requesting. If you request for one line, it will return only one line.
