### ISSUE TITLE
Sensio Generator Bundle no longer available on Symfony 4

### ISSUE THREAD

**Issue by Zoopme** [stwe/DatatablesBundle#814]
Hi,

I am currently upgrading to Symfony 4 and removing non supported bundles such as sensio/generator-bundle. However, I now get a fatal error: 

> Class 'Sensio\Bundle\GeneratorBundle\Command\GenerateDoctrineCommand' not found in vendor\sg\datatablesbundle\Command\CreateDatatableCommand.php on line 31

Thanks for you help.

**Comment by drboboev** [comment]
i got same error. anybody knows when this will be fixed.

thanks.

**Comment by ProfM2** [comment]
Straight from Packagist ([https://packagist.org/packages/sensio/generator-bundle](https://packagist.org/packages/sensio/generator-bundle))

> WARNING: This bundle does not support Symfony 4. It also does not support the new bundle-less directory structure as created by Symfony Flex. Use the Maker bundle instead.

**Comment by AlexandraDeMatos** [comment]
Hi ! 
I know someone else tell that but I can't find response. 
I'm on Symfony 4.1 and I can't use Datatable bundle 

#> php bin/console sg:datatable:generate AppBundle:Post
  There are no commands defined in the "sg:datatable" namespace.
  Did you mean this?
      doctrine:database

Thank's by advance

**Comment by mpeshehonov** [comment]
@Seb33300 plz check and merge.

**Comment by Seb33300** [comment]
@mpeshehonov plz provide a pull request

**Comment by stwe** [comment]
wontfix
