### ISSUE TITLE
Get id of result in rowCallback

### ISSUE THREAD

**Issue by rvmourik** [stwe/DatatablesBundle#817]
Hi,

Is there a way to get the id of and result in the rowCallback.
I want to make the row clickable and need the id for that, or is there another way to achieve this?

Thanks in advance.

**Comment by agatagolebiowska** [comment]
You can make column
`                ->add('id', Column::class, [
                    'searchable' => false,
                    'visible' => false
                ])`

and then in callback 
`function rowCallback(nRow, aData) {
let id = aData.id;
}`
