### ISSUE TITLE
Global search with national characters in datetime column causes error

### ISSUE THREAD

**Issue by samius** [stwe/DatatablesBundle#818]
If there are datetime columns that are searchable, it causes that global search operates with these columns.
When some national characters are used (e.g. "ř" ), there is a problem with missing collation in datetime columns:

SQL General error: 1271 Illegal mix of collations for operation 'like'

**Comment by konradja100** [comment]
I can confirm that solution presented by @samius is working properly, but it's not elegant and option to disable columns from global search would be great.

**Comment by konradja100** [comment]
Also worth to mention, this solution is not working properly for one polish special char "ł".So we're hoping for some support in this case with default options.

**Comment by konradja100** [comment]
Any updates on this issue?

**Comment by stephanvierkant** [comment]
No, otherwise it would have been posted here, I presume.

Feel free to open a PR!
