### ISSUE TITLE
Can I use custom query repository as data of a column?

### ISSUE THREAD

**Issue by NicolaPez** [stwe/DatatablesBundle#821]
I'm implementing DataTables in my project. All works fine, but one of my column is a particularly difficult query under a metod of my EntityRepository. The query is not implemented in DQL. I can use this query as a data of a colum in my Datatables?

**Comment by Seb33300** [comment]
If your repository return a query builder, you can get the DQL query form it and use it like provided here: https://github.com/stwe/DatatablesBundle/issues/796

**Comment by roxid** [comment]
You may be able to implement a custom formatter (for reference see `Sg\DatatablesBundle\Response\DatatableFormatter`) to add the results of your query to the the datatable output. But I guess it won't be easy.

Then use it in your controller like this
```
// ...
$datatable->buildDatatable();

/** @var \Sg\DatatablesBundle\Response\DatatableResponse $responseService */
$responseService = $this->get('sg_datatables.response');
$responseService->setDatatable($datatable);

/** @var \Sg\DatatablesBundle\Response\DatatableQueryBuilder $datatableQb */
$datatableQb = $responseService->getDatatableQueryBuilder();

$paginator = new Paginator($datatableQb->execute(), true);
$paginator->setUseOutputWalkers(false);

$formatter = new CustomDatatableFormatter();
$formatter->runFormatter($paginator, $datatable);

$data = $formatter->getOutput()['data'];
// return the serialized data ...
```

**Comment by NicolaPez** [comment]
For now I choose to rewrite my query in dql, think is the best way.
