### ISSUE TITLE
ImageColumn not work with NULL

### ISSUE THREAD

**Issue by NicolaPez** [stwe/DatatablesBundle#822]
I'm using this option for manage a cover image
```
->add('multimediaFile.url', ImageColumn::class, array(
                'title' => 'cover',
                'default_content' => 'undefined Cover',
                'searchable' => false,
                'imagine_filter' => 'thumbnail_50_x_50',
                'imagine_filter_enlarged' => 'thumbnail_250_x_250',
                'relative_path' => '',
                'orderable' => false,
                'holder_url' => 'example.com',
                'enlarge' => true,
            ))
```

but I have this error when the cover is set to NULL:

> PropertyAccessor requires a graph of objects or arrays to operate on, but it found type "NULL" while trying to traverse path "[multimediaCover][url]" at property "url".

**Comment by NicolaPez** [comment]
still unresolved.  How use ImageColumn with NULL value?

**Comment by NicolaPez** [comment]
I found this, seems the same problem:

https://github.com/stwe/DatatablesBundle/issues/643

This bundle have some problem with nullable associations? There's a way to fix it?

**Comment by stephanvierkant** [comment]
Thanks for point out this issue and thanks to @Asia321 as well. I've recently joined this library as a maintainer, but I don't have enough time to resolve all issues.

Feel free to create a Pull Request with a fix. Or provide a testcase to reproduce the problem, so I can look into it.

**Comment by stwe** [comment]
wontfix
