### ISSUE TITLE
Encore/Webpack initialization

### ISSUE THREAD

**Issue by svantetic** [stwe/DatatablesBundle#823]
Hello. I'm trying to make Datatables work with Encore and Webpack and I have a hard time with initializing datatables in frontend.

I've added jQuery to Encore pipe with
``` javascript
.autoProvideVariables({
        $: 'jquery',
        jQuery: 'jquery',
```

and included initialization (as here https://datatables.net/manual/installation#NPM)  of datatables with
``` javascript
const dt = require('datatables.net');
```

before adding that file to Encore's `.addEntry`.
After opening page with datatable there is an error in console
```
Cannot read property 'isDataTable' of undefined`
```
pointing to the line in injected JS between `<script>` in rendered `html.twig` template
`if (!$.fn.dataTable.isDataTable(selector))`

Other scripts using jQuery are working as expected, so my guess is either I'm doing something wrong with initializing datatables or there is no support for Encore at the moment. 
I couldn't find any information about webpack configuration for this bundle.

**Comment by Seb33300** [comment]
This is what I did to make Datatable working with Webpack Encore:
``` javascript
var dt = require('datatables.net');
window.$.DataTable = dt;
```

**Comment by Seb33300** [comment]
Can you also confirm that your `<script>` is placed after the Datatable library `<script>` tag?

**Comment by svantetic** [comment]
@Seb33300 I've tried your solution and unfortunately it still doesn't work. However, it seems that somehow`$` object that is used by datatables in between rendered template `<script>` tags is a different object than $ used in initialization in my example above, so perhaps somethings is overwriting `$` with new jQuery declaration. So it might be a problem with application's code, not with DatatableBundle.

**Comment by svantetic** [comment]
Ok, it seems that https://github.com/symfony/webpack-encore/issues/32#issuecomment-309646363 solved the problem with jQuery overwriting. Basically `autoProvidejQuery` or setting `autoProvideVariables` overwrites previous manual $/jQuery extensions.
