### ISSUE TITLE
Searching in column with relation not working

### ISSUE THREAD

**Issue by golebiowska** [stwe/DatatablesBundle#826]
Hi. What I want to do is to simply add a searchable column with structure like this
`                ->add('company.country.name', Column::class, [
                    'title' => $this->translator->trans('company.country'),
                    'searchable' => true,
                    'filter' => [TextFilter::class,
                        [
                            'cancel_button' => true,
                        ]
                    ]])`

in Person::class datatable
person entity -> company entity -> country entity -> country name field

it displays a name properly but I cannot search in that column because of this error
`[Semantical Error] line 0, col 102 near '.country company_country': Error: Identification Variable company used in join path expression but was not defined before.`

What does this mean 'Identification Variable company was not defined before'? Column above I have company.name and it works fine. 
How can I make this column searchable?

**Comment by Seb33300** [comment]
I think you original example will work if you add `company.id` as invisible column.
