### ISSUE TITLE
Multi filter does not work

### ISSUE THREAD

**Issue by samius** [stwe/DatatablesBundle#829]
Last version 1.0.4:
I am trying to search in smallint column with Select2 filter with multiple choices enabled, with search_type="in".
After second and more value the querybuilder starts to add "AND WHERE 1=0" to the query.
It is because the search value that comes to AbstractFilter::getExpression is for example "1,2", which is treated as incompatible with smallint.

String columns are working fine. 
In older versions, smallint columns are working fine too.

How to reproduce:
In the demo project, update sg/datatablesbundle to 1.0.4
In "posts", select multiple choices in "visible columns" after second choice it shows nothing

Another bug is in daterange. 
If you filter date range only, it works well. But if you combine it with some text search, it will show nothing.
In demo, select the daterange to match at least one record. Then type "T" in "title" column. The record will disapear although it contains this letter.

**Comment by samius** [comment]
Workaround: In column definition you can set 
`'type_of_field'=>'string'`
After setting this, everything works ok

**Comment by stephanvierkant** [comment]
The daterange bug is mentioned in #803.

**Comment by stwe** [comment]
wontfix
