### ISSUE TITLE
How can I set a limit to the query?

### ISSUE THREAD

**Issue by maurotrentini** [stwe/DatatablesBundle#83]
I'm trying to use this bundle on a pretty big db table. It takes ages to load, so I was trying to set a limit in the default query.

I tried to add a "setMaxResult" on the callback function (inside the indexResultsAction()), but seems like it's ignored and it still returned all data. I'm not sure if this is the right approach.

Does anyone know how to add a limit to the result in order to speed up the data retrieval?

// Callback example
    $function = function($qb)
    {
        //$qb->andWhere("Post.visible = true");
        $qb->setMaxResults(100);
    };

Thanks very much in advance.

Mauro

**Comment by stwe** [comment]
The callback function mit setMaxResult doesn't work.
The use of setMaxResults is also the completely wrong way to reduce the amount of data. 
This should be done for example with one or more where clauses. Please try a non server-side table.
