### ISSUE TITLE
Double datatable : One Fix and the other in popup (or modal)

### ISSUE THREAD

**Issue by herivola** [stwe/DatatablesBundle#830]
Hi,

Context : I have a datatable in my page. Then, i open a modal/popup with an other datatable in.
In my modal, the datatable isn't displayed. I have no errors.
According to me, the **JS** is blocked by the first datatable.

Someone can help me please ?

Thanks,
Seb.

**Comment by stephanvierkant** [comment]
Do they have a unique name?

**Comment by herivola** [comment]
No, indeed, they have the same name :/ thanks for you help. I look for a solution.
