### ISSUE TITLE
How to handle Two DT in same webpage(action)

### ISSUE THREAD

**Issue by RefreshMyMind** [stwe/DatatablesBundle#832]
Hi,
I would like to know how to handle  2 Datatables in the same page, both have unique iDs but I get the same data in both which create an error related to columns not relate to json  response.
Please an example will be much appreciated
This is what I did and has problem:

```
  /**
     * @Route("/test" , name= "test")
     */
    public function testAction(Request $request){
        $isAjax = $request->isXmlHttpRequest();
        $datatable = $this->get('sg_datatables.factory')->create(BanqueDatatable::class);
        $datatable2 = $this->get('sg_datatables.factory')->create(EcritureDatatable::class);
        $datatable->buildDatatable();
        $datatable2->buildDatatable();

        if ($isAjax) {
            $responseService = $this->get('sg_datatables.response');
            $responseService->setDatatable($datatable2);

            $responseService->setDatatable($datatable);
            $responseService->getDatatableQueryBuilder();

            return $responseService->getResponse();
        }

        return $this->render('@BanqueEcriture/Default/index2.html.twig', array(
            'datatable' => $datatable,
            'datatable2' => $datatable2,
        ));
    }
```

**Comment by Seb33300** [comment]
You can add multiple datatables on the same page but you have to create a different action for each datatable ajax response.

- Remove `if ($isAjax) {` section from your current action
- Create 2 other actions in your controller with the code inside `if ($isAjax) {` section (one for each datatable)
- Update your datatable class to specify the new URL for the ajax call

See also: https://github.com/stwe/DatatablesBundle/issues/742

**Comment by RefreshMyMind** [comment]
Hi @Seb33300 ,
#742 was really helpful thank you. I resolved the problem.
I think it will be better if the bundle handles all of the DTs in the same action maybe by sending a parameter in the header of the ajax call to distinguish which Dt is calling the datasource.
Duplicating the action to the exactly the same thing seems tricky ! Anyway thank you
