### ISSUE TITLE
SearchType SelectBox Filter in the client-Side 

### ISSUE THREAD

**Issue by RefreshMyMind** [stwe/DatatablesBundle#842]
Hi all,
Is it possible to make a selectbox containing the operators ('like', 'notLike', 'eq', 'neq', 'lt', 'lte', 'gt', 'gte', 'in', 'notIn', 'isNull', 'isNotNull') in combination with a text input as a filter ?   

For example I want to list all of the values greater than 3  ? How can I do that in client side ? 
 
Thank u

**Comment by RefreshMyMind** [comment]
This issue #797 helped me to resolve the problem, however, I still would like to know if the bundle can add these operators automatically to the filters. It's a must have feature

**Comment by mshd** [comment]
This would enable search such as ">0" or "<=10"

Add to Sg\DatatablesBundle\Datatable\Filter\AbstractFilter.php to Line 368
```
        if($searchTypeOfField == "integer"){
          preg_match('/^([>=<]{1,2})(\d+(\.\d+)?)$/', $searchValue, $matches);
          if($matches && count($matches) == 3){
            switch ($matches[1]) {
              case '=':
                $searchType = "eq";
                break;
              case '<':
                $searchType = "lt";
                break;
              case '<=':
                $searchType = "lte";
                break;
              case '>':
                $searchType = "gt";
                break;
              case '>=':
                $searchType = "gte";
                break;
            }
            if($searchType != "integer"){
              $searchValue = $matches[2];
            }
          }
        }
```
