### ISSUE TITLE
New Stable  Version 1.0.5

### ISSUE THREAD

**Issue by fadmaz** [stwe/DatatablesBundle#843]
Hi , can you release a new stable version ? , it's not comfortable to work with the master Dev version.
Thank you

**Comment by stephanvierkant** [comment]
There are some changes that require a new minor version tag so I think it would be 1.1.0. Some upgrade notes should be written first.

**Comment by stephanvierkant** [comment]
New version: 1.1.0.

Dropping support for PHP versions might deserve a major release (2.0) but since they're (almost) EOL I created 1.1.0 instead.
