### ISSUE TITLE
like% possible in filter ?

### ISSUE THREAD

**Issue by ElNelyo** [stwe/DatatablesBundle#848]
Hello,
I have two questions,
First , i can't find any informations about the filters
"like", "notLike", "eq", "neq", "lt", "lte", "gt", "gte", "in", "notIn", "isNull", "isNotNull" in the documentation, did anyone get something ?

Two , is there a way to use a "Like%" in the filter section ?
For example, 

- 33500
- 44330
- 55300

If i type "33" in my filter, it should retrieve only "33500", ( like in SQL).

Thanks for reading ;)

**Comment by ElNelyo** [comment]
Hi , @stephanvierkant Any possibilities to add it to the bundle ? 
Thanks you

**Comment by radhanpuraankit** [comment]
Hello @ElNelyo 
Let me know when It's merge into master. I need to use "like%" in datatable.
Thanks

**Comment by ashishranpara** [comment]
Hello @ElNelyo
Please let me know when It will in current version. I also need to use "%like" in datatable.
Thanks

**Comment by ElNelyo** [comment]
Hi @radhanpuraankit , @ashishranpara , 
i think Seb33300  will validate this PR soon ;)

**Comment by ElNelyo** [comment]
@radhanpuraankit @ashishranpara , done 
have a nice day

**Comment by radhanpuraankit** [comment]
@ElNelyo Thank you, 
But still If I update this pachage using composer after that in code there has not seems changes update. 
When I tried to update using your last commit ID. It's gettting below error. Let me know your suggestion.

[Composer\Downloader\TransportException]                                                                                                           
  The "https://codeload.github.com/stwe/DatatablesBundle/legacy.zip/9200d75a2d87efcb5e783364d80800778d09b0a4f" file could not be downloaded (HTTP/1  
  .1 404 Not Found)

**Comment by radhanpuraankit** [comment]
Hello @ElNelyo 
Can you please merge this changes in version (1.1.1) Or create new version with letest master commit so it will help me.
Thanks

**Comment by ElNelyo** [comment]
@radhanpuraankit Hello, this commit has been merged to the master version, no ?

**Comment by radhanpuraankit** [comment]
@ElNelyo 
So Can you please tell me which version I can use in composer.json file for get letest master code?

**Comment by ElNelyo** [comment]
I see what you means, i've the same "issue".
atm the pr is on master, and not on v1.1.1 tag so we can't download id with composer...

Can you help us a little more @Seb33300 , we don't know how to get this pr with composer :/ 
Thanks you !

**Comment by Seb33300** [comment]
Edit your `composer.json`:
```
"sg/datatablesbundle": "dev-master"
```

And then, 
```
composer update sg/datatablesbundle
```

**Comment by radhanpuraankit** [comment]
@ElNelyo 
I have tried this also. It's taking older version. But if I update letest commit id from composer.lock then it's taking new version. 
Thus one more issue is occring that is
When I add custom query using QB it's generatting error "'table name' is not defined.
In bedore version "1.0" version it's working fine. Let me know your suggestion.
Thanks
