### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by stephanvierkant** [stwe/DatatablesBundle#851]
I'm using this bundle for years now and it's a great, powerful bundle. Thanks to all contributors for that!

Unfortunately, there are many open PR's that deserve some attention. Some of them may be closed, some of them provide bugfixes or useful new features. Many of the 72 issues are outdated or just support questions.

I'd really like to help maintaining this bundle. I see @stwe hasn't been active for more than a year on this project. @Seb33300 stepped in, but isn't very active right now.

**Comment by stwe** [comment]
May the force be with you! Welcome to the team.

**Comment by stephanvierkant** [comment]
Thanks! I'll start with cleaning up some PR's and issues.
