### ISSUE TITLE
Select filter choices do not trigger call to back-end

### ISSUE THREAD

**Issue by drososanastasios** [stwe/DatatablesBundle#865]
Hello,

after I migrated to version 1.1.1 in order to fix the issue with the dateRange filter, I realized that now when I click on the choices on Select2Filter (or on SelectFilter), no ajax called is being triggered to the backend. Any ideas why?

This is the code on my datatable:

```
           ->add(
                'used',
                Column::class,
                [
                    'title' => 'Used',
                    'filter' => [
                        Select2Filter::class, [
                            'classes' => 'select2',
                            'search_type' => 'eq',
                            'select_options' => [
                                '' => 'All',
                                false => 'false',
                                true => 'true',
                            ],
                            'cancel_button' => true,
                        ]
                    ],
                ]
            )
```

This was working fine on 1.0.4, but on that version the dateRange filter is not working properly.

**Comment by drososanastasios** [comment]
Hello, do we have any updates on this?

**Comment by lvillanne** [comment]
Hello, same problem here.

**Comment by drososanastasios** [comment]
Unfortunately, version 1.0.4 is not compatible with symfony 4. Maybe someone can guide on this order to fix it?

**Comment by stwe** [comment]
wont fix
