### ISSUE TITLE
cast date for query in postgresql

### ISSUE THREAD

**Issue by boyere31** [stwe/DatatablesBundle#866]
Hello
I have a datable with date and when I use the search feature I get an error :
ERROR:  operator does not exist: timestamp without time zone ~~ unknown

PostreSQL is not fully supported  ?

How can I cast date in the query please ?

thanks a lot for your help.
I use :         "sg/datatablesbundle": "^1.0",

**Comment by Seb33300** [comment]
You should read the [readme file](https://github.com/stwe/DatatablesBundle/blob/master/README.md) and the `Info about PostgreSQL` section.
