### ISSUE TITLE
Reload to page 1 while edit inline a row

### ISSUE THREAD

**Issue by CondonesMix** [stwe/DatatablesBundle#869]
Hello,
(It's a suggestion)
When you edit in-line from any page, always reload the first page.

It is uncomfortable if you are on page 20 because to return to 20 you have to make several clicks.

I found the solution in datatablesbundle/Resources/views/column/**column_post_create_dt.js.twig**
(line 73)

Changing
`     success: function() {
        if (pipeline > 0) {
            oTable.clearPipeline().draw();
        } else {
            oTable.draw();
        }
    }`
to
`     success: function() {
        if (pipeline > 0) {
            oTable.clearPipeline().draw(false);
        } else {
            oTable.draw(false);
        }
    }`

maybe should be in the master, and if not, I expect that those who have the same uncomfortable problem that I have had serve them.

Greetings from Barcelona, and congratulations for the great work with this bundle, for me, a "must have"

**Comment by Seb33300** [comment]
Hello, can you submit a pull request for this?

**Comment by klupa-gotoma** [comment]
Was this fixed? Same problem I'm having.

**Comment by CondonesMix** [comment]
Is fixed with my modif . (@Seb33300 I try to make PR, thanks)

**Comment by klupa-gotoma** [comment]
Where is this fix?

**Comment by CondonesMix** [comment]
@klupa-gotoma read:

datatablesbundle/Resources/views/column/column_post_create_dt.js.twig
(line 73)

Changing
success: function() { if (pipeline > 0) { oTable.clearPipeline().draw(); } else { oTable.draw(); } }
to
success: function() { if (pipeline > 0) { oTable.clearPipeline().draw(false); } else { oTable.draw(false); } }

**Comment by klupa-gotoma** [comment]
of course it was the first thing I tried. Unfortunately, this file is not used at all (don't know why yet).
I thought maybe you solved it differently. Anyway, thank you for the answer.

**Comment by CondonesMix** [comment]
@klupa-gotoma  what version you have?

**Comment by klupa-gotoma** [comment]
1.0
I tried update to the newest, but it does not work - https://github.com/stwe/DatatablesBundle/issues/945 same problem.

**Comment by klupa-gotoma** [comment]
I fixed this. the problem was not related to the bundle, but the way we reload ajax within the project:
was: table.DataTable().ajax.reload();
fix: table.DataTable().ajax.reload(null, false);
