### ISSUE TITLE
export excel

### ISSUE THREAD

**Issue by boyere31** [stwe/DatatablesBundle#872]
Hello

I try to export data to excel but I never get "Excel" button :(

I use : symphony 3.4 et sg/datatable 1.0

my part of code to build datatable :

    public function buildDatatable(array $options = array())
{
...
        $this->options->set(array(
             ....
                        'dom' => 'Bfrtip',
              ...
        ));

         ...
         $this->extensions->set(array(
            'buttons' => array(
                'show_buttons' => array('excel', 'print')
            )
        ));

And in my datatble I only have "Print" button :(
Where is my mistake please ?

**Comment by Seb33300** [comment]
See: https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/extensions.md#1-buttons

> Be sure to install the Buttons Extension before using.

https://datatables.net/extensions/buttons/

**Comment by boyere31** [comment]
yes I dit it and my includes are :

    <script type="text/javascript" src="{{ asset('assets/vendor/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendor/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendor/datatables.net-buttons/js/buttons.colVis.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendor/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendor/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>

No error in my javascript console

**Comment by Seb33300** [comment]
https://datatables.net/download/release

> Please note that the HTML5 export buttons require JSZip and PDFMake in order to operate.

**Comment by boyere31** [comment]
Thanks but I only need excel export

**Comment by Seb33300** [comment]
I think they are required anyway.

**Comment by boyere31** [comment]
ok I will install it but why I have ony one button : "Print" ?
By default I should have 5 buttons when I set the option for button to 'true'
:(

**Comment by boyere31** [comment]
I had a cache problem.
After reload, I have 3 buttons : Copy, CSV, Print
I haven't PDF and Excel ...
I install  JSZip and PDFMake and I will tell you...
thanks

**Comment by boyere31** [comment]
Yes !
after install jszip I have the excel button

I love you :)

But where could I find this info by myself ?
