### ISSUE TITLE
ORDER BY case insensitive

### ISSUE THREAD

**Issue by arturomf** [stwe/DatatablesBundle#878]
Hi all!

I have a problem with a string column order. The order is case sensitive so is A-Za-z instead of Aa-Zz.

Is there any configuration or workaround to use order by in case-insensitive mode?

Thanks in advance!

**Comment by Seb33300** [comment]
I am not sure to understand what you want.

Do expect the search to be case sensitive or case insensitive?
Which database are you using?

**Comment by arturomf** [comment]
Hi Seb, i'm using MySQL and Doctrine. The search is case sensitive, but i expect it to be case insensitive.

When i order a string column, i get:

Name
====
Carla
John
carlton
henry

I'd like to get the column ordered case insensitive:

Name
====
Carla
carlton
henry
John

**Comment by Seb33300** [comment]
This is probably related to the collation used by you table / columns in MySQL.

You should use `utf8_general_ci` instead of `utf8_general_ci` for example.
`ci` = case insensitive
`cs` = case sensitive

**Comment by arturomf** [comment]
All my tables and columns are using `utf8_general_ci`. I think i have other problem somewhere else.

I'm closing the issue after having more information. 

Thank you very much!

**Comment by Seb33300** [comment]
You should try to get the query from logs and try to execute it in MySQL to see the returned order by MySQL.

**Comment by arturomf** [comment]
Thank you very much for your help Seb, it was my fault, nothing related to this wonderful bundle.
