### ISSUE TITLE
How can I remove "distinct" from count query

### ISSUE THREAD

**Issue by ashishranpara** [stwe/DatatablesBundle#879]
Hello 

I have a large database. So count query is adding to mysql query slow log. So I have to remove distinct from count query. Can anyone have a suggestion which was a help to for the same.

**Comment by radhanpuraankit** [comment]
I have same requirement anyone know how can this possible?

**Comment by radhanpuraankit** [comment]
Hello @ElNelyo @Seb33300,
Please can you please suggest solution for this?

**Comment by ashishranpara** [comment]
Hello @ElNelyo @Seb33300,
Any Update for this?

**Comment by ElNelyo** [comment]
If you can't do a count query, it's a management issue.. not relative to this bundle 🤔 @radhanpuraankit @ashishranpara

**Comment by ashishranpara** [comment]
Hello @ElNelyo @stephanvierkant 

I have already checked that In the bundle count query has **hardcoded** "distinct". Please check below link.

https://github.com/stwe/DatatablesBundle/blob/master/Response/DatatableQueryBuilder.php#L545

**Comment by stephanvierkant** [comment]
This is an open source project. Instead of spamming maintainers, you could also do a Pull Request.

The method `DatatableQueryBuilder::getCountAllResults` is a public method, so you could extend it yourself.

**Comment by stwe** [comment]
@stephanvierkant rarely read a better comment
