### ISSUE TITLE
Translation of column content

### ISSUE THREAD

**Issue by Rashguir** [stwe/DatatablesBundle#882]
Hi, 

Is there a way of using the symfony translator to translate a column content?

I've set this in my `buildDatatable` function : 
```
$this->language->set([
    'language_by_locale' => true,
]);
```

but it does not translate the content of my column...

Maybe there is an option to say "this column's content has to go through translator" ?

Thx for this lib, outside of this problem, it's an ease to work with! 😄

**Comment by stephanvierkant** [comment]
I think you should use `getLineFormatter` for this.

**Comment by Rashguir** [comment]
Thanks @stephanvierkant !
