### ISSUE TITLE
Packagist hook

### ISSUE THREAD

**Issue by stephanvierkant** [stwe/DatatablesBundle#888]
I've created a new release 3 days ago, but it's not still available on Packagist. Any idea how to push a new version?

**Comment by stwe** [comment]
I will take a look at weekend.

**Comment by fyrye** [comment]
@stwe  I am guessing that your repository is using the old hook that was depreciated Jan 2019.
https://packagist.org/about#how-to-update-packages

Alternatively you can force an update by using the packagist API from your local repository hooks.
```
curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username=PACKAGIST_USERNAME&apiToken=PACKAGIST_API_TOKEN' -d'{"repository":{"url":"PACKAGIST_PACKAGE_URL"}}'
```
Your packagist API token is viewable on your profile page.

---

In the interim you should be able manually update the package version from the packagist UI.
My Packages -> [Package Name] -> Update

**Comment by stwe** [comment]
should now work again, if not, please info

![Unbenannt](https://user-images.githubusercontent.com/2964748/57480968-5dc4f200-72a1-11e9-8d3c-085152331da6.PNG)
