### ISSUE TITLE
load an specific page in DataTable

### ISSUE THREAD

**Issue by Azraelir** [stwe/DatatablesBundle#890]
hi @stephanvierkant ,

Do we have an option to load an specific page for example page 60 of 1000?

I have an edit action and when the user is done editing, I want to return user to the exact page he came from in datatable.

regards

**Comment by stephanvierkant** [comment]
While I'm one of the maintainers, you don't have to tag me in this question. There are other maintainers too (and non-maintaining users can help as well).

I think this is a front end question? Take a look at datatables.net if you can find an answer there.

**Comment by Eloar** [comment]
@Azraelir it looks like you may use datatable api function `page()`:
https://datatables.net/reference/api/page()

**Comment by Azraelir** [comment]
thank both of you for your answers.
