### ISSUE TITLE
change labels on pagination

### ISSUE THREAD

**Issue by konradja100** [stwe/DatatablesBundle#892]
Is there any way to change translations of "previous" nad "next" buttons on pagination?

![image](https://user-images.githubusercontent.com/28842587/57909566-6dd16880-7883-11e9-9e7b-4c259513b2b1.png)

I've tried to override translations fron i18n folder ( following SF docs) by creating pl.json.twig file with changed translations in ```bundles\SgDatatablesBundle\i18n\pl.json.twig``` but it did't work.

Any solution?

**Comment by stephanvierkant** [comment]
Have you looked at https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/internationalisation.md?
