### ISSUE TITLE
Misleading DateTime column format docs

### ISSUE THREAD

**Issue by curtchan** [stwe/DatatablesBundle#895]
https://github.com/stwe/DatatablesBundle/blame/master/Resources/doc/columns.md#L252

It's not php format, after few tests it seems like it is moment.js/js format of date/datetime.

**Comment by mshd** [comment]
Yes it is rendered by Javascript (of which I'm not too happy about either)
```
<script type="text/javascript">
        $(function() {
            moment.locale("de_INFRAME");
           $("#sg-datatables-mediafieldvalue_datatable-datetime-fdeaa1902bbb6b48ee3a390ceaa0351462972c0b").html(moment.unix(1563180781).format("lll"));
            });
    </script>
```
