### ISSUE TITLE
Add scrollX to options

### ISSUE THREAD

**Issue by mshd** [stwe/DatatablesBundle#900]
Please add [ScrollX from Datatables](https://datatables.net/reference/option/scrollX) to [options.html.twig](https://github.com/stwe/DatatablesBundle/blob/master/Resources/views/datatable/options.html.twig)

**Comment by Seb33300** [comment]
Scroll X "option" is in features: https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/features.md

**Comment by mshd** [comment]
Thank you, I didn't see it
