### ISSUE TITLE
Sort translated column content

### ISSUE THREAD

**Issue by hauke68** [stwe/DatatablesBundle#908]
Hi,

I have a column with translated data (translated by the line formatter) by
`$row['type'] = $this->trans($row['type']);`

The column contains the values from the database "flat", "house", "villa". Translated to German: "Wohnung", "Haus", "Villa".
I want the column be ordered as "Haus", "Wohnung", "Villa" but I cannot find a solution.
Could someone help me? 

Thanks,
Hauke

**Comment by mshd** [comment]
Hi Hauke,

I don't think this is possible as the ordering is happening in the database/SQL. They only option would be to add another column "type_de" (with the translations) and use `'order_column' => "type_de"` (for each language).

Viel Erfolg

**Comment by hauke68** [comment]
Hi mshd,

thanks for your answer :smiley:  I will think about the additional column; maybe I will try it with using a database table view.

Regards,
Hauke
