### ISSUE TITLE
Action doenst work

### ISSUE THREAD

**Issue by Luisrdrgz100** [stwe/DatatablesBundle#913]
$this->actions = array(
            'start_html' => '<div class="row"><div class="col-sm-3">',
            'end_html' => '<hr></div></div>',
            'actions' => array(
                array(
                    'route' => $this->router->generate('admin_artist'),
                    'label' => $this->translator->trans('datatables.actions.new'),
                    'icon' => 'glyphicon glyphicon-plus',
                    'attributes' => array(
                        'rel' => 'tooltip',
                        'title' => $this->translator->trans('datatables.actions.new'),
                        'class' => 'btn btn-primary',
                        'role' => 'button',
                    ),
                )
            ),
        );

actions is declared dianmically

**Comment by stephanvierkant** [comment]
Is this a bug report? Or a support question?

Please create a reproducible example, so we can look into this. GitHub is an community of open source contributors, not a helpdesk.

(and please use a spell checker. I can read your question, but please show some effort before asking questions if you expect effort from the community. I'm not a native English speaker either, but at least I try my best to check for obvious typing/spelling mistakes. It's not very hard to use a spell checker in modern browsers these days)
