### ISSUE TITLE
Revert #914

### ISSUE THREAD

**Issue by Seb33300** [stwe/DatatablesBundle#917]
PR https://github.com/stwe/DatatablesBundle/pull/914 introduces many BC break by adding a new parameter to `AbstractColumn` public methods.

https://symfony.com/doc/current/contributing/code/bc.html#changing-classes

This is breaking all my projects and probably many other project of people who have created their own `Column` classes

Can you also provide more information about this PR.
I am not able to understand what is the benefit of this feature compared to the existing `VirtualColumn` or using dql.
Any example of use?

**Comment by Seb33300** [comment]
Ping @stephanvierkant 

This is your pull request

**Comment by mwansinck** [comment]
Had to update our own Column classes also, this is BC break indeed.
