### ISSUE TITLE
Symfony 2.6 support

### ISSUE THREAD

**Issue by meron1122** [stwe/DatatablesBundle#92]
Catchable Fatal Error: Argument 1 passed to Sg\DatatablesBundle\Datatable\View\AbstractDatatableView::__construct() must be an instance of Symfony\Bundle\TwigBundle\TwigEngine

Symfony 2.6.3 is not supported?

**Comment by stwe** [comment]
I work with version 2.6.4-dev. It works.

**Comment by meron1122** [comment]
Yup my typo, but i have now:
Notice: Undefined index: columns 

Code:
<?php

namespace Raltech\WarehouseBundle\Datatables;

use Sg\DatatablesBundle\Datatable\View\AbstractDatatableView;

/**
 * Class WardrobeDatatable
 *
 * @package Raltech\WarehouseBundle\Datatables
 */
class WardrobeDatatable extends AbstractDatatableView
{
    /**
     * {@inheritdoc}
     */
    public function buildDatatableView()
    {
        $this->getFeatures()
                        ->setServerSide(true)
                        ->setPaging(true)
                        ->setSearching(true)
                        ->setProcessing(true);

        $this->getAjax()->setUrl($this->getRouter()->generate('backend_warehouse_wardrobes_list'));
        
        $this->setStyle(self::BOOTSTRAP_3_STYLE);

        
        $this->getColumnBuilder()
                ->add('id', 'column', array('title' => 'Id',))
                ->add('name', 'column', array('title' => 'Name',))
                ->add('description', 'column', array('title' => 'Description',))
                ->add('magazine.id', 'column', array('title' => 'Magazine Id',))
                ->add('magazine.name', 'column', array('title' => 'Magazine Name',))
                ->add('magazine.description', 'column', array('title' => 'Magazine Description',))
                ;
    }

    /**
     * {@inheritdoc}
     */
    public function getEntity()
    {
        return 'Raltech\WarehouseBundle\Entity\Wardrobe';
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'wardrobe_datatable';
    }
}

**Comment by hopsoid** [comment]
Same issue with Symfony 2.6.6

**Comment by ThatCheck** [comment]
No issue with 2.6.6 to me.
