### ISSUE TITLE
MultiSelect not sending CSRF Token on large selection

### ISSUE THREAD

**Issue by andrea-daru** [stwe/DatatablesBundle#923]
I've noticed that if I select 50 rows and then I call a MultiSelect action the csrf token it's empty (in the controller)
It work correctly on smaller selection.
Does anyone else have the same problem?
Are there known solutions?

Thank you in advance

**Comment by secit-pl** [comment]
Had the similar problem almost 2 years ago (see https://bugs.php.net/bug.php?id=76010). Changing the PHP version to upper should help.

**Comment by Eloar** [comment]
> Had the similar problem almost 2 years ago (see https://bugs.php.net/bug.php?id=76010). Changing the PHP version to upper should help.

@secit-pl  which PHP version was it related to in your case?

**Comment by secit-pl** [comment]
@Eloar you can find the versions list on php bug report I linked before

**Comment by Eloar** [comment]
@secit-pl yes, I've seen mentioned version in linked report. I'm curious about Your case.

**Comment by secit-pl** [comment]
AFAIR it was first spotted by me on XAMPP with PHP 7.2.1... But it was almost 2 years ago so I'm not 100% sure.

**Comment by kaistaerk** [comment]
did someone find any solution? I have the same problem. more than 20 items selected will crash, but no idea what. php version is 7.3

**Comment by secit-pl** [comment]
@kaistaerk update php to newest version. I also noticed the problem is only on Windows.

**Comment by kaistaerk** [comment]
I have the same on linux and also with more than 20 items. PHP is on 7.3

**Comment by kaistaerk** [comment]
@stwe  hi. have you any idea about this problem? its very tricky

**Comment by kaistaerk** [comment]
I see all items in the network debug. But request object have only a small number of items....perhaps not datatables related but some hints would be great ;)

**Comment by stwe** [comment]
Nein, habe ich nicht. Ich programmiere nur als Freizeitvergnügen und mache derzeit viel mit C++ und 3D mit OpenGL. Das Bundle hier ist einige Jahre alt und ich müsste mir erst mal wieder den kompletten Code ansehen, wozu ich ehrlich gesagt auch keine Lust habe - das Privileg eines Hobbyprogrammierers.

**Comment by kaistaerk** [comment]
kann ich verstehen. schade

Steffen <notifications@github.com> schrieb am Do., 9. Apr. 2020, 07:49:

**Comment by kaistaerk** [comment]
The problem is that, the post request is too large. Because all column data are transfered to the ajax. Now i extracted only the values of the checkboxes. Then it works fine.

Look at: 
> Resources/views/datatable/multiselect_actions.html.twig

```
$(".sg-datatables-{{ datatable_name }}-multiselect-action").on("click", function(event) {
   // change handling of ajax here
});
```

**Comment by stwe** [comment]
wont fix
