### ISSUE TITLE
DateRangeFilter not working

### ISSUE THREAD

**Issue by andrea-daru** [stwe/DatatablesBundle#924]
DateRangeFilter doesn't work.
Wheter I select the date from the calendar, the value in the input box remain "For0amto" and "For59pmto".
Maybe it's due to a locale setting?
Thank you in advance.
![Schermata 2019-10-21 alle 14 29 20](https://user-images.githubusercontent.com/8058905/67205118-5177c000-f40f-11e9-8099-23b4821127d1.png)

**Comment by stwe** [comment]
wont fix
