### ISSUE TITLE
Removing Page Length

### ISSUE THREAD

**Issue by ProfM2** [stwe/DatatablesBundle#932]
DataTables has the option to remove the Page length dropdown via lengthChange = false.

See: [https://datatables.net/reference/option/lengthChange](https://datatables.net/reference/option/lengthChange)

I'm unable to locate this option in the bundle.  Is it hiding somewhere?

I did look in [https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/options.md](https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/options.md), but it doesn't appear to be there.

**Comment by mshd** [comment]
I think you can set the feature to false see https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/features.md
Or you can also change the DOM and remove the "l" parameter

**Comment by ProfM2** [comment]
Gah, I can't believe I missed that.  Thanks!
