### ISSUE TITLE
Server Side Pagination

### ISSUE THREAD

**Issue by selimppc** [stwe/DatatablesBundle#933]
Is there any way to get server-side pagination?
I need to call minimum data from the database

**Comment by Eloar** [comment]
Data is served in pages from server. If you want to limit data transfer from DB it is done by default.

**Comment by selimppc** [comment]
@Eloar, it's serving all data. I need to fetch data 20-row data only with pagination. in 2nd-page system will fetch another 20 data from the database. 

Please guide me.

**Comment by selimppc** [comment]
<img width="1207" alt="Screenshot 2020-02-03 17 30 15" src="https://user-images.githubusercontent.com/7763876/73649828-dc24b800-46aa-11ea-8ddb-304124f48f05.png">

Currently, it's fetching all data from the database. 

@Eloar , Please provide me the syntax for pagination and its limit

**Comment by Seb33300** [comment]
Your screenshot shows that only 20 results are fetched from the database.

**Comment by Eloar** [comment]
@selimppc bundle serves data in pages what You may check in debug panel (doctrine tab).

**Comment by selimppc** [comment]
@Eloar - it fetched all data at a time and then paginating on-page.  I need to fetch limited data from data 

did you get my point? I checked doctrine tab -- it calls for whole data as I have thousands of data

**Comment by selimppc** [comment]
@Seb33300, No data tables did it. But from the database, it fetched all data . 

check here : https://datatables.net/examples/styling/bootstrap

**Comment by selimppc** [comment]
@Seb33300  my screenshot showing fetch data 5,127 and data-tables shows 20 in the first page. 

my question - why I need to fetch 5,127 instead of 20?

**Comment by Seb33300** [comment]
Your screenshot shhows:
20 rows fetched
from 5,127 rows (based on your filters)
from 36,129 rows in the tables

**Comment by Eloar** [comment]
@selimppc one of features of this bundle is filtering, ordering and pagination on server side. You may see it in action in Doctrine page in debug panel for each ajax request made by DataTable plugin. This is quite neat solution.

**Comment by selimppc** [comment]
@Seb33300 : 
I have data and sub-data (s) that are 36,129. I am saying exactly the same you pointed --> fetched all data from Database and paginating on-page on debatable. 

I am looking for this:

20 from 20 rows .. 20 will come from DB ... 

FYI: DataTable works paging on-page. Not server-side ( backend )

@Eloar 👍 
I need the script where I need to change. Would you please provide me a screenshot or code here. 
I read the documentation - I did not find anything that I want. 
 
As I am using Symfony bundle -> I believe there might have an option.

**Comment by Seb33300** [comment]
Did you check SQL queries?
Please copy / paste your SQL queries.

![image](https://user-images.githubusercontent.com/915273/73715558-e7c5bc80-4746-11ea-8ab1-3b19400d3e8a.png)

**Comment by selimppc** [comment]
<img width="1088" alt="Screenshot 2020-02-04 11 51 47" src="https://user-images.githubusercontent.com/7763876/73717700-be0b9600-4744-11ea-99d6-0d9c5d64505a.png">

**Comment by Seb33300** [comment]
As you can see, the query #3 is fetching only 20 rows.

**Comment by selimppc** [comment]
```
private function executeQuery()
    {	    
       $query = $this->qb->getQuery();
        $query->setHydrationMode(Query::HYDRATE_ARRAY);
        $fresults = new Paginator($query, true);
        $output = array("aaData" => array());

```

this could be helpful
