### ISSUE TITLE
Project is abandoned?

### ISSUE THREAD

**Issue by genetus** [stwe/DatatablesBundle#934]
Last commit at least 4 month ago.
LTS Symfony version 4.4 is not supproted (I don't say anything about support symfony 5.*).

**Comment by Eloar** [comment]
Is 4.4 really unsupported? I'm pretty sure I am using this bundle in project based on 4.4.

**Comment by genetus** [comment]
For base version non from git, from comopser I get DI exception on update.

**Comment by Seb33300** [comment]
I am waiting for feedback on this PR since I don't have time to test it:
https://github.com/stwe/DatatablesBundle/pull/930

If you can test it and confirm this fix compatibility with SF 4.4 & 5.0 I will merge it.
If not, you can contribute and submit a PR.

**Comment by Knallcharge** [comment]
I have just applied the changes from PR #930 on a Symfony 4.4.4 project and can confirm it works.

**Comment by Seb33300** [comment]
PR is merged
