### ISSUE TITLE
Exception: null value for setSelectSearchType

### ISSUE THREAD

**Issue by Knallcharge** [stwe/DatatablesBundle#936]
I just got an exception with a specific search:

`Uncaught PHP Exception TypeError: "Argument 1 passed to Sg\DatatablesBundle\Datatable\Filter\SelectFilter::setSelectSearchType() must be of the type string, null given, called in (...)\vendor\sg\datatablesbundle\Datatable\Filter\SelectFilter.php on line 74" at (...)\vendor\sg\datatablesbundle\Datatable\Filter\SelectFilter.php line 174`

The options in the search-dropdown are all strings (and an empty string for "show all") but no NULL-value (as suggested in the exception message), so the question is, how is it even possible to have NULL as a search string in a select filter? Unfortunately I can't reproduce error.

Suggestion for a quick fix: Casting $searchValue to string in SelectFilter (line 74)?

Using dev-master with Symfony 4.4.5 and PHP 7.3.13

**Comment by Eloar** [comment]
@Knallcharge could You post that column full configuration with filter configuration? I had some problems when using SelectFilter lately, and it was quite bizare, yet got it resolved.

**Comment by Knallcharge** [comment]
@Eloar thanks for getting back, here's my column-config:

`        $fields             = $this->em->getRepository(Field::class)->findAll();
        $fieldSelectOptions = array_merge($this->getOptionAll(), $this->getOptionsArrayFromEntities($fields, 'name', 'name'));
        $fieldFilterOptions = [
            'title'           => $this->translator->trans('field', [], 'datatables'),
            'default_content' => $this->translator->trans(self::NA_TEXT, [], 'datatables'),
            'searchable'      => true,
            'orderable'       => true,
            'filter'          => [
                SelectFilter::class,
                [
                    'select_options' => $fieldSelectOptions,
                    'search_type'    => 'eq',
                ],
            ],
        ];`

self::NA_TEXT = 'n/a', getOptionAll returns

`return ['' => '-- ' . $this->translator->trans('all', [], 'datatables') . ' --'];`

I doubt it's the source of the problem as the exception occured only once in I don't know how many thousand usages and the option values are all not NULL, but maybe there's something I'm missing?

**Comment by Eloar** [comment]
@Knallcharge if it occured once, do You have callstack logged?

**Comment by Knallcharge** [comment]
@Eloar Unfortunately nothing more than the above (TypeError) was logged, so I know *where* the NULL-value threw the error,  but not how it got there.

**Comment by Eloar** [comment]
@Knallcharge is Your column regular column, virtual column or some extension of above?

**Comment by Knallcharge** [comment]
@Eloar 
just the regular column:
`->add('field.name', Column::class, $fieldFilterOptions)`

**Comment by Eloar** [comment]
@Knallcharge one more thing. Could you post info about version You are using? Maybe post output of
```
composer info sg/datatablesbundle
```

**Comment by Knallcharge** [comment]
@Eloar it's dev-master as stated in the original post
```
name     : sg/datatablesbundle
descrip. : Symfony Datatable Bundle For Doctrine2 Entities
keywords : data-table, datagrid, datatable, datatables, grid, pagination, symfony3, table
versions : * dev-master
type     : symfony-bundle
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/stwe/DatatablesBundle.git 51cebfd941dacda8636e02c0607caa65ec6761f3
dist     : [zip] https://api.github.com/repos/stwe/DatatablesBundle/zipball/51cebfd941dacda8636e02c0607caa65ec6761f3 51cebfd941dacda8636e02c0607caa65ec6761f3
path     : (...)\vendor\sg\datatablesbundle
names    : sg/datatablesbundle

autoload
psr-4
Sg\DatatablesBundle\ => .

requires
doctrine/orm ^2.5
friendsofsymfony/jsrouting-bundle ^1.6|^2.0
php >=7.1
symfony/framework-bundle ^3.4|^4.1
symfony/options-resolver ^3.4|^4.1
symfony/property-access ^3.4|^4.1
symfony/security ^3.4|^4.1
symfony/translation ^3.4|^4.1
twig/twig ^2.9

requires (dev)
friendsofphp/php-cs-fixer ^2.15
phpunit/phpunit 5.7.*
```

**Comment by Eloar** [comment]
This error is more bizare than I had. You are right, I don't see anything wrong in Your filter configuration. Maybe Your cache was rebuilding when this error occured.

**Comment by Knallcharge** [comment]
Can't tell. I patched my proposed quick fix for my installation to be on the save side, can't see anything wrong with that. Anyways, thanks for double checking.
