### ISSUE TITLE
Double header row in 1.2

### ISSUE THREAD

**Issue by Eloar** [stwe/DatatablesBundle#940]
Last version worked as it should with Symfony 3.4 application, but after 1.2 update it started to render header twice.First one header, next one filter line and then header again.

![Example](https://user-images.githubusercontent.com/8638725/77333127-452bc200-6d23-11ea-9c80-4d3d4242e32a.png)

**Comment by Seb33300** [comment]
Anyone else is reproducing this issue?

**Comment by K0rell** [comment]
Yes 

Commit see : 637bb04e907dcd8b6b6f09c93b815e03bdd18e92
File : datatable_html.html.twig row: 41

![image](https://user-images.githubusercontent.com/2000155/77353853-0c4f1580-6d42-11ea-9797-d4e3fd0910ff.png)

My code
`
        $this->options->set([
            'classes' => Style::BOOTSTRAP_4_STYLE,
            'individual_filtering' => true,
            'search_in_non_visible_columns' => true,
        ]);
`

**Comment by Seb33300** [comment]
@philippemilink this is your PR

**Comment by Seb33300** [comment]
Fixed in 1.2.1
