### ISSUE TITLE
individual_filtering to associated collumns

### ISSUE THREAD

**Issue by AlexanderMur** [stwe/DatatablesBundle#942]
Is it possible apply filter without changes of values in column?
Values of coulmns are also filtered when collumn is applied for filter.

```
$this->columnBuilder
    ->add('createdBy.username', Column::class, array(
        'title' => 'Created by',
        'width' => '100%',
        'filter' => array(Select2Filter::class,
            array(
                'search_type' => 'gt',
                'cancel_button' => true,
                'url' => 'select2_usernames',
            ),
        ),
    ))
```

Also you can see example in [demo application](https://github.com/stwe/DtBundleDemo10). when you trying to filter "comment" collumn. For example if you type "comment 4" it will show only "comment 4" without other values.
![12c3257303](https://user-images.githubusercontent.com/9999654/77695613-dc1ba700-6fcd-11ea-9cae-26ccbeaae71d.jpg)

**Comment by Seb33300** [comment]
I don't understand your question.
The purpose of the filter is to filter rows matching with the value you are searching for.

**Comment by AlexanderMur** [comment]
If I search "Comment 4" in another datatable library with same databse it will look like this:
![download](https://user-images.githubusercontent.com/9999654/82740359-7f383500-9d61-11ea-9f60-5b5e9cdbc913.png)

But if I search "Comment 4" in sg/datatablesbundle instead of "Comment 1,Comment 2,Comment 3,Comment 4" it will show only "Comment 4"
![download2](https://user-images.githubusercontent.com/9999654/82740363-82cbbc00-9d61-11ea-9b60-3f7669786507.png)
