### ISSUE TITLE
1.2.0 and 1.2.1 tags based on same commit

### ISSUE THREAD

**Issue by mbabker** [stwe/DatatablesBundle#944]
The 1.2.1 release is identical to 1.2.0 and does not contain any fixes, based on the [releases list](https://github.com/stwe/DatatablesBundle/releases) the two tags are based on the same commit.

![Screen Shot 2020-04-06 at 10 18 38 AM](https://user-images.githubusercontent.com/368545/78574725-09e3c580-77f0-11ea-9198-b96a00076b95.png)

**Comment by Eloar** [comment]
It seems You are absolutely right. There is tag v.1.2.0-beta which should be renamed back to v1.2.0.

**Comment by Seb33300** [comment]
I don't really know what happened but 1.2.1 is the latest commit available on master: d57f9776f67efc20546fd44a4003a162697e52a0

So it's ok.
