### ISSUE TITLE
phoneNumber showing [object Object] into the column

### ISSUE THREAD

**Issue by davidmorenonuez** [stwe/DatatablesBundle#950]
I have this columnbuilder column defined:

```
->add('phone', Column::class, array(
                    'title' => 'Phone number',
                    'default_content' => '',
                    'visible' => true,
                    'data' => 'phone',
                ))
```

The entity:

```
    /**
     * @ORM\Column(name="phone", type="phone_number", length=50, nullable=true)
     * @AssertPhoneNumber(type="any")
     * @AssertUniquePhoneNumber()
     */
    protected $phone = null;
```

The object is an instance of https://github.com/misd-service-development/phone-number-bundle

When rendering the column, it shows the value [object Object] into the datatable.

What am I doing wrong?
![Anotación 2020-06-03 155742](https://user-images.githubusercontent.com/19350239/83688417-fae08000-a5b2-11ea-86c7-774324d956ac.png)

**Comment by Seb33300** [comment]
Maybe you will need to use a VirtualColumn to display it
