### ISSUE TITLE
DatatableController has no container set error after Symfony5 upgrade

### ISSUE THREAD

**Issue by davidmorenonuez** [stwe/DatatablesBundle#955]
Greetings,

I'm getting this error when using the **"In-place editing"** feature of stwe/Datatables.

`"Sg\DatatablesBundle\Controller\DatatableController" has no container set, did you forget to define it as a service subscriber?`

It was working fine in Symfony 4 but started failing when I upgraded.

Any ideas on how to solve?

![Anotación 2020-07-26 024404](https://user-images.githubusercontent.com/19350239/88474261-5b70a700-ceea-11ea-8a0f-5387b359ca28.png)

![Anotación 2020-07-26 024404s](https://user-images.githubusercontent.com/19350239/88474300-9ffc4280-ceea-11ea-928e-f5379b8ab758.png)

Thank you and kind regards,
David Moreno.

**Comment by Knallcharge** [comment]
Can confirm, happens for me, too, after upgrading to Symfony 5 (4.4 still works fine).

**Comment by Knallcharge** [comment]
Don't think this is a proper fix, but I got it to work by adding this to my services.yaml:

`    Sg\DatatablesBundle\Controller\DatatableController:
        calls: [['setContainer', ['@Psr\Container\ContainerInterface']]]
`

**Comment by davidmorenonuez** [comment]
> Don't think this is a proper fix, but I got it to work by adding this to my services.yaml:
> 
> ```
>  Sg\DatatablesBundle\Controller\DatatableController:
>         calls: [['setContainer', ['@Psr\Container\ContainerInterface']]]
> ```

That worked, thanks.
