### ISSUE TITLE
Error with doctrine/persistence 2.0.0

### ISSUE THREAD

**Issue by Knallcharge** [stwe/DatatablesBundle#956]
Hi,

after upgrading doctrine/doctrine-bundle to version 2.1.2 (from 2.1.0) which comes with doctrine/persistence 2.0.0, the bundle stopped working. The error I'm getting is:

Argument 1 passed to Sg\DatatablesBundle\Datatable\Column\ColumnBuilder::__construct() must be an instance of Doctrine\Common\Persistence\Mapping\ClassMetadata, instance of Doctrine\ORM\Mapping\ClassMetadata given

Quick fix for now: Adding "doctrine/persistence": "^1" to my composer.json will allow me to update the doctrine-bundle, but I think in the long run, doctrine/persistence should be supported.

**Comment by mbartok** [comment]
+1

**Comment by Seb33300** [comment]
Hello, can you please guys test this PR fix and confirm this fix the issue: https://github.com/stwe/DatatablesBundle/pull/957

**Comment by Knallcharge** [comment]
@Seb33300 Works for me, thanks.

**Comment by Fl0ux** [comment]
Works for me too. I am looking forward the next release !
