### ISSUE TITLE
Edit inline selected value missing

### ISSUE THREAD

**Issue by MProntera** [stwe/DatatablesBundle#962]
Hi,

Using your bundle, I have seen that it is not possible in inline editing to have the selected value in any select.
Searching on X-Editable (http://vitalets.github.io/x-editable/docs.html#editable)
there is the possibility to set a select option to selected.
In theory, it would only be necessary to add this option and obviously do a get of the value in order to insert it in the initialization of the editable field.

I hope the problem was clear. Thank you in advance and good luck!

**Comment by stwe** [comment]
wont fix
