### ISSUE TITLE
Notice: Array to string conversion in search VirtualColumn

### ISSUE THREAD

**Issue by jcgriebel** [stwe/DatatablesBundle#963]
Hello,
I have an error message on the search for a VirtualColumn.
the message is: Notice: Array to string conversion
in: DatatableResponse-> getResponse ()

After a search I found the cause.
followed the commit of 4/05/2020 (Search / Order on several columns with VirtualColumn)
in file: Response / DatatableQueryBuilder.php
line 450: the [$ key] would be too many.
when it is removed there is no more error.

**Comment by andrea-daru** [comment]
Hi, 
I have the same problem using filter on a _VirtualColum_ pointing (_search_column_) to a _OneToMany_ field :

> `php.CRITICAL: Fatal Error: Method Doctrine\ORM\Query\Expr\Comparison::__toString() must not throw an exception, caught ErrorException: Notice: Array to string conversion`.

Someone has encountered the same behaviour? Solution?
Thank you in advance

**Comment by Gielovic** [comment]
Hi,

I have encountered the same issue with a VitualColumn pointing to a DateTime field.

> Fatal Error: Method Doctrine\ORM\Query\Expr\Comparison::__toString() must not throw an exception, caught Symfony\Component\Debug\Exception\ContextErrorException: Notice: Array to string conversion

Did not find a solution just yet.

**Comment by Eloar** [comment]
@Gielovic post your VirtualColumn configuration from `buildDatatable` method and its manipulation from `getLineFormatter` or any other method.

**Comment by stwe** [comment]
Please reopen with the necessary information

**Comment by lemorragia** [comment]
i'm experiencing the same problem. What i'm doing is uniting two "phone contact" columns (telephone + cellularNumber) searching in both of them at the same time. It didn't work so i simplified it to the minimum: one virtual column as a mirror of another text column (telephone). The configuration:

```
    public function getLineFormatter()
    {
        return function ($row) {
            $row['phonecontact'] = $row['telephone'];

            return $row;
        };
    }
```

```
public function buildDatatable(array $options = []): void
    {
        $this->columnBuilder
            ->add('phonecontact', VirtualColumn::class, [
                'title' => 'Phone',
                'searchable' => true,
                'orderable' => false,
                'search_column' => 'telephone',
                'filter' => [
                    TextFilter::class,
                    ['cancel_button' => false],
                ],
            ])
            ->add('telephone', Column::class, [
                'visible' => false,
            ])
       ;
   }
```

The problem(if not a configuration problem) seems to be in the query generation: inside doctrine\orm\[..]\Comparison.php the left operand is indeed an array: [0=>'partner.telephone'], and the code fails on an Array-to-String conversion. Any ideas?
