### ISSUE TITLE
Compound columns, renderif

### ISSUE THREAD

**Issue by jesusherencia** [stwe/DatatablesBundle#97]
Hi,
I'm using v0.6.1, I want to know how can I show in one column the combination of two columns (ex: firstName, lastName columns together in one column getting a full name).
Another question is how can I use a boolean column as a renderif in an action column but using the not operator (ex: true->false, false->true).

Thanks

**Comment by stwe** [comment]
you can use a Line Formatter in your DatatableClass:

    /**
     * {@inheritdoc}
     */
    public function getLineFormatter()
    {
        $formatter = function($line){
            $line["firstName"] = $line["firstName"] . " " . $line["lastName"];

            return $line;
        };

        return $formatter;
    }

    /**
     * {@inheritdoc}
     */
    public function buildDatatableView()
    {    
         // ....

        $this->getColumnBuilder()
           // ...
            ->add('firstName', 'column', array(
                'title' => "Name",
                "searchable" => true,
                "orderable" => true
            ))
            ->add('lastName', 'column', array(
               "visible" => false
            ));
    }

**Comment by jesusherencia** [comment]
Hi,

Thanks for the answer, it works when the attributes are from the entity itself, but when I want to use the attributes of a related OneToOne entity it doesn't work.

///
$this->getColumnBuilder()
   ->add('person.firstName', 'column', array('visible' => false,))
   ->add('person.lastName', 'column', array('visible' => false,))

///
$line["person.firstName"] = $line["person.firstName"]." ".$line["person.lastName"];

The error shown by the ajax request is:
Notice: Undefined index: person.firstName

**Comment by jesusherencia** [comment]
Related to this question, I tried to use a getter from an entity to show it as a column, this getter gives the combination of two attributes:

$private firstName;
$private lastName;

public getFullName(){
    return $this->firstName.' '.$this->lastName;
}

But the fullName as a column in datatable is not recognized:
->add('fullName', 'column', array('title' => 'Full Name',))

Error message: Warning: in_array() expects parameter 2 to be array, object given

Is it possible to use this getter in a column?

**Comment by Minishlink** [comment]
In the line formatter, $line['person.firstName'] is in fact $line['person']['firstName'].

**Comment by jesusherencia** [comment]
Thanks, that worked for me.
