### ISSUE TITLE
Undefined constant Doctrine\DBAL\Types\Type::DATETIME

### ISSUE THREAD

**Issue by Knallcharge** [stwe/DatatablesBundle#973]
I'm getting the error "Undefined constant Doctrine\DBAL\Types\Type::DATETIME" when trying to use inline-editing in a datatable.
The error occurs in vendor\sg\datatablesbundle\Controller\DatatableController.php (line 115) when using doctrine/dbal 3(.1.3), everything works as expected with doctrine/dbal 2(.13.4).
Currently this behavior is the only thing that keeps me from updating to doctrine/dbal 3, so I wonder if there's a quick fix for it.
Kind regards

**Comment by Seb33300** [comment]
Hello, if you can submit a pull request to make this bundle compatible with doctrine/dbal 3, I can review and merge it.

**Comment by Knallcharge** [comment]
As the types from Doctrine\DBAL\Types\Type that are used in the DatatableController are already marked as deprecated in doctrine/dbal 2 and have suggested replacements in Doctrine\DBAL\Types\Types, this should be pretty straightforward:
https://github.com/stwe/DatatablesBundle/pull/974

**Comment by Seb33300** [comment]
I just merged your PR, can you please try to update your project to use dev-master and confirm that there is no other issues related to doctrine dbal 3?

**Comment by Knallcharge** [comment]
I have checked dev-master and everything looks good now. I'm pretty positive that there are no other issues as the formerly used constants (from Type) were already deprecated in dbal 2 and I just changed them to the suggested replacements (in Types) which are available in dbal 2 and 3. But please note that I don't use all features and column types of the datatables-bundle so a second opinion may be advised.
