### ISSUE TITLE
Sorting localized dates

### ISSUE THREAD

**Issue by Minishlink** [stwe/DatatablesBundle#98]
Hello,

There's a problem of sorting dates in some languages because information is not in the order YEAR-MONTH-DAY HOUR-MIN-SECONDS anymore (ISO format).
One way to fix the problem would be to insert an HTML comment with the date in ISO format in the row.

**Comment by stwe** [comment]
I need an example to reproduce this issue.

**Comment by Minishlink** [comment]
This issue seems to be fixed in the master branch since 0.7 at least. :+1: (It may have been fixed by an update of datatables.js or moment.js though)
