### ISSUE TITLE
Symfony 6.0 support

### ISSUE THREAD

**Issue by victormacko** [stwe/DatatablesBundle#981]
Any thoughts on supporting Symfony 6.0 by chance?
Thanks for all your hard work, great package!

**Comment by mwansinck** [comment]
@victormacko I created a PR that adds Symfony 6 / PHP 8 support
https://github.com/stwe/DatatablesBundle/pull/982

**Comment by victormacko** [comment]
Wow, epic amount of work there -- nice going!! Looking forward to using it in the next release (hopefully soon!)
Thank you!!!

**Comment by mwansinck** [comment]
> Wow, epic amount of work there -- nice going!! Looking forward to using it in the next release (hopefully soon!) Thank you!!!

FYI, v1.3.0 has been released 18 days ago, so this issue could be closed :-)
